### ISSUE TITLE
Glowroot server is not listening to port 4000

### ISSUE THREAD

**Issue by Nandakumar-M** [glowroot/glowroot#1002]
I am trying to setup glowroot on a java application. In the console output, I can see that Glowroot version is printed. However, I am **not seeing** the `INFO org.glowroot - UI listening on 127.0.0.1:4000`  message being printed.

```
 2023-05-04 13:12:36.597 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2023-05-04 13:12:36.600 INFO  org.glowroot - Java version: 1.8.0_191 (Oracle Corporation / Linux)
2023-05-04 13:12:36.601 INFO  org.glowroot - Java args: -javaagent:/home/ubuntu/glowroot/glowroot.jar -Xms1024m -Xmx159744m -Xloggc:./../2023-05-04_13-12-36-gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:-PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation-XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -XX:+UseParNewGC -XX:MaxNewSize=256m -XX:NewSize=256m -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0 -XX:+UseTLAB -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./../heap_dump2023-05-04_13-12-36.hprof
2023-05-04 13:12:42.087 INFO  o.g.agent.impl.BytecodeServiceImpl - entering azkaban.webapp.AzkabanWebServer.main()
java.lang.Exception: location stack trace
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:252)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
        at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
        at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at azkaban.webapp.AzkabanWebServer.loadUserManager(AzkabanWebServer.java:246)
        at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:194)
        at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:741)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at azkaban.webapp.AzkabanWebServer.loadUserManager(AzkabanWebServer.java:242)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: User xml file conf/azkaban-users.xml doesn't exist.
        at azkaban.user.XmlUserManager.parseXMLFile(XmlUserManager.java:90)
        at azkaban.user.XmlUserManager.<init>(XmlUserManager.java:84)
        ... 7 more
```

We had glowroot on this application and it used to work fine earlier. Now I am seeing this problem after we restarted the application (no code changes).

The error `java.lang.RuntimeException: java.lang.reflect.InvocationTargetException` seems unrelated.

Things that I tried

1. Checked whether the port 4000 is being used by any other process using `netstat`. **Nothing found**.
2. Checked whether the linux user has ownership of glowroot.jar and entire glowroot directory. **Yes**
3. Added the `-Dglowroot.debug.mainClass=true`. I can see the stack trace printed in the logs, but the **UI is not coming up**.
4. Stopped the java application. Navigated to glowroot directory and tried `java -jar glowroot.jar`. The glowroot UI is now up and running in port 4000. I am able to access it from remote machines as well. I can also see the web traces that were collected during the brief period when my java application was running in Glowroot UI now.

```
~/glowroot$ java -jar glowroot.jar
2023-05-04 13:09:18.328 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2023-05-04 13:09:18.335 INFO  org.glowroot - Java version: 1.8.0_191 (Oracle Corporation / Linux)
2023-05-04 13:09:20.319 INFO  org.glowroot - Offline viewer listening on 0.0.0.0:4000
```

I am not sure how I can enable debug logging for glowroot. This is something I tried but haven't been able to do.

Any help would be much appreciated @trask .
Thanks.

**Comment by Never-lab** [comment]
Thanks for the detailed report — this looks like **expected timing**, not a bind/port problem on Glowroot''s side.

### What the log shows
1. Glowroot agent starts (`Glowroot version: …`).
2. With `-Dglowroot.debug.mainClass=true`, Glowroot detects `AzkabanWebServer.main()`.
3. Immediately after that, Azkaban exits with:
   `User xml file conf/azkaban-users.xml doesn''t exist.`

That Azkaban failure is very likely **related**, not unrelated.

### Why there is no `UI listening on …:4000`
In embedded mode the HTTP UI does **not** bind during agent premain. It starts only after the application `main` is entered, on a **daemon** background thread (`Glowroot-Init-UI`). If the JVM process exits right after `main` throws, that thread is stopped before bind completes, so you never see:

`INFO org.glowroot - UI listening on 127.0.0.1:4000`

That also matches what you already observed:
- Port 4000 free → nothing bound yet.
- `java -jar glowroot.jar` → offline viewer works (process stays up).
- Traces visible later → agent had already collected some data before the process died.

### What to do
1. Fix Azkaban startup (`conf/azkaban-users.xml` / working directory / config paths) so the JVM stays running.
2. Restart with `-javaagent:…/glowroot.jar` and confirm `UI listening on …` appears in the console / `glowroot` logs.
3. Optional: check `glowroot/logs/glowroot*.log` for `Glowroot cannot start` (repo/UI init failure).

Glowroot''s own logging is separate from the app''s SLF4J NOP warning. Agent logs go to the glowroot log dir; you can override with `glowroot.logback.xml` under the glowroot conf directory if needed.

If the app stays up and you still never get `UI listening`, reply with the glowroot log from that run and we can dig further.

**Comment by Never-lab** [comment]
﻿Already answered here (Never-lab): embedded UI binds **after** ``main``; Azkaban exited on missing ``azkaban-users.xml`` so ``UI listening`` never appeared. Fix app startup first.

@nowheresly — please close as support.
