### ISSUE TITLE
Glowroot central not working with jdk 1.8

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#1008]
java -jar glowroot-central.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/glowroot/central/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

The commit history :
"The minimum Java version has been bumped to Java 8 with this release."

**Comment by lfen21** [comment]
![image](https://github.com/glowroot/glowroot/assets/38753048/7be5fd0a-a28d-4e51-82c0-7d332d9aa2c7)

:(

**Comment by Nowheresly** [comment]
Hi @lfen21 

as stated on the README, glowroot central now requires java 11+

> Requirements
> Java 8+ for agent
> Java 11+ for glowroot-central

Some of the dependencies of glowroot-central simply just does not work anymore with java 1.8 (example: infinspan).

Please, note that java 8 has no more active support since 03/2022 while the end of active support for java 11 is planned for 09/2023 (see [here](https://endoflife.date/java))

Therefore, it's pretty hard to get the best performance for the central collector while still sticking on java 1.8.
