### ISSUE TITLE
java.lang.NoClassDefFoundError in JBoss 4.2.2-GA

### ISSUE THREAD

**Issue by miles-b** [glowroot/glowroot#101]
This looks like a fantastic project, and we'd love to use it with a JBoss 4.2.2-GA server. Unfortunately when attaching the --javaagent the server fails to start up with a NoClassDefFoundError.

I've stepped through to the NoClassDefFoundErrorConstructor (as mentioned in #44) and this is the value of loader:
`WebappClassLoader
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
java.net.FactoryURLClassLoader@727b3afd`

The glowroot.log doesn't seem to have anything useful, but I've attached it as well just in case.
[glowroot-log.txt](https://github.com/glowroot/glowroot/files/349776/glowroot-log.txt)

Here's the JBoss stacktrace:
`java.lang.NoClassDefFoundError: org/glowroot/agent/advicegen/GeneratedMethodMeta27
        at org.glowroot.agent.weaving.MetaHolder26.<clinit>(Unknown Source)
        at org.jboss.seam.servlet.SeamListener.contextInitialized(SeamListener.java)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3856)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4361)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:790)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:770)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:553)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:296)
        at org.jboss.mx.server.RawDynamicInvoker.invoke(RawDynamicInvoker.java:164)
        at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
        at org.apache.catalina.core.StandardContext.init(StandardContext.java:5312)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:296)
        at org.jboss.mx.server.RawDynamicInvoker.invoke(RawDynamicInvoker.java:164)
        at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
        at org.jboss.web.tomcat.service.TomcatDeployer.performDeployInternal(TomcatDeployer.java:301)
        at org.jboss.web.tomcat.service.TomcatDeployer.performDeploy(TomcatDeployer.java:104)
        at org.jboss.web.AbstractWebDeployer.start(AbstractWebDeployer.java:375)
        at org.jboss.web.WebModule.startModule(WebModule.java:83)
        at org.jboss.web.WebModule.startService(WebModule.java:61)
        at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:289)
        at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:245)
        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
...
...
Caused by: java.lang.ClassNotFoundException: No ClassLoaders found for: org.glowroot.agent.advicegen.GeneratedMethodMeta27
        at org.jboss.mx.loading.LoadMgr3.beginLoadTask(LoadMgr3.java:306)
        at org.jboss.mx.loading.RepositoryClassLoader.loadClassImpl(RepositoryClassLoader.java:521)
        at org.jboss.mx.loading.RepositoryClassLoader.loadClass(RepositoryClassLoader.java:415)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) `

**Comment by trask** [comment]
Hi, thanks for reporting this.  I just downloaded JBoss 4.2.2.GA and was able to run the jboss-seam-spring sample application from JBoss Seam 2.1.2 successfully.  I dropped the jboss-seam-spring.war into jboss-4.2.2.GA/server/default/deploy and ran jboss-4.2.2.GA/bin/run (after setting JAVA_OPTS=-javaagent:...).  What JDK version are you using?  Have you set any interesting JBoss configuration?  Other thoughts how I can repro would be great.  Thanks.

**Comment by miles-b** [comment]
Thanks for the speedy response. We are using JDK v1.7.0_80 with Seam 2.2.2.Final. I can't see anything strange in the JBoss config so I'll try and reproduce in a Vagrant box with a fresh copy and one of the Seam examples. I'll let you know how I get on.

**Comment by trask** [comment]
Hi, any luck with this, or additional ideas how I can repro?  Thanks.

**Comment by miles-b** [comment]
None at all I'm afraid, I've not been able to get it working nor track down which bits of config might be causing the issue, so I'll close this for now. If I come across something in the future I'll let you know. Thanks for your help!

**Comment by trask** [comment]
Re-opening, good news, I was able to reproduce today, the key to reproducing was tweaking the jboss class loading via jboss-web.xml:

```
<jboss-web>
  <class-loading java2ClassLoadingCompliance="false">
    <loader-repository>
      xxx:loader=yyy
      <loader-repository-config>java2ParentDelegation=false</loader-repository-config>
    </loader-repository>
  </class-loading>
</jboss-web>
```

I'll work on a fix.

**Comment by miles-b** [comment]
Fantastic, thanks.

**Comment by trask** [comment]
This is now in the latest snapshot build https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9.1-SNAPSHOT-dist.zip
