### ISSUE TITLE
Unable to start central-collector - OOME - Unable to create native thread

### ISSUE THREAD

**Issue by grib0** [glowroot/glowroot#1011]
I'm upgrading glowroot from 0.13.1 to 0.14.0 without keeping data.
I use cassandra v3.11.14

The glowroot instance is a pod inside k8s. When starting the 0.14.0 version instance, I got plenty of logs : 

```
[...]
[94.177s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.178s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2151"
[94.178s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.178s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2152"
[94.178s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.178s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2153"
[94.180s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.180s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2154"
[94.180s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.180s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2155"
[94.180s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.180s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2156"
[94.181s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.181s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2157"
[94.181s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.181s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2158"
[94.181s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.181s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2159"
[94.181s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.182s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2160"
[94.182s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.182s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2161"
[94.182s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.182s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2162"
[94.182s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.186s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2163"
[94.187s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.187s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2164"
[94.187s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.187s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2165"
[94.187s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.187s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2166"
[94.188s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.188s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2167"
[94.188s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.188s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2168"
[94.188s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.188s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2169"
[94.188s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.189s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2170"
[94.189s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.189s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2171"
[94.189s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.189s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2172"
[94.189s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.194s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2173"
[94.195s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.195s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2134"
[94.195s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.195s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2174"
[94.195s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.196s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2175"
[94.196s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.196s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2176"
[94.196s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.196s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2177"
[94.196s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.196s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2178"
[94.197s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.197s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2179"
[94.197s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.197s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2180"
[94.197s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.197s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2181"
[94.198s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.198s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2182"
[94.199s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.199s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2183"
[94.199s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.199s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2184"
[94.199s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.199s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2185"
[94.199s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.200s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2186"
[94.200s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.200s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2187"
[94.200s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[94.200s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Repo-Async-Worker-2188"
2023-06-07 12:27:13,364 ERROR [org.glowroot.central.RollupService] six-programmation-api - java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
 at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
 at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
 at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
 at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
 at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
 at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
 at java.base/java.lang.Thread.start0(Native Method)
 at java.base/java.lang.Thread.start(Thread.java:802)
 at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
 at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
 at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
 at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
 ```
 We do have put a limit of 400 threads (open files) in the kubelet config (podPidsLimit: 400) and it is reached (that's the "process/resource limits reached" message) but the question is why glowroot 0.14.0 creates so many "Repo-Async-Worker" threads ?
 
 In the 0.13.1 versions, we have 137 threads for glowroot but with 0.14.0 the pod crashed at 400 threads.

**Comment by Nowheresly** [comment]
Hi @grib0 
Thanks for your feedback!
Glowroot 0.14 is now using the new version of the cassandra datastax driver. One of its major features is the heavy use of asynchronous queries (`AsyncResultSet`, see [here](https://docs.datastax.com/en/developer/java-driver/4.0/upgrade_guide/)).
This feature should allow a better throughput and a better scalability...
By looking at the code, I see that the threadpool has no max size defined

https://github.com/glowroot/glowroot/blob/8f545ddc159e362a577300d8a7aec8dc0340769d/central/src/main/java/org/glowroot/central/CentralModule.java#L190

In your case, it seems you reach a point where there's so much `AsyncResultSet` to manage in the same time that too much threads get instantiated resulting in an Oom...

Probably providing some kind of configuration to set the threadpool max size could help prevent this situation.

**Comment by Nowheresly** [comment]
Now glowroot central uses a fixed size thread pool. By default, thread pool max size is set to 50. This can be overridden by using `central.threadPoolMaxSize` property in `glowroot-central.properties` file

**Comment by Nowheresly** [comment]
Hi, please let me know if it is beter with tis release : https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta

**Comment by grib0** [comment]
Hi, Thank you for the release. The fix is working I don't reproduce the error, although I still not succeed to have glowroot working on heavy load test.
I think it's because of the new cassandra driver with cassandra 3.11.14.
I got plenty of errors like : 

```
2023-06-30 08:32:13,383 WARN  [o.g.central.CollectorServiceImpl] my-test-project - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: collection rejected due to backlog (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)

```
I'm still investigating...

**Comment by Nowheresly** [comment]
It seems glowroot-central is not able to write quick enough to cassandra.
I would suggest to consider adjusting some cassandra properties in your glowroot-central.properties file

**Comment by Nowheresly** [comment]
Btw, can you share your heavy load test?
