### ISSUE TITLE
Could not find TLS ALPN provider - agent v0.14.0 - OpenJDK8

### ISSUE THREAD

**Issue by k-gomes** [glowroot/glowroot#1023]
Reopening this issue because i have the same problem but due to project constraints i am unable to change my JDK.

#971 

I had to anonymize some bits of logs with XXX.

Java version : 
> openjdk version "1.8.0_191"
> OpenJDK Runtime Environment (build 1.8.0_191-b12)
> OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`

Agent version : 0.14.0
Central collector version : 0.14.0

2023-06-30 10:25:22.327 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-06-30 10:25:22.331 INFO  org.glowroot - Java version: 1.8.0_191 (Oracle Corporation / Linux)
2023-06-30 10:25:22.332 INFO  org.glowroot - Java args: -javaagent:/XXX/glowroot_agent/glowroot.jar -Xbootclasspath/p:/XXX/alpn-boot-8.1.13.v20181017.jar -Xms2048m -Xmx6144m -XX:+UseG1GC -XX:+UseStringDeduplication
2023-06-30 10:25:30.863 INFO  org.glowroot - agent id: XXX_XXX
2023-06-30 10:25:31.174 ERROR o.g.agent.impl.BytecodeServiceImpl - Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.glowroot.agent.central.CentralConnection.<init>(CentralConnection.java:121)
	at org.glowroot.agent.central.CentralCollector.<init>(CentralCollector.java:135)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:136)
	at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:255)
	at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
	at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
	at XXXX.mainclass.main(XXX.java)
	
I tried to manually add the jetty alpn boot jar in the classpath with the JVM ARG 
> Xbootclasspath/p:/XXX/alpn-boot-8.1.13.v20181017.jar

It doesn't solve the issue.

Thanks in advance for any lead you may have.

**Comment by Nowheresly** [comment]
Hi
glowroot 0.14.0 is using grpc 1.54.0 + boringssl 2.0.56 as specified in the netty documentation [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty).
The glowroot distribution comes with an agent and a lib folder that contains mandatory lib to use when tcnative is used. Be sure ta have this lib folder in the same where where the glowroot agent is located.

**Comment by Nowheresly** [comment]
You may try as well the glowroot 0.14.1-beta agent. It internally uses grpc 1.56.0 + boringssl 2.0.61. [0.14.1-beta](https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta)

**Comment by Dinty0** [comment]
Hello, 

I indeed have the lib folder in the same location of the glowroot agent, but i still face the issue

![image](https://github.com/glowroot/glowroot/assets/14872236/96325d8d-9742-44ab-a1e5-ea17b0af2ee7)

I also initially tried with the 0.14.1-beta glowroot agent, and I had the same issue.

**Comment by Nowheresly** [comment]
Hi, thanks for your feedback!
it seems ALPN has been backported to openjdk version 8_252.
So my guess is that your openjdk version may be too old (8_191) and you should try updating openjdk to at least version 8_252.

**Comment by Dinty0** [comment]
Upgrading to the latest version of OpenJDK8 indeed fixed the issue.

Thanks for the support.
