### ISSUE TITLE
Glowroot Not starting. could not create platform mbean server: java/lang/management/ManagementFactory

### ISSUE THREAD

**Issue by yogeshjangrax** [glowroot/glowroot#1025]
Getting below error. 

17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) 2023-07-06 17:29:10.459 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at javax.servlet.GenericServlet.init(GenericServlet.java)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
17:29:10,460 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:309)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,461 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
17:29:10,462 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at java.lang.Thread.run(Thread.java:750)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.threads.JBossThread.run(JBossThread.java:513)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory from [Module "javax.servlet.api" version 2.0.0.Final-redhat-00001 from local module loader @3401a114 (finder: local module finder @5066d65f (roots: /some_path/jboss-eap-7.4.11/modules,/some_path/jboss-eap-7.4.11/modules/system/layers/base/.overlays/layer-base-jboss-eap-7.4.11.CP,/some_path/jboss-eap-7.4.11/modules/system/layers/base))]
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
17:29:10,463 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
17:29:10,464 INFO [stdout] (ServerService Thread Pool -- 70) at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
17:29:10,464 INFO [stdout] (ServerService Thread Pool -- 70) ... 28 common frames omitted
17:29:10,492 INFO [stdout] (ServerService Thread Pool -- 73) 2023-07-06 17:29:10.490 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
17:29:10,493 INFO [stdout] (ServerService Thread Pool -- 73) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
17:29:10,493 INFO [stdout] (ServerService Thread Pool -- 73) at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
17:29:10,495 INFO [stdout] (ServerService Thread Pool -- 73) at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
17:29:10,495 INFO [stdout] (ServerService Thread Pool -- 73) at javax.servlet.GenericServlet.init(GenericServlet.java)

**Comment by yogeshjangrax** [comment]
this also not worked for me.

<minimum-set>
                    <permission class="javax.management.MBeanServerPermission" name="createMBeanServer" module="java.se"/>
                </minimum-set>

**Comment by yogeshjangrax** [comment]
this also not worked for me.
minimum-set
                    permission class="javax.management.MBeanServerPermission" name="createMBeanServer" module="java.se"
                minimum-set

**Comment by yogeshjangrax** [comment]
using jboss7.4.11 glow0.13.6.  and unable to reproduce in another instance

**Comment by MrAligual** [comment]
I got the same error running Wildfly 24.0.1 with OpenJDK1.8 and glowroot 0.13.6 or newer versions.

```
ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
        at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
        at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
        at javax.servlet.GenericServlet.init(GenericServlet.java)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1535)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1535)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1535)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1535)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:106)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:750)
        at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory from [Module "javax.servlet.api" version 2.0.0.Final from local module loader @1849db1a (finder: local module finder @69c79f09 (roots: /opt/wildfly01/modules,/opt/wildfly01/modules/system/layers/base))]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)


```

Any advice?

**Comment by borysmarceloherrera** [comment]
Same issue here. Glowroot 

Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000

`
2023-12-12 14:55:40.502 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
14:55:40,503 INFO [stdout] (default task-2) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
14:55:40,503 INFO [stdout] (default task-2) at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
14:55:40,503 INFO [stdout] (default task-2) at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
14:55:40,503 INFO [stdout] (default task-2) at javax.servlet.GenericServlet.init(GenericServlet.java)
`

**Comment by smalltox** [comment]
Hi, Same issue 
To resolve it :

**Comment by mauromol** [comment]
We have the same problem with JBoss EAP 7. I will try by adding that dependency. But why is it needed? If we disable Glowroot there's no such `ClassNotFoundException` being thrown.

**Comment by lbadzaghua** [comment]
> Hi, Same issue To resolve it : add to module.xml io.undertow.servlet, javax.servlet.api, javax.faces.api in wildfly directory `<dependencies>` ` <module name="java.management"/>` `</dependencies>`

The solution works for **Wildfly33** and **Glowroot 0.14.2**. But you should probably create a custom reference module called  _"java.management"_ that depends on _"javax.api"_ (wildfly33 contains it by default) which contains _ManagementFactory_ class.

**Comment by Never-lab** [comment]
This is a **JBoss Modules / WildFly classloader** issue, not “Glowroot failed to boot”. The servlet plugin’s startup advice calls `ManagementFactory.getPlatformMBeanServer()` while the TCCL is the `javax.servlet.api` (or `jakarta.servlet.api`) module, which often **does not depend on `java.management`** — hence `ClassNotFoundException: java.lang.management.ManagementFactory`. The call is wrapped in try/catch and logged as ERROR; the agent can still be running.

### Workaround (confirmed in-thread for WildFly / EAP)

Add a dependency on `java.management` to the servlet API module, e.g.:

- older: `$WILDFLY/modules/.../javax/servlet/api/main/module.xml`
- newer: `.../jakarta/servlet/api/main/module.xml`

```xml
<dependencies>
  <module name="java.management"/>
</dependencies>
```

(Same idea for related modules if you still hit CNFE.)

### Why Glowroot touches it

`ContainerStartup.initPlatformMBeanServer()` eagerly creates the platform MBean server so later gauge/JMX code can see it. Under modular servers that only shows up when the servlet plugin advice runs.

Optional product fix would be to resolve `ManagementFactory` via the **bootstrap/system** classloader instead of the servlet module TCCL — worth an `enhancement` if maintainers want it; not required for the ops workaround.

Further install Qs → [Discussions](https://github.com/glowroot/glowroot/discussions) / [wiki](https://github.com/glowroot/glowroot/wiki).

@nowheresly — OK to close as support (workaround), or keep open + `enhancement` for the CL fix.
