### ISSUE TITLE
Spring Boot App with MySQL,Elastic APM & Glowroot: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by shashank915** [glowroot/glowroot#1026]
Hi,

Application details:
Java - 1.8.0_342(OpenJDK 8)
Spring Boot - 2.3.4.RELEASE
Hibernate(Spring Data Jpa) - 5.4.21.Final
MySQL Connector Java - 8.0.30
Liquibase Core- 4.3.1

Elastic APM Agent - 1.19.0

When I run this application with **Glowroot version 0.14.0-beta**, It throws the error below:
`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
10-07-2023 11:06:35.747 [main, ,] ERROR org.springframework.boot.SpringApplication.reportFailure(837) - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IncompatibleClassChangeError: Class com.zaxxer.hikari.pool.HikariProxyStatement does not implement the requested interface org.glowroot.agent.plugin.jdbc.StatementAspect$HasStatementMirrorMixin
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.frostinteractive.loginservice.config.LoginServiceApplication.main(LoginServiceApplication.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IncompatibleClassChangeError: Class com.zaxxer.hikari.pool.HikariProxyStatement does not implement the requested interface org.glowroot.agent.plugin.jdbc.StatementAspect$HasStatementMirrorMixin
        at org.glowroot.agent.plugin.jdbc.StatementAspect$StatementExecuteQueryAdvice.isEnabled(StatementAspect.java:346)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
        at liquibase.database.core.CockroachDatabase.isCorrectDatabaseImplementation(CockroachDatabase.java:38)
        at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:101)
        at liquibase.integration.spring.SpringLiquibase.createDatabase(SpringLiquibase.java:363)
        at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:330)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:273)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 27 common frames omitted
        Suppressed: java.lang.IncompatibleClassChangeError: Class com.zaxxer.hikari.pool.HikariProxyStatement does not implement the requested interface org.glowroot.agent.plugin.jdbc.StatementAspect$HasStatementMirrorMixin
                at org.glowroot.agent.plugin.jdbc.StatementAspect$CloseAdvice.isEnabled(StatementAspect.java:632)
                at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java)
                at liquibase.database.core.CockroachDatabase.isCorrectDatabaseImplementation(CockroachDatabase.java:44)
                ... 33 common frames omitted`

I have tried multiple versions of Glowroot, Mysql connector and Liquibase but same issue occurred everytime.

**Comment by Never-lab** [comment]
`IncompatibleClassChangeError` on `HikariProxyStatement` / Glowroot JDBC `HasStatementMirrorMixin` almost always means **two bytecode agents** fighting over the same JDBC proxies (here: **Elastic APM + Glowroot**), or a partial weave of Hikari/Liquibase paths. Glowroot’s JDBC plugin expects its mixin on statement wrappers; another agent’s transforms break that contract.

Practical order:

1. Run with **only Glowroot** (no Elastic APM) on current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7) — confirm Liquibase/Hikari start.
2. If you must keep Elastic APM, do **not** dual-agent the same JVM (unsupported combo; same theme as #938).
3. Temporary escape hatch: disable the **jdbc** plugin under the agent `plugins/` dir (loses SQL capture).

@nowheresly — keep as compatibility, or close as support if “one agent only” is enough.
