### ISSUE TITLE
java.lang.RuntimeException: Bytecode service retrieved too early

### ISSUE THREAD

**Issue by macau23** [glowroot/glowroot#1034]
```
2023-08-16 12:04:12.509 INFO  org.glowroot - Glowroot version: 0.14.1-beta.2, built 2023-07-22 21:55:30 +0000
2023-08-16 12:04:12.512 INFO  org.glowroot - Java version: 11.0.15.1 (Oracle Corporation / Linux)
2023-08-16 12:04:12.513 INFO  org.glowroot - Java args: -Xms256m -Xmx512m -XX:CompileThreshold=8000 -XX:MaxPermSize=256m -Xms4608m -Xmx4608m -javaagent:/home/oracle/glowroot/glowroot.jar -javaagent:/opt/oracle/product/fusion/wlserver/server/lib/debugpatch-agent.jar -da
Exception in thread "main" java.lang.ExceptionInInitializerError
        at weblogic.Server.main(Server.java)
Caused by: java.lang.RuntimeException: Bytecode service retrieved too early
        at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:32)
        at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:26)
        ... 1 more
```

**Comment by macau23** [comment]
Same as #511 ?

**Comment by macau23** [comment]
@Nowheresly any chance of a release of 0.14.1-beta3 so I can test it?

**Comment by macau23** [comment]
@trask any chance you can help?

**Comment by macau23** [comment]
No feedback, so closing.
