### ISSUE TITLE
Unable to start glowroot central 0.14.0, I get the error com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S

### ISSUE THREAD

**Issue by HerbertKoelman** [glowroot/glowroot#1048]
Hello,

I have upgraded my glowroot central server from 0.13 to 0.14. 

But when I restart (`systemctl start glowroot`) , I get the message Query timed out after PT2S

```
2023-11-06 15:36:11.115 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-11-06 15:36:11.123 INFO  org.glowroot - Java version: 11.0.20
2023-11-06 15:36:11.438 INFO  c.d.o.d.i.c.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.15.0
2023-11-06 15:36:12.634 WARN  c.d.o.d.i.core.session.PoolManager - [s0] Detected a keyspace change at runtime (<none> => glowroot). This is an anti-pattern that should be avoided in production (see 'advanced.request.warn-if-set-keyspace' in the configuration).
2023-11-06 15:36:13.250 INFO  org.glowroot - connected to Cassandra (version 4.0.7), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM
2023-11-06 15:36:15.337 ERROR org.glowroot - Query timed out after PT2S
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:376)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:305)
        at org.glowroot.central.util.Session.createTableWithTracking(Session.java:320)
        at org.glowroot.central.util.Session.createTableWithLCS(Session.java:293)
        at org.glowroot.central.util.Session.createTableWithLCS(Session.java:287)
        at org.glowroot.central.repo.SchemaUpgrade.<init>(SchemaUpgrade.java:117)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:180)
        at org.glowroot.central.CentralModule.create(CentralModule.java:130)
        at org.glowroot.central.CentralModule.create(CentralModule.java:125)
        at org.glowroot.central.Main.start(Main.java:44)
        at org.glowroot.central.Main.main(Main.java:28)
```

Any suggestion

**Comment by HerbertKoelman** [comment]
**FYI** My first configuration was using java 11. I saw mentions about using java 17 to run glowroot central, so I have switched to java 17 and it's not doing better.

I'm using AlmaLinux 8

```
logs]$ /usr/lib/jvm/jre-17/bin/java -jar /home/glowroot/glowroot-central/glowroot-central.jar
18:58:55,802 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.7
18:58:55,833 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:58:55,849 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/glowroot/glowroot-central/glowroot-central.jar!/logback.xml]
18:58:55,883 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@41a0aa7d - URL [jar:file:/home/glowroot/glowroot-central/glowroot-central.jar!/logback.xml] is not of type file
18:58:56,036 |-WARN in IfNestedWithinSecondPhaseElementSC - <if> elements cannot be nested within an <appender>, <logger> or <root> element
18:58:56,036 |-WARN in IfNestedWithinSecondPhaseElementSC - See also http://logback.qos.ch/codes.html#nested_if_element
18:58:56,044 |-WARN in IfNestedWithinSecondPhaseElementSC - Element <root> at line 33 contains a nested <if> element at line 35
18:58:56,111 |-INFO in ch.qos.logback.classic.model.processor.LoggerContextListenerModelHandler - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
18:58:56,112 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@2794eab6 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
18:58:56,118 |-INFO in ch.qos.logback.classic.model.processor.LoggerContextListenerModelHandler - Starting LoggerContextListener
18:58:56,411 |-INFO in ch.qos.logback.core.model.processor.conditional.IfModelHandler - Condition [p("glowroot.log.auditOn").equalsIgnoreCase("true")] evaluated to false on line 44
18:58:56,413 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
18:58:56,413 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:58:56,420 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:58:56,451 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
18:58:56,451 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
18:58:56,457 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@6340e5f0 - No compression will be used
18:58:56,459 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:58:56,460 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /home/glowroot/glowroot-central/logs/glowroot-central.log
18:58:56,460 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/home/glowroot/glowroot-central/logs/glowroot-central.log]
18:58:56,461 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.google.common.util.concurrent.AggregateFuture] to OFF
18:58:56,461 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@2794eab6 - Propagating OFF level on Logger[com.google.common.util.concurrent.AggregateFuture] onto the JUL framework
18:58:56,461 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
18:58:56,461 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@2794eab6 - Propagating INFO level on Logger[ROOT] onto the JUL framework
18:58:56,464 |-INFO in ch.qos.logback.core.model.processor.conditional.IfModelHandler - Condition [p("glowroot.log.consoleOff").equalsIgnoreCase("true")] evaluated to false on line 35
18:58:56,464 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
18:58:56,465 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
18:58:56,465 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [audit] to OFF
18:58:56,465 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@2794eab6 - Propagating OFF level on Logger[audit] onto the JUL framework
18:58:56,465 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@45099dd3 - End of configuration.
18:58:56,466 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@13e344d - Registering current configuration as safe fallback point

2023-11-06 18:58:56.476 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-11-06 18:58:56.479 INFO  org.glowroot - Java version: 17.0.9
2023-11-06 18:58:56.780 INFO  c.d.o.d.i.c.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.15.0
2023-11-06 18:58:57.655 WARN  c.d.o.d.i.core.session.PoolManager - [s0] Detected a keyspace change at runtime (<none> => glowroot). This is an anti-pattern that should be avoided in production (see 'advanced.request.warn-if-set-keyspace' in the configuration).
2023-11-06 18:58:57.771 INFO  org.glowroot - connected to Cassandra (version 4.0.7), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM
2023-11-06 18:58:57.846 INFO  org.glowroot - creating glowroot central schema...
2023-11-06 18:59:00.886 ERROR org.glowroot - Query timed out after PT2S
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:376)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:305)
        at org.glowroot.central.util.Session.createTableWithTracking(Session.java:320)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:257)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:237)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:232)
        at org.glowroot.central.repo.AggregateDaoImpl.<init>(AggregateDaoImpl.java:303)
        at org.glowroot.central.repo.CentralRepoModule.<init>(CentralRepoModule.java:138)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:192)
        at org.glowroot.central.CentralModule.create(CentralModule.java:130)
        at org.glowroot.central.CentralModule.create(CentralModule.java:125)
        at org.glowroot.central.Main.start(Main.java:44)
        at org.glowroot.central.Main.main(Main.java:28)
Exception in thread "main" com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:376)
        at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:305)
        at org.glowroot.central.util.Session.createTableWithTracking(Session.java:320)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:257)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:237)
        at org.glowroot.central.util.Session.createTableWithTWCS(Session.java:232)
        at org.glowroot.central.repo.AggregateDaoImpl.<init>(AggregateDaoImpl.java:303)
        at org.glowroot.central.repo.CentralRepoModule.<init>(CentralRepoModule.java:138)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:192)
        at org.glowroot.central.CentralModule.create(CentralModule.java:130)
        at org.glowroot.central.CentralModule.create(CentralModule.java:125)
        at org.glowroot.central.Main.start(Main.java:44)
        at org.glowroot.central.Main.main(Main.java:28)
```

**Comment by Nowheresly** [comment]
Hi @HerbertKoelman 
thanks for reporting this. 
It's not related to the jvm version, Cassandra may be slow for DDL.
The next version should correct this. In the meantime, you could try the beta4 version that should improve this a little bit...

**Comment by HerbertKoelman** [comment]
I will give the beta4 a chance as suggested.

On the Cassandra side, do you know if an upgrade of my cassandra server might help ? I see that there is a Cassandra version 4.1 and 5.0.

**Comment by HerbertKoelman** [comment]
Hello @Nowheresly, I'm trying to build what's on the branch 0.14.1-beta.4 running `mvn compile` and I end up with this error below. 

Any suggestion ?

```
[INFO] Glowroot Agent ..................................... FAILURE [  0.002 s]
[INFO] Glowroot Central Collector ......................... SKIPPED
[INFO] Glowroot WebDriver Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:37 min
[INFO] Finished at: 2023-11-07T11:24:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to parse plugin descriptor for org.glowroot:glowroot-agent-dist-maven-plugin:0.14.1-beta.4 (/share/home/herbert/java/glowroot-0.14.1-beta.4/agent/dist-maven-plugin/target/classes): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException
```

**Comment by Nowheresly** [comment]
I'll have a look.
In the meantime, maybe using the prebuilt biraries is easier.
You can get then here:
[v0.14.1-beta.4](https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta.4)

**Comment by HerbertKoelman** [comment]
@Nowheresly thanks for the tip. I succeeded in setting up glowroot central. Thanks for your help :-)
