### ISSUE TITLE
[support] Remote Collection isn't working?

### ISSUE THREAD

**Issue by equake** [glowroot/glowroot#105]
HI @trask!
First of all: Glowroot is a great tool! Thanks for sharing it with us :)

I'm having issues setting up remote collection. What should I do to enable it?
I've started one standalone Glowroot instance and pointed my app server to it (using -Dglowroot.collector.host and -Dglowroot.collector.port) but I'm getting the following error in the logs:

`2016-07-15 18:59:06.372 WARN  o.g.a.s.n.u.c.PromiseNotifier - Failed to mark a promise as failure because it's done already: DefaultChannelPromise@55d978cc(failure: java.io.IOException: Broken pipe)
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.glowroot.agent.shaded.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:305)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:859)
	at org.glowroot.agent.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:375)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:826)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1436)
	at org.glowroot.agent.shaded.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:381)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at org.glowroot.agent.shaded.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:161)
	at org.glowroot.agent.shaded.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:381)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1129)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannel.flush(AbstractChannel.java:234)
	at org.glowroot.agent.shaded.grpc.netty.WriteQueue.flush(WriteQueue.java:131)
	at org.glowroot.agent.shaded.grpc.netty.WriteQueue.access$000(WriteQueue.java:48)
	at org.glowroot.agent.shaded.grpc.netty.WriteQueue$1.run(WriteQueue.java:58)
	at org.glowroot.agent.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at org.glowroot.agent.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at org.glowroot.agent.shaded.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)` 

What I am doing wrong?

Thanks!

**Comment by trask** [comment]
Hi, I'm glad you are interested in the central collector.  In order to scale to lots of agents, the central collector/UI is a separate service that stores all the data in Cassandra. The source for the central collector is in this repo under the "server" directory.  I've been making lots of improvement lately as I have been rolling out the central collector/UI where I work over the past few months. I recommend waiting for 0.9.1 release for other people to deploy it, sometime around the end of this month. And at that time I will add installation instructions and post back to this issue.  Thanks.

**Comment by equake** [comment]
Hi!

That's great to hear. I'm going to wait for 0.9.1 then while using 0.9.0 individually. 

Thanks again for sharing this great tool with us. :)

**Comment by trask** [comment]
0.9.1 has been released, please see [Optional central collector](../wiki/Optional-central-collector) for installation instructions for the central collector and post back with any questions.

**Comment by Deepti1HCL** [comment]
Hi @Trask ,
I have standalone glow root setup on my local machine and its working fine but I want to run it on remote server, I made changes in admin.json as below
 "web": {
    "port": <serverPort>,
    "bindAddress": <serverIP>,
    "contextPath": "/",
    "sessionTimeoutMinutes": 30,
    "sessionCookieName": "GLOWROOT_SESSION_ID"
  },

but not sure how it will point to remote server app, how should i start glowroot to point remote server app.
