### ISSUE TITLE
Bytecode service retrieved too early

### ISSUE THREAD

**Issue by yalcindogan** [glowroot/glowroot#1050]
Hi,

I got this error when I wanted to run the 0.14 glowroot agent in WebLogic 14.1.1.0. The only things in the glowroot log are these:

2023-11-13 18:13:57.964 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-11-13 18:13:57.967 INFO  org.glowroot - Java version: 11.0.17 (Oracle Corporation / Linux)
2023-11-13 18:13:57.968 INFO  org.glowroot - Java args: -Xms12288m -Xmx12288m -XX:CompileThreshold=8000 -XX:MaxMetaspaceSize=6144m --add-modules=java.se --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -javaagent:/app/Middleware/products/wl14110/wlserver/server/lib/debugpatch-agent.jar -da -javaagent:/app/glowroot/glowroot.jar

**The following are WebLogic logs:**
Starting WLS with line:
/app/Middleware/jdk/bin/java -server   -Xms12288m -Xmx12288m -XX:CompileThreshold=8000 -XX:MaxMetaspaceSize=6144m -Dweblogic.Name=granite_core_3 -Djava.security.policy=/app/Middleware/products/wl14110/wlserver/server/lib/weblogic.policy  -Dweblogic.ProductionModeEnabled=true  -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Dxng.log.server=granite_core_3 -Dnashorn.args=--no-deprecation-warning -Doracle.jdbc.fanEnabled=false --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED --add-exports jdk.unsupported/sun.reflect=ALL-UNNAMED  -javaagent:/app/Middleware/products/wl14110/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/app/Middleware/products/wl14110/wlserver/server -Dweblogic.home=/app/Middleware/products/wl14110/wlserver/server   -Dweblogic.management.server=http://persian00sap0:7001  -javaagent:/app/glowroot/glowroot.jar -Dglowroot.agent.id=granite_core_3 -Dglowroot.agent.rollup.id=granite  weblogic.Server
2023-11-13 18:13:57.964 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-11-13 18:13:57.967 INFO  org.glowroot - Java version: 11.0.17 (Oracle Corporation / Linux)
2023-11-13 18:13:57.968 INFO  org.glowroot - Java args: -Xms12288m -Xmx12288m -XX:CompileThreshold=8000 -XX:MaxMetaspaceSize=6144m --add-modules=java.se --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -javaagent:/app/Middleware/products/wl14110/wlserver/server/lib/debugpatch-agent.jar -da -javaagent:/app/glowroot/glowroot.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at weblogic.Server.main(Server.java)
Caused by: java.lang.RuntimeException: Bytecode service retrieved too early
        at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:32)
        at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:26)
        ... 1 more

I am waiting for your valuable help.
Thanks.

**Comment by Never-lab** [comment]
## Triage

WebLogic **14.1.1** / Java 11 / Glowroot **0.14.0** — JVM fails at startup:

```
ExceptionInInitializerError
Caused by: RuntimeException: Bytecode service retrieved too early
  at BytecodeServiceHolder.get (classLoader == null → bootstrap)
  at Bytecode.<clinit>
```

`Bytecode` static-init calls `BytecodeServiceHolder.get()` before the agent finishes `premain` and registers the service. On WebLogic this happens because woven `weblogic.Server.main` triggers bytecode helpers while Glowroot is still starting. Complicated by **two javaagents** (`debugpatch-agent.jar` + `glowroot.jar`) and WebLogic's `LaunchClassLoader`.

Similar root cause was fixed in #511 (`BytecodeSafe` for early MBean access), but this path still fails on WL 14.

**Suggestions to try:**
1. Upgrade to latest 0.14.8-beta.x
2. Test with only `glowroot.jar` (remove debugpatch-agent temporarily)
3. Ensure `-javaagent:glowroot.jar` is last among agents
4. Share full startup log if still failing on current version

**Verdict:** **keep open** as bug (`plugin`/WebLogic startup). Needs repro on current agent + WL version.

---
*Community triage*

**Comment by Never-lab** [comment]
Closing as **obsolete**.

This report predates the current 0.14.x line, has no recent reproducible path, and we are not keeping it open without a fresh repro on a supported build. If it still happens, please open a new issue with version, JVM, and a minimal repro.

**Brief analysis:** Bytecode service timing bug awaiting feedback; no minimal repro on current agent.
