### ISSUE TITLE
spring boot 3 and logback 4 java.lang.IncompatibleClassChangeError 

### ISSUE THREAD

**Issue by zd-dalibor** [glowroot/glowroot#1055]
Hi, I think that glowroot 0.14.0 is not compatible with logback 1.4.11.

I am getting this error:
![image](https://github.com/glowroot/glowroot/assets/226822/cc437dd0-d22f-4003-b994-49043e69b356)

**Comment by Nowheresly** [comment]
I see logback 1.4.14 is now available. Does it help fixing the issue?

**Comment by zd-dalibor** [comment]
@Nowheresly
Nop. I got the same error:
`Caused by: java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.Level does not implement the requested interface org.glowroot.agent.plugin.logger.LogbackAspect$Level`

**Comment by Nowheresly** [comment]
Could you try with the latest version of glowroot available [here](https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta.6) ?

**Comment by GuiF007** [comment]
I have same problem, I tried with your beta version and not working :/

`[ERROR] 16:50:34 [ANON][]             org.apache.catalina.core.ContainerBase - A child container failed during start 
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:488)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:105)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:499)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:218)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:464)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
	at fr.XXXXXX.XXXX.XXXX.XXXX.XXXXXApplication.main(XXXXXApplication.java:10)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:885)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	... 21 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
	... 30 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:419)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:186)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	... 30 common frames omitted
Caused by: java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.Level does not implement the requested interface org.glowroot.agent.plugin.logger.LogbackAspect$Level
	at org.glowroot.agent.plugin.logger.LogbackAspect$CallAppendersAdvice.onBefore(LogbackAspect.java:91)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:426)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.log(Logger.java:780)
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.info(LogAdapter.java:452)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.prepareWebApplicationContext(ServletWebServerApplicationContext.java:296)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:237)
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:52)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4850)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)`

**Comment by Nowheresly** [comment]
I just used start.spring.io to generate a sample spring project. And I'm unable to reproduce the issue. Could you provide a minimalistic project that reproduces the issue ?

**Comment by GuiF007** [comment]
I have to analyze what's the difference between two of our project, because one is affected, not the other, and it's the same common base :/

**Comment by GuiF007** [comment]
Looks like it's IntelliJ debug mode the guilty when this problem occurs !
I don't have this problem with no debug mode.

**Comment by zd-dalibor** [comment]
@GuiF007
Yes, I can confirm your statement.
This error appears only when I run application in debug mode in IntelliJ.

**Comment by ctobe-zen** [comment]
Did anyone fix this in IntelliJ?

**Comment by razisam** [comment]
> Did anyone find a fix for this? I mainly use glowroot while debugging in Intellij :-(

let's try this way:
https://youtrack.jetbrains.com/issue/IDEA-360896/java.lang.IncompatibleClassChangeError-Class-ch.qos.logback.classic.Level-does-not-implement-the-requested-interface

**Comment by Never-lab** [comment]
Closing as **obsolete**.

This report predates the current 0.14.x line, has no recent reproducible path, and we are not keeping it open without a fresh repro on a supported build. If it still happens, please open a new issue with version, JVM, and a minimal repro.

**Brief analysis:** Spring Boot 3 / Logback compatibility is already tracked under epic #1244 — use that instead of this 2023 report.
