### ISSUE TITLE
JDK21/Glowroot  0.14.2-beta.3 --> java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by razisam** [glowroot/glowroot#1072]
```
Connected to the target VM, address: '127.0.0.1:59636', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2024-03-27 11:17:30.286 INFO  org.glowroot - Glowroot version: 0.14.2-beta.3, built 2024-03-25 17:32:31 +0000
2024-03-27 11:17:30.289 INFO  org.glowroot - Java version: 21.0.2 (Microsoft / Windows 10)
2024-03-27 11:17:30.290 INFO  org.glowroot - Java args: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59636,suspend=y,server=n -Xms256m -Xmx512m -javaagent:XXXXXXXX/glowroot.jar -javaagent:XXXXXX\IntelliJ\plugins\Groovy\lib\agent\gragent.jar -javaagent:XXXXXXX\IntelliJ\plugins\java\lib\rt\debugger-agent.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2024-03-27 11:17:33.936 INFO  org.glowroot - creating glowroot schema...
2024-03-27 11:17:34.110 INFO  org.glowroot - glowroot schema created
...
2024-03-27 11:17:34.658 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
...
```

![image](https://github.com/glowroot/glowroot/assets/59828907/ea1a7b8e-7127-4b20-885e-dfb86eb6c3d6)

```
2024-03-27 11:17:51.420 ERROR o.g.a.e.s.o.g.ui.CommonHandler - java.lang.UnsupportedOperationException
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionJsonService.getOverview(TransactionJsonService.java:106)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:585)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:324)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:235)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handle(CommonHandler.java:159)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at org.glowroot.agent.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsupportedOperationException: null
	at org.glowroot.agent.shaded.com.google.common.collect.ImmutableCollection.addAll(ImmutableCollection.java:292)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.lambda$getOverviewAggregates$3(TransactionCommonService.java:167)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.lambda$getOverviewAggregates$4(TransactionCommonService.java:165)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.getOverviewAggregates(TransactionCommonService.java:140)
	... 39 common frames omitted
```

**Comment by Nowheresly** [comment]
Hi @razisam 
thanks for the report. It should be fixed in the next beta release.

**Comment by rob-dotmatics** [comment]
I see a very similar issue in the 0.14.2 release build, but triggered by `getPercentileAggregates` instead of `getOverviewAggregrates` - shall I raise a new issue @Nowheresly? 

```
2024-06-18 09:52:37.987 ERROR o.g.a.e.s.o.g.ui.CommonHandler - java.lang.UnsupportedOperationException
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionJsonService.getPercentiles(TransactionJsonService.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:585)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:324)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:235)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handle(CommonHandler.java:159)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at org.glowroot.agent.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsupportedOperationException: null
at org.glowroot.agent.shaded.com.google.common.collect.ImmutableCollection.addAll(ImmutableCollection.java:297)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.lambda$getPercentileAggregates$6(TransactionCommonService.java:230)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.lambda$getPercentileAggregates$7(TransactionCommonService.java:228)
at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.getPercentileAggregates(TransactionCommonService.java:203)
... 39 common frames omitted
```
