### ISSUE TITLE
Getting no such method error OverallSummaryCollector.mergeSummary(double, long, long) while running glowroot.

### ISSUE THREAD

**Issue by sahilkamboj334** [glowroot/glowroot#1075]
I have checked the repo code and mentioned code does not exist. 
glowroot version - 0.14.2
java version - 17
platform - linux
Below are the logs

`2024-05-02 17:01:52.329 ERROR o.g.a.e.s.o.g.ui.CommonHandler - null
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor849.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:585)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:324)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:235)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handle(CommonHandler.java:159)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at org.glowroot.agent.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'void org.glowroot.agent.shaded.org.glowroot.common.model.OverallSummaryCollector.mergeSummary(double, long, long)'
        at org.glowroot.agent.embedded.repo.AggregateDao$OverallSummaryQuery.processResultSet(AggregateDao.java:671)
        at org.glowroot.agent.embedded.repo.AggregateDao$OverallSummaryQuery.processResultSet(AggregateDao.java:634)
        at org.glowroot.agent.embedded.util.DataSource.query(DataSource.java:287)
        at org.glowroot.agent.embedded.repo.AggregateDao.mergeOverallSummaryInto(AggregateDao.java:254)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionCommonService.readOverallSummary(TransactionCommonService.java:91)
        at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionJsonService.getSummaries(TransactionJsonService.java:433)
        ... 39 common frames omitted
`

**Comment by Never-lab** [comment]
`NoSuchMethodError: OverallSummaryCollector.mergeSummary(double, long, long)` means the **running agent has mismatched Glowroot classes** (an older `AggregateDao` calling a newer/different `OverallSummaryCollector`, or the reverse). Current `main` uses a wider `mergeSummary(...)` signature — this is not something you fix by editing app code.

Typical causes: mixed jars from two Glowroot versions on the classpath, a partial copy/upgrade of `glowroot.jar` / plugins, or an old unpack left beside a new jar.

Please retry with a **clean** [0.14.7 dist](https://github.com/glowroot/glowroot/releases/tag/v0.14.7) (single `glowroot.jar` from that zip, no leftover older agent files), then reopen only if it still fails on a clean install.

@nowheresly — please close as support / environment unless reproduced on current 0.14.x clean dist.
