### ISSUE TITLE
Cannot start the Java project in IntelliJ IDEA using JRebel and Glowroot

### ISSUE THREAD

**Issue by wanqiu410** [glowroot/glowroot#1084]
IntelliJ IDEA version: 2024.1.2
JRebel version: 2024.2.1
Mac OS:12.6.1

When starting up using JRebel + Glowroot, an error occurs (it has been determined to be caused by JRebel through the process of elimination).
The error log is as follows:
2024-05-29 21:38:54.043 INFO  org.glowroot - Glowroot version: 0.14.2, built 2024-04-06 19:02:00 +0000
2024-05-29 21:38:54.044 INFO  org.glowroot - Java version: 17.0.2 (Oracle Corporation / Mac OS X)
2024-05-29 21:38:54.044 INFO  org.glowroot - Java args: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50570,suspend=y,server=n -Xshare:off -agentpath:/Users/hand/Library/Application Support/JetBrains/IntelliJIdea2024.1/plugins/jr-ide-idea/lib/jrebel6/lib/libjrebel64.dylib -javaagent:/Users/hand/soft/glowroot0.14.2/glowroot.jar --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED -XX:TieredStopAtLevel=1 -javaagent:/Users/hand/Library/Caches/JetBrains/IntelliJIdea2024.1/captureAgent/debugger-agent.jar=file:/private/var/folders/9f/lq_s52q15w3_ph6mtfpxw1q80000gn/T/capture.props
2024-05-29 21:38:54.657 ERROR org.glowroot.agent.weaving.Weaver - not reweaving org.apache.logging.log4j.spi.AbstractLogger because cannot add shim type: org.glowroot.agent.plugin.logger.Log4j2xAspect$Logger
2024-05-29 21:38:54.664 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving org/apache/logging/log4j/spi/AbstractLogger: 'boolean org.glowroot.agent.plugin.executor.ExecutorAspect$ThreadInitWithThreadGroupAdvice.onBefore(boolean, org.glowroot.agent.plugin.api.ThreadContext, java.lang.ThreadGroup, org.glowroot.agent.plugin.api.ParameterHolder)'
java.lang.NoSuchMethodError: 'boolean org.glowroot.agent.plugin.executor.ExecutorAspect$ThreadInitWithThreadGroupAdvice.onBefore(boolean, org.glowroot.agent.plugin.api.ThreadContext, java.lang.ThreadGroup, org.glowroot.agent.plugin.api.ParameterHolder)'
	at java.base/java.lang.Thread.<init>(Thread.java)
	at java.base/java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:660)
	at org.glowroot.agent.shaded.com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(ThreadFactoryBuilder.java:173)
	at org.glowroot.agent.util.ThreadFactories$1.newThread(ThreadFactories.java:34)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:630)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1353)
	at org.glowroot.agent.init.CollectorLogbackAppender.flush(CollectorLogbackAppender.java:101)
	at org.glowroot.agent.init.CollectorLogbackAppender.append(CollectorLogbackAppender.java:90)
	at org.glowroot.agent.init.CollectorLogbackAppender.append(CollectorLogbackAppender.java:38)
	at org.glowroot.agent.shaded.ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at org.glowroot.agent.shaded.ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at org.glowroot.agent.shaded.ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at org.glowroot.agent.shaded.ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at org.glowroot.agent.shaded.ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at org.glowroot.agent.shaded.ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at org.glowroot.agent.shaded.ch.qos.logback.classic.Logger.error(Logger.java:530)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:242)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformJava9(WeavingClassFileTransformer.java:77)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl._jrDoTransform(InstrumentationImpl.java:541)
	at java.instrument/sun.instrument.InstrumentationImpl._jrTransform(InstrumentationImpl.java:42001)
	at java.base/com.zeroturnaround.jrebelbase.reorder.b.transform(SourceFile:180)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:43001)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at org.glowroot.agent.live.LiveWeavingServiceImpl.initialReweave(LiveWeavingServiceImpl.java:262)
	at org.glowroot.agent.weaving.AdviceCache.initialReweave(AdviceCache.java:158)
	at org.glowroot.agent.init.AgentModule.<init>(AgentModule.java:208)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit.init(NonEmbeddedGlowrootAgentInit.java:105)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:266)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl._jrLoadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.base/com.zeroturnaround.jrebelbase.reorder.b.start(SourceFile:106)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:41001)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
2024-05-29 21:38:54.971 WARN  org.glowroot - one or more important classes were loaded before Glowroot instrumentation could be applied to them: java.net.HttpURLConnection, java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask, java.util.concurrent.CompletableFuture$UniHandle, java.util.concurrent.CompletableFuture$UniCompletion, java.util.concurrent.CompletableFuture$Completion, java.util.concurrent.ThreadPoolExecutor$Worker, java.util.concurrent.ExecutorCompletionService$QueueingFuture, java.util.concurrent.Executors$RunnableAdapter, java.util.concurrent.FutureTask. This likely occurred because there are one or more native agents listed in the JVM args (-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50570,suspend=y,server=n -agentpath:/Users/hand/Library/Application Support/JetBrains/IntelliJIdea2024.1/plugins/jr-ide-idea/lib/jrebel6/lib/libjrebel64.dylib), and native agents have higher loading precedence than java agents.

Current solution:
Modify the glowroot.plugins.json within the glowroot.jar file.
Remove the following content:
{
    "id": "executor",
    "name": "Executor Plugin",
    "aspects": [
      "org.glowroot.agent.plugin.executor.ExecutorAspect"
    ],
    "collocate": false
}
After this modification, JRebel + Glowroot can launch the project.

Hope to resolve this issue so that the ExecutorAspect plugin can be used normally.

**Comment by Never-lab** [comment]
JRebel is a **native agent** (`-agentpath`); those load before `-javaagent`, which is why Glowroot also warns that important JDK classes were already loaded. The `NoSuchMethodError` on `ExecutorAspect$ThreadInitWithThreadGroupAdvice.onBefore` during JRebel’s retransform path is a known painful combo (Glowroot weaver + JRebel instrumentation), not a general Executor plugin failure in plain JVM runs.

Practical options today:

1. Dev without JRebel when you need Glowroot, or without Glowroot when you need JRebel.
2. Keep your workaround: disable the **executor** plugin (or don’t ship that plugin jar) if you must run both — selective exclude of one plugin is the supported escape hatch; editing `glowroot.plugins.json` inside the jar works but is brittle across upgrades (prefer removing/renaming the executor plugin jar under `plugins/` if your dist layout allows).
3. Put `-javaagent:glowroot.jar` as early as the launcher allows; it still won’t beat a native agent’s precedence.

A durable “JRebel + all plugins” fix would be a weaving/compatibility enhancement — not a quick config flip. Further how-to → [Discussions](https://github.com/glowroot/glowroot/discussions).

@nowheresly — keep open as compatibility/enhancement, or close if you prefer Discussions-only for JRebel combos.
