### ISSUE TITLE
Unsupported class file major version 61

### ISSUE THREAD

**Issue by mikitex70** [glowroot/glowroot#1086]
Hi all, tank you for this great software.
I'm experiencing a recurring error with GlowRoot Agent 0.14.2 (I'm using `glowroot.jar` from the `dist` release).
This is the typical stack trace:
```
2024-05-31 08:41:28.501 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving jdk/internal/reflect/GeneratedMethodAccessor144: Unsupported class file major version 61
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:294)
	at org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:240)
	at org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:187)
	at org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:144)
	at org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:143)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:213)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformJava9(WeavingClassFileTransformer.java:77)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2303)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:66)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:401)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:395)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:394)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:63)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:657)
	at com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:456)
       ...
```

The method `GeneratedMethodAccessor144` is changing every time, seems to have some kind of counter at the end.
I suspect it is related to MongoDB query traces, but I'm not sure.
The application is not affected, but the error fills the logs.
Let me know if you need more info.

**Comment by vsoldera** [comment]
I'm having the exact same problem, but mine is throwing Unsupported class file major version 65. Maybe this has to be with unsupported java versions?

**Comment by Nowheresly** [comment]
Hi @mikitex70 

as you can see here, the latest version of the glowroot agent (0.14.2) is filtering dynamic proxies (such as class whose name starts with `jdk/internal/reflect/Generated*`) from being weaved.

https://github.com/glowroot/glowroot/blob/bb302f74392da671b5bc214d5f2a538f1de90338/agent/core/src/main/java/org/glowroot/agent/weaving/WeavingClassFileTransformer.java#L132

Yet, your stack trace suggests classes starting with `jdk/internal/reflect/Generated*` are still weaved... which makes me think that you may be using a glowroot agent older than this commit: 

https://github.com/search?q=repo%3Aglowroot%2Fglowroot+cf8b5a3bdb6237a07186361f9316bad1cf1e49b1&type=commits

or you may have some configuration that may override the default behavior of the weaving class?

**Comment by mikitex70** [comment]
Hi all, sorry for the delay.
I rebuilt the Docker image of the application I am testing, and which contains the GlowRoot client.
Everything is working correctly now, evidently the GlowRoot jar had not been updated correctly.
Sorry for the false problem.
