### ISSUE TITLE
[0.14.3-beta4]Central colector warnings in querrys to cassandra

### ISSUE THREAD

**Issue by FilipeCoelhoAlves** [glowroot/glowroot#1100]
Good morning friends

I have some warnings and I wanted to know if it could be a problem with glowroot or some configuration to be done in cassandra

`WARN  [epollEventLoopGroup-5-5] 2024-07-30 08:20:16,709 ExceptionHandlers.java:139 - Unknown exception in client networking
io.netty.handler.codec.DecoderException: org.apache.cassandra.transport.messages.ErrorMessage$WrappedException: org.apache.cassandra.exceptions.InvalidRequestException: Request is too big: length 21749760 exceeds maximum allowed length 16777216.
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:388)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.cassandra.transport.messages.ErrorMessage$WrappedException: org.apache.cassandra.exceptions.InvalidRequestException: Request is too big: length 21749760 exceeds maximum allowed length 16777216.
        at org.apache.cassandra.transport.messages.ErrorMessage.wrap(ErrorMessage.java:470)
        at org.apache.cassandra.transport.Envelope$Decoder.fail(Envelope.java:450)
        at org.apache.cassandra.transport.Envelope$Decoder.decode(Envelope.java:341)
        at org.apache.cassandra.transport.Envelope$Decoder.decode(Envelope.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        ... 17 common frames omitted
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: Request is too big: length 21749760 exceeds maximum allowed length 16777216.
        ... 22 common frames omitted
`

**Comment by Never-lab** [comment]
@FilipeCoelhoAlves — that WARN is Cassandra rejecting a CQL frame, not a Glowroot query bug.

`Request is too big: length 21749760 exceeds maximum allowed length 16777216` means Central sent ~21 MiB and Cassandra's default native-transport max is 16 MiB (`native_transport_max_frame_size` / `native_transport_max_frame_size_in_mb`). Fat traces / query text / profiles can push inserts over that limit.

Ops today: prefer cutting volume first (raise slow threshold, tighten full query text / capture, quiet noisy agents — same capacity family as #748 / #899). Escape hatch: raise `native_transport_max_frame_size_in_mb` in `cassandra.yaml` (often align `max_value_size_in_mb`), restart Cassandra. Huge blobs stay a bad idea for C* latency/repair. See https://github.com/glowroot/glowroot/wiki/Troubleshooting-Tips and https://github.com/glowroot/glowroot/wiki/Administration-Storage

Product angle: Central does not pre-check or chunk writes against the 16 MiB frame, so fat payloads fail at Cassandra instead of being truncated/split with a clear agent/central log. That is a real gap, but workability is low priority unless this is frequent — a guard/chunk path is medium effort and needs fat-trace fixtures. Keeping the issue open for that, not closing as FAQ-only.

If it still happens on current 0.14.x, paste Cassandra version and whether writes/UI fail or you only see this WARN.

@nowheresly — keeping open as capacity / possible Central write sizing (ops workaround exists).
