### ISSUE TITLE
Glowroot cannot start error General error: "java.lang.RuntimeException: page[xxxxx] data leaf table:24 T24 entries:1 parent:yyyyy overflow:508494 keys:[xxxxx] offsets:[21] parent aaaa expected bbbb" [50000-176]

### ISSUE THREAD

**Issue by clambert51** [glowroot/glowroot#1103]
Hi,

got this error on JVM startup with embedded collector

2024-08-21 00:08:42.611 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2024-08-21 00:08:42.612 INFO  org.glowroot - Java version: 1.8.0_341 (Oracle Corporation / Linux)
2024-08-21 00:08:42.613 INFO  org.glowroot - Java args: -Xms32768m -Xmx32768m -Xss1m -XX:NewRatio=3 -XX:+UseConcMarkSweepGC -XX:Survi
vorRatio=3 -XX:+CMSClassUnloadingEnabled -XX:+CMSIncrementalMode -XX:CMSInitiatingOccupancyFraction=40 -XX:+DisableExplicitGC -XX:+Us
eParNewGC -javaagent:/var/opt/application/alfresco/glowroot/glowroot.jar
2024-08-21 00:08:45.898 ERROR org.glowroot - Glowroot cannot start: General error: "java.lang.RuntimeException: page[445575] data leaf table:24 T24 entries:1 parent:363424 overflow:508494 keys:[2515531] offsets:[21] parent 363424 expected 580" [50000-176]
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: General error: "java.lang.RuntimeException: page[445575] data leaf t
able:24 T24 entries:1 parent:363424 overflow:508494 keys:[2515531] offsets:[21] parent 363424 expected 580" [50000-176]
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:167)
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.convert(DbException.java:294)
        at org.glowroot.agent.embedded.shaded.org.h2.table.RegularTable.removeRow(RegularTable.java:408)
        at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.redo(PageStore.java:1577)
        at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.redoDelete(PageStore.java:1550)
        at org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.recover(PageLog.java:347)
        at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.recover(PageStore.java:1407)

forced to delete collected files for it to work again

didn't find any other cases like this => have you ever encountered such an issue?

we still have not upgraded to latest version cause embedded collector 0.14.x didn't work with Java 8, we have tested the 0.14.2 because the Percentile display is NOK (relates to https://github.com/glowroot/glowroot/issues/1072 ?)
0.14.1 seems OK however

should we upgrade? 

Thank you.
Regards.

**Comment by clambert51** [comment]
of course then we find the following logs

...
2024-08-20 00:00:47.360 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 10 warnings were suppressed since it was last logged)
2024-08-20 00:01:00.001 WARN  o.g.agent.impl.TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2024-08-20 00:01:47.383 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 11 warnings were suppressed since it was last logged)
...

**Comment by Never-lab** [comment]
Hi @clambert51 — thanks for the detailed logs.

## What the error is

`page[...] data leaf table ... parent X expected Y` with `[50000-176]` is classic **H2 PageStore file corruption** during recovery (your stack is in `PageStore.recover` / `redoDelete`). Glowroot embedded 0.13.x uses shaded H2 **1.3.x** (PageStore). Once the on-disk store is inconsistent, the agent cannot open it and fails startup — deleting the Glowroot `data` directory (as you did) is the usual recovery.

This is typically **not** an application code bug; common triggers:

- abrupt JVM/host kill while H2 was writing
- disk full / I/O errors
- storage backlog so severe that the process is under heavy write pressure (your follow-up warnings fit this)

The gauge/aggregate backlog warnings:

```
not storing a gauge collection because of an excessive backlog...
not storing an aggregate because of an excessive backlog...
```

mean the embedded collector could not keep up with writes **before** the corrupt open. That often goes together with large retention / capped DB sizes, slow disk, or very busy apps.

## Practical guidance

1. **Short term:** keep a backup of `glowroot/data` only if you need forensics; otherwise empty/recreate `data` so Glowroot can start (you already did this).
2. **Reduce write pressure** (Administration → Storage): lower rollup/trace retention and capped database sizes so H2 stays smaller and flushes less aggressively.
   - We are also implementing **embedded Deployment profile presets (Dev / Prod)** that apply leaner rollup expiration + capped sizes (and lighter profiling) in one place — see PR https://github.com/glowroot/glowroot/pull/1188 (draft). That should make the “Prod / shared JVM” storage sizing path easier without hand-tuning every field.
3. **Upgrade path:**
   - You are on **0.13.6** (2020) + **Java 8**.
   - Current **0.14.x agent still targets Java 8** for the agent/embedded collector (central collector needs a newer JDK). If an earlier 0.14.x trial failed on Java 8, please share that stack — worth separating from this H2 corruption.
   - **0.14.1+** is also the right direction for the percentile display issues you mentioned (#1072 area).
   - Newer 0.14 builds moved embedded storage to a newer H2 (MVStore); that changes the corruption/perf profile (some users report higher CPU with large DBs — see #1180 — so sizing storage still matters).

## Questions (to close or escalate)

- Did corruption recur after wiping `data`, or was it a one-off after a crash/restart?
- Rough size of `glowroot/data` and disk type (local SSD vs NFS)?
- Can you try **0.14.7** (or latest 0.14.8-beta) on a non-prod Java 8 node with a **fresh** data dir and report whether startup + percentiles look OK?

If it was a one-off after wipe and you’ve since upgraded / tightened storage, we can close this as “corrupt H2 store + recovery by recreating data.”

---

cc @nowheresly @trask — if the reporter confirms it was a one-off (or no further feedback after upgrade / storage sizing), please **close** as resolved / not a persistent product bug.
