### ISSUE TITLE
Unable to Start Springboot 3.3.2 OpenJDK 17 App with Glowroot version 0.14.2

### ISSUE THREAD

**Issue by pallerana** [glowroot/glowroot#1105]
I am seeing below error when am tryign to start the  Springboot 3.3.2 OpenJDK 17 App with Glowroot version 0.14.2
```
2024-10-01 12:27:11.192[HW0015904,partner,,,,][main][ERROR][SpringApplication] - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at us.enterprise.partner.PartnerApplication.main(PartnerApplication.java:28)
Caused by: java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.Level does not implement the requested interface org.glowroot.agent.plugin.logger.LogbackAspect$Level
	at org.glowroot.agent.plugin.logger.LogbackAspect$CallAppendersAdvice.onBefore(LogbackAspect.java:91)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:426)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.log(Logger.java:780)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.logging.Slf4jLocationAwareLogger.doLog(Slf4jLocationAwareLogger.java:100)
	at org.jboss.logging.Slf4jLocationAwareLogger.doLog(Slf4jLocationAwareLogger.java:85)
	at org.jboss.logging.Logger.info(Logger.java:976)
	at org.jboss.logging.DelegatingBasicLogger.info(DelegatingBasicLogger.java:508)
	at io.undertow.servlet.spec.ServletContextImpl.log(ServletContextImpl.java:372)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.prepareWebApplicationContext(ServletWebServerApplicationContext.java:286)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:237)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory$Initializer.onStartup(UndertowServletWebServerFactory.java:509)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createManager(UndertowServletWebServerFactory.java:331)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
```

**Comment by baov** [comment]
I can not start either: 

`work.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at com.oxand.simeox.SimeoXApplication.main(SimeoXApplication.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
2024-10-03 17:07:12.174 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving org/springframework/security/web/authentication/session/SessionAuthenticationException: Unsupported class file major version 65
java.lang.IllegalArgumentException: Unsupported class file major version 65`

Notes : 
- sprinboot 3
- jdk 21

**Comment by Never-lab** [comment]
Hi @pallerana — thanks for the stack trace.

## Original report (`IncompatibleClassChangeError` / Logback)

This looks like the known **Logback 1.5.x** incompatibility with Glowroot’s logger plugin. Spring Boot 3.3 ships Logback 1.5, and older agent builds used a `@Shim` on `ILoggingEvent` that breaks with:

`Class ch.qos.logback.classic.Level does not implement the requested interface ... LogbackAspect$Level`

That was fixed in:

- commit `c03c3f5b1` — *Fix Logback 1.5.x IncompatibleClassChangeError in LogbackAspect*
- first released in **Glowroot 0.14.5** (and later)

**Please try agent ≥ 0.14.5** (ideally current **0.14.7** / latest 0.14.8-beta) with the same `-javaagent:.../glowroot.jar` setup and report back whether the app starts cleanly. If it does, we can close this.

Workaround if you must stay on 0.14.2 temporarily: disable the logger plugin (remove/rename `plugins/logger-plugin-*.jar` under the Glowroot directory) — you lose log-as-trace-entry capture, but the app should boot.

## Comment from @baov (different error)

`Failed to find Premain-Class manifest attribute in .../glowroot-central-collector-https-osx.jar` means the JVM `-javaagent` path points at the **central HTTPS collector helper JAR**, not the agent.

Use the agent distribution’s `glowroot.jar` (from the agent zip), e.g.:

```
-javaagent:/path/to/glowroot/glowroot.jar
```

The `glowroot-central-collector-https-*.jar` files are not Java agents.

---

cc @nowheresly @trask — if the reporter confirms with ≥ 0.14.5 (or no further feedback), this looks safe to **close as fixed**.
