### ISSUE TITLE
Long Traces & Query Stats are not Showing up and through a Javascript error

### ISSUE THREAD

**Issue by Haseeb-Akram** [glowroot/glowroot#1107]
Here is its error stack;

scripts.938ba2e0.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.<anonymous> (scripts.938ba2e0.js:1:38639)
    at 5 (scripts.938ba2e0.js:1:244972)
    at Object.o [as fn] (vendor.78a2e137.js:1:391003)
    at Object.<anonymous> (scripts.938ba2e0.js:1:36411)
    at Object.main (scripts.938ba2e0.js:1:252913)
    at r (vendor.78a2e137.js:1:389195)
    at Object.c [as trace-entry] (vendor.78a2e137.js:1:389348)
    at E (scripts.938ba2e0.js:1:47665)
    at Object.<anonymous> (scripts.938ba2e0.js:1:42671)
    at i (vendor.78a2e137.js:1:27177)

﻿

**Comment by Never-lab** [comment]
Already fixed on current `main` (Handlebars `ifLongMessage` / `ifLongQuery` guards for truncated `sharedQueryText` without `fullText` — see `ui/app/scripts/handlebars-rendering.js`). Landed via the #1187 work (rebase onto main).

Please retest on [0.14.7+](https://github.com/glowroot/glowroot/releases) / latest main; if Entries / Query Stats still throw `.length` on a long truncated query, comment with version + a sample trace.

@nowheresly — please **close** as fixed.
