### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glowroot/agent/weaving/GeneratedMethodMeta*

### ISSUE THREAD

**Issue by mauromol** [glowroot/glowroot#1112]
Recently the following error started to happen on our EAR application being deployed on JBoss EAP 7.4:

```
Caused by: java.lang.NoClassDefFoundError: org/glowroot/agent/weaving/GeneratedMethodMeta81
        at org.glowroot.agent.weaving.MetaHolder659.<clinit>(Unknown Source)
        at com.example.Foo$$$view739.getBar(Unknown Source)
[...]
Caused by: java.lang.ClassNotFoundException: org.glowroot.agent.weaving.GeneratedMethodMeta81 from [Module "deployment.our-ear.ear.Example.jar" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 226 more
```

Nothing special is printed to the Glowroot log, just the same error.
Any idea of what is going on? How can we troubleshoot?
If we disable Glowroot, everything works fine and our application is getting deployed correctly. With this problem, instead, the application deployment fails.

It started to happen with 0.14.0-beta3, but then we upgraded to 0.14.2 and the same error persists.

Thanks.

**Comment by novumMatjaz** [comment]
Hi, I am getting the same error on the version 0.14.2.
Using Wildfly 26. The application server starts up and glowroot agent is reporting, but at some point it just crashed due to the class not found.

**Comment by Never-lab** [comment]
Hi @mauromol @novumMatjaz — thanks for the stacks and the EAR-lib workaround note.

## What is going on

This is a **JBoss / WildFly module classloader visibility** problem, not a missing Glowroot JAR on disk.

When Glowroot weaves an application class it:

1. Defines a generated `MetaHolder*` into the **deployment** `ModuleClassLoader`
2. That holder’s `<clinit>` does `new org.glowroot.agent.weaving.GeneratedMethodMetaN(...)`
3. Those `GeneratedMethodMeta*` / `GeneratedAdvice*` classes live in the **agent / bootstrap** loader

JBoss modules do **not** automatically expose agent packages to deployment modules, so you get:

```text
ClassNotFoundException: org.glowroot.agent.weaving.GeneratedMethodMeta81
  from [Module "deployment....ear....jar"]
```

The `Foo$$$view739` frame is also a clue: JBoss/Weld (or similar) **proxy/view** classes are being woven, which makes the isolation issue show up at deploy/runtime.

Putting `glowroot.jar` into the EAR `lib` (as @novumMatjaz did) can “work” by changing what the deployment classloader can see, but the supported approach with `-javaagent` is to mark Glowroot packages as system packages.

## Workaround to try first

Add (or append) Glowroot to `jboss.modules.system.pkgs` so deployment modules can load agent weaving classes from the system/bootstrap loader:

```bash
-Djboss.modules.system.pkgs=org.glowroot
```

If you already set that property for other agents, **append**:

```bash
-Djboss.modules.system.pkgs=org.jboss.byteman,org.glowroot
```

(Keep any packages you already need; this is a comma-separated list.)

Still use only:

```bash
-javaagent:/path/to/glowroot/glowroot.jar
```

Do **not** point `-javaagent` at a central collector helper JAR, and prefer **not** shipping `glowroot.jar` inside the EAR once `system.pkgs` is set correctly.

## Troubleshooting / logging

Agent logging is Logback (`glowroot.logback.xml` next to the agent, or override). For weaving noise you can raise the weaving package temporarily, e.g. logger `org.glowroot.agent.weaving` to `DEBUG` — but this particular failure usually does **not** need that: the CNFE from the deployment module is already the smoking gun.

## Questions

- Exact JVM args (especially any existing `jboss.modules.system.pkgs`)?
- Does adding `org.glowroot` to `system.pkgs` fix deploy on EAP 7.4 / WildFly 26 without putting the agent in the EAR?
- Which Glowroot plugins / custom instrumentation configs are enabled (custom instrumentation that uses templates creates more `GeneratedMethodMeta*` classes)?

This has been reported on **0.14.0-beta3 → 0.14.4**; I don’t believe it is fixed purely by upgrading — it needs the classloader visibility fix above (or equivalent).

---

cc @nowheresly @trask — if the `jboss.modules.system.pkgs=org.glowroot` workaround is the intended WildFly/EAP guidance, we can document it and close once reporters confirm.
