### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by javalover123** [glowroot/glowroot#117]
java.lang.StackOverflowError: null
	at java.util.AbstractCollection.<init>(AbstractCollection.java:66)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap$WrappedCollection.<init>(AbstractMapBasedMultimap.java:362)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap$WrappedList.<init>(AbstractMapBasedMultimap.java:777)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap$RandomAccessWrappedList.<init>(AbstractMapBasedMultimap.java:922)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap.wrapList(AbstractMapBasedMultimap.java:332)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap.wrapCollection(AbstractMapBasedMultimap.java:325)
	at org.glowroot.agent.shaded.google.common.collect.AbstractMapBasedMultimap.get(AbstractMapBasedMultimap.java:309)
	at org.glowroot.agent.shaded.google.common.collect.AbstractListMultimap.get(AbstractListMultimap.java:68)
	at org.glowroot.agent.shaded.google.common.collect.ArrayListMultimap.get(ArrayListMultimap.java:66)
	at org.glowroot.agent.shaded.google.common.collect.AbstractListMultimap.get(AbstractListMultimap.java:36)
	at org.glowroot.agent.model.Transaction.isEmptyAuxThreadRoot(Transaction.java:778)
	at org.glowroot.agent.model.Transaction.isEmptyAuxThreadRoot(Transaction.java:779)
	at org.glowroot.agent.model.Transaction.isEmptyAuxThreadRoot(Transaction.java:779)

**Comment by javalover123** [comment]
-Xss256K

**Comment by trask** [comment]
Thanks for reporting!  I was able to repro and fix based on the info you provided.  Try the latest snapshot to verify, and please re-open this issue if not.

https://oss.sonatype.org/content/repositories/snapshots/org/glowroot/glowroot-agent/0.9.2-SNAPSHOT/glowroot-agent-0.9.2-20160901.045145-3-dist.zip
