### ISSUE TITLE
0.9.4: error sending data to server: UNKNOWN

### ISSUE THREAD

**Issue by robokaso** [glowroot/glowroot#123]
After upgrading both server and clients to 0.9.4 I keep getting the exception listed below. With 0.9.2 all worked well.

```
WARN  o.g.agent.util.RateLimitedLogger - error sending data to server: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)
org.glowroot.agent.shaded.grpc.StatusRuntimeException: UNKNOWN
        at org.glowroot.agent.shaded.grpc.Status.asRuntimeException(Status.java:545)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:370)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
        at org.glowroot.agent.shaded.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by trask** [comment]
Are there any errors in the glowroot server log?

**Comment by robokaso** [comment]
nope, no errors in the server log

**Comment by trask** [comment]
Is glowroot server getting any data from agents?  Is glowroot server listening on port 8181 (can you telnet to verify from one of the agent boxes)?

**Comment by robokaso** [comment]
Yes, the server is listening on port 8181 and clients connect successfuly.

The behavior from user's perspective after the upgrade was that the web UI was showing only partial information. E.g. for a grails application it listed slow traces, but other tabs were empty. For a java+spring application the response tab was populated, but queries and continuous profiling was showing no data.

Meanwhile I reverted back to 0.9.2 and things are back to normal.

**Comment by trask** [comment]
Did you upgrade the server or agents first?  The server supports older agents, but not the other way around.  I need to add this info to the [Central Collector Upgrade](https://github.com/glowroot/glowroot/wiki/Central-Collector-Upgrade) wiki page.

I just tried with 0.9.4 agent and 0.9.2 server and got the same exception, and the same behavior of response time tab populated, but queries and continuous profiling data empty.

I'm surprised though that things didn't resolve themselves once the server was upgraded to 0.9.4.

When you have a chance, can you try upgrading just the server to 0.9.4, and seeing how it looks, and if everything looks good, then upgrading one agent to 0.9.4, and seeing how that looks?

I'm heading over to update that wiki page now...

**Comment by robokaso** [comment]
Tried again making sure to upgrade the server first with no luck. The 0.9.2 clients keep working correctly so I'm keeping the server at 0.9.4, however as soon as I switch the client to 0.9.4 the reported exception keeps popping up. When I switch the client back to 0.9.2 I get no more exceptions (tried with both java+spring and grails app).

I figured I was perhaps upgrading the client incorrectly as I was replacing the client completely with the new version. This time I only replaced the glowroot.jar keeping the local client data but the problem remains the same.

**Comment by trask** [comment]
Can you attach `glowroot.log` file from the glowroot server?

**Comment by robokaso** [comment]
The server log only shows the startup and nothing more:
```
2016-09-30 18:05:22.342 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2016-09-30 18:05:22.418 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2016-09-30 18:05:22.801 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-09-30 18:05:22.803 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2016-09-30 18:05:23.462 INFO  org.glowroot - Glowroot UI listening on 0.0.0.0:4000
```

**Comment by trask** [comment]
I'm confused, from my reading of gRPC code, a call to client-side onError() with `StatusRuntimeException UNKNOWN` seems to only come from server-side calling onError(), which are all preceded by error logging (e.g. https://github.com/glowroot/glowroot/blob/v0.9.4/server/src/main/java/org/glowroot/server/GrpcServer.java#L139).  But I'm obviously missing something.

In the meanwhile, I reverted cc6caa6d5256bf1b07cd6ebb287061d9791cca01 locally, which is the most likely culprit, can you try this agent build out and see if it resolves the issue or no?  https://glowroot.org/issue-123/glowroot-agent-0.9.5-SNAPSHOT-dist.zip

**Comment by robokaso** [comment]
I tried the snapshot, in case of a recent grails 3 app it seems to work fine (no more exceptions and all tabs in the webUI populated).

When I next tried a legacy spring app it failed to start with the error below:
```
java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(Z)V
        at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:47)
        at net.sf.cglib.core.DefaultGeneratorStrategy.getClassWriter(DefaultGeneratorStrategy.java:30)
        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:215)
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:117)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
        at org.springframework.aop.framework.Cglib2AopProxy.createEnhancer(Cglib2AopProxy.java:228)
        at org.springframework.aop.framework.Cglib2AopProxy.getProxy(Cglib2AopProxy.java:170)
        at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:112)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:476)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:362)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:322)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:407)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1553)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:162)
        ... 74 more
```

**Comment by trask** [comment]
The build I gave you accidentally had some unshaded artifacts (including asm) which is why you got the `NoSuchMethodError` on one of your apps.

I put up another local agent build at https://glowroot.org/issue-123/glowroot-agent-0.9.5-SNAPSHOT-2-dist.zip

This build brings back the problematic commit, but will write out the contents of the first failed message sent to the server.  It will write the file to the glowroot agent folder with file name "bad-message".

Can you try this out and zip/send me the "bad-message" file?  You can find my email address on my github profile.

**Comment by robokaso** [comment]
I sent the `bad-message` file by email, hope it helps

**Comment by trask** [comment]
Can you update your server to the latest [glowroot-server-0.9.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/content/repositories/snapshots/org/glowroot/glowroot-server/0.9.5-SNAPSHOT/glowroot-server-0.9.5-20161005.004615-3-dist.zip) and then update one of your agents to the latest [glowroot-agent-0.9.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/content/repositories/snapshots/org/glowroot/glowroot-agent/0.9.5-SNAPSHOT/glowroot-agent-0.9.5-20161005.004611-3-dist.zip), try again, and attach the agent and server logs?  Thanks.

**Comment by robokaso** [comment]
This is what happens with 0.9.5-200161005.004615-3 

client log:
```
2016-10-05 10:07:00.839 INFO  org.glowroot - Glowroot version: 0.9.5-SNAPSHOT, commit cbafc08835, built 2016-10-05 00:42:05 +0000
2016-10-05 10:07:03.268 INFO  org.glowroot - Glowroot plugins loaded: Cassandra Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spray Plugin, Spring Plugin, Struts Plugin
2016-10-05 10:07:07.320 INFO  org.glowroot - connected to server glowroot.cweb.sk:8181, version 
2016-10-05 10:07:07.362 INFO  org.glowroot - downstream connection established with server
2016-10-05 10:08:30.938 WARN  o.g.agent.util.RateLimitedLogger - error sending data to server: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectTraceStream (this warning will be logged at most once a minute)
org.glowroot.agent.shaded.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectTraceStream
        at org.glowroot.agent.shaded.grpc.Status.asRuntimeException(Status.java:545)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:370)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
        at org.glowroot.agent.shaded.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-10-05 10:09:34.086 WARN  o.g.agent.util.RateLimitedLogger - error sending data to server: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectAggregateStream (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)
org.glowroot.agent.shaded.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectAggregateStream
        at org.glowroot.agent.shaded.grpc.Status.asRuntimeException(Status.java:545)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:370)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
        at org.glowroot.agent.shaded.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-10-05 10:11:08.062 WARN  o.g.agent.util.RateLimitedLogger - error sending data to server: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectAggregateStream (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)
org.glowroot.agent.shaded.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: org_glowroot_wire_api_model.CollectorService/collectAggregateStream
        at org.glowroot.agent.shaded.grpc.Status.asRuntimeException(Status.java:545)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:370)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
        at org.glowroot.agent.shaded.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

server log:
```
2016-10-05 08:04:29.260 INFO  org.glowroot - Glowroot version: 0.9.5-SNAPSHOT, commit cbafc08835, built 2016-10-05 00:42:05 +0000
2016-10-05 08:04:29.495 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2016-10-05 08:04:29.568 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2016-10-05 08:04:29.964 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-10-05 08:04:29.966 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2016-10-05 08:04:30.939 INFO  org.glowroot - gRPC listening on 0.0.0.0:8181
2016-10-05 08:04:31.087 INFO  org.glowroot - UI listening on 0.0.0.0:4000
```

**Comment by trask** [comment]
It looks like the agent is connecting to a different glowroot server process.  There should be an agent connect message in the server log.  Also, the server that the agent connected to is not sending back the server version (which I just added in 0.9.5-SNAPSHOT), which is why version is blank in the agent log message:

```
2016-10-05 10:07:07.320 INFO  org.glowroot - connected to server glowroot.cweb.sk:8181, version 
```

It seems from the server log that gRPC is binding successfully to port 8181.  Is it possible `glowroot.cweb.sk` on the agent side resolves to a different server from where you are running 0.9.5-SNAPSHOT server?

**Comment by robokaso** [comment]
omg, you're right, I was upgrading the wrong server instance the whole time. So the only real issue was to make sure the server is upgraded prior to clients. 

Sorry for wasting your time with a false alarm, hope at least the logging improvements will be useful at the end of the day.

**Comment by trask** [comment]
No problem.  Really glad it's working for you.  And yes, logging improvements were much needed.  Thanks.
