### ISSUE TITLE
Glowroot memory usage

### ISSUE THREAD

**Issue by nezda** [glowroot/glowroot#124]
We have several busy servers serving complex compute intensive tasks over REST which are often hitting “GC overhead limit exceeded” after installing glowroot 0.9.2 with default configuration.  Any guidance on how much additional memory it needs since it shares with host app?  Guidance on which parameters require the most memory?  Are there any known gross memory inefficiencies which might be addressed in future versions?

(Glowroot has already given us some great insights - really neat thing!  If there were a mailing list, I would've sent this there instead of making an issue .)

**Comment by trask** [comment]
Thanks for opening an issue.

Steady state memory usage for Glowroot is around 25mb when I've analyzed in the past.  But there are times when it needs much more than that temporarily, in particular (I've noticed recently) when serializing large protobuf objects (traces, aggregates) for storage into the local capped dbs (I'm planning to address this).

Is there a java.lang.OutOfMemoryError in glowroot.log?  If there is one, that stack trace would be very helpful to identify the issue you are running into.

If not, can you run one of the servers with -XX:+HeapDumpOnOutOfMemoryError and zip/upload the resulting heap dump privately to me at https://www.dropbox.com/request/h4ms7xhS5heuPPAwFBre?

**Comment by nezda** [comment]
Here are some stack traces from glowroot logs

```
2016-09-25 08:30:48.826 ERROR o.g.a.i.Aggregator$TransactionProcessor - GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2016-09-25 08:31:39.475 ERROR o.g.a.i.Aggregator$TransactionProcessor - java.lang.OutOfMemoryError: GC overhead limit exceeded
org.glowroot.agent.shaded.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.glowroot.agent.shaded.google.common.cache.LocalCache$Segment.get(LocalCache.java:2205)
        at org.glowroot.agent.shaded.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at org.glowroot.agent.shaded.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at org.glowroot.agent.shaded.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at org.glowroot.agent.fat.storage.util.DataSource.prepareStatement(DataSource.java:427)
        at org.glowroot.agent.fat.storage.util.DataSource.update(DataSource.java:304)
        at org.glowroot.agent.fat.storage.AggregateDao$RollupOverallAggregates.processResultSet(AggregateDao.java:1044)
        at org.glowroot.agent.fat.storage.AggregateDao$RollupOverallAggregates.processResultSet(AggregateDao.java:986)
        at org.glowroot.agent.fat.storage.util.DataSource.query(DataSource.java:227)
        at org.glowroot.agent.fat.storage.AggregateDao.rollup(AggregateDao.java:422)
        at org.glowroot.agent.fat.storage.AggregateDao.store(AggregateDao.java:238)
        at org.glowroot.agent.fat.init.CollectorImpl.collectAggregates(CollectorImpl.java:68)
        at org.glowroot.agent.init.CollectorProxy.collectAggregates(CollectorProxy.java:56)
        at org.glowroot.agent.impl.AggregateIntervalCollector.flush(AggregateIntervalCollector.java:261)
        at org.glowroot.agent.impl.Aggregator$TransactionProcessor$1.run(Aggregator.java:259)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
2016-09-25 08:40:15.727 WARN  o.g.a.s.g.ui.HttpServerHandler - GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2016-09-25 22:11:49.194 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2016-09-25 22:12:01.443 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2016-09-25 22:12:01.443 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2016-09-25 22:15:53.071 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
...
```

lot of these
```
2016-09-26 01:46:13.609 ERROR o.g.a.i.Aggregator$TransactionProcessor - The database has been closed [90098-176]
org.glowroot.agent.shaded.h2.jdbc.JdbcSQLException: The database has been closed [90098-176]
        at org.glowroot.agent.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:178)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:154)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:143)
        at org.glowroot.agent.shaded.h2.engine.Database.checkPowerOff(Database.java:490)
        at org.glowroot.agent.shaded.h2.command.Command.executeUpdate(Command.java:274)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcConnection.setQueryTimeout(JdbcConnection.java:735)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcStatement.setQueryTimeout(JdbcStatement.java:599)
        at org.glowroot.agent.fat.storage.util.DataSource.query(DataSource.java:257)
        at org.glowroot.agent.fat.storage.AggregateDao.rollup(AggregateDao.java:419)
        at org.glowroot.agent.fat.storage.AggregateDao.store(AggregateDao.java:238)
        at org.glowroot.agent.fat.init.CollectorImpl.collectAggregates(CollectorImpl.java:68)
        at org.glowroot.agent.init.CollectorProxy.collectAggregates(CollectorProxy.java:56)
        at org.glowroot.agent.impl.AggregateIntervalCollector.flush(AggregateIntervalCollector.java:261)
        at org.glowroot.agent.impl.Aggregator$TransactionProcessor$1.run(Aggregator.java:259)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
2016-10-02 10:21:20.707 WARN  o.glowroot.agent.init.GaugeCollector - error accessing mbean attribute: java.lang:type=MemoryPool,name=PS Old Gen Usage.used
javax.management.RuntimeErrorException: java.lang.OutOfMemoryError: Java heap space
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:841)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:651)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at org.glowroot.agent.util.LazyPlatformMBeanServer.getAttribute(LazyPlatformMBeanServer.java:124)
        at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:197)
        at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:179)
        at org.glowroot.agent.init.GaugeCollector.runInternal(GaugeCollector.java:127)
        at org.glowroot.agent.shaded.glowroot.common.util.ScheduledRunnable.run(ScheduledRunnable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
2016-10-02 10:22:03.179 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2016-10-02 10:35:07.740 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
...
```

```
2016-09-30 14:32:26.937 ERROR o.glowroot.agent.init.GaugeCollector - Out of memory.; SQL statement:
merge into gauge_value_rollup_2 (gauge_id, capture_time, value, weight) key (gauge_id, capture_time) select gauge_id, ceil(capture_time / 300000.0) * 300000 ceil_capture_time, sum(value * weight) / sum(weight), sum(weight) from gauge_value_rollup_1 gp where gp.capture_time > ? and gp.capture_time <= ? group by gp.gauge_id, ceil_capture_time [90108-176]
org.glowroot.agent.shaded.h2.jdbc.JdbcSQLException: Out of memory.; SQL statement:
merge into gauge_value_rollup_2 (gauge_id, capture_time, value, weight) key (gauge_id, capture_time) select gauge_id, ceil(capture_time / 300000.0) * 300000 ceil_capture_time, sum(value * weight) / sum(weight), sum(weight) from gauge_value_rollup_1 gp where gp.capture_time > ? and gp.capture_time <= ? group by gp.gauge_id, ceil_capture_time [90108-176]
        at org.glowroot.agent.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:167)
        at org.glowroot.agent.shaded.h2.message.DbException.convert(DbException.java:288)
        at org.glowroot.agent.shaded.h2.command.Command.executeUpdate(Command.java:260)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
        at org.glowroot.agent.fat.storage.util.DataSource.update(DataSource.java:308)
        at org.glowroot.agent.fat.storage.util.DataSource.update(DataSource.java:278)
        at org.glowroot.agent.fat.storage.GaugeValueDao.rollup(GaugeValueDao.java:183)
        at org.glowroot.agent.fat.storage.GaugeValueDao.store(GaugeValueDao.java:143)
        at org.glowroot.agent.fat.init.CollectorImpl.collectGaugeValues(CollectorImpl.java:78)
        at org.glowroot.agent.init.CollectorProxy.collectGaugeValues(CollectorProxy.java:63)
        at org.glowroot.agent.init.GaugeCollector$2.run(GaugeCollector.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by trask** [comment]
Thanks, this is very helpful

**Comment by nezda** [comment]
Please note our app has been known to misbehave and cause its own `OutOfMemoryError`s but the big uptick in them we've been seeing recently is highly correlated with our adding glowroot monitoring so thanks for taking a look.

**Comment by trask** [comment]
I made some significant improvements to memory consumption during collection.  Previously, it would serialize all the collected data, then store it all.  Now it serializes and stores the data incrementally, so it doesn't need as much memory during collection.  Please try out the latest [glowroot-agent-0.9.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/content/repositories/snapshots/org/glowroot/glowroot-agent/0.9.5-SNAPSHOT/glowroot-agent-0.9.5-20161005.004611-3-dist.zip) when you have a chance.  Thanks.

**Comment by nezda** [comment]
Very cool!  Just pushed that snapshot to one of our servers - will report back in day or 2.

(An aside: When I upgraded from 0.9.2 → 0.9.4 incidence of OOME went down a lot but still much more than pre-glowroot.)

**Comment by trask** [comment]
Closing this with the release of 0.9.5, but please re-open if you still see any issues.

**Comment by nezda** [comment]
@trask this seems to be working beautifully - thank you!

**Comment by trask** [comment]
Great to hear, thanks.
