### ISSUE TITLE
removing an agent

### ISSUE THREAD

**Issue by robokaso** [glowroot/glowroot#135]
It would be nice to have the option to remove an agent that is no longer used via the UI. I have an obsolete agent that has not sent any data for weeks but I don't see any easy way to clean it up (all I can think of is using CQL).

**Comment by trask** [comment]
Thanks for submitting issue.  I will target for next release.

**Comment by equake** [comment]
That's going to be great for people (like me) that are monitoring apps within AWS AutoScaling groups. Everyday some agents die and new ones are born.

**Comment by trask** [comment]
This is released in 0.9.7, let me know if any issues.

**Comment by robokaso** [comment]
Unfortunately my glowroot-central upgrade from 0.9.6 to 0.9.7 failed. First run seemed to hang on schema upgrade until eventually an error popped up. Further restarts then fail immediately.
```
2016-11-16 11:11:10.559 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-11-16 11:11:10.561 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2016-11-16 11:11:10.857 INFO  org.glowroot - upgrading cassandra schema from version 10...
2016-11-16 11:13:56.145 ERROR org.glowroot - Unknown identifier agent_rollup_id
com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier agent_rollup_id
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
        at org.glowroot.central.repo.SchemaUpgrade.updateAgentRollup(SchemaUpgrade.java:422)
        at org.glowroot.central.repo.SchemaUpgrade.upgrade(SchemaUpgrade.java:132)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:141)
        at org.glowroot.central.Bootstrap.main(Bootstrap.java:30)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier agent_rollup_id
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)
2016-11-16 11:15:25.087 INFO  org.glowroot - Glowroot version: 0.9.7, built 2016-11-14 23:01:20 +0000
2016-11-16 11:15:25.374 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2016-11-16 11:15:25.420 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2016-11-16 11:15:26.123 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-11-16 11:15:26.124 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2016-11-16 11:15:26.248 INFO  org.glowroot - upgrading cassandra schema from version 12...
2016-11-16 11:15:26.289 ERROR org.glowroot - Unknown identifier agent_rollup_id
com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier agent_rollup_id
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
        at org.glowroot.central.repo.SchemaUpgrade.updateAgentRollup(SchemaUpgrade.java:422)
        at org.glowroot.central.repo.SchemaUpgrade.upgrade(SchemaUpgrade.java:132)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:141)
        at org.glowroot.central.Bootstrap.main(Bootstrap.java:30)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier agent_rollup_id
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by trask** [comment]
Can you run "describe glowroot.agent_rollup" from cqlsh and post the output?

**Comment by trask** [comment]
My guess is the old `agent_rollup` table (from 0.9.4 and prior) still exists in your schema for some reason, though not sure how the upgrade to 0.9.5 succeeded without it getting dropped.

Run `drop glowroot.agent_rollup` from cqlsh and then try to start up glowroot central again.

**Comment by robokaso** [comment]
Dropping the `glowroot.agent_rollup` table resolved the issue and I was able to remove the unused agents from the UI.

Thanks a lot.

**Comment by akibshahnoor** [comment]
Hi Trask,
While running  cqlsh> describe glowroot.agent_rollup; i am getting error "Keyspace 'glowroot' not found.". Could you please help me on this.
