### ISSUE TITLE
Glowroot agent and jOOQ incompatibility

### ISSUE THREAD

**Issue by dariokures** [glowroot/glowroot#175]
Hi,

Looks like Glowroot agent breaks some classes from jOOQ library.

For example, this doesn't work if we start it with agent:
```java
public static void main(String[] args){
	DSLContext db = DSL.using("jdbc:h2:./test", "sa", "");
        Result result = db.selectOne().fetch();
        System.out.println("result: " + result.get(0));
}
```
```
Exception in thread "main" java.lang.VerifyError: class org.jooq.impl.CursorImpl$CursorResultSet overrides final method getObject.(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jooq.impl.CursorImpl.<init>(CursorImpl.java:138)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:286)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2708)
	at playground.GlowrootTest.main(GlowrootTest.java:12)
```
Glowroot: 0.9.11
jOOQ: 3.9.1
Java 8

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.12-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.12-SNAPSHOT).

**Comment by dariokures** [comment]
Fix verified.
Thanks
