### ISSUE TITLE
Glowroot-Central running out of cassandra connections

### ISSUE THREAD

**Issue by MaikJaek** [glowroot/glowroot#181]
Hey there,

We are currently evaluating Glowroot in its glowroot-central flavor with Cassandra. Having connected 12 test application nodes, we frequently experience outages of the web app and see the enclosed stacktrace in glowroot.log

We presume that this issue may be resolved by setting an appropriate configuration value. We are not sure where to start, though. Any help is appreciated =)

[stacktrace_glowroot.TXT](https://github.com/glowroot/glowroot/files/811279/stacktrace_glowroot.TXT)

**Comment by MaikJaek** [comment]
PS.: In general, the application works. At some point we have to restart it, but for quite some time glowroot is usable in the browser and is able to display actual metrics.

**Comment by trask** [comment]
Hi!

That limit is configurable via the Cassandra driver, though it's not exposed as a configuration property of glowroot central currently.

I'd like to understand why you are hitting that limit with only 12 agents reporting.  It would be great if you can put glowroot agent on the glowroot central box and use it to monitor glowroot central (which is already instrumented to be monitored by the glowroot agent), e.g.

```
java -javaagent:path/to/glowroot.jar -jar glowroot-central.jar
```

and after the next time this happens, zip up the glowroot agent folder (including the data folder under it) and upload it privately to me at https://www.dropbox.com/request/iQLl1gYXpgqsEaYZwzom

The glowroot agent that is monitoring glowroot central only collects data about glowroot central, and not any data from your applications.  It will collect agent ids though, if that is a concern I could create an option to mask the agent ids.

**Comment by MaikJaek** [comment]
Hi,

Thanks for the quick response!

> It will collect agent ids though, if that is a concern I could create an option to mask the agent ids.
That option would be great, as I may not hand out inside information about our system landscape. If you provide me with the option, I'll be happy to provide the data to analyze the root cause of the problem.

**Comment by trask** [comment]
Great, you will need to use the latest glowroot agent snapshot to monitor glowroot central: [glowroot-agent-0.9.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.13-SNAPSHOT).

Configure a different UI port for the glowroot agent if you are running glowroot central on port 4000 already, e.g. create `admin.json` file in the glowroot agent folder with the contents:

```
{
  "web": {
    "port": 8000
  }
}
```

And run glowroot central using the glowroot agent, e.g.

```
java -javaagent:path/to/glowroot.jar -jar glowroot-central.jar
```

Then, when you run into the issue with glowroot central again, stop glowroot central, and run this from the glowroot agent directory:

```
java -jar glowroot.jar mask-central-data
```

Finally, zip up the glowroot agent `data` directory and upload it to https://www.dropbox.com/request/iQLl1gYXpgqsEaYZwzom

Thanks,
Trask

**Comment by MaikJaek** [comment]
Dear Trask,

Thanks again for your quick response. I attached the glowroot agent to glowroot-central. I'll send the data to you, once the errors occur again.

**Comment by MaikJaek** [comment]
So the exceptions have been occurring again. When trying to run your data masking tool, the attached exception arises. In the data folder, a file named data.trace.db is created with 366 bytes of size. Whenever I run the tool again, it fails and size of the trace file increases by 366 bytes :



_java -jar glowroot.jar mask-central-data
Exception in thread "main" org.glowroot.agent.shaded.h2.jdbc.JdbcSQLException: Table "TRACE" not found; SQL statement:
update trace set headline = left(headline, position(': ', headline) + 1) || left(hash('sha256', stringtoutf8(substr(headline, position(': ', headline) + 2)), 100000), 40) where transaction_type <> 'Web' and headline like '%: %' [42102-176]
	at org.glowroot.agent.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:178)
	at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:154)
	at org.glowroot.agent.shaded.h2.command.Parser.readTableOrView(Parser.java:5213)
	at org.glowroot.agent.shaded.h2.command.Parser.readTableOrView(Parser.java:5190)
	at org.glowroot.agent.shaded.h2.command.Parser.readSimpleTableFilter(Parser.java:758)
	at org.glowroot.agent.shaded.h2.command.Parser.parseUpdate(Parser.java:707)
	at org.glowroot.agent.shaded.h2.command.Parser.parsePrepared(Parser.java:456)
	at org.glowroot.agent.shaded.h2.command.Parser.parse(Parser.java:306)
	at org.glowroot.agent.shaded.h2.command.Parser.parse(Parser.java:278)
	at org.glowroot.agent.shaded.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.glowroot.agent.shaded.h2.engine.Session.prepareLocal(Session.java:442)
	at org.glowroot.agent.shaded.h2.engine.Session.prepareCommand(Session.java:384)
	at org.glowroot.agent.shaded.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.glowroot.agent.shaded.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.glowroot.agent.shaded.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.glowroot.agent.shaded.h2.tools.RunScript.process(RunScript.java:261)
	at org.glowroot.agent.shaded.h2.tools.RunScript.process(RunScript.java:191)
	at org.glowroot.agent.shaded.h2.tools.RunScript.process(RunScript.java:329)
	at org.glowroot.agent.shaded.h2.tools.RunScript.runTool(RunScript.java:142)
	at org.glowroot.agent.shaded.h2.tools.RunScript.main(RunScript.java:69)
	at org.glowroot.agent.ToolMain.maskCentralData(ToolMain.java:137)
	at org.glowroot.agent.ToolMain.main(ToolMain.java:59)_

**Comment by trask** [comment]
What other files are in the data folder?

**Comment by trask** [comment]
Can you post the glowroot log file from the agent directory?

**Comment by MaikJaek** [comment]
My bad! It looks like an automatic deployment script has removed my manual change to run the agent. Sorry!

I'll get back to you, once I really have trace data.

**Comment by MaikJaek** [comment]
(Un)fortunately above mentioned exception has not occurred again. Therefore, I suggest closing this issue for now. Thanks for the quick offer to look into it, even though I could not make use of it.

**Comment by trask** [comment]
No problem, just re-open if (when) it happens again.
