### ISSUE TITLE
Exception: message size too large

### ISSUE THREAD

**Issue by MaikJaek** [glowroot/glowroot#182]
Hi,

I'm still waiting for the bug from issue #181 to occur again. Meanwhile, I'm experiencing the following exceptions from time to time:

2017-03-03 12:33:43.407 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1@31b7cd4
io.grpc.StatusRuntimeException: INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder
        at io.grpc.Status.asRuntimeException(Status.java:536)
        at io.grpc.internal.MessageDeframer$SizeEnforcingInputStream.verifySize(MessageDeframer.java:446)
        at io.grpc.internal.MessageDeframer$SizeEnforcingInputStream.read(MessageDeframer.java:409)
        at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2715)
        at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2677)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readStringRequireUtf8(CodedInputStream.java:2234)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Error.<init>(TraceOuterClass.java:7317)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Error.<init>(TraceOuterClass.java:7279)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Error$1.parsePartialFrom(TraceOuterClass.java:7927)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Error$1.parsePartialFrom(TraceOuterClass.java:7922)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry.<init>(TraceOuterClass.java:10458)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry.<init>(TraceOuterClass.java:10366)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry$1.parsePartialFrom(TraceOuterClass.java:12181)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry$1.parsePartialFrom(TraceOuterClass.java:12176)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace.<init>(TraceOuterClass.java:248)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace.<init>(TraceOuterClass.java:183)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$1.parsePartialFrom(TraceOuterClass.java:15799)
        at org.glowroot.wire.api.model.TraceOuterClass$Trace$1.parsePartialFrom(TraceOuterClass.java:15794)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
        at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage.<init>(CollectorServiceOuterClass.java:6660)
        at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage.<init>(CollectorServiceOuterClass.java:6590)
        at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage$1.parsePartialFrom(CollectorServiceOuterClass.java:7574)
        at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage$1.parsePartialFrom(CollectorServiceOuterClass.java:7569)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at io.grpc.protobuf.lite.ProtoLiteUtils$1.parseFrom(ProtoLiteUtils.java:124)
        at io.grpc.protobuf.lite.ProtoLiteUtils$1.parse(ProtoLiteUtils.java:111)
        at io.grpc.protobuf.lite.ProtoLiteUtils$1.parse(ProtoLiteUtils.java:81)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:207)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:237)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:485)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-03 12:33:43.408 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@71385292
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at org.glowroot.central.GrpcServer$CollectorServiceImpl$2.onCompleted(GrpcServer.java:409)
        at io.grpc.stub.ServerCalls$2$1.onHalfClose(ServerCalls.java:217)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:261)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:503)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-03 12:33:43.419 WARN  org.glowroot.central.GrpcServer - some-internal-system-name.some-internal-domain.com -- WARN -- org.glowroot.agent.central.CentralConnection -- error sending data to the central collector: INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder (this warning will be logged at most once a minute)
className: "org.glowroot.agent.shaded.grpc.StatusRuntimeException"
message: "INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder"
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.Status"
  method_name: "asRuntimeException"
  file_name: "Status.java"
  line_number: 545
}
stack_trace_element {
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-03 12:33:43.408 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@71385292
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at org.glowroot.central.GrpcServer$CollectorServiceImpl$2.onCompleted(GrpcServer.java:409)
        at io.grpc.stub.ServerCalls$2$1.onHalfClose(ServerCalls.java:217)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:261)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:503)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-03 12:33:43.419 WARN  org.glowroot.central.GrpcServer - some-internal-system-name.some-internal-domain.com -- WARN -- org.glowroot.agent.central.CentralConnection -- error sending data to the central collector: INTERNAL: Compressed frame ex
ceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder (this warning will be logged at most once a minute)
className: "org.glowroot.agent.shaded.grpc.StatusRuntimeException"
message: "INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder"
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.Status"
  method_name: "asRuntimeException"
  file_name: "Status.java"
  line_number: 545
}
stack_trace_element {
        at io.grpc.stub.ServerCalls$2$1.onHalfClose(ServerCalls.java:217)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:261)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:503)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-03 12:33:43.419 WARN  org.glowroot.central.GrpcServer - some-internal-system-name.some-internal-domain.com -- WARN -- org.glowroot.agent.central.CentralConnection -- error sending data to the central collector: INTERNAL: Compressed frame ex
ceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder (this warning will be logged at most once a minute)
className: "org.glowroot.agent.shaded.grpc.StatusRuntimeException"
message: "INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197138. If this is normal, increase the maxMessageSize in the channel/server builder"
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.Status"
  method_name: "asRuntimeException"
  file_name: "Status.java"
  line_number: 545
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter"
  method_name: "onClose"
  file_name: "ClientCalls.java"
  line_number: 395
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl"
  method_name: "close"
  file_name: "ClientCallImpl.java"
  line_number: 481
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl"
  method_name: "access$600"
  file_name: "ClientCallImpl.java"
  line_number: 398
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed"
  method_name: "runInContext"
  file_name: "ClientCallImpl.java"
  line_number: 513
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ContextRunnable"
  method_name: "run"
  file_name: "ContextRunnable.java"
  line_number: 52
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner"
  method_name: "run"
  file_name: "SerializingExecutor.java"
  line_number: 154
}
stack_trace_element {
  class_name: "java.util.concurrent.ThreadPoolExecutor"
  method_name: "runWorker"
  file_name: "ThreadPoolExecutor.java"
  line_number: 1142
}
stack_trace_element {
  class_name: "java.util.concurrent.ThreadPoolExecutor$Worker"
  method_name: "run"
  file_name: "ThreadPoolExecutor.java"
  line_number: 617
}
stack_trace_element {
  class_name: "java.lang.Thread"
  method_name: "run"
  file_name: "Thread.java"
  line_number: 745
}

**Comment by cecrdle** [comment]
Hi,
I have the same problem in monitoring 1JVM (other JVM is ok]. In this JVM running jboss with 40 deploy .war. Applications has many logging statement. I try to modify some of parameters in agent setting (Transactions and Advanced menu), but this doen't help.
It's seem that possibilty to set maxMessageSize is only in code, not in configuration of grpc libries.

The exception:
2017-03-06 11:03:06.370 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1@5537104b
io.grpc.StatusRuntimeException: INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197426. If this is normal, increase the maxMessageSize in the channel/server builder
	at io.grpc.Status.asRuntimeException(Status.java:536)
	at io.grpc.internal.MessageDeframer$SizeEnforcingInputStream.verifySize(MessageDeframer.java:446)
	at io.grpc.internal.MessageDeframer$SizeEnforcingInputStream.read(MessageDeframer.java:409)
	at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2715)
	at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2677)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readStringRequireUtf8(CodedInputStream.java:2234)
	at org.glowroot.wire.api.model.Proto$StackTraceElement.<init>(Proto.java:1900)
	at org.glowroot.wire.api.model.Proto$StackTraceElement.<init>(Proto.java:1859)
	at org.glowroot.wire.api.model.Proto$StackTraceElement$1.parsePartialFrom(Proto.java:2654)
	at org.glowroot.wire.api.model.Proto$StackTraceElement$1.parsePartialFrom(Proto.java:2649)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry.<init>(TraceOuterClass.java:10450)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry.<init>(TraceOuterClass.java:10366)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry$1.parsePartialFrom(TraceOuterClass.java:12181)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$Entry$1.parsePartialFrom(TraceOuterClass.java:12176)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace.<init>(TraceOuterClass.java:248)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace.<init>(TraceOuterClass.java:183)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$1.parsePartialFrom(TraceOuterClass.java:15799)
	at org.glowroot.wire.api.model.TraceOuterClass$Trace$1.parsePartialFrom(TraceOuterClass.java:15794)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage.<init>(CollectorServiceOuterClass.java:6660)
	at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage.<init>(CollectorServiceOuterClass.java:6590)
	at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage$1.parsePartialFrom(CollectorServiceOuterClass.java:7574)
	at org.glowroot.wire.api.model.CollectorServiceOuterClass$TraceStreamMessage$1.parsePartialFrom(CollectorServiceOuterClass.java:7569)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$1.parseFrom(ProtoLiteUtils.java:124)
	at io.grpc.protobuf.lite.ProtoLiteUtils$1.parse(ProtoLiteUtils.java:111)
	at io.grpc.protobuf.lite.ProtoLiteUtils$1.parse(ProtoLiteUtils.java:81)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:207)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:237)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:485)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-06 11:03:06.372 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@505ab208
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at org.glowroot.central.GrpcServer$CollectorServiceImpl$2.onCompleted(GrpcServer.java:409)
	at io.grpc.stub.ServerCalls$2$1.onHalfClose(ServerCalls.java:217)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:261)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:503)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-06 11:03:06.373 WARN  org.glowroot.central.GrpcServer - jboss-olin -- WARN -- org.glowroot.agent.central.CentralConnection -- error sending data to the central collector: INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197426. If this is normal, increase the maxMessageSize in the channel/server builder (this warning will be logged at most once a minute)
className: "org.glowroot.agent.shaded.grpc.StatusRuntimeException"
message: "INTERNAL: Compressed frame exceeds maximum frame size: 4194304. Bytes read: 4197426. If this is normal, increase the maxMessageSize in the channel/server builder"
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.Status"
  method_name: "asRuntimeException"
  file_name: "Status.java"
  line_number: 545
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter"
  method_name: "onClose"
  file_name: "ClientCalls.java"
  line_number: 395
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl"
  method_name: "close"
  file_name: "ClientCallImpl.java"
  line_number: 481
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl"
  method_name: "access$600"
  file_name: "ClientCallImpl.java"
  line_number: 398
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed"
  method_name: "runInContext"
  file_name: "ClientCallImpl.java"
  line_number: 513
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.ContextRunnable"
  method_name: "run"
  file_name: "ContextRunnable.java"
  line_number: 52
}
stack_trace_element {
  class_name: "org.glowroot.agent.shaded.grpc.internal.SerializingExecutor$TaskRunner"
  method_name: "run"
  file_name: "SerializingExecutor.java"
  line_number: 154
}
stack_trace_element {
  class_name: "java.util.concurrent.ThreadPoolExecutor"
  method_name: "runWorker"
  file_name: "ThreadPoolExecutor.java"
  line_number: 1142
}
stack_trace_element {
  class_name: "java.util.concurrent.ThreadPoolExecutor$Worker"
  method_name: "run"
  file_name: "ThreadPoolExecutor.java"
  line_number: 617
}
stack_trace_element {
  class_name: "java.lang.Thread"
  method_name: "run"
  file_name: "Thread.java"
  line_number: 745
}

**Comment by trask** [comment]
Thanks for reporting!  I'm working on a fix to stream the trace entries instead of sending them all at once, which should solve the frame size error (and as a side effect, should improve memory profile of the agent in a way similar to the fix for #124).  I think this will be better than just bumping the limit.  I'll target this for the next release.
