### ISSUE TITLE
Glowroot OOM and DB issues after big post

### ISSUE THREAD

**Issue by hgomez** [glowroot/glowroot#206]
Hi all

I'm using glowroot on an application where contents in protobuf format are upload to a web application.
Each time a large protobuf file is received, glowroot fail in OOM and then I got DBCP errors 

`2017-05-03 11:12:41.558 ERROR o.glowroot.agent.init.GaugeCollector - The database has been closed [90098-176]
org.glowroot.agent.shaded.h2.jdbc.JdbcSQLException: The database has been closed [90098-176]
        at org.glowroot.agent.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:178)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:154)
        at org.glowroot.agent.shaded.h2.message.DbException.get(DbException.java:143)
        at org.glowroot.agent.shaded.h2.engine.Database.checkPowerOff(Database.java:490)
        at org.glowroot.agent.shaded.h2.command.Command.executeUpdate(Command.java:274)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcConnection.setQueryTimeout(JdbcConnection.java:735)
        at org.glowroot.agent.shaded.h2.jdbc.JdbcStatement.setQueryTimeout(JdbcStatement.java:599)
        at org.glowroot.agent.embedded.util.DataSource.prepareStatement(DataSource.java:432)
        at org.glowroot.agent.embedded.util.DataSource.batchUpdate(DataSource.java:323)
        at org.glowroot.agent.embedded.repo.GaugeValueDao.store(GaugeValueDao.java:130)
        at org.glowroot.agent.embedded.init.CollectorImpl.collectGaugeValues(CollectorImpl.java:59)
        at org.glowroot.agent.init.CollectorProxy.collectGaugeValues(CollectorProxy.java:86)
        at org.glowroot.agent.init.GaugeCollector$2.run(GaugeCollector.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
` 

Eclipse MAT report 3 huge objects

![screenshot from 2017-05-03 13-11-23](https://cloud.githubusercontent.com/assets/274370/25658234/279b8fce-3002-11e7-85cf-b4d2acecc720.png)

Then glowroot is unusable and I have to restart application.

Any suggestion on how to avoid such problem ?

**Comment by hgomez** [comment]
I added post parameter who contains large content to Mask request parameters, but unsure if it will be enough.

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.16-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.16-SNAPSHOT).
