### ISSUE TITLE
Missing/corrupt agent config causes glowroot central web UI to be unusable 

### ISSUE THREAD

**Issue by jaikiran** [glowroot/glowroot#209]
For some reason one of our Java process (backed by glowroot agent) ended up in a state where glowroot central did not have `agentConfig` for the agent rollup id of that process. The Java process itself is no longer around (we run them in container and sometimes they can be short lived).

With this state, of one agent, the central web UI no longer renders. The home page of the UI throws a exception stacktrace that looks like:

```
stackTrace	"org.glowroot.common.repo.ConfigRepository$AgentConfigNotFoundException: foo-bar
	at org.glowroot.central.repo.ConfigRepositoryImpl.getUiConfig(ConfigRepositoryImpl.java:118)
	at org.glowroot.ui.LayoutService$CentralLayoutBuilder.process(LayoutService.java:360)
	at org.glowroot.ui.LayoutService$CentralLayoutBuilder.process(LayoutService.java:386)
	at org.glowroot.ui.LayoutService$CentralLayoutBuilder.access$500(LayoutService.java:310)
	at org.glowroot.ui.LayoutService.buildLayoutCentral(LayoutService.java:144)
	at org.glowroot.ui.LayoutService.buildLayout(LayoutService.java:87)
	at org.glowroot.ui.LayoutService.getLayoutJson(LayoutService.java:76)
	at org.glowroot.ui.IndexHtmlHttpService.handleRequest(IndexHtmlHttpService.java:54)
	at org.glowroot.ui.CommonHandler.handleHttpService(CommonHandler.java:224)
	at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:200)
	at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:153)
	at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:137)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by trask** [comment]
Thanks for reporting this!  I think the latest snapshot should clean up the existing bad data and prevent new bad data from getting in, but I kept the try/catch in LayoutService also just in case.  Let me know if you see the error logged from LayoutService after updating (which means I didn't solve the underlying bad data issue).

**Comment by jaikiran** [comment]
Thanks Trask. I'll try and reproduce this locally in our setups and see how it goes.
