### ISSUE TITLE
Cannot build EmbeddedWebConfigResponse, some of required attributes are not set [sharedConfDir]

### ISSUE THREAD

**Issue by cocorossello** [glowroot/glowroot#219]
Hi,

I just added glowroot agent to my tomee server and I get this error when accesing http://localhost:4000/admin/web

java.lang.IllegalStateException: Cannot build EmbeddedWebConfigResponse, some of required attributes are not set [sharedConfDir]
	at org.glowroot.agent.shaded.glowroot.ui.ImmutableEmbeddedWebConfigResponse$Builder.build(ImmutableEmbeddedWebConfigResponse.java:556)
	at org.glowroot.agent.shaded.glowroot.ui.AdminJsonService.getEmbeddedWebConfig(AdminJsonService.java:419)
	at org.glowroot.agent.shaded.glowroot.ui.AdminJsonService.getWebConfig(AdminJsonService.java:135)
...

I can see admin.json, config.json and tmp and data folders created. 

Is it an error?

Thanks in advance

Glowroot 0.9.17

**Comment by trask** [comment]
Thanks for posting!  This is due to the same bug as in #218 and should be fixed now in the latest snapshot release [glowroot-agent-0.9.18-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.18-SNAPSHOT).
