### ISSUE TITLE
Aggregate views not updating

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#237]
Hi, In my small setup (9 agents, 1 central collector with cassandra on same machine as collector), I am seeing a lag in the updating of aggregated throughput, percentiles etc.

I.e., this is taken at 10 AM for a rollup id with three agents
![image](https://user-images.githubusercontent.com/14833645/28008719-fa75511a-6558-11e7-84fa-8e1db10adf7c.png)

Same, but for a single agent, instead of the rollup 
![image](https://user-images.githubusercontent.com/14833645/28008701-e23aa6a4-6558-11e7-8f42-22a15b153fc0.png)

This is the same for all single agents, (they show updated data immediatly), but the roll ups are hours behind.

The glowroot-central.log says something about a pool being busy, with a max queue length of 4096. What could be causing this
````
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 4096)))
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:213)
	at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:49)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:277)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:340)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1228)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:911)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:645)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:101)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1209)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1167)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.query(RequestHandler.java:299)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:274)
	at com.datastax.driver.core.RequestHandler.startNewExecution(RequestHandler.java:117)
	at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:97)
	at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:132)
	at org.glowroot.central.util.Sessions.executeAsyncWithOnFailure(Sessions.java:98)
	at org.glowroot.central.repo.FullQueryTextDao.storeCheckInternal(FullQueryTextDao.java:162)
	at org.glowroot.central.repo.FullQueryTextDao.storeInternal(FullQueryTextDao.java:145)
	at org.glowroot.central.repo.FullQueryTextDao.store(FullQueryTextDao.java:109)
	at org.glowroot.central.repo.AggregateDao.store(AggregateDao.java:421)
	... 11 common frames omitted
````
Cassandra seems to be replying, as I can see the live agent data and traces just fine. Its just the aggregates thats behind. 

Can anyone give pointers as to what needs to be upgraded? More ram for Cassandra, more servers for Cassandra? Bigger queue size?

My glowroot-central.config is the default one, w/o changes.
I am using glowroot version 0.9.19

**Comment by trask** [comment]
Thanks for reporting this!  I think this should be fixed now in the latest snapshot release [glowroot-agent-0.9.22-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.22-SNAPSHOT).
