### ISSUE TITLE
Issue instrumenting project with drools

### ISSUE THREAD

**Issue by saurabh256** [glowroot/glowroot#247]
When i click on instrumentation tab for the project attached with Glowroot agent. I get the following exception on the back end. Even the front end UI also shows the same stack trace. This is happening only for those projects where we are using Drools engine and others are working fine. Due to corporate security restriction I am only putting generic stack trace and not all. Please let me know if this is useful to diagnose problem. 

The project is spring-boot (version 1.5.1 )based and Drools version is 6.4 and even with 7.1 I get same error. 

java.lang.RuntimeException: Unable to get bytes for: \XXXX\XXXX\XXXXXX\target\classes
	at org.drools.compiler.kie.builder.impl.FileKieModule.getBytes(FileKieModule.java:66)
	at org.drools.compiler.kie.builder.impl.AbstractKieModule.hasResource(AbstractKieModule.java:346)
	at org.drools.compiler.kie.builder.impl.AbstractKieModule$KieModuleResourceProvider.getResource(AbstractKieModule.java:552)
	at org.drools.core.common.ProjectClassLoader.getResources(ProjectClassLoader.java:285)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1138)
	at org.glowroot.agent.live.ClasspathCache.getURLs(ClasspathCache.java:321)
	at org.glowroot.agent.live.ClasspathCache.updateCache(ClasspathCache.java:265)
	at org.glowroot.agent.live.ClasspathCache.updateCache(ClasspathCache.java:164)
	at org.glowroot.agent.live.ClasspathCache.getMatchingClassNames(ClasspathCache.java:99)
	at org.glowroot.agent.live.LiveWeavingServiceImpl.getMatchingClassNames(LiveWeavingServiceImpl.java:99)
	at org.glowroot.agent.shaded.glowroot.ui.InstrumentationConfigJsonService.getMatchingClassNames(InstrumentationConfigJsonService.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glowroot.agent.shaded.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:550)
	at org.glowroot.agent.shaded.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:294)
	at org.glowroot.agent.shaded.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:211)
	at org.glowroot.agent.shaded.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
	at org.glowroot.agent.shaded.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.glowroot.agent.shaded.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.glowroot.agent.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at org.glowroot.agent.shaded.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.glowroot.agent.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.glowroot.agent.shaded.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at org.glowroot.agent.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at org.glowroot.agent.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at org.glowroot.agent.shaded.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.glowroot.agent.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.glowroot.agent.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at org.glowroot.agent.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at org.glowroot.agent.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at org.glowroot.agent.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at org.glowroot.agent.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at org.glowroot.agent.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at org.glowroot.agent.shaded.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

Regards
Saurabh

**Comment by trask** [comment]
Hi @saurabh256, thanks for reporting this!  I think it should be fixed now in the latest snapshot release [glowroot-agent-0.9.23-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.23-SNAPSHOT).

**Comment by saurabh256** [comment]
Thanks for the prompt fix ..the very next day of reporting this. I really love using glowroot.
