### ISSUE TITLE
GaugeCollector - error accessing mbean attribute

### ISSUE THREAD

**Issue by Albertus82** [glowroot/glowroot#257]
Dear @trask, I found this exception in the yesterday's log file:
```
2017-08-08 10:00:01.166 WARN  o.glowroot.agent.init.GaugeCollector - error accessing mbean attribute: java.lang:type=MemoryPool,name=Eden Space Usage.used
javax.management.RuntimeErrorException: java.lang.InternalError: Memory Pool not found
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:841)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:651)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.getAttribute(LazyPlatformMBeanServer.java:136)
	at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:191)
	at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:173)
	at org.glowroot.agent.init.GaugeCollector.runInternal(GaugeCollector.java:121)
	at org.glowroot.agent.shaded.glowroot.common.util.ScheduledRunnable.run(ScheduledRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InternalError: Memory Pool not found
	at sun.management.MemoryPoolImpl.getUsage0(Native Method)
	at sun.management.MemoryPoolImpl.getUsage(MemoryPoolImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
	at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at javax.management.StandardMBean.getAttribute(StandardMBean.java:372)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	... 13 common frames omitted
```
Anyway, Glowroot is running fine but the Eden Space Usage graph lacks some data:

![Screenshot](https://user-images.githubusercontent.com/8672431/29117826-fd3cfa9c-7cff-11e7-8a59-4a03de19a838.PNG)

The execution evironment is Linux Raspbian Jessie (armhf). This is the startup log:
```
2017-08-07 22:11:10.045 INFO  org.glowroot - Glowroot version: 0.9.23, built 2017-08-07 04:44:13 +0000
2017-08-07 22:11:10.053 INFO  org.glowroot - Java version: 1.8.0_144
2017-08-07 22:11:22.184 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2017-08-07 22:11:41.121 INFO  org.glowroot - UI listening on 0.0.0.0:8080
```
If you need further information, feel free to ask. Thank you.

**Comment by trask** [comment]
Hi @Albertus82, thanks for reporting!  That's really interesting, did another memory pool happen to get captured during that time instead?  (check the gauges listed below the chart)

**Comment by Albertus82** [comment]
Hi @trask, here I selected all **java.lang / Memory*** gauges; as you can see, only _Eden Space_ lacks data.

![Screenshot](https://user-images.githubusercontent.com/8672431/29134656-ab5ddf92-7d37-11e7-98f0-3bf0d87a1486.PNG)

**Comment by Albertus82** [comment]
New log: [glowroot.2017-08-20.txt](https://github.com/glowroot/glowroot/files/1237333/glowroot.2017-08-20.txt)

**Comment by trask** [comment]
Hi @Albertus82, thanks again for reporting the error.  I think in this case logging the error is a good thing, as it explain why the Eden Space gauge was not captured for a period of time.  I'm not sure what glowroot can do better here, but if you or anyone else has ideas please feel free to re-open this issue.  Thanks.
