### ISSUE TITLE
Websphere Application Server 8.5 + java 7, IncompatibleClassChangeError in JUL Aspect

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#270]
Hi,
I tried upgrading  to 0.9.24, and restarted my app server, and got the following exceptions in the log.

(It came a bunch of times, but this is representative of it).

Is there any way to disable the JavaLoggingAspect?

Is there any additional information I can provide on this?

Its IBMs JDK 1.7 thats being used.
```
[9/20/17 11:34:23:092 CEST] 0000005d webapp        E com.ibm.ws.webcontainer.webapp.WebApp initializeStaticFileHandler SRVE0302E: Error while adding static file processor: {0}
                                 java.lang.IncompatibleClassChangeError
	at org.glowroot.agent.plugin.logger.JavaLoggingAspect$LogAdvice.onBefore(JavaLoggingAspect.java:62)
	at com.ibm.ws.logging.WsLogger.log(WsLogger.java)
	at com.ibm.ws.logging.WsLogger.logp(WsLogger.java:607)
	at com.ibm.wsspi.webcontainer.logging.WebContainerLogger.logp(WebContainerLogger.java:65)

```

**Comment by trask** [comment]
Hi @asgerjensen, thanks for reporting this!  I'm able to reproduce and will look into it.

**Comment by trask** [comment]
Thanks again for reporting this. It should be fixed now in the latest snapshot release [glowroot-agent-0.9.25-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.25-SNAPSHOT).
