### ISSUE TITLE
Error AbstractMethodError

### ISSUE THREAD

**Issue by willsilvano** [glowroot/glowroot#284]
Hi friends!

My application is crashing in some integrations, displaying errors like this:

`Caused by: java.lang.AbstractMethodError: com.ning.http.client.RequestBuilderBase$RequestImpl.getMethod()Ljava/lang/String;
	at org.glowroot.agent.plugin.httpclient.AsyncHttpClientAspect$OldExecuteRequestAdvice.onBefore(AsyncHttpClientAspect.java:211)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java)
	at br.senai.sc.sgn2.integracao.core.moodle.business.MoodleIntegracaoBusiness.enviaServicoHttp(MoodleIntegracaoBusiness.java:64)
	at br.senai.sc.sgn2.integracao.core.moodle.business.MoodleDiarioBusiness.obterCategoria(MoodleDiarioBusiness.java:116)
	at br.senai.sc.sgn2.integracao.core.moodle.business.MoodleDiarioBusiness.integrarDiarioMoodle(MoodleDiarioBusiness.java:80)
	... 107 more
JBAS014268: Failure in caller transaction.: java.lang.RuntimeException`

Is that conflict with Glowroot?

**Comment by trask** [comment]
Hi @willsilvano, thanks for posting!  Yes, this looks like an issue, what version of AsyncHttpClient are you using?  Thanks.

**Comment by willsilvano** [comment]
Hello @trask !!

It's version 1.4.0.

**Comment by trask** [comment]
Thanks for reporting this. It should be fixed now in the latest snapshot release [glowroot-agent-0.9.27-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.27-SNAPSHOT).
