### ISSUE TITLE
Support for OpenLiberty

### ISSUE THREAD

**Issue by tfarter** [glowroot/glowroot#307]
Hello,

I discovered a problem with glowroot and OpenLiberty. Are there any solutions for this issue?
Glowroot is amazing and it is exactly what I am looking for. But in the current state it is not useable for me. 

/thx

[03.01.18 07:01:38:572 MEZ] 0000001b LogService-4-com.ibm.ws.kernel.service.location              E CWWKE0701E: FrameworkEvent ERROR Bundle:com.ibm.ws.kernel.service.location(id=4) org.osgi.framework.BundleException: Exception in com.ibm.ws.kernel.service.location.internal.Activator.start() of bundle com.ibm.ws.kernel.service.location.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NoClassDefFoundError: org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:377)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:276)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:655)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:578)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	at com.ibm.ws.kernel.service.location.internal.SymbolRegistry.<clinit>(SymbolRegistry.java:39)
	at com.ibm.ws.kernel.service.location.internal.WsLocationAdminImpl.createLocations(WsLocationAdminImpl.java:106)
	at com.ibm.ws.kernel.service.location.internal.Activator.start(Activator.java:53)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(AccessController.java:694)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin cannot be found by com.ibm.ws.kernel.service.location_1.1.19.201712061531
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 33 more
 Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.kernel.service.location_1.1.19.201712061531 [4]] 
[03.01.18 07:01:38:901 MEZ] 0000001f com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: Es wurde ein FFDC-Vorfall erstellt: "java.lang.NullPointerException com.ibm.ws.config.admin.internal.WSConfigAdminActivator 85" unter ffdc_18.01.03_07.01.38.0.log
[03.01.18 07:01:38:916 MEZ] 0000001b LogService-8-com.ibm.ws.config                               E CWWKE0701E: FrameworkEvent ERROR Bundle:com.ibm.ws.config(id=8) org.osgi.framework.BundleException: Exception in com.ibm.ws.config.internal.WSConfigActivator.start() of bundle com.ibm.ws.config.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NullPointerException
	at com.ibm.ws.config.admin.internal.WSConfigAdminActivator.quit(WSConfigAdminActivator.java:128)
	at com.ibm.ws.config.admin.internal.WSConfigAdminActivator.start(WSConfigAdminActivator.java:87)
	at com.ibm.ws.config.internal.WSConfigActivator.start(WSConfigActivator.java:30)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(AccessController.java:694)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 12 more
 Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.config_1.0.19.201712061602 [8]] 
[03.01.18 07:01:38:963 MEZ] 0000001b LogService-11-com.ibm.ws.org.apache.felix.scr                E CWWKE0701E: FrameworkEvent ERROR Bundle:com.ibm.ws.org.apache.felix.scr(id=11) org.osgi.framework.BundleException: Exception in org.apache.felix.scr.impl.Activator.start() of bundle com.ibm.ws.org.apache.felix.scr.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NoClassDefFoundError: org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:377)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:276)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:655)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:578)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	at org.apache.felix.scr.impl.Activator.doStart(Activator.java:167)
	at org.apache.felix.utils.extender.AbstractExtender.start(AbstractExtender.java:114)
	at org.apache.felix.scr.impl.Activator.restart(Activator.java:142)
	at org.apache.felix.scr.impl.config.ScrConfigurationImpl.configure(ScrConfigurationImpl.java:196)
	at org.apache.felix.scr.impl.config.ScrConfigurationImpl.start(ScrConfigurationImpl.java:117)
	at org.apache.felix.scr.impl.Activator.start(Activator.java:110)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(AccessController.java:694)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin cannot be found by com.ibm.ws.org.apache.felix.scr_1.0.19.201712061531
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 36 more
 Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.org.apache.felix.scr_1.0.19.201712061531 [11]]

**Comment by trask** [comment]
Hi @tfarter, thanks for reporting this! I'm able to reproduce this and will look into it.

**Comment by trask** [comment]
Thanks again for reporting this.  It should be fixed now in the latest snapshot release [glowroot-agent-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.0-SNAPSHOT).

**Comment by tfarter** [comment]
Thank you for the fast response and for the fix. But unfortunately the fix do not work for me. Please tell me what environment (JVM) do you use for OpenLiberty.
[commons-daemon.2018-01-15.zip](https://github.com/glowroot/glowroot/files/1630509/commons-daemon.2018-01-15.zip)

/best regards
tfarter

**Comment by trask** [comment]
Hi @tfarter, I used the "Get started" (git clone) instructions at https://openliberty.io.  I'm not sure why I didn't run into the java.lang.VerifyError you are getting now, but I just tried with the download from the same page, and got the java.lang.VerifyError right away, so that's good.  I will look into and fix soon.

**Comment by trask** [comment]
Hi @tfarter, I think this should be fixed now, have another try with the latest snapshot release [glowroot-agent-0.10.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.1-SNAPSHOT). Thanks.

**Comment by tfarter** [comment]
Hello, thank you very much for your effort. The new build works fine :-). Is there place where I can donate a little for your hard work?
