### ISSUE TITLE
Getting 500 error in app when glowroot is enabled

### ISSUE THREAD

**Issue by zshahan** [glowroot/glowroot#322]
I am getting a 500 error in my application on certain pages with glowroot enabled.  I'm assuming this is a bug?
```
 2018-02-16 15:49:42.725 ERROR 29019 --- [pr-8009-exec-20] o.s.b.w.s.ErrorPageFilter                : Forwarding to error page from request [/gpls/create] due to exception [java.util.ArrayList cannot be cast to [Ljava.lang.String;]

java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.String;
	at org.glowroot.agent.plugin.servlet.DetailCapture.captureRequestParameters(DetailCapture.java:60) ~[?:0.10.2]
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.captureRequestParameters(RequestParameterAspect.java:91) ~[?:0.10.2]
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.onReturn(RequestParameterAspect.java:51) ~[?:0.10.2]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:140) ~[servlet-api.jar:3.0.FR]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:75) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) ~[catalina.jar:7.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) ~[catalina.jar:7.0.50]
    ...

2018-02-16 15:49:42.758  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: timestamp Value: Fri Feb 16 15:49:42 CST 2018
2018-02-16 15:49:42.758  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: status Value: 500
2018-02-16 15:49:42.758  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: error Value: Internal Server Error
2018-02-16 15:49:42.758  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: exception Value: java.lang.ClassCastException
2018-02-16 15:49:42.759  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: message Value: java.util.ArrayList cannot be cast to [Ljava.lang.String;
2018-02-16 15:49:42.759  INFO 29019 --- [pr-8009-exec-20] c.f.o.c.e.e.ServletErrorController       : Key: trace Value: java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.String;
	at org.glowroot.agent.plugin.servlet.DetailCapture.captureRequestParameters(DetailCapture.java:60)
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.captureRequestParameters(RequestParameterAspect.java:91)
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.onReturn(RequestParameterAspect.java:51) 
```

**Comment by trask** [comment]
Hi @zshahan, thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.10.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.3-SNAPSHOT).

**Comment by zshahan** [comment]
Awesome, thanks!
