### ISSUE TITLE
Transactions -> Service Calls are not being captured

### ISSUE THREAD

**Issue by Sohailjp** [glowroot/glowroot#328]
Dear Trask,

I have configured agents on JBoss and WebLogic App servers and I noticed that the "Service Calls" inside Transactions section is not being captured for WebLogic application server. For JBoss it is being captured and I can see the data. 

I am pretty much sure that the applications running on WebLogic are indeed making webservice calls (REST and SOAP) which I expect to see in the service calls section. 

Is there any config that I need to do to capture this service call data for WebLogic?

Thank you.

**Comment by trask** [comment]
Hi @Sohailjp, what library/api is the application using to make the outgoing webservice calls?

**Comment by Sohailjp** [comment]
Hello @trask,
The developer just said the he is using the core java stuff but not sure on the libraray, beacuse he use the jdeveloper to generate the proxy and stubs for the wsdl and not sure what library that jde use in the 
backed. 

Below is the stack trace of one of the web service calls isMobileNoExist(). Can you figure it out what library is being used. 





sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
com.sun.proxy.$Proxy290.isMobileNoExist()
com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:161)
com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:92)
com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:191)
com.sun.xml.ws.client.Stub.process(Stub.java:463)
com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:110)
com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:145)
com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:232)
com.sun.xml.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:241)
com.sun.xml.ws.transport.http.client.HttpClientTransport.readResponseCodeAndMessage(HttpClientTransport.java:206)
weblogic.net.http.HttpURLConnection.getResponseCode(HttpURLConnection.java:1545)
weblogic.net.http.SOAPHttpURLConnection.getInputStream(SOAPHttpURLConnection.java:41)
weblogic.net.http.HttpURLConnection.getInputStream(HttpURLConnection.java:688)
weblogic.net.http.HttpClient.parseHTTP(HttpClient.java:554)
weblogic.net.http.MessageHeader.parseHeader(MessageHeader.java:232)
weblogic.net.http.MessageHeader.isHTTP(MessageHeader.java:310)
java.io.BufferedInputStream.read(BufferedInputStream.java:345)
java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
weblogic.socket.NIOInputStream.read(NIOInputStream.java:73)
weblogic.socket.NIOInputStream.read(NIOInputStream.java:90)
weblogic.socket.NIOInputStream.readInternal(NIOInputStream.java:146)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.DevPollSelectorImpl.doSelect(DevPollSelectorImpl.java:98)
sun.nio.ch.DevPollArrayWrapper.poll(DevPollArrayWrapper.java:223)
sun.nio.ch.DevPollArrayWrapper.poll0(Native Method)

**Comment by trask** [comment]
Thanks, this helps.  What version of WebLogic are you running?

**Comment by Sohailjp** [comment]
Weblogic Version: 12.2.1.0.0
java version "1.8.0_77"

**Comment by trask** [comment]
Hi @Sohailjp, thanks for reporting this!  It should be fixed in the latest release [glowroot-0.10.4-dist.zip](https://github.com/glowroot/glowroot/releases/download/v0.10.4/glowroot-0.10.4-dist.zip).

**Comment by Sohailjp** [comment]
Dear @trask ,

I upgraded the central and the agent to 0.10.4 version. The WebLogic failed to start due to the below exceptions.

-----------------------------------
java.lang.RuntimeException: RetransformClasses returned 66
        at jdk.internal.instrumentation.Tracer.retransformClasses0(Native Method)
        at jdk.internal.instrumentation.Tracer.addInstrumentations(Tracer.java:213)
        at jdk.management.resource.internal.inst.InitInstrumentation.run(InitInstrumentation.java:89)
        at jdk.management.resource.ResourceContextFactory.initInstrumentation(ResourceContextFactory.java:140)
        at jdk.management.resource.ResourceContextFactory.getInstance(ResourceContextFactory.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.weblogic.rcm.framework.base.RCMHelper.isRMEnabledInJDK(RCMHelper.java:166)
        at com.oracle.weblogic.rcm.framework.base.RCMHelper.<clinit>(RCMHelper.java:111)
        at com.oracle.weblogic.rcm.framework.init.RCMInitService.start(RCMInitService.java:45)
        at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1262)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:332)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
TestLogger error: Unable to load class: RetransformClasses returned 66, ex: java.lang.RuntimeException: RetransformClasses returned 66
java.lang.RuntimeException: RetransformClasses returned 66
        at jdk.internal.instrumentation.Tracer.retransformClasses0(Native Method)
        at jdk.internal.instrumentation.Tracer.addInstrumentations(Tracer.java:213)
        at jdk.management.resource.internal.inst.InitInstrumentation.run(InitInstrumentation.java:89)
        at jdk.management.resource.ResourceContextFactory.initInstrumentation(ResourceContextFactory.java:140)
        at jdk.management.resource.ResourceContextFactory.getInstance(ResourceContextFactory.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.weblogic.rcm.framework.base.RCMHelper.isRMEnabledInJDK(RCMHelper.java:166)
        at com.oracle.weblogic.rcm.framework.init.RCMInitService.start(RCMInitService.java:65)
        at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1262)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:332)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
-------------------------------------------------





<Mar 5, 2018 11:55:34 AM AST> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.0.0 Tue Oct  6 10:05:47 PDT 2015 1721936> 
<Mar 5, 2018 11:55:34 AM AST> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: A MultiException has 4 exceptions.  They are:
1. java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    weblogic/net/http/HttpURLConnection.connect()V @211: invokestatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer'
  Current Frame:
    bci: @211
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, integer, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 014c 014d 10ff 3e03 3604 b800 fd59 4cb6
    0x0000010: 0103 594d c600 1e2c b901 0901 0059 3e13
    0x0000020: 010a 9f00 102c 1301 0ab9 010e 0200 04a7
    0x0000030: 0004 0336 0401 3a05 1504 9900 0a2c 2ab8
    0x0000040: 0114 3a05 2ab4 011b 9900 06a7 0081 2a2a
    0x0000050: b401 1e2a b400 9f2a b601 202a b400 6b2a
    0x0000060: b601 232a b601 262a b400 852a b400 87b8
    0x0000070: 012a b500 c1a7 000e 3a06 2a19 06b5 0083
    0x0000080: 1906 bf2a b400 c12a b601 2e2a 04b5 011b
    0x0000090: b200 d099 0036 bb00 d259 b700 d313 0130
    0x00000a0: b600 d92a b400 c1b6 00dc 1301 32b6 00d9
    0x00000b0: 2ab4 006b 9900 0913 0134 a700 0613 0136
    0x00000c0: b600 d9b6 00df b800 e2a7 0003 1504 9900
    0x00000d0: 0819 05b8 0141 1d10 ff9f 000a 2c1d b901
    0x00000e0: 0e02 00b1 1504 9900 0959 1905 b801 471d
    0x00000f0: 10ff 9f00 0a2c 1db9 010e 0200 bf       
  Exception Handler Table:
    bci [78, 117] => handler: 120
    bci [68, 204] => handler: 228
  Stackmap Table:
    full_frame(@50,{Object[#2],Object[#255],Object[#261],Integer,Integer},{})
    same_locals_1_stack_item_frame(@51,Integer)
    append_frame(@68,Object[#278])
    same_frame(@78)
    same_locals_1_stack_item_frame(@120,Object[#280])
    same_frame(@131)
    same_locals_1_stack_item_frame(@189,Object[#210])
    full_frame(@192,{Object[#2],Object[#255],Object[#261],Integer,Integer,Object[#278]},{Object[#210],Object[#312]})
    same_frame(@201)
    same_frame(@204)
    same_frame(@214)
    same_frame(@227)
    same_locals_1_stack_item_frame(@228,Object[#323])
    same_locals_1_stack_item_frame(@239,Object[#323])
    same_locals_1_stack_item_frame(@252,Object[#323])

2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.FinalThreadLocalService errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.FinalThreadLocalService
