### ISSUE TITLE
Agent throws LinkageError in TomEE deployment

### ISSUE THREAD

**Issue by droidnxs** [glowroot/glowroot#333]
Apache TomEE Version: Apache TomEE Plus 7.0.3
Error:
`2018-03-07 12:11:20.135 ERROR o.glowroot.agent.init.GaugeCollector - General error: "java.lang.LinkageError: org/glowroot/agent/embedded/shaded/org/h2/expression/AggregateData"; SQL statement:
merge into gauge_value_rollup_1 (gauge_id, capture_time, value, weight) key (gauge_id, capture_time) select gauge_id, ceil(capture_time / 60000.0) * 60000 ceil_capture_time, sum(value * weight) / sum(weight), sum(weight) from gauge_value_rollup_0 gp where gp.capture_time > ? and gp.capture_time <= ? group by gp.gauge_id, ceil_capture_time [50000-176]
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: General error: "java.lang.LinkageError: org/glowroot/agent/embedded/shaded/org/h2/expression/AggregateData"; SQL statement:
merge into gauge_value_rollup_1 (gauge_id, capture_time, value, weight) key (gauge_id, capture_time) select gauge_id, ceil(capture_time / 60000.0) * 60000 ceil_capture_time, sum(value * weight) / sum(weight), sum(weight) from gauge_value_rollup_0 gp where gp.capture_time > ? and gp.capture_time <= ? group by gp.gauge_id, ceil_capture_time [50000-176]
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:167)
        at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.convert(DbException.java:290)
        at org.glowroot.agent.embedded.shaded.org.h2.command.Command.executeUpdate(Command.java:262)
        at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
        at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
        at org.glowroot.agent.embedded.util.DataSource.update(DataSource.java:371)
        at org.glowroot.agent.embedded.util.DataSource.update(DataSource.java:343)
        at org.glowroot.agent.embedded.repo.GaugeValueDao.rollup(GaugeValueDao.java:194)
        at org.glowroot.agent.embedded.repo.GaugeValueDao.store(GaugeValueDao.java:154)
        at org.glowroot.agent.embedded.init.CollectorImpl.collectGaugeValues(CollectorImpl.java:109)
        at org.glowroot.agent.init.CollectorProxy.collectGaugeValues(CollectorProxy.java:86)
        at org.glowroot.agent.init.GaugeCollector$2.run(GaugeCollector.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.LinkageError: org/glowroot/agent/embedded/shaded/org/h2/expression/AggregateData
        at org.glowroot.agent.embedded.shaded.org.h2.expression.Aggregate.updateAggregate(Aggregate.java:244)
        at org.glowroot.agent.embedded.shaded.org.h2.expression.Operation.updateAggregate(Operation.java:388)
        at org.glowroot.agent.embedded.shaded.org.h2.command.dml.Select.queryGroup(Select.java:356)
        at org.glowroot.agent.embedded.shaded.org.h2.command.dml.Select.queryWithoutCache(Select.java:641)
        at org.glowroot.agent.embedded.shaded.org.h2.command.dml.Query.query(Query.java:323)
        at org.glowroot.agent.embedded.shaded.org.h2.command.dml.Query.query(Query.java:291)
        at org.glowroot.agent.embedded.shaded.org.h2.command.dml.Merge.update(Merge.java:111)
        at org.glowroot.agent.embedded.shaded.org.h2.command.CommandContainer.update(CommandContainer.java:79)
        at org.glowroot.agent.embedded.shaded.org.h2.command.Command.executeUpdate(Command.java:254)
        ... 12 common frames omitted`

**Comment by trask** [comment]
Hi @droidnxs, thanks for reporting this!  I'm not getting this error when I try with TomEE Plus 7.0.3, what JVM/version are you using, and what JVM args (e.g. any other agents), so I can try to repro?  Thanks.

**Comment by trask** [comment]
Oh yes, and what glowroot version? Thanks.

**Comment by droidnxs** [comment]
Hi @trask,

We're using **Glowroot-0.10.4**, and there is another Java agent (OpenEJB) we have deployed in the same container for JPA.
**JVM Args**:
`-Djava.util.logging.config.file=/opt/ApacheTomeePlus7.0.3/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -javaagent:/opt/ApacheTomeePlus7.0.3/lib/openejb-javaagent.jar -Djdk.tls.ephemeralDHKeySize=2048 -javaagent:/home/Glowroot/glowroot.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9094 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=10.10.8.65 -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/logs/gc.out-2018-03-14 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Duser.timezone=GMT -Djava.security.egd=file:/dev/./urandom -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+ParallelRefProcEnabled -Dcatalina.base=/opt/ApacheTomeePlus7.0.3 -Dcatalina.home=/opt/ApacheTomeePlus7.0.3 -Djava.io.tmpdir=/opt/ApacheTomeePlus7.0.3/temp`

Thank you for glowroot! :)

**Comment by trask** [comment]
Hi @droidnxs, I'm still unable to reproduce this.  What Java version are you running?  And is it Oracle/OpenJDK/other?  

I'm not seeing anything that might cause `java.lang.LinkageError` at `org.glowroot.agent.embedded.shaded.org.h2.expression.Aggregate.updateAggregate(Aggregate.java:244)`.

Can you download and try with a fresh copy of glowroot 0.10.4 (or 0.10.5), just to be sure your local jar file didn't get corrupted somehow?

Thanks,
Trask

**Comment by droidnxs** [comment]
Hi @trask ,

Apologies for the delayed response. We are using jdk 1.8.0_161. I am fairly certain the glowroot installation is not corrupt as it works on another service running on the same VM with the same JVM version as well. I tried deploying it again and the error seems slightly different this time:

> 2018-04-25 09:40:46.186 ERROR org.glowroot - Glowroot cannot start: General error: "java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: ""org/glowroot/agent/embedded/shaded/org/h2/store/PageOutputStream""" [50000-176]
> org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: General error: "java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: ""org/glowroot/agent/embedded/shaded/org/h2/store/PageOutputStream""" [50000-176]
> 	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
> 	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:167)
> 	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.convert(DbException.java:290)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.openDatabase(Database.java:291)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.<init>(Database.java:254)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(Engine.java:57)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(Engine.java:164)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(Engine.java:125)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(Engine.java:27)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
> 	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
> 	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
> 	at org.glowroot.agent.embedded.util.DataSource.createConnection(DataSource.java:615)
> 	at org.glowroot.agent.embedded.util.DataSource.<init>(DataSource.java:108)
> 	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.createDataSource(EmbeddedAgentModule.java:355)
> 	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.access$100(EmbeddedAgentModule.java:75)
> 	at org.glowroot.agent.embedded.init.EmbeddedAgentModule$1.run(EmbeddedAgentModule.java:173)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/glowroot/agent/embedded/shaded/org/h2/store/PageOutputStream"
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.openForWriting(PageLog.java:186)
> 	at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.openForWriting(PageStore.java:387)
> 	at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.openExisting(PageStore.java:373)
> 	at org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.open(PageStore.java:289)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.getPageStore(Database.java:2366)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.open(Database.java:657)
> 	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.openDatabase(Database.java:260)
> 	... 15 common frames omitted

I checked datasource configuration and there seems to be an entry for H2 that the application seems to use internally. Could it be that glowroot is conflicting with the existing H2 classes in the classloader?

**Comment by trask** [comment]
Hi @droidnxs, can you add `-verbose:class` to your JVM args and re-run and post the (long) output?  Thanks.

**Comment by droidnxs** [comment]
@trask 

Attaching file since the browser crashes if I try to paste the content.
Noteworthy - The error was different this time too i.e., on a different class, so the issue possibly isn't related to a specific class or group of classes.
[catalina.out.log](https://github.com/glowroot/glowroot/files/1950124/catalina.out.log)

**Comment by trask** [comment]
Hi @droidnxs, can you add `-Dglowroot.debug.printClassLoading=true` to your JVM args and re-run using the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).  This will print out an exception stack trace every time that an `org.glowroot...` class is loaded via `sun/misc/Launcher$AppClassLoader`, so I can see where the duplicate class loading is coming from.  Thanks!

**Comment by droidnxs** [comment]
@trask - Here you go:
[catalina.log](https://github.com/glowroot/glowroot/files/1954717/catalina.log)

**Comment by droidnxs** [comment]
@trask - Appreciate the timely help :)
