### ISSUE TITLE
IllegalArgumentException when trying grpc.https with self signed cert and key

### ISSUE THREAD

**Issue by gregpierro** [glowroot/glowroot#345]
Hello. I have a Tomcat based installation of .10.5.0 just deployed yesterday. things going well until i try to set up grpc over https for my agents i'm testing. 

I followed this step in the wiki
Note: A private key and self signed certificate can be generated at the command line meeting these requirements using: openssl req -new -x509 -nodes -days 365 -out grpc-cert.pem -keyout grpc-key.pem.

followed it verbatim with that command. when loading, glowroot-central dumps out with this. glowroot-servlet is the glowroot folder with properties file used by the JVM running it as well. 

non https works great! 

2018-03-30 11:12:15.762 ERROR org.glowroot - File does not contain valid private key: G:\Glowroot\glowroot-servlet\grpc-key.pem
java.lang.IllegalArgumentException: File does not contain valid private key: G:\Glowroot\glowroot-servlet\grpc-key.pem
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:54)
	at io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:104)
	at io.grpc.netty.NettyServerBuilder.useTransportSecurity(NettyServerBuilder.java:434)
	at org.glowroot.central.GrpcServer.startServer(GrpcServer.java:92)
	at org.glowroot.central.GrpcServer.<init>(GrpcServer.java:80)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:183)
	at org.glowroot.central.CentralModule.createForServletContainer(CentralModule.java:104)
	at org.glowroot.central.GlowrootServlet.init(GlowrootServlet.java:72)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1124)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1079)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:407)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1045)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 29 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
	at java.security.KeyFactory.generatePrivate(Unknown Source)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1043)
	... 31 common frames omitted
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
	at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
	at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73)
	at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
	... 33 common frames omitted

**Comment by trask** [comment]
Hi @gregpierro, thanks for posting!  Can you run `openssl version` to check what version of openssl you are using so I can try to repro?

**Comment by gregpierro** [comment]
hi Trask, thanks for replying. and let me start by just saying this tool is very slick. We are looking for alternatives to a big name vendor tool in an effort to slash costs and we are in a very large enterprise, and this tool has a lot of nice promise and amazing features at the data and agent level. Not to be taken wrong, though we have worked with other vendor tools with teams of UX folks behind them and those might have some aspects that this doesn't, this has features and speed that others don't. so great work!

now, the version.

G:\GnuWin32\bin>openssl version
OpenSSL 0.9.8h 28 May 2008

gosh this is old, but i just downloaded it a few days ago.

**Comment by trask** [comment]
Thanks for the kind words.

I was able to repro the same issue using that version.

It looks like OpenSSL changed the default write format for private keys in 1.0.0: https://github.com/openssl/openssl/blob/OpenSSL_1_0_0-stable/CHANGES#L759

I've updated the Wiki to note that command should be run using OpenSSL 1.0.0 or later. Thanks for reporting this!

Btw, you can still use 0.9.8 to generate the key, but since it generates a PKCS#1 private key, you will then need to convert it to PKCS#8 using

```
openssl pkcs8 -in grpc-key.pem -topk8 -nocrypt -out grpc-key-new.pem
```

(see https://github.com/glowroot/glowroot/wiki/Private-key-and-X.509-certificate-chain-tips)

**Comment by gregpierro** [comment]
Hi Trask thanks again for the quick research and fix.!
