### ISSUE TITLE
All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException

### ISSUE THREAD

**Issue by vgmonnet** [glowroot/glowroot#351]
Cassandra is running on 9042 and able to query it using netstat. But still I am facing the following issue. Is it something to do with firewall exceptions?

2018-04-04 11:04:54.409 ERROR org.glowroot - All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.0.1:9042] Timed out waiting for server response))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.0.1:9042] Timed out waiting for server response))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
        at org.glowroot.central.util.Session.createTableWithLCS(Session.java:190)
        at org.glowroot.central.repo.AggregateDaoImpl.<init>(AggregateDaoImpl.java:371)
        at org.glowroot.central.repo.CentralRepoModule.<init>(CentralRepoModule.java:103)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:157)
        at org.glowroot.central.CentralModule.create(CentralModule.java:100)
        at org.glowroot.central.Main.start(Main.java:44)
        at org.glowroot.central.Main.main(Main.java:28)

**Comment by trask** [comment]
Hi @vgmonnet, thanks for posting!  Are you able to connect to Cassandra using `cqlsh`?

**Comment by vgmonnet** [comment]
@trask, hello... Eventhough I got this error, glowroot-cetral has started and I am able to proceed. But can you explain why this error is returned?
