### ISSUE TITLE
problem with glowroot central error message missing agent-rollup-id query parameter

### ISSUE THREAD

**Issue by quochoangnguyen** [glowroot/glowroot#366]
Hi 
I try to use glowroot central and glowroot agent.
More preciseley, in one machine where I install Tomcat Server, I put the following line in the catalina.bat 
set CATALINA_OPTS="-javaagent:C:\savliv\glowroot.jar -Dglowroot.agent.id=Tomcat -Dglowroot.agent.rollup.id=ma-app-BPM -Dglowroot.collector.address=http://50.89.56.34:8181"
And in an other machine where  I install Cassandra datastax. and glowroot central agent, when I start glowroot central agent, I have the following log :grinning:
2018-04-25 10:48:15.720 INFO  org.glowroot - Glowroot version: 0.10.8, built 2018-04-19 13:40:38 +0000

2018-04-25 10:48:15.736 INFO  org.glowroot - Java version: 1.8.0_121

2018-04-25 10:48:16.001 INFO  com.datastax.driver.core.Native - Could not load JNR C Library, native system calls through this library will not be available (set this logger level to DEBUG to see the full stack trace).

2018-04-25 10:48:16.001 INFO  c.datastax.driver.core.ClockFactory - Using java.lang.System clock to generate timestamps.
2018-04-25 10:48:16.017 INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer

2018-04-25 10:48:16.205 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.

2018-04-25 10:48:16.783 INFO  com.datastax.driver.core.Cluster - Cannot connect with protocol version V4, trying with V3

2018-04-25 10:48:17.080 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)

2018-04-25 10:48:17.080 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added

2018-04-25 10:48:17.283 INFO  org.glowroot - connected to Cassandra (version 2.1.15), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM

2018-04-25 10:48:28.283 INFO  org.glowroot - gRPC listening on 0.0.0.0:8181

2018-04-25 10:48:28.918 INFO  org.glowroot - UI listening on 0.0.0.0:4000

2018-04-25 10:48:28.919 INFO  org.glowroot - startup complete

2018-04-25 11:04:41.205 ERROR org.glowroot.ui.HttpServerHandler - error handling request /backend/synthetic-monitor/results?from=1524645240000&to=1524647280000: missing agent-rollup-id query parameter

org.glowroot.ui.JsonServiceException: missing agent-rollup-id query parameter

                at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:306)

                at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:236)

                at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)

                at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:127)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

                at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

                at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)

                at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

                at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)

                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)

                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)

                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)

                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)

                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)

                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)

                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)

                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)

                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)

                at java.lang.Thread.run(Unknown Source)

****
**Do you have any idea why I get the error message missing agent-rollup-id query parameter ?**

Thanks in advance

**Comment by quochoangnguyen** [comment]
Hi Trask

I have  made the modification in the file catalina.bat where I put set "CATALINA_OPTS=-javaagent:C:\savliv\glowroot.jar -Dglowroot.agent.id=Tomcat -Dglowroot.agent.rollup.id=ma-app-BPM -Dglowroot.collector.address=http://50.89.56.34:8181"

I restart the Tomcat server by running the catalina.bat But the problem remains.

It seems that the Glowroot Central UI can not get the data from the Tomcat Server because the Glowroot UI does not display the data of the Tomcat server (it displays just the message --> No active Agents in this time period) 

Do you have any idea for  the problem ?

Thanks a lot

**Comment by trask** [comment]
Can you post the Glowroot agent log?

**Comment by quochoangnguyen** [comment]
Hi Trask

I post the glowroot log file and the glowroot central properties file 

[glowroot-central.log](https://github.com/glowroot/glowroot/files/1951366/glowroot-central.log)

**Comment by quochoangnguyen** [comment]
Here is the glowroot central properties 
[glowroot-central_properties.txt](https://github.com/glowroot/glowroot/files/1951382/glowroot-central_properties.txt)

**Comment by trask** [comment]
Hi @quochoangnguyen, what about on the agent side?  Is there a `log` folder in the glowroot folder on the agent?  Can you post the log?

**Comment by quochoangnguyen** [comment]
Hi Trask

No There is not a folder for the agent side, because I have just downloaded the glowroot agent (a jar file) and after I put the  glowroot.jar in the directory C:\savliv\ of the machine where I have installed the Tomcat8

**Comment by trask** [comment]
Hi @quochoangnguyen, can you run tomcat from the command line and post the console output?  Thanks.

**Comment by trask** [comment]
Glad to hear it is working for you on Linux.

Based on the Windows logs you posted, it looks like you are running Tomcat as a service:

```
[2018-05-02 14:02:10] [info]  [ 1924] Stopping service...
[2018-05-02 14:02:11] [info]  [ 1924] Service stop thread completed.
[2018-05-02 14:02:11] [info]  [ 3440] Run service finished.
[2018-05-02 14:02:11] [info]  [ 3440] Commons Daemon procrun finished
[2018-05-02 14:02:24] [info]  [ 4528] Commons Daemon procrun (1.1.0.0 64-bit) started
[2018-05-02 14:02:24] [info]  [ 4528] Running 'Tomcat8' Service...
[2018-05-02 14:02:24] [info]  [ 2904] Starting service...
[2018-05-02 14:02:26] [info]  [ 2904] Service started in 1254 ms.
```

which means you should have a file `<tomcat>/bin/tomcat8w.exe`. Run that executable and add `-javaagent:path/to/glowroot.jar` to the Java Options under the Java tab (see https://github.com/glowroot/glowroot/wiki/Where-are-my-application-server's-JVM-args%3F#running-tomcat-as-a-windows-service).

**Comment by trask** [comment]
Great to hear!

**Comment by Rinkuujjainwal** [comment]
> Hi Trask,
> 
> It works now for me,
> 
> You know, I just move my application from the windows machine to a Linux machine and it is OK
> 
> It seems I have a problem with the starting of my tomcat server on the windows machine in the command line of the tomcat server and no problem for the Linux machine
> 
> Thanks

Dear quochoangnguyen,


Can you share the document, for Linux configuration?
