### ISSUE TITLE
Issue with one of our application on wildfly8

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#368]
Hi,

We tried glowroot with some of our applications,

But for one, we have an error and our application isn't working.

Thanks 

2018-04-26 11:43:29,190 ERROR [io.undertow.request] (undertow task-1) UT005023: Exception handling request to /front: java.lang.NullPointerException: null value in entry: CONTEXT=null
        at org.glowroot.agent.shaded.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) [glowroot.jar:0.10.8]
        at org.glowroot.agent.shaded.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:71) [glowroot.jar:0.10.8]
        at org.glowroot.agent.shaded.com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:48) [glowroot.jar:0.10.8]
        at org.glowroot.agent.shaded.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:359) [glowroot.jar:0.10.8]
        at org.glowroot.agent.shaded.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:332) [glowroot.jar:0.10.8]
        at org.glowroot.agent.impl.PluginServiceImpl.toImmutableMap(PluginServiceImpl.java:92) [glowroot.jar:0.10.8]
        at org.glowroot.agent.plugin.api.util.ImmutableMap.copyOf(ImmutableMap.java:30) [glowroot.jar:0.10.8]
        at org.glowroot.agent.plugin.servlet.HttpSessions.getSessionAttributes(HttpSessions.java:51) [glowroot.jar:0.10.8]
        at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceAdvice.onBeforeCommon(ServletAspect.java:196) [glowroot.jar:0.10.8]
        at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceAdvice.access$100(ServletAspect.java:124) [glowroot.jar:0.10.8]
        at org.glowroot.agent.plugin.servlet.ServletAspect$DoFilterAdvice.onBefore(ServletAspect.java:251) [glowroot.jar:0.10.8]
   
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_66]

**Comment by lfen21** [comment]
We cannot find CollectPreconditions.java in your git project ? can you give us this file's location please ?

Thanks

**Comment by trask** [comment]
Hi @lfen21, thanks for reporting this!  I think this should be fixed now in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).

**Comment by lfen21** [comment]
Thanks it's great !
