### ISSUE TITLE
issue with old version of jboss

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#370]
Hi

We have an issue with an old version of jboss with jdk6

Can you help please ? 

2018-04-27 10:59:42,577 INFO  [STDOUT] 2018-04-27 10:59:42.576 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving org/apache/jsp/****_
jsp: null
java.lang.NegativeArraySizeException: null
        at org.glowroot.agent.shaded.org.objectweb.asm.Frame.merge(Frame.java:1197)
        at org.glowroot.agent.shaded.org.objectweb.asm.CurrentFrame.execute(CurrentFrame.java:53)
        at org.glowroot.agent.shaded.org.objectweb.asm.MethodWriter.visitInsn(MethodWriter.java:851)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1937)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1238)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:631)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:617)
        at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:287)
        at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:147)
        at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
        at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:133)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:65)
        at org.apache.jasper.JspCompilationContext.load(JspCompilationContext.java:596)
        at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:147)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:314)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:264)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:810)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1124)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:932)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3951)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4225)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)
        at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

**Comment by trask** [comment]
Hi @lfen21, thanks for reporting this!  What version of JBoss are you using?  Also, what exact JDK6 version are you using (`java -version`)?

**Comment by trask** [comment]
Hi @lfen21, I'm not able to repro, but I fixed the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT) to dump the class file that Glowroot is failing on in this case (Glowroot will log the location where it dumps the class file).

Can you re-run with the latest snapshot release and upload the class file it dumps to me at https://www.dropbox.com/request/Jj1y4Jn8ajqYiBAcJNP4?

**Comment by trask** [comment]
It looks like a jsp class file that Glowroot is failing to weave: `WeavingClassFileTransformer - error weaving org/apache/jsp/****_jsp`.  Can you re-run with the latest snapshot release and upload the class file it dumps to me at https://www.dropbox.com/request/Jj1y4Jn8ajqYiBAcJNP4?

**Comment by lfen21** [comment]
i took the class file but i'm asking my direction if i can give it to you :).

Anyway have you a more secure way than dropbox please?

I tell you tomorrow, thanks

**Comment by trask** [comment]
You can email it to me if that is better.  You can find my email address on my github profile.  Thanks.

**Comment by lfen21** [comment]
it's ok, email sended

**Comment by lfen21** [comment]
have you receipt my mail ? thanks :)

**Comment by trask** [comment]
Yes thanks! I was able to repro and fix locally, I will post today or
tomorrow.

Trask

**Comment by lfen21** [comment]
great ! 

i will wait for it :) 

snapshot version are stable ? or it's better to wait version ?

**Comment by lfen21** [comment]
Hi, can i take a snapshot ? how long to a stable version  ? :)
Can i have the link please ? 

Thanks for your rapidity

**Comment by trask** [comment]
Snapshot is building right now, I'll post back when it's ready.

**Comment by trask** [comment]
Hi @lfen21, this should be fixed now in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT). If you have a chance to test the snapshot version that would be great. I will probably be releasing 0.10.9 in a few days.

**Comment by lfen21** [comment]
Hi, i have a new error, 

2018-05-04 10:37:58,130 ERROR [org.jboss.ejb.txtimer.TimerImpl] Error invoking ejbTimeout: javax.ejb.EJBException: java.lang.NullPointerException
2018-05-04 10:37:58,134 ERROR [org.jboss.ejb.txtimer.TimerImpl] Error invoking ejbTimeout: javax.ejb.EJBException: java.lang.NullPointerException
2018-05-04 10:37:58,142 ERROR [org.jboss.ejb.txtimer.TimerImpl] Error invoking ejbTimeout: javax.ejb.EJBException: java.lang.NullPointerException


Do you think, it's coming from the new version of glowroot ?

**Comment by lfen21** [comment]
Nevermind, error was already here without glowroot.

I'm sorry. Everything ok
