### ISSUE TITLE
About Oracle Application Server Profiler

### ISSUE THREAD

**Issue by vgmonnet** [glowroot/glowroot#371]
@trask, Will I be able to configure glowroot for Oracle Application Server in a Oracle EBS suite? Please suggest.

**Comment by trask** [comment]
Hi @vgmonnet, are you referring to Oracle WebLogic Server, or something else?  Thanks.

**Comment by vgmonnet** [comment]
Hi Trask, it is not Oracle WLS, but it is Oracle Application Server with OC4J

**Comment by trask** [comment]
Hi @vgmonnet, I tried and it worked for me, let me know if you have any issues.

**Comment by vgmonnet** [comment]
Hi Trask, I will try and let you know. Thanks.

**Comment by vgmonnet** [comment]
@Trask, If it is not a problem to ask, Can you share me the steps on how you added glowroot to Oracle Application Server?

**Comment by trask** [comment]
Hi @vgmonnet, no problem, I downloaded OC4J (so the setup might be a bit different) and ran it from the command line using the included `bin/oc4j` script, with first setting the environment variable `OC4J_JVM_ARGS=-javaagent:path/to/glowroot.jar`.

**Comment by vgmonnet** [comment]
ok. thanks for sharing.

**Comment by vgmonnet** [comment]
Hello Trask,
 Following are the parameters which I am trying to modify with the glowroot.jar
s_oafm_jvm_start_options and s_oacore_jvm_start_options. Please let me know if I need to add the glowroot.jar in s_oafm_jvm_stop_options and s_oacore_jvm_stop_options also??

Thanks in advance.

**Comment by trask** [comment]
Hi @vgmonnet, I suggest that you not add glowroot to the "stop" options (unless I am missing the purpose of the "stop" options which is possible).

**Comment by vgmonnet** [comment]
thanks for the response @trask

**Comment by vgmonnet** [comment]
Hello trask,

I got the glowroot configured in forms, oafm and oarcore under OC4J containers and getting a tmp lock issue. I have three different folders and copy of glowroot jar files for all the three containers specified above. But wondering why this tmp file lock issue occurs.

Please help me on this.

**# tmp file lock issue**
2018-05-27 12:15:11.793 ERROR org.glowroot - Glowroot not started, directory in use by another jvm process: /home/user/glowroot-profiler (unable to obtain lock on /home/user/glowroot-profiler/tmp/.lock)

2018-05-27 12:14:44.849 ERROR org.glowroot - Glowroot not started, directory in use by another jvm process: /home/user/glowroot-profiler-oacore (unable to obtain lock on /home/user/glowroot-profiler-oacore/tmp/.lock)

2018-05-27 12:14:44.849 ERROR org.glowroot - Glowroot not started, directory in use by another jvm process: /home/user/glowroot-profiler-oacore (unable to obtain lock on /home/user/glowroot-profiler-oacore/tmp/.lock)

**# Also I get the following error in log files,**
2018-05-27 12:14:45.543 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving load/C4: null
java.lang.Error: null
	at oracle.classloader.util.ClassLoadEnvironment$DependencyLoader.loadClass(ClassLoadEnvironment.java:2313)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClassPlanB(AnalyzedWorld.java:319)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:272)
	at org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:224)
	at org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:181)
	at org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:138)
	at org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:103)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:224)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:118)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:95)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at oracle.classloader.util.ClassLoadEnvironment$DependencyLoader.getCallStack(ClassLoadEnvironment.java:2304)
	at oracle.classloader.util.ClassLoadEnvironment.doGetDependencyResolutionMethodName(ClassLoadEnvironment.java:1425)
	at oracle.classloader.util.ClassLoadEnvironment.getDependencyResolutionMethodName(ClassLoadEnvironment.java:605)
	at oracle.classloader.util.ExecutionStack.<clinit>(ExecutionStack.java:69)
	at oracle.classloader.PolicyClassLoader.handleClassNotFound(PolicyClassLoader.java:2194)
	at oracle.classloader.PolicyClassLoader.internalLoadClass(PolicyClassLoader.java:1726)
	at oracle.classloader.PolicyClassLoader.loadClass(PolicyClassLoader.java:1682)
	at oracle.classloader.PolicyClassLoader.loadClass(PolicyClassLoader.java:1667)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2383)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1406)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1365)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1292)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1234)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:715)
	at com.evermind.util.OC4JProperty.<clinit>(OC4JProperty.java:23)
	at com.evermind.util.OC4JProperties.<clinit>(OC4JProperties.java:11)
	at com.evermind.util.ServerProperties.getOracleIasJcache(ServerProperties.java:71)
	at com.evermind.server.ApplicationServer.<clinit>(ApplicationServer.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at oracle.classloader.util.MainClass.invoke(MainClass.java:128)
	at oracle.oc4j.loader.boot.BootStrap.main(BootStrap.java:41)

**Comment by vgmonnet** [comment]
@trask, Please be informed that I initially get some statistics on both the forms and oacore OC4J containers. But it looks like after we navigate from Login to another module I don't see any statistics. Please help.

**Comment by vgmonnet** [comment]
more information:
when I grep the forms or oacore java process I find that more then 3 processes are running for each of them and in all their jvm params glowroot.jar is present.

**Comment by vgmonnet** [comment]
Hello Trask,
Can you please help me on this?

**Comment by trask** [comment]
Hi @vgmonnet, I think the `error weaving load/C4` should be fixed now in v0.10.10.

The tmp file locking issue is because multiple JVM processes are using Glowroot, see the wiki section [Monitoring multiple JVM processes on one box](https://github.com/glowroot/glowroot/wiki/Agent-Installation-(with-Embedded-Collector)#monitoring-multiple-jvm-processes-on-one-box) on how to address this.

Let me know if this makes sense / helps.

**Comment by vgmonnet** [comment]
@trask , 

> I think the error weaving load/C4 should be fixed now in v0.10.10.

Thanks for this. Will try with the current version.

> 
The tmp file locking issue is because multiple JVM processes are using Glowroot, see the wiki section Monitoring multiple JVM processes on one box on how to address this.

No, this is not solving the issue. I have tried. It may be because Oracle ERP is creating multiple client processes from inside the same JVM. Hope you have gone through all my previous posts.

**Comment by trask** [comment]
Hi @vgmonnet, can you find a way to set the JVM args individually for each of these client JVM processes? If so, then you could specify different `-Dglowroot.agent.id=...` for each one.

**Comment by trask** [comment]
Hi @vgmonnet, are you using the central or embedded collector for this?

**Comment by vgmonnet** [comment]
@trask it is the central collector I am using.

**Comment by vgmonnet** [comment]
@track, How are you? Did you check on this issue?

**Comment by trask** [comment]
Hi @vgmonnet, what are the complete JVM args used for the each JVM process?  I'm wondering if there's something distinct in the JVM args (e.g. a system property, or the main class / jar) that Glowroot could use internally to construct a distinct value for `glowroot.agent.id`.

**Comment by vgmonnet** [comment]
Hello @trask, There are three different JVM Processes namely forms, oafm and oacore. For which I am having different glowroot agents. Below are the actual JVM args,

> <forms_jvm_start_options oa_var="s_forms_jvm_start_options">-server -verbose:gc -Xmx256M -Xms64M -XX:MaxPermSize=128M -XX:NewRatio=2 -XX:+PrintGCTimeStamps -XX:+UseTLAB -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Djava.security.policy=$ORACLE_HOME/j2ee/oacore/config/java2.policy -Djava.awt.headless=true -Dhttp.webdir.enable=false -Doracle.security.jazn.config=/u01/oracle/Env/inst/apps/Server1/ora/10.1.3/j2ee/forms/config/jazn.xml -javaagent:/u01/profiler-forms/glowroot.jar</forms_jvm_start_options>
> 
> <oacore_jvm_start_options oa_var="s_oacore_jvm_start_options">-server -verbose:gc -Xmx3072M -Xms1024M -XX:MaxPermSize=600M -XX:NewRatio=2  -XX:+PrintGCTimeStamps -XX:+UseTLAB -XX:+UseParallelGC  -XX:ParallelGCThreads=4  -Dcom.sun.management.jmxremote -Djava.security.policy=$ORACLE_HOME/j2ee/oacore/config/java2.policy -Djava.awt.headless=true -Dhttp.webdir.enable=false -Doracle.security.jazn.config=/u01/oracle/Env/inst/apps/Server1/ora/10.1.3/j2ee/oacore/config/jazn.xml -javaagent:/u01/profiler-oacore/glowroot.jar</oacore_jvm_start_options>
> 
> <oafm_jvm_start_options oa_var="s_oafm_jvm_start_options">-server -verbose:gc -Xmx1024M -Xms512M -XX:MaxPermSize=512M -XX:NewRatio=2 -XX:+PrintGCTimeStamps -XX:+UseTLAB -XX:+UseParallelGC -XX:ParallelGCThreads=2  -Djava.security.policy=$ORACLE_HOME/j2ee/oacore/config/java2.policy  -Djava.awt.headless=true  -Dhttp.webdir.enable=false -Doracle.security.jazn.config=/u01/oracle/Env/inst/apps/Server1/ora/10.1.3/j2ee/oafm/config/jazn.xml -javaagent:/u01/profiler-oafm/glowroot.jar</oafm_jvm_start_options>

The above JVMs create **Child JVM Processes** and I am **not getting any transactions from the Child JVM Processes**.

**Comment by trask** [comment]
Thanks, this helped me look up a bit more about how it works. Looks like there is a "nproc" (number of processes) setting for each of these. Just want to confirm, you are running with nproc > 1 for each of these? e.g.

```
<forms_nprocs oa_var="s_forms_nprocs">2</forms_nprocs>

<oacore_nprocs oa_var="s_oacore_nprocs">2</oacore_nprocs>

<oafm_nprocs oa_var="s_oafm_nprocs">2</oafm_nprocs>
```

Thanks,
Trask

**Comment by vgmonnet** [comment]
@trask, Exactly. The nproc is > 1 for all the configurations.

**Comment by trask** [comment]
@vgmonnet Thanks for helping me understand this use case!

I think I'll add a feature where if you specify

`-Dglowroot.agent.id=myrollup::myagent-{{1..10}}`

then glowroot will try `myagent-1`, and if that agent subdir is locked by another JVM process, it will try `myagent-2` and so on up to `myagent-10`.

**Comment by vgmonnet** [comment]
@trask, Great! Will wait for that feature.

**Comment by trask** [comment]
Hi @vgmonnet, thanks for your patience!

`-Dglowroot.agent.id=myrollup::myagent-{{1..10}}`

should work now in the latest snapshot release [glowroot-agent-0.11.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.11.0-SNAPSHOT).

**Comment by vgmonnet** [comment]
Thanks @trask . Will try to test this. Unfortunately, I no longer have this environment. :(

**Comment by mnatsakanyank** [comment]
@trask Hi, I have used `-Dglowroot.agent.id=myrollup::myagent-{{1..10}}` on the latest **0.13.5** version of an agent and it seems it's not working as expected because in the glowroot central it shows up with exact `myagent-{{1..10}}` name.
