### ISSUE TITLE
Getting error when trying to use WebSphere 8.5.5

### ISSUE THREAD

**Issue by zshahan** [glowroot/glowroot#387]
I am getting this error below when starting WebSphere after adding glowroot.  Is it something I did wrong?

```
2018-05-16 21:39:29.709 INFO  org.glowroot - Glowroot version: 0.10.9, built 2018-05-10 00:48:11 +0000
2018-05-16 21:39:29.714 INFO  org.glowroot - Java version: 1.8.0_151
2018-05-16 21:39:32.187 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-05-16 21:39:32.531 ERROR o.g.agent.impl.BytecodeServiceImpl - null
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.ensureInit(LazyPlatformMBeanServer.java:207)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.create(LazyPlatformMBeanServer.java:81)
	at org.glowroot.agent.init.AgentModule.onEnteringMain(AgentModule.java:270)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:117)
	at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMain(BytecodeServiceImpl.java:72)
	at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
	at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java)
Caused by: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.ibm.ws.management.PlatformMBeanServerBuilder: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:514)
	at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:550)
	at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:327)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:242)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:203)
	at java.lang.management.ManagementFactory$ServerHolder.<clinit>(ManagementFactory.java:466)
	... 8 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:329)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:457)
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:499)
	... 13 common frames omitted
```

**Comment by trask** [comment]
Hi @zshahan, thanks for reporting this! It looks like Glowroot is not detecting that you are running WebSphere, and I'm not sure why. I added some debug logging to the latest snapshot release. Can you run with [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT), and also increase the logging level by creating a file named `glowroot.logback.xml` in the glowroot folder with the contents below, and then post back with the new log?

glowroot.logback.xml contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration>
<configuration>
  <appender name="CONSOLE" class="org.glowroot.agent.shaded.ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
  <appender name="FILE" class="org.glowroot.agent.shaded.ch.qos.logback.core.rolling.RollingFileAppender">
    <rollingPolicy class="org.glowroot.agent.shaded.ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>${glowroot.log.dir}/glowroot.%d{yyyy-MM-dd}.log</fileNamePattern>
      <maxHistory>7</maxHistory>
    </rollingPolicy>
    <prudent>true</prudent>
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
  <logger name="org.glowroot.agent.util.AppServerDetection" level="debug" />
  <logger name="org.glowroot.agent.shaded" level="warn" />
  <logger name="org.glowroot.agent.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler" level="off" />
  <root level="info">
    <appender-ref ref="CONSOLE" />
    <appender-ref ref="FILE" />
  </root>
  <logger name="audit" level="off" />
</configuration>
```

**Comment by zshahan** [comment]
Sure thing.  Attached is the new debug log.
[glowroot.2018-05-17.log](https://github.com/glowroot/glowroot/files/2013240/glowroot.2018-05-17.log)

**Comment by trask** [comment]
Hi @zshahan, thanks for the debug log. I think this should be fixed now in the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT).

**Comment by lcp573** [comment]
Good Morning
I relive this issue because I am having a similar problem with websphere version 9, in AIX environment
I have to say glowroot works wonders, but I have a permanent exception in the SystemOut causing unnecessary IO to be generated on the server
The exception is the following:

2020-08-19 00:00:00.696 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java.lang.management.ManagementFactory$ServerHolder (initializ
ation failure)
java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory$ServerHolder (initialization failure)
        at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:98)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
        at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
        at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
        at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.init(ServletWrapperImpl.java)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.load(ServletWrapper.java:1385)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1029)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963)
        at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
        at com.ibm.ws.ssl.channel.impl.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1187)
        at com.ibm.ws.ssl.channel.impl.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:694)
        at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
        at com.ibm.ws.tcp.channel.impl.WorkQueueManager.requestComplete(WorkQueueManager.java:558)
        at com.ibm.ws.tcp.channel.impl.WorkQueueManager.attemptIO(WorkQueueManager.java:608)
        at com.ibm.ws.tcp.channel.impl.WorkQueueManager.workerRun(WorkQueueManager.java:985)
        at com.ibm.ws.tcp.channel.impl.WorkQueueManager$Worker.run(WorkQueueManager.java:1074)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
Caused by: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.ibm.ws.management.PlatformMBeanServerBuilder: java.lang.ClassNotFoundExcepti
on: com.ibm.ws.management.PlatformMBeanServerBuilder
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:514)
        at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:550)
        at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:327)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:242)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:203)
        at java.lang.management.ManagementFactory$ServerHolder.<clinit>(ManagementFactory.java:466)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
        at oracle.jdbc.driver.OracleDriver.registerMBeans(OracleDriver.java:365)
        at oracle.jdbc.driver.OracleDriver$1.run(OracleDriver.java:241)
        at java.security.AccessController.doPrivileged(AccessController.java:647)
        at oracle.jdbc.driver.OracleDriver.<clinit>(OracleDriver.java:237)
        at java.lang.J9VMInternals.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1848)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:391)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:415)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:491)
        at java.sql.DriverManager$2.run(DriverManager.java:614)
        at java.sql.DriverManager$2.run(DriverManager.java:594)
        at java.security.AccessController.doPrivileged(AccessController.java:647)
        at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:594)
        at java.sql.DriverManager.<clinit>(DriverManager.java:112)
        at com.ibm.ws.runtime.component.JreMemoryLeakPreventionListener.lifecycleEvent(JreMemoryLeakPreventionListener.java:239)
        at com.ibm.ws.runtime.component.MemoryLeakMgrImpl.initialize(MemoryLeakMgrImpl.java:150)
        at com.ibm.ws.runtime.component.ContainerHelper.initWsComponent(ContainerHelper.java:1193)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponent(ContainerHelper.java:1100)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponents(ContainerHelper.java:902)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:776)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:750)
        at com.ibm.ws.runtime.component.ApplicationServerImpl.initialize(ApplicationServerImpl.java:192)
        at com.ibm.ws.runtime.component.ContainerHelper.initWsComponent(ContainerHelper.java:1193)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponent(ContainerHelper.java:1100)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponents(ContainerHelper.java:929)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:776)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:750)
        at com.ibm.ws.runtime.component.ServerImpl.initialize(ServerImpl.java:377)
        at com.ibm.ws.runtime.WsServerImpl.bootServerContainer(WsServerImpl.java:293)
        at com.ibm.ws.runtime.WsServerImpl.start(WsServerImpl.java:224)
        at com.ibm.ws.runtime.WsServerImpl.main(WsServerImpl.java:697)
        at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
        at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.wsspi.bootstrap.WSLauncher.launchMain(WSLauncher.java:234)
        at com.ibm.wsspi.bootstrap.WSLauncher.main(WSLauncher.java:101)
        at com.ibm.wsspi.bootstrap.WSLauncher.run(WSLauncher.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
        at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
        at org.eclipse.core.launcher.Main.run(Main.java:981)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:415)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:176)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:610)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:937)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:343)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:865)
        at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:457)
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:499)
        ... 64 common frames omitted


I've searched a lot before asking for help and can't really find any information about it
Any suggestion is welcome

Thank you!
