### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by Madrity** [glowroot/glowroot#393]
Hello,

i had some issue  : 

Caused by: java.lang.RuntimeException: Bytecode service retrieved too early
[2018-05-23 10:54:51.560 CEST]:     at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:28)
[2018-05-23 10:54:51.560 CEST]:     at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:27)
[2018-05-23 10:54:51.560 CEST]:     ... 8 more

what does that mean? 

thx.

**Comment by trask** [comment]
Thanks for reporting this! Can you post the full stack trace?

**Comment by Madrity** [comment]
[2018-05-23 10:54:51.457 CEST]: INFO: Starting Servlet Engine: Apache Tomcat/7.0.42
[2018-05-23 10:54:51.558 CEST]: May 23, 2018 10:54:51 AM org.apache.catalina.core.ContainerBase startInternal
[2018-05-23 10:54:51.558 CEST]: SEVERE: A child container failed during start
[2018-05-23 10:54:51.558 CEST]: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Engine].StandardHost[wkslx103.fra.local].StandardContext[/]]
[2018-05-23 10:54:51.558 CEST]:     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[2018-05-23 10:54:51.558 CEST]:     at java.util.concurrent.FutureTask.get(FutureTask.java:188)
[2018-05-23 10:54:51.558 CEST]:     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1123)
[2018-05-23 10:54:51.558 CEST]:     at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:800)
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
[2018-05-23 10:54:51.559 CEST]:     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[2018-05-23 10:54:51.559 CEST]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[2018-05-23 10:54:51.559 CEST]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[2018-05-23 10:54:51.559 CEST]:     at java.lang.Thread.run(Thread.java:744)
[2018-05-23 10:54:51.559 CEST]: Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Engine].StandardHost[wkslx103.fra.local].StandardContext[/]]
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
[2018-05-23 10:54:51.559 CEST]:     ... 6 more
[2018-05-23 10:54:51.559 CEST]: Caused by: java.lang.ExceptionInInitializerError
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java)
[2018-05-23 10:54:51.559 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.559 CEST]:     ... 6 more
[2018-05-23 10:54:51.559 CEST]: Caused by: java.lang.RuntimeException: Bytecode service retrieved too early
[2018-05-23 10:54:51.560 CEST]:     at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:28)
[2018-05-23 10:54:51.560 CEST]:     at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:27)
[2018-05-23 10:54:51.560 CEST]:     ... 8 more
[2018-05-23 10:54:51.560 CEST]:
 SEVERE: Exception during ServletEngine startup has occured
[2018-05-23 10:54:51.565 CEST]: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[8005]]
[2018-05-23 10:54:51.565 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
[2018-05-23 10:54:51.565 CEST]:     at com.intershop.beehive.core.internal.environment.ServletEngineMgr.startServletEngine(ServletEngineMgr.java:301)
[2018-05-23 10:54:51.565 CEST]:     at com.intershop.beehive.core.internal.environment.ServletEngineMgr.startServletEngine(ServletEngineMgr.java:261)
[2018-05-23 10:54:51.565 CEST]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2018-05-23 10:54:51.565 CEST]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[2018-05-23 10:54:51.565 CEST]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2018-05-23 10:54:51.565 CEST]:     at java.lang.reflect.Method.invoke(Method.java:606)
[2018-05-23 10:54:51.566 CEST]:     at com.intershop.beehive.loaderapp.Lifecycle.doStart(Lifecycle.java:139)
[2018-05-23 10:54:51.566 CEST]:     at com.intershop.beehive.loaderapp.Lifecycle.start(Lifecycle.java:101)
[2018-05-23 10:54:51.566 CEST]:     at com.intershop.beehive.loaderapp.ApplicationContextListener.contextInitialized(ApplicationContextListener.java:63)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
[2018-05-23 10:54:51.566 CEST]:     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
[2018-05-23 10:54:51.567 CEST]:     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1653)
[2018-05-23 10:54:51.567 CEST]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[2018-05-23 10:54:51.567 CEST]:     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[2018-05-23 10:54:51.567 CEST]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[2018-05-23 10:54:51.567 CEST]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[2018-05-23 10:54:51.567 CEST]:     at java.lang.Thread.run(Thread.java:744)
[2018-05-23 10:54:51.567 CEST]: Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Catalina]]
[2018-05-23 10:54:51.567 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
[2018-05-23 10:54:51.567 CEST]:     at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:732)
[2018-05-23 10:54:51.567 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.568 CEST]:     ... 22 more
[2018-05-23 10:54:51.568 CEST]: Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Engine]]
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.core.StandardService.startInternal(StandardService.java:443)
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.568 CEST]:     ... 24 more
[2018-05-23 10:54:51.568 CEST]: Caused by: org.apache.catalina.LifecycleException: A child container failed during start
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1131)
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:302)
[2018-05-23 10:54:51.568 CEST]:     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[2018-05-23 10:54:51.569 CEST]:     ... 26 more

**Comment by trask** [comment]
Hi @Madrity, to help track down the issue, I added a bit more info to the exception that is thrown. Can you re-run with the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT), and attach the new glowroot log?

**Comment by trask** [comment]
Hi @Madrity, I'd like to fix understand and fix this, can you still reproduce it? Can you re-run with the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT), and attach the new glowroot log?

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue.

**Comment by salimchami** [comment]
Hi, I have the same issue with the version 0.12.3.

**Comment by trask** [comment]
Hi @salimchami, can you try with 0.13.1? I believe this is fixed in 0.13.1 by #511. Thanks.

**Comment by Madrity** [comment]
It's OK for me with 0.13.1 release.

Thanks.

**Comment by trask** [comment]
👍
