### ISSUE TITLE
Glowroot causes exceptions for hikari

### ISSUE THREAD

**Issue by sergebug** [glowroot/glowroot#400]
Greeting,

We use hikari (2.3.8) for connection pooling.
After adding glowroot v0.10.9 as java agent attempt to run results in following exception:

2018-06-01 11:36:01.337 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)java.lang.ExceptionInInitializerError
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:31)

....

Caused by: java.lang.RuntimeException: Fatal exception during proxy generation
	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:61)
	... 22 more
Caused by: javassist.NotFoundException: glowroot$getStatementMirror(..) is not found in com.zaxxer.hikari.proxy.StatementProxy
	at javassist.CtClassType.getMethod(CtClassType.java:1196)
	at com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(JavassistProxyFactory.java:174)
	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<init>(JavassistProxyFactory.java:86)
	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:57)
	... 22 more

**Comment by sergebug** [comment]
If that's any help v0.9.21 of glowroot doesn't seem to have this problem. 
I also tried 0.9.28 and 0.10.4 and both have failed to launch

**Comment by sergebug** [comment]
Was able to resolve this issue by upgrading hikari from 2.3.8 to 2.6.1. You can close this issue

**Comment by trask** [comment]
Hi @sergebug, thanks for reporting this! I was able to repro, and went ahead and fixed in case others hit the same. Fix is available in the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT).
