### ISSUE TITLE
AgentUnsupportedOperationException on Glowroot Central

### ISSUE THREAD

**Issue by hgomez** [glowroot/glowroot#408]
I upgraded to 10.10, on central and agent side and now I cannot get query stats anymore.
I got this message on browser console but also on Glowroot central log

    2018-06-12 15:24:33.313 ERROR org.glowroot.ui.HttpServerHandler - error handling request /backend/trace/queries?agent-id=loggy%3A%3Aserver840a.mycorp.com-web&trace-id=0163f42985b81e4030654c56181ab072&check-live-traces=true: null
    org.glowroot.common.live.LiveJvmService$AgentUnsupportedOperationException: null
	    at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:441)
	    at org.glowroot.central.DownstreamServiceImpl.getQueries(DownstreamServiceImpl.java:366)
	    at org.glowroot.central.LiveTraceRepositoryImpl.getQueries(LiveTraceRepositoryImpl.java:47)
	    at org.glowroot.ui.TraceCommonService.getQueriesJson(TraceCommonService.java:126)
	    at org.glowroot.ui.TraceDetailHttpService.getDetailChunkSource(TraceDetailHttpService.java:90)
	    at org.glowroot.ui.TraceDetailHttpService.handleRequest(TraceDetailHttpService.java:69)
	    at org.glowroot.ui.CommonHandler.handleHttpService(CommonHandler.java:263)
	    at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:232)
	    at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
	    at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:127)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	    at java.lang.Thread.run(Thread.java:748)
    2018-06-12 15:33:20.866 ERROR org.glowroot.ui.HttpServerHandler - error handling request /backend/trace/queries?agent-id=loggy%3A%3Aserver840a.mycorp.com-web&trace-id=0163f42985b81e4030654c56181ab072&check-live-traces=true: null
    org.glowroot.common.live.LiveJvmService$AgentUnsupportedOperationException: null
	    at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:441)
	    at org.glowroot.central.DownstreamServiceImpl.getQueries(DownstreamServiceImpl.java:366)
	    at org.glowroot.central.LiveTraceRepositoryImpl.getQueries(LiveTraceRepositoryImpl.java:47)
	    at org.glowroot.ui.TraceCommonService.getQueriesJson(TraceCommonService.java:126)
	    at org.glowroot.ui.TraceDetailHttpService.getDetailChunkSource(TraceDetailHttpService.java:90)
	    at org.glowroot.ui.TraceDetailHttpService.handleRequest(TraceDetailHttpService.java:69)
	    at org.glowroot.ui.CommonHandler.handleHttpService(CommonHandler.java:263)
	    at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:232)
	    at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
	    at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:127)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	    at java.lang.Thread.run(Thread.java:748)

**Comment by hgomez** [comment]
I reverted my glowroot-central server from 0.10.10 to 0.10.9 and problem disapears. This is something specific to 0.10.10

**Comment by trask** [comment]
Hi @hgomez, thanks for reporting this! There were a couple of strange modal issues introduced in 0.10.10. Can you try the latest snapshot release [glowroot-agent-0.10.11-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.11-SNAPSHOT), and see if this issue is fixed now?

**Comment by hgomez** [comment]
glowroot-agent ? Shouldn't it be glowroot-central ?

**Comment by hgomez** [comment]
I tested with latest glowroot-central (glowroot-central-0.10.11-20180612.225324-3-dist.zip) and no more problem
