### ISSUE TITLE
NullPointerException for org.glowroot.agent.shaded.com.google.common.collect.ImmutableList

### ISSUE THREAD

**Issue by vinodhavala** [glowroot/glowroot#421]
2018-07-17 11:59:42,189 ERROR [default task-18]: [com.xxxxxxxx.error.xxxxxxxExceptionHandler] com.xxxxxxx.exception.xxxxxxxException: java.lang.NullPointerException
at org.glowroot.agent.shaded.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:267)
at org.glowroot.agent.model.ErrorMessage.buildThrowableInfo(ErrorMessage.java:74)
at org.glowroot.agent.model.ErrorMessage.fromThrowable(ErrorMessage.java:65)
at org.glowroot.agent.model.ErrorMessage.create(ErrorMessage.java:51)
at org.glowroot.agent.impl.Transaction.setError(Transaction.java:640)
at org.glowroot.agent.impl.ThreadContextImpl.setTransactionError(ThreadContextImpl.java:957)
at org.glowroot.agent.plugin.logger.JavaLoggingAspect$LogAdvice.onBeforeCommon(JavaLoggingAspect.java:97)
at org.glowroot.agent.plugin.logger.JavaLoggingAspect$LogAdvice.access$700(JavaLoggingAspect.java:44)
at org.glowroot.agent.plugin.logger.JavaLoggingAspect$JBossLogAdvice.onBefore(JavaLoggingAspect.java:121)
at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java)
at org.jboss.logmanager.Logger.logRaw(Logger.java:850)
at org.slf4j.impl.Slf4jLogger.log(Slf4jLogger.java:326)
at org.slf4j.impl.Slf4jLogger.log(Slf4jLogger.java:70)
at org.apache.commons.logging.impl.SLF4JLocationAwareLog.error(SLF4JLocationAwareLog.java:225)

**Comment by trask** [comment]
Hi @vinodhavala, thanks for reporting this! It should be fixed now in the latest snapshot release [glowroot-agent-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.13-SNAPSHOT).
