### ISSUE TITLE
Fails with VerifyError when yourkit also included in java options

### ISSUE THREAD

**Issue by MFAshby** [glowroot/glowroot#446]
Glowroot + wildfly + yjpagent causes a mysterious error. This is probably to be expected since both yjpagent and glowroot are attempting to instrument the bytecode, however the mysterious error took a little while to diagnose. 

Maybe it would be possible to detect that another instrumentation library is running in parallel and quit with a helpful error message?

minimal reproduction of the problem here:
https://github.com/MFAshby/glowroot-yjpagent-problem

```
10:19:04,101 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    org/jboss/as/server/BootstrapImpl$ShutdownHook.<init>()V @75: lload
  Reason:
    Local index 5 is invalid
  Bytecode:
    0x0000000: 014c 014d 10ff 3e03 3604 1229 1400 2ab8
    0x0000010: 0031 3705 2a11 00d6 1605 b800 35b7 0037
    0x0000020: b800 3d59 4cb6 0043 594d c600 1c2c b900
    0x0000030: 4901 0059 3e12 4a9f 000f 2c12 4ab9 004e
    0x0000040: 0200 04a7 0004 0336 0412 2916 05b8 0051
    0x0000050: a700 0315 0499 0008 2c2a b800 5a1d 10ff
    0x0000060: 9f00 0a2c 1db9 004e 0200 b11d 10ff 9f00
    0x0000070: 0a2c 1db9 004e 0200 bf                 
  Exception Handler Table:
    bci [73, 83] => handler: 107
  Stackmap Table:
    full_frame(@70,{Object[#2],Object[#63],Object[#69],Integer,Integer},{})
    same_locals_1_stack_item_frame(@71,Integer)
    same_frame(@83)
    same_frame(@93)
    same_frame(@106)
    same_locals_1_stack_item_frame(@107,Object[#92])
    same_locals_1_stack_item_frame(@120,Object[#92])

	at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:65)
	at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:275)
	at org.jboss.as.server.Main.main(Main.java:105)
	at org.jboss.modules.Module.run(Module.java:344)
	at org.jboss.modules.Main.main(Main.java:525)
```

**Comment by trask** [comment]
Hi @MFAshby, thanks so much for the repro! This should be fixed now in the latest snapshot release [glowroot-agent-0.11.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.11.0-SNAPSHOT).
