### ISSUE TITLE
Not able to connect glowroot agent to Jboss EAP 6.4.16 

### ISSUE THREAD

**Issue by risrikanth** [glowroot/glowroot#447]
Hi Trask,

We are trying to connect  glowroot agent  0.10.4 or 0.10.11 to Jboss collector and we are not bale to connect . We are getting below error. I have debug logs for both  10.4 and 10.11 agents. If you can send me drop box link i can send u the logs.
Caused by: org.glowroot.agent.shaded.io.netty.channel.ConnectTimeoutException: connection timed out: tapm-uat1-col.test.att.com/135.69.200.72:8181
	at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	... 3 common frames omitted
2018-08-17 15:22:46.955 DEBUG o.g.agent.central.CentralConnection - UNAVAILABLE: io exception
org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.glowroot.agent.shaded.io.grpc.Status.asRuntimeException(Status.java:526)
	at org.glowroot.agent.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
	at org.glowroot.agent.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.glowroot.agent.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at org.glowroot.agent.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.glowroot.agent.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
	at org.glowroot.agent.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.glowroot.agent.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by trask** [comment]
Hi @risrikanth, sure, upload logs to https://www.dropbox.com/request/TUegb8pXFR8aSx85OMRF and I'll review. Also, since it's a `connection timed out` error, can you verify that 135.69.200.72:8181 is accessible from the box where the agent is running and not blocked by firewall?

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue. Thanks.
