### ISSUE TITLE
Trying to setup on java 11 and tomcat9.0.12

### ISSUE THREAD

**Issue by carlosmuller** [glowroot/glowroot#466]
I'm trying to setup on tomcat and java 11. 
The glowroot is up but my application is not

[catalina.log.txt](https://github.com/glowroot/glowroot/files/2496900/catalina.log.txt)
[glowroot.2018-10-19.log](https://github.com/glowroot/glowroot/files/2496901/glowroot.2018-10-19.log)
Some errors i'm seeing:

```
    ERROR o.g.a.w.WeavingClassFileTransformer - error weaving java/lang/Thread: null
2018-10-19 15:19:42.755 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving sun/net/www/protocol/ftp/FtpURLConnection: null
2018-10-19 15:19:42.794 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving java/sql/SQLFeatureNotSupportedException: null
```

**Comment by carlosmuller** [comment]
Now my application is up but the errors keep happening

**Comment by trask** [comment]
Hi @carlosmuller, thanks for reporting this! Glowroot should support Java 11 now in the latest snapshot releases [glowroot-agent-0.12.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.0-SNAPSHOT).

**Comment by carlosmuller** [comment]
thanks it worked like a charm

**Comment by anurag4869** [comment]
Hello
I am facing the same error as:

021-02-10 13:10:57.840 ERROR o.g.central.CollectorServiceImpl - sowlx088.ba.de.eld.ericsson.se - 2021-02-10 13:10:54.420 ERROR org.glowroot.agent.weaving.WeavingClassFileTransformer - error weaving sun/security/rsa/RSACore: Unsupported class file major version 55
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)


The version of both glowroot-central and glowroot is 0.13.6

Can anyone help me resolve it ?
