### ISSUE TITLE
Release of a Java 11 comaptible version

### ISSUE THREAD

**Issue by prodanov** [glowroot/glowroot#468]
Hi, thanks a lot for building this great product. We are currently migrating to Java 11 and have some issues with the embedded collector. I saw that there are already Java 11 builds but so far no official version. 

Currently we have a lot of issues of the type:

ERROR o.g.a.w.WeavingClassFileTransformer - error weaving com/sun/org/apache/xalan/internal/utils/XMLSecurityManager: null
java.lang.UnsupportedOperationException: null
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:183)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:148)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformJava9(WeavingClassFileTransformer.java:77)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.<init>(TransformerFactoryImpl.java:273)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:169)
	at java.xml/javax.xml.transform.FactoryFinder.find(FactoryFinder.java:257)
	at java.xml/javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:126)
	at org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:51)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2023)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.addMessageBodyReader(ResteasyProviderFactory.java:761)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.processProviderContracts(ResteasyProviderFactory.java:1358)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1334)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1286)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:77)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:37)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:239)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:239)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:527)
	at com.bd4travel.rest.UndertowServerBuilder.buildAndStart(UndertowServerBuilder.java:144)
	at com.bd4travel.rest.AbstractServerMain.start(AbstractServerMain.java:52)
	at com.bd4travel.rest.AbstractServerMain.start(AbstractServerMain.java:35)
	at com.bd4travel.rest.AbstractServerMain.run(AbstractServerMain.java:31)
	at com.bd4travel.analytics.api.AnalyticsApiMain.main(AnalyticsApiMain.java:54)

happening for all kinds of classes on openJDK based JRE. Even for java/math/BigDecimal$StringBuilderHelper

Thanks in advance

**Comment by trask** [comment]
Hi @prodanov, thanks for posting! I'm planning to release 0.12.0 in a couple of days.

**Comment by prodanov** [comment]
Thanks!
