### ISSUE TITLE
ERROR org.glowroot.agent.weaving.Weaver - wrote bytecode 

### ISSUE THREAD

**Issue by jluna754** [glowroot/glowroot#471]
Hi,

Could you help me please with this error on Oracle OSM, WebLogic Server: 10.3.5.0 

ERROR org.glowroot.agent.weaving.Weaver - unable to weave oracle/jdbc/driver/OracleClosedStatement: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.remove(ArrayList.java:390)
	at org.glowroot.agent.shaded.org.objectweb.asm.commons.AdviceAdapter.popValue(AdviceAdapter.java:604)
	at org.glowroot.agent.shaded.org.objectweb.asm.commons.AdviceAdapter.visitInsn(AdviceAdapter.java:159)
	at org.glowroot.agent.shaded.org.objectweb.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
	at org.glowroot.agent.weaving.FrameDeduppingMethodVisitor.visitInsn(FrameDeduppingMethodVisitor.java:52)
	at org.glowroot.agent.shaded.org.objectweb.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
	at org.glowroot.agent.weaving.AdviceAdapter.visitInsn(AdviceAdapter.java:337)
	at org.glowroot.agent.weaving.WeavingMethodVisitor.visitInsn(WeavingMethodVisitor.java:223)
	at org.glowroot.agent.shaded.org.objectweb.asm.tree.InsnNode.accept(InsnNode.java:65)
	at org.glowroot.agent.shaded.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.glowroot.agent.shaded.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at org.glowroot.agent.shaded.org.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:150)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:286)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:304)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:218)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:211)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at oracle.jdbc.driver.OracleStatementWrapper.<clinit>(OracleStatementWrapper.java:63)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:3587)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:3461)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:526)
	at weblogic.jdbc.common.internal.ConnectionEnvFactory.makeConnection(ConnectionEnvFactory.java:352)
	at weblogic.jdbc.common.internal.ConnectionEnvFactory.createResource(ConnectionEnvFactory.java:238)
	at weblogic.common.resourcepool.ResourcePoolImpl.makeResources(ResourcePoolImpl.java:1249)
	at weblogic.common.resourcepool.ResourcePoolImpl.makeResources(ResourcePoolImpl.java:1166)
	at weblogic.common.resourcepool.ResourcePoolImpl.reserveResourceInternal(ResourcePoolImpl.java:450)
	at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:342)
	at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:329)
	at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:417)
	at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:324)
	at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:94)
	at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:63)
	at weblogic.jdbc.jts.Driver.newConnection(Driver.java:915)
	at weblogic.jdbc.wrapper.JTSLoggableResourceImpl.getNewJTSConnection(JTSLoggableResourceImpl.java:503)
	at weblogic.jdbc.wrapper.JTSLoggableResourceImpl.recoverXARecords(JTSLoggableResourceImpl.java:237)
	at weblogic.transaction.internal.ServerTransactionManagerImpl.registerLoggingResourceTransactions(ServerTransactionManagerImpl.java:747)
	at weblogic.jdbc.common.internal.RmiDataSource.recoverLoggingResourceTransactions(RmiDataSource.java:302)
	at weblogic.jdbc.common.internal.DataSourceManager.createAndStartDataSource(DataSourceManager.java:148)
	at weblogic.jdbc.common.internal.DataSourceManager.createAndStartDataSource(DataSourceManager.java:97)
	at weblogic.jdbc.module.JDBCModule.activate(JDBCModule.java:359)
	at weblogic.application.internal.flow.ModuleListenerInvoker.activate(ModuleListenerInvoker.java:227)
	at weblogic.application.internal.flow.DeploymentCallbackFlow$2.next(DeploymentCallbackFlow.java:541)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52)
	at weblogic.application.internal.flow.DeploymentCallbackFlow.activate(DeploymentCallbackFlow.java:175)
	at weblogic.application.internal.flow.DeploymentCallbackFlow.activate(DeploymentCallbackFlow.java:167)
	at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:636)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52)
	at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:205)
	at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:43)
	at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:161)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:79)
	at weblogic.deploy.internal.targetserver.BasicDeployment.activate(BasicDeployment.java:184)
	at weblogic.deploy.internal.targetserver.BasicDeployment.activateFromServerLifecycle(BasicDeployment.java:361)
	at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:42)
	at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:191)
	at weblogic.management.deploy.internal.AppTransition$1.transitionApp(AppTransition.java:21)
	at weblogic.management.deploy.internal.ConfiguredDeployments.transitionApps(ConfiguredDeployments.java:240)
	at weblogic.management.deploy.internal.ConfiguredDeployments.prepare(ConfiguredDeployments.java:165)
	at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:122)
	at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:180)
	at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:96)
	at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:209)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:178)

ERROR org.glowroot.agent.weaving.Weaver - wrote bytecode to: /var/tmp/glowroot-weaving-error-OracleClosedStatement.class

**Comment by trask** [comment]
Hi @jluna754, thanks for reporting this! Can you attach the file that Glowroot wrote out to `/var/tmp/glowroot-weaving-error-OracleClosedStatement.class`? Also, what version of Glowroot agent are you using?

**Comment by jluna754** [comment]
Hi @trask 

Thanks for your attention, look:

 Glowroot version: 0.12.1, built 2018-11-01 00:27:45 +0000

I use coherence server, can be related with that?

Many thanks,

**Comment by trask** [comment]
Can you attach (or email to me) the file that Glowroot wrote out to `/var/tmp/glowroot-weaving-error-OracleClosedStatement.class`?

**Comment by jluna754** [comment]
look this another error:
####<Nov 1, 2018 2:53:01 PM COT> <Warning> <oms> <netvm-rosmapp4> <newOSM_ManagedServer_2> <Thread-76> <oms-internal> <> <0000MRGnn778pm8Lnik3yZ1RqpTx000002> <1541101981276> <BEA-000000> <cluster.ClusteredHandlerFactory: Failed to collect all cluster member info after 10 attempts>

**Comment by jluna754** [comment]
yeah, check your mail please.

**Comment by trask** [comment]
Thanks, can you also attach (or email me) your glowroot log?

**Comment by jluna754** [comment]
Look this error:

servlet dispatch: /MainMenu.jsp
 EJB Exception:; nested exception is: 
	java.lang.RuntimeException: Cannot process request. ClusteredHandlerFactory is not running - current state is [STARTING]. The likely cause of this error is that the application is in the process of being started or stopped.

I think this error is related with coherence, maybe glowroot not support coherence?

Many thanks!

**Comment by trask** [comment]
Hi @jluna754, can you send me `/var/tmp/glowroot-weaving-error-MDListener.class` from your most recent try above?

**Comment by trask** [comment]
Hi @jluna754, are you still facing this issue?  Can you send me `/var/tmp/glowroot-weaving-error-MDListener.class` from your most recent try above?  Thanks.

**Comment by jluna754** [comment]
Hi @trask, sorry but I cannot access to this file.

**Comment by jluna754** [comment]
I close this case because I migrate platform.
