### ISSUE TITLE
Updating glowroot agent causes IOException

### ISSUE THREAD

**Issue by ross-everitt** [glowroot/glowroot#478]
I'm upgrading from agent glowroot-0.10.12 to glowroot-0.12.2.  I see the following error:

Glowroot not started: Permission denied
java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at org.glowroot.agent.AgentDirsLocking.touch(AgentDirsLocking.java:70)
        at org.glowroot.agent.AgentDirsLocking.tryLockAgentDirs(AgentDirsLocking.java:36)
        at org.glowroot.agent.Directories.<init>(Directories.java:120)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

My glowroot properties file looks as follows:

data.dir=/trace/glowroot-data
conf.dir=/trace/glowroot-conf
log.dir=/trace/glowroot-logs
tmp.dir=/trace/glowroot-tmp
multi.dir=true

If I change the agent id on the running application from -Dglowroot.agent.id=appname to -Dglowroot.agent.id=appname1 then glowroot starts successfully, so this seems to be an issue using the previously created files/folders.  There are no open locks on the unix filesystem for any of the folders specified above.

I have also tried migrating to the interim version 0.11.1 with the same problems encountered.

**Comment by trask** [comment]
Hi @ross-everitt, thanks for posting! The file it's trying to create is `/trace/glowroot-tmp/{agent.id}/.lock`. Can you check the owner and permissions on both '/trace/glowroot-tmp/appname' and '/trace/glowroot-tmp/appname1` to see if there is a difference that would explain this?

**Comment by ross-everitt** [comment]
Hi thanks, at a glance this seems to have resolved the issue.  The
directory was accessible by the user, but owned by group (the mask
is drwxr-xr-x if you're interested so interestingly it seems that write
permissions were missing which is surprising as the app has been running
successfully before upgrade).  In my case I have simply adjusted
ownernship, but I guess a permissions adjustment would have worked equally
well.

Ross.

**Comment by trask** [comment]
👍
