### ISSUE TITLE
Service calls and queries not being captured - Weblogic 10.3.2/java 6

### ISSUE THREAD

**Issue by Sohailjp** [glowroot/glowroot#480]
Dear Trask,

Data base queries and service calls for one of my application is not being captured. Below are the version details. 

Central collector version 0.11.1, built 2018-10-01 23:15:02 +0000
Agent version 0.11.1, built 2018-10-01 23:15:02 +0000

Weblogic: 10.3.2
java: 1.6.0_17

weblogic.work.ExecuteThread.run(ExecuteThread.java:173)
weblogic.work.ExecuteThread.execute(ExecuteThread.java:201)
weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1432)
weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2108)
weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2202)
weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121)
weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3594)
weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:175)
weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:292)
weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
weblogic.wsee.jaxws.JAXWSServlet.service(JAXWSServlet.java:87)
javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
weblogic.wsee.jaxws.JAXWSServlet.doPost(JAXWSServlet.java:310)
weblogic.wsee.jaxws.HttpServletAdapter.post(HttpServletAdapter.java:232)
weblogic.wsee.jaxws.HttpServletAdapter$AuthorizedInvoke.run(HttpServletAdapter.java:319)
com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:140)
com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:250)
com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:454)
com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:275)
com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:445)
com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:548)
com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:563)
com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:604)
com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93)
com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:264)
com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:152)
weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:83)
weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:101)

**Comment by trask** [comment]
Hi @Sohailjp, thanks for posting! Can you try with the latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT) and see if you get the same issue?

Also, I'm unsure what the stack trace above is? Did it get cut off when posting? Can you post the full glowroot agent log? Thanks.

**Comment by Sohailjp** [comment]
Hello @trask ,


I checked the logs, before upgrading the agent it is giving the below warning.

2018-11-27 23:58:45.106 WARN  o.g.agent.central.CentralConnection - not sending data to the central collector because pending request limit (100) exceeded (this warning will be logged at most once a minute, 12 warnings were suppressed since it was last logged)
2018-11-27 23:59:45.223 WARN  o.g.agent.central.CentralConnection - not sending data to the central collector because pending request limit (100) exceeded (this warning will be logged at most once a minute, 12 warnings were suppressed since it was last logged)



After upgrading the agent to 0.12.3, the below error messages are getting logged. 

2018-11-28 10:15:33.110 ERROR o.g.agent.central.CentralConnection - Plugin property captureRequestHeaders has incorrect type: SVAL
java.lang.IllegalStateException: Plugin property captureRequestHeaders has incorrect type: SVAL
        at org.glowroot.agent.config.PluginConfig.create(PluginConfig.java:178)
        at org.glowroot.agent.config.AllConfig.create(AllConfig.java:81)
        at org.glowroot.agent.init.ConfigUpdateService.update(ConfigUpdateService.java:44)
        at org.glowroot.agent.central.CentralCollector$1.doWithResponse(CentralCollector.java:171)
        at org.glowroot.agent.central.CentralCollector$1.doWithResponse(CentralCollector.java:151)
        at org.glowroot.agent.central.CentralConnection$RetryingStreamObserver.onNext(CentralConnection.java:378)
        at org.glowroot.agent.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407)
        at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
        at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
        at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
        at org.glowroot.agent.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.glowroot.agent.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)

**Comment by trask** [comment]
Hi @Sohailjp, I believe `Plugin property captureRequestHeaders has incorrect type: SVAL` means your central collector is still on an older version.

**Comment by Sohailjp** [comment]
Hello @trask,

I have upgraded the central controller to 0.12.2 as I couldn't find the 0.12.3 version. 

Now I am getting the below message in the agent logs


Agent1
==================================================




2018-11-29 12:14:46.737 INFO  org.glowroot - connected to the central collector http://XXXXXXXXXXXXXXXXXXXX, version 0.12.2, built 2018-11-09 00:50:19 +0000
2018-11-29 12:14:46.741 WARN  org.glowroot - the central collector version is older than the agent version which could cause unpredictable issues
2018-11-29 12:15:45.138 ERROR o.g.a.util.LazyPlatformMBeanServer - platform mbean server was never created by container
2018-11-29 12:22:48.069 INFO  org.glowroot - Glowroot version: 0.12.3-SNAPSHOT, commit 23faf0833e, built 2018-11-28 04:29:20 +0000
2018-11-29 12:22:48.105 INFO  org.glowroot - Java version: 1.6.0_17
2018-11-29 12:22:50.782 WARN  org.glowroot - one or more important classes were loaded before Glowroot instrumentation could be applied to them: java.net.HttpURLConnection
2018-11-29 12:22:50.868 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Kafka Plugin, Logger Plugin, MongoDB Plugin, Netty Plugin, Play Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-11-29 12:22:51.195 INFO  org.glowroot - agent id: AGENT1
2018-11-29 12:22:52.213 WARN  o.g.a.s.c.google.protobuf.UnsafeUtil - platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: sun.misc.Unsafe.copyMemory(java.lang.Object, long, java.lang.Object, long, long)
2018-11-29 12:22:52.486 INFO  org.glowroot - connected to the central collector http://wapinuatjb201.warbabank.com:37075, version 0.12.2, built 2018-11-09 00:50:19 +0000
2018-11-29 12:22:52.489 WARN  org.glowroot - the central collector version is older than the agent version which could cause unpredictable issues
2018-11-29 12:23:51.070 ERROR o.g.a.util.LazyPlatformMBeanServer - platform mbean server was never created by container




I have enabled Weblogic Domain -> Advance  -> Platform MBean Server Enabled and restarted the domain, but I am still getting the above message. 

==================================================

Agent2
=========================================
2018-11-29 12:22:35.084 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Kafka Plugin, Logger Plugin, MongoDB Plugin, Netty Plugin, Play Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-11-29 12:22:35.392 INFO  org.glowroot - agent id: AGENT2
2018-11-29 12:22:36.462 WARN  o.g.a.s.c.google.protobuf.UnsafeUtil - platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: sun.misc.Unsafe.copyMemory(java.lang.Object, long, java.lang.Object, long, long)
2018-11-29 12:22:36.736 INFO  org.glowroot - connected to the central collector http://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, version 0.12.2, built 2018-11-09 00:50:19 +0000
2018-11-29 12:22:36.740 WARN  org.glowroot - the central collector version is older than the agent version which could cause unpredictable issues
2018-11-29 12:23:35.277 ERROR o.g.a.util.LazyPlatformMBeanServer - platform mbean server was never created by container
2018-11-29 12:24:21.632 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method weblogic.jdbc.wrapper.JTSConnection.setAutoCommit(boolean) which is being used by a subclass weblogic.jdbc.wrapper.JTSConnection_oracle_jdbc_driver_T4CConnection to implement one or more instrumented interfaces
2018-11-29 12:24:21.640 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method weblogic.jdbc.wrapper.JTSConnection.commit() which is being used by a subclass weblogic.jdbc.wrapper.JTSConnection_oracle_jdbc_driver_T4CConnection to implement one or more instrumented interfaces
2018-11-29 12:24:21.641 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method weblogic.jdbc.wrapper.JTSConnection.rollback() which is being used by a subclass weblogic.jdbc.wrapper.JTSConnection_oracle_jdbc_driver_T4CConnection to implement one or more instrumented interfaces
2018-11-29 12:24:21.641 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method weblogic.jdbc.wrapper.JTSConnection.close() which is being used by a subclass weblogic.jdbc.wrapper.JTSConnection_oracle_jdbc_driver_T4CConnection to implement one or more instrumented interfaces

**Comment by trask** [comment]
Hi @Sohailjp, can you download the (new) latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT) and run with the additional JVM arg `-Dglowroot.debug.mainClass=true`, and then post the full agent log? Thanks.

**Comment by trask** [comment]
Hi @Sohailjp, can you download the (new again) latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT), and then post the full agent log? It will now log a bit more info that I'm hoping will help me understand/repro this issue. Thanks.

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue. Thanks.
