### ISSUE TITLE
Weblogic 12c issue with Glowroot 

### ISSUE THREAD

**Issue by dhanunjay8** [glowroot/glowroot#482]
<Nov 22, 2018 6:57:27 AM EST> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: A MultiException has 2 exceptions.  They are:
1. java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    weblogic/net/http/HttpURLConnection.getOutputStream()Ljava/io/OutputStream; @70: aload_0
  Reason:
    Type 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' (current frame, locals[5]) is not assignable to 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' (stack map, locals[5])
  Current Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' }
    stack: { }
  Stackmap Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' }
    stack: { }
  Bytecode:
    0x0000000: 033c 014d 014e 0236 0401 3a05 2cc7 0007
    0x0000010: b800 fd4d 2cb6 0107 594e c600 1f2d b901
    0x0000020: 0b01 0059 3604 1301 0c9f 0010 2d13 010c
    0x0000030: b901 1002 0004 a700 0403 3c1b 9900 0a2d
    0x0000040: 2ab8 0153 3a05 2ab4 0158 9a00 0ebb 015a
    0x0000050: 5913 015c b701 5ebf 2ab4 0161 1301 63b6
    0x0000060: 0167 9900 0a2a 1301 69b6 016c 1301 6e2a
    0x0000070: b401 61b6 0167 9a00 2a13 0170 2ab4 0161
    0x0000080: b601 679a 001d 1301 722a b401 61b6 0167
    0x0000090: 9a00 1013 0174 2ab4 0161 b601 6799 0039
    0x00000a0: 2ab6 0176 2ab4 011e b601 77b6 0167 9900
    0x00000b0: 28bb 015a 59bb 00d2 59b7 00d3 1301 79b6
    0x00000c0: 00d9 2ab4 0161 b600 d913 017b b600 d9b6
    0x00000d0: 00df b701 5ebf 2ab4 0061 c600 0ebb 015a
    0x00000e0: 5913 017d b701 5ebf b201 7f9a 00d7 2ab4
    0x00000f0: 006b 9900 792a b400 8d99 0072 2ab6 0181
    0x0000100: 2ab6 0183 2a2a b400 799e 0018 bb01 8559
    0x0000110: 2ab4 00c1 b600 c52a b400 79b7 0188 a700
    0x0000120: 11bb 0185 592a b400 c1b6 00c5 b701 8ab5
    0x0000130: 0063 b200 d099 002f bb00 d259 b700 d313
    0x0000140: 018c b600 d92a b400 799e 000a 2ab4 0079
    0x0000150: a700 0bb2 0191 1006 6405 64b6 0194 b600
    0x0000160: dfb8 00e2 2ab4 0063 a700 a22a b701 9899
    0x0000170: 0053 2ab6 0181 2ab6 0183 2a13 019a b601
    0x0000180: 9e3a 062a bb01 a059 2ab4 00c1 b600 c519
    0x0000190: 06b8 01a6 b701 a7b5 0063 b200 d099 001e
    0x00001a0: bb00 d259 b700 d313 01a9 b600 d919 06b8
    0x00001b0: 01a6 b601 94b6 00df b800 e22a b400 63a7
    0x00001c0: 004b 2ab4 0065 c700 112a bb00 ee59 b701
    0x00001d0: aab5 0065 a700 112a b401 1b9a 000a 2ab4
    0x00001e0: 0065 b601 adb2 00d0 9900 0913 01af b800
    0x00001f0: e22a b400 65a7 0015 3a06 2ab6 01b2 1906
    0x0000200: bf3a 062a b601 b219 06bf 1b99 000a 592a
    0x0000210: 1905 b801 ba15 0402 9f00 0b2d 1504 b901
    0x0000220: 1002 00b0 1b99 0009 5919 05b8 01bb 1504
    0x0000230: 029f 000b 2d15 04b9 0110 0200 bf       
  Exception Handler Table:
    bci [70, 360] => handler: 504
    bci [363, 447] => handler: 504
    bci [450, 501] => handler: 504
    bci [70, 360] => handler: 513
    bci [363, 447] => handler: 513
    bci [450, 501] => handler: 513
    bci [70, 522] => handler: 548
  Stackmap Table:
    full_frame(@20,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{})
    same_frame(@57)
    same_locals_1_stack_item_frame(@58,Integer)
    same_frame(@70)
    same_frame(@88)
    same_frame(@108)
    same_frame(@160)
    same_frame(@214)
    same_frame(@232)
    same_locals_1_stack_item_frame(@289,Object[#2])
    full_frame(@303,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#2],Object[#389]})
    same_locals_1_stack_item_frame(@339,Object[#210])
    full_frame(@347,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#210],Integer})
    same_frame(@356)
    same_frame(@363)
    append_frame(@443,Object[#312])
    chop_frame(@450,1)
    same_frame(@471)
    same_frame(@485)
    same_frame(@497)
    same_locals_1_stack_item_frame(@504,Object[#341])
    same_locals_1_stack_item_frame(@513,Object[#185])
    same_locals_1_stack_item_frame(@522,Object[#439])
    same_locals_1_stack_item_frame(@533,Object[#439])
    same_locals_1_stack_item_frame(@547,Object[#439])
    same_locals_1_stack_item_frame(@548,Object[#323])
    same_locals_1_stack_item_frame(@558,Object[#323])
    same_locals_1_stack_item_frame(@572,Object[#323])

2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService

A MultiException has 2 exceptions.  They are:
1. java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    weblogic/net/http/HttpURLConnection.getOutputStream()Ljava/io/OutputStream; @70: aload_0
  Reason:
    Type 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' (current frame, locals[5]) is not assignable to 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' (stack map, locals[5])
  Current Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' }
    stack: { }
  Stackmap Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' }
    stack: { }
  Bytecode:
    0x0000000: 033c 014d 014e 0236 0401 3a05 2cc7 0007
    0x0000010: b800 fd4d 2cb6 0107 594e c600 1f2d b901
    0x0000020: 0b01 0059 3604 1301 0c9f 0010 2d13 010c
    0x0000030: b901 1002 0004 a700 0403 3c1b 9900 0a2d
    0x0000040: 2ab8 0153 3a05 2ab4 0158 9a00 0ebb 015a
    0x0000050: 5913 015c b701 5ebf 2ab4 0161 1301 63b6
    0x0000060: 0167 9900 0a2a 1301 69b6 016c 1301 6e2a
    0x0000070: b401 61b6 0167 9a00 2a13 0170 2ab4 0161
    0x0000080: b601 679a 001d 1301 722a b401 61b6 0167
    0x0000090: 9a00 1013 0174 2ab4 0161 b601 6799 0039
    0x00000a0: 2ab6 0176 2ab4 011e b601 77b6 0167 9900
    0x00000b0: 28bb 015a 59bb 00d2 59b7 00d3 1301 79b6
    0x00000c0: 00d9 2ab4 0161 b600 d913 017b b600 d9b6
    0x00000d0: 00df b701 5ebf 2ab4 0061 c600 0ebb 015a
    0x00000e0: 5913 017d b701 5ebf b201 7f9a 00d7 2ab4
    0x00000f0: 006b 9900 792a b400 8d99 0072 2ab6 0181
    0x0000100: 2ab6 0183 2a2a b400 799e 0018 bb01 8559
    0x0000110: 2ab4 00c1 b600 c52a b400 79b7 0188 a700
    0x0000120: 11bb 0185 592a b400 c1b6 00c5 b701 8ab5
    0x0000130: 0063 b200 d099 002f bb00 d259 b700 d313
    0x0000140: 018c b600 d92a b400 799e 000a 2ab4 0079
    0x0000150: a700 0bb2 0191 1006 6405 64b6 0194 b600
    0x0000160: dfb8 00e2 2ab4 0063 a700 a22a b701 9899
    0x0000170: 0053 2ab6 0181 2ab6 0183 2a13 019a b601
    0x0000180: 9e3a 062a bb01 a059 2ab4 00c1 b600 c519
    0x0000190: 06b8 01a6 b701 a7b5 0063 b200 d099 001e
    0x00001a0: bb00 d259 b700 d313 01a9 b600 d919 06b8
    0x00001b0: 01a6 b601 94b6 00df b800 e22a b400 63a7
    0x00001c0: 004b 2ab4 0065 c700 112a bb00 ee59 b701
    0x00001d0: aab5 0065 a700 112a b401 1b9a 000a 2ab4
    0x00001e0: 0065 b601 adb2 00d0 9900 0913 01af b800
    0x00001f0: e22a b400 65a7 0015 3a06 2ab6 01b2 1906
    0x0000200: bf3a 062a b601 b219 06bf 1b99 000a 592a
    0x0000210: 1905 b801 ba15 0402 9f00 0b2d 1504 b901
    0x0000220: 1002 00b0 1b99 0009 5919 05b8 01bb 1504
    0x0000230: 029f 000b 2d15 04b9 0110 0200 bf       
  Exception Handler Table:
    bci [70, 360] => handler: 504
    bci [363, 447] => handler: 504
    bci [450, 501] => handler: 504
    bci [70, 360] => handler: 513
    bci [363, 447] => handler: 513
    bci [450, 501] => handler: 513
    bci [70, 522] => handler: 548
  Stackmap Table:
    full_frame(@20,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{})
    same_frame(@57)
    same_locals_1_stack_item_frame(@58,Integer)
    same_frame(@70)
    same_frame(@88)
    same_frame(@108)
    same_frame(@160)
    same_frame(@214)
    same_frame(@232)
    same_locals_1_stack_item_frame(@289,Object[#2])
    full_frame(@303,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#2],Object[#389]})
    same_locals_1_stack_item_frame(@339,Object[#210])
    full_frame(@347,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#210],Integer})
    same_frame(@356)
    same_frame(@363)
    append_frame(@443,Object[#312])
    chop_frame(@450,1)
    same_frame(@471)
    same_frame(@485)
    same_frame(@497)
    same_locals_1_stack_item_frame(@504,Object[#341])
    same_locals_1_stack_item_frame(@513,Object[#185])
    same_locals_1_stack_item_frame(@522,Object[#439])
    same_locals_1_stack_item_frame(@533,Object[#439])
    same_locals_1_stack_item_frame(@547,Object[#439])
    same_locals_1_stack_item_frame(@548,Object[#323])
    same_locals_1_stack_item_frame(@558,Object[#323])
    same_locals_1_stack_item_frame(@572,Object[#323])

2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService

	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused By: java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    weblogic/net/http/HttpURLConnection.getOutputStream()Ljava/io/OutputStream; @70: aload_0
  Reason:
    Type 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' (current frame, locals[5]) is not assignable to 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' (stack map, locals[5])
  Current Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer_' }
    stack: { }
  Stackmap Frame:
    bci: @70
    flags: { }
    locals: { 'weblogic/net/http/HttpURLConnection', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/httpclient/HttpURLConnectionAspect$TraceEntryOrTimer' }
    stack: { }
  Bytecode:
    0x0000000: 033c 014d 014e 0236 0401 3a05 2cc7 0007
    0x0000010: b800 fd4d 2cb6 0107 594e c600 1f2d b901
    0x0000020: 0b01 0059 3604 1301 0c9f 0010 2d13 010c
    0x0000030: b901 1002 0004 a700 0403 3c1b 9900 0a2d
    0x0000040: 2ab8 0153 3a05 2ab4 0158 9a00 0ebb 015a
    0x0000050: 5913 015c b701 5ebf 2ab4 0161 1301 63b6
    0x0000060: 0167 9900 0a2a 1301 69b6 016c 1301 6e2a
    0x0000070: b401 61b6 0167 9a00 2a13 0170 2ab4 0161
    0x0000080: b601 679a 001d 1301 722a b401 61b6 0167
    0x0000090: 9a00 1013 0174 2ab4 0161 b601 6799 0039
    0x00000a0: 2ab6 0176 2ab4 011e b601 77b6 0167 9900
    0x00000b0: 28bb 015a 59bb 00d2 59b7 00d3 1301 79b6
    0x00000c0: 00d9 2ab4 0161 b600 d913 017b b600 d9b6
    0x00000d0: 00df b701 5ebf 2ab4 0061 c600 0ebb 015a
    0x00000e0: 5913 017d b701 5ebf b201 7f9a 00d7 2ab4
    0x00000f0: 006b 9900 792a b400 8d99 0072 2ab6 0181
    0x0000100: 2ab6 0183 2a2a b400 799e 0018 bb01 8559
    0x0000110: 2ab4 00c1 b600 c52a b400 79b7 0188 a700
    0x0000120: 11bb 0185 592a b400 c1b6 00c5 b701 8ab5
    0x0000130: 0063 b200 d099 002f bb00 d259 b700 d313
    0x0000140: 018c b600 d92a b400 799e 000a 2ab4 0079
    0x0000150: a700 0bb2 0191 1006 6405 64b6 0194 b600
    0x0000160: dfb8 00e2 2ab4 0063 a700 a22a b701 9899
    0x0000170: 0053 2ab6 0181 2ab6 0183 2a13 019a b601
    0x0000180: 9e3a 062a bb01 a059 2ab4 00c1 b600 c519
    0x0000190: 06b8 01a6 b701 a7b5 0063 b200 d099 001e
    0x00001a0: bb00 d259 b700 d313 01a9 b600 d919 06b8
    0x00001b0: 01a6 b601 94b6 00df b800 e22a b400 63a7
    0x00001c0: 004b 2ab4 0065 c700 112a bb00 ee59 b701
    0x00001d0: aab5 0065 a700 112a b401 1b9a 000a 2ab4
    0x00001e0: 0065 b601 adb2 00d0 9900 0913 01af b800
    0x00001f0: e22a b400 65a7 0015 3a06 2ab6 01b2 1906
    0x0000200: bf3a 062a b601 b219 06bf 1b99 000a 592a
    0x0000210: 1905 b801 ba15 0402 9f00 0b2d 1504 b901
    0x0000220: 1002 00b0 1b99 0009 5919 05b8 01bb 1504
    0x0000230: 029f 000b 2d15 04b9 0110 0200 bf       
  Exception Handler Table:
    bci [70, 360] => handler: 504
    bci [363, 447] => handler: 504
    bci [450, 501] => handler: 504
    bci [70, 360] => handler: 513
    bci [363, 447] => handler: 513
    bci [450, 501] => handler: 513
    bci [70, 522] => handler: 548
  Stackmap Table:
    full_frame(@20,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{})
    same_frame(@57)
    same_locals_1_stack_item_frame(@58,Integer)
    same_frame(@70)
    same_frame(@88)
    same_frame(@108)
    same_frame(@160)
    same_frame(@214)
    same_frame(@232)
    same_locals_1_stack_item_frame(@289,Object[#2])
    full_frame(@303,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#2],Object[#389]})
    same_locals_1_stack_item_frame(@339,Object[#210])
    full_frame(@347,{Object[#2],Integer,Object[#255],Object[#257],Integer,Object[#259]},{Object[#210],Integer})
    same_frame(@356)
    same_frame(@363)
    append_frame(@443,Object[#312])
    chop_frame(@450,1)
    same_frame(@471)
    same_frame(@485)
    same_frame(@497)
    same_locals_1_stack_item_frame(@504,Object[#341])
    same_locals_1_stack_item_frame(@513,Object[#185])
    same_locals_1_stack_item_frame(@522,Object[#439])
    same_locals_1_stack_item_frame(@533,Object[#439])
    same_locals_1_stack_item_frame(@547,Object[#439])
    same_locals_1_stack_item_frame(@548,Object[#323])
    same_locals_1_stack_item_frame(@558,Object[#323])
    same_locals_1_stack_item_frame(@572,Object[#323])

	at weblogic.net.http.Handler.openConnection(Handler.java:28)
	at weblogic.net.http.BaseHandler.openConnection(BaseHandler.java:37)
	at java.net.URL.openConnection(URL.java:979)
	at weblogic.protocol.URLManager.createAdminHttpConnection(URLManager.java:441)
	at weblogic.management.provider.internal.BootStrapHelper.getBootStrapStruct(BootStrapHelper.java:86)
	at weblogic.management.provider.internal.RuntimeAccessImpl.initialize(RuntimeAccessImpl.java:483)
	at weblogic.management.provider.internal.RuntimeAccessService.start(RuntimeAccessService.java:72)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
> 
<Nov 22, 2018 6:57:27 AM EST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FAILED.> 
<Nov 22, 2018 6:57:27 AM EST> <Error> <WebLogicServer> <BEA-000383> <A critical service failed. The server will shut itself down.> 
<Nov 22, 2018 6:57:27 AM EST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.> 
<Nov 22, 2018 6:57:27 AM EST> <Info> <WebLogicServer> <BEA-000238> <Shutdown has completed.> 
<Nov 22, 2018 6:57:28 AM EST> <INFO> <NodeManager> <The server 'MS02' with process id 4340 is no longer alive; waiting for the process to die.>
<Nov 22, 2018 6:57:28 AM EST> <FINEST> <NodeManager> <Process died.>
<Nov 22, 2018 6:57:28 AM EST> <INFO> <NodeManager> <Server failed during startup. It may be retried according to the auto restart configuration.>
<Nov 22, 2018 6:57:28 AM EST> <FINEST> <NodeManager> <get latest startup configuration before deciding/trying to restart the server>
<Nov 22, 2018 6:57:28 AM EST> <INFO> <NodeManager> <Server failed but will not be restarted because the maximum number of restart attempts has been exceeded>
<Nov 22, 2018 6:57:28 AM EST> <FINEST> <NodeManager> <runMonitor returned, setting finished=true and notifying waiters>

**Comment by trask** [comment]
Hi @dhanunjay8, thanks for reporting this! It should be fixed now in the latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT).
