### ISSUE TITLE
ERROR ORACLE SOA 

### ISSUE THREAD

**Issue by jluna754** [glowroot/glowroot#485]
Hi @trask I try to deploy the APM on Oracle SOA/WEBLOGIC 12 over JDK 1.8 (IBM) and I got this error:

2018-11-27 15:24:39.350 INFO  org.glowroot - Glowroot version: 0.12.2, built 2018-11-09 00:50:19 +0000
2018-11-27 15:24:39.365 INFO  org.glowroot - Java version: 1.8.0_144
2018-11-27 15:24:39.385 ERROR org.glowroot - Glowroot not started: org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInitFactory
java.lang.ClassNotFoundException: org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInitFactory
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.glowroot.agent.MainEntryPoint.createGlowrootAgentInit(MainEntryPoint.java:290)
        at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:255)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:408)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:423)

Can you help me please.

Thanks a lot.

**Comment by trask** [comment]
Hi @jluna754, thanks for posting! Can you try with the latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT) and see if you get the same issue?

**Comment by jluna754** [comment]
Hi @trask 

I deploy this version but I have this error:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/logs/glowroot/glowroot.jar!/org/glowroot/agent/shaded/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/logs/glowroot/glowroot.jar!/org/glowroot/agent/shaded/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

16:52:35,900 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [glowroot.logback-test.xml]
16:52:35,905 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [glowroot.logback.groovy]
16:52:35,905 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Found resource [glowroot.logback.xml] at [jar:file:/logs/glowroot/glowroot.jar!/glowroot.logback.xml]
16:52:35,910 |-WARN in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Resource [glowroot.logback.xml] occurs multiple times on the classpath.
16:52:35,910 |-WARN in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Resource [glowroot.logback.xml] occurs at [jar:file:/logs/glowroot/glowroot.jar!/glowroot.logback.xml]
16:52:35,910 |-WARN in org.glowroot.agent.shaded.ch.qos.logback.classic.LoggerContext[default] - Resource [glowroot.logback.xml] occurs at [jar:file:/logs/glowroot/glowroot.jar!/glowroot.logback.xml]
16:52:35,911 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.spi.ConfigurationWatchList@e90613cb - URL [jar:file:/logs/glowroot/glowroot.jar!/glowroot.logback.xml] is not of type file
16:52:35,994 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:52:35,997 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.glowroot.agent.shaded.ch.qos.logback.core.ConsoleAppender]
16:52:36,000 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
16:52:36,005 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [org.glowroot.agent.shaded.ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:52:36,019 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.glowroot.agent.shaded.ch.qos.logback.core.rolling.RollingFileAppender]
16:52:36,020 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
16:52:36,027 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@-1496304494 - No compression will be used
16:52:36,027 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@-1496304494 - Will use the pattern /logs/glowroot/logs/glowroot.%d{yyyy-MM-dd}.log for the active file
16:52:36,031 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/logs/glowroot/logs/glowroot.%d{yyyy-MM-dd}.log'.
16:52:36,031 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
16:52:36,039 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Nov 29 16:52:36 COT 2018
16:52:36,041 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [org.glowroot.agent.shaded.ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:52:36,042 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /logs/glowroot/logs/glowroot.2018-11-29.log
16:52:36,042 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
16:52:36,044 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.glowroot.agent.shaded] to WARN
16:52:36,044 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.glowroot.agent.embedded.shaded] to WARN
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.glowroot.agent.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler] to OFF
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [audit] to OFF
16:52:36,045 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:52:36,046 |-INFO in org.glowroot.agent.shaded.ch.qos.logback.classic.joran.JoranConfigurator@10d0d2e - Registering current configuration as safe fallback point

SLF4J: Actual binding is of type [org.glowroot.agent.shaded.ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2018-11-29 16:52:36.067 INFO  org.glowroot - Glowroot version: 0.12.3-SNAPSHOT, commit 3dde2e6e4e, built 2018-11-29 18:50:49 +0000
2018-11-29 16:52:36.074 INFO  org.glowroot - Java version: 1.8.0_144
2018-11-29 16:52:36.081 ERROR org.glowroot - Glowroot not started: org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInitFactory
java.lang.ClassNotFoundException: org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInitFactory
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.glowroot.agent.MainEntryPoint.createGlowrootAgentInit(MainEntryPoint.java:290)
        at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:255)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:408)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:423)

It's important say something: I do that on weblogic 12c but this weblogic is part of OSB.

I hope your help please.

**Comment by trask** [comment]
Hi @jluna754, can you try with this build https://glowroot.org/issue-485/glowroot-agent-0.12.3-SNAPSHOT-dist.zip and then post the full agent log? I added some additional logging to hopefully get a better idea what's going wrong. Thanks.

**Comment by trask** [comment]
Hi @jluna754, it looks like you have `glowroot.jar` on your classpath.  Can you remove it from your classpath and try again?  Thanks.

**Comment by jluna754** [comment]
Hi @trask, I put the glowroot flag over weblogic web->start server->arguments, I not do that over classpath.

Can you explain me please where I can put the glowroot flag.
Thanks.

**Comment by trask** [comment]
Hi @jluna754, sorry for the late reply, I'm not sure what could be wrong here, I'm wondering if this issue only happens on IBM JVM on AIX, do you have another platform you can try it out on? That would help me troubleshoot. Thanks.

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue. Thanks.
