### ISSUE TITLE
Unexpected message: MESSAGE_NOT_SET

### ISSUE THREAD

**Issue by pilgrim2go** [glowroot/glowroot#487]
Hi, 

First try Glowroot (central) with spring boot. I got following error

```
glowroot     | Dec 06, 2018 10:12:33 AM io.grpc.internal.SerializingExecutor run
glowroot     | SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1@3f897959
glowroot     | java.lang.RuntimeException: Unexpected message: MESSAGE_NOT_SET
glowroot     | 	at org.glowroot.central.CollectorServiceImpl$TraceStreamObserver.onNext(CollectorServiceImpl.java:470)
glowroot     | 	at org.glowroot.central.CollectorServiceImpl$TraceStreamObserver.onNext(CollectorServiceImpl.java:424)
glowroot     | 	at io.grpc.stub.ServerCalls$2$1.onMessage(ServerCalls.java:204)
glowroot     | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:243)
glowroot     | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:555)
glowroot     | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
glowroot     | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
glowroot     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
glowroot     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
glowroot     | 	at java.lang.Thread.run(Thread.java:745)
glowroot     | 
```

What is it? is it OK?

Thanks,
Van

**Comment by trask** [comment]
Hi @pilgrim2go, thanks for posting! That doesn't look familiar to me. Are you getting a lot of those errors? Are the agents connecting and reporting? Do things look good otherwise? Thanks.

**Comment by pilgrim2go** [comment]
Hi @trask :  I've used wrong version of `glowroot-central`. After getting right version of glowroot. This errors seem gone.
Continue monitoring and updating.

**Comment by trask** [comment]
👍
