### ISSUE TITLE
Could not initialize class org.glowroot.agent.weaving.MetaHolder27

### ISSUE THREAD

**Issue by pilgrim2go** [glowroot/glowroot#488]
Hi,

I've got following error in my Spring Boot service
```
java.lang.NoClassDefFoundError: Could not initialize class org.glowroot.agent.weaving.MetaHolder27
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1081)
	at java.lang.Thread.run(Thread.java:745)

```

I'm using Java 1.8.0_111
```
 java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

I don't know the issue. Any help?

Thanks,
Van

**Comment by trask** [comment]
Hi @pilgrim2go, what version of spring boot? Can you post the agent log? Thanks.

**Comment by pilgrim2go** [comment]
@trask thanks for your quick reply.

Here are my libs info
```
spring-boot-2.0.1.RELEASE.jar
spring-jms-5.0.5.RELEASE.jar
```
and agent logs
```
2018-12-07 02:28:52.880 INFO  org.glowroot - Glowroot version: 0.12.2, built 2018-11-09 00:50:19 +0000
2018-12-07 02:28:52.882 INFO  org.glowroot - Java version: 1.8.0_111
2018-12-07 02:28:55.559 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Kafka Plugin, Logger Plugin, MongoDB Plugin, Netty Plugin, Play Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-12-07 02:28:56.030 INFO  org.glowroot - agent id: vc_scheduler
2018-12-07 02:28:56.736 INFO  org.glowroot - connected to the central collector http://glowroot:8181, version 0.12.2, built 2018-11-09 00:50:19 +0000
```

**Comment by trask** [comment]
Is there any other error right before/after the `java.lang.NoClassDefFoundError`?  Thanks.

**Comment by pilgrim2go** [comment]
ah yes, there is a warning 
```
WARN [2018-12-07 - 02:30:07.039] org.springframework.jms.listener.DefaultMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.
```
I didn't write this Java service so not sure what it is. To check with Dev team to remove the `warn`.

**Comment by trask** [comment]
Are there any `ClassNotFoundException` or ExceptionInInitializerError` anywhere beforehand? Thanks.

**Comment by pilgrim2go** [comment]
Sadly, I haven't found any exceptions like those.

**Comment by trask** [comment]
Can you download the latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT), and try again, and then post the full agent log? It will now log a bit more info that I'm hoping will help me understand/repro this issue. Thanks.

**Comment by pilgrim2go** [comment]
Thanks @trask 
Here is the latest log
```
2018-12-07 03:21:54.215 INFO  org.glowroot - Glowroot version: 0.12.3-SNAPSHOT, commit f1abdcae72, built 2018-12-04 06:57:20 +0000
2018-12-07 03:21:54.218 INFO  org.glowroot - Java version: 1.8.0_111 (Oracle Corporation / Linux)
2018-12-07 03:21:54.219 INFO  org.glowroot - Java args: -Xmx1024m -Xms512m -javaagent:/glowroot/glowroot.jar
2018-12-07 03:21:56.594 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Kafka Plugin, Logger Plugin, MongoDB Plugin, Netty Plugin, Play Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-12-07 03:21:56.963 INFO  org.glowroot - agent id: vc_scheduler
2018-12-07 03:21:57.327 INFO  org.glowroot - connected to the central collector http://glowroot:8181, version 0.12.2, built 2018-11-09 00:50:19 +0000
2018-12-07 03:21:57.328 WARN  org.glowroot - the central collector version is older than the agent version which could cause unpredictable issues
```

**Comment by trask** [comment]
Hi @pilgrim2go, can you download the (new) latest snapshot release [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT), and try again, and then post the full agent log (again)? I added a try/catch to hopefully log the underlying exception. Thanks.

**Comment by pilgrim2go** [comment]
Thanks @trask 

Is this one correct?
```
2018-12-11 09:50:37.478 INFO  org.glowroot - Glowroot version: 0.12.3-SNAPSHOT, commit f1abdcae72, built 2018-12-04 06:57:20 +0000
2018-12-11 09:50:37.481 INFO  org.glowroot - Java version: 1.8.0_111 (Oracle Corporation / Linux)
2018-12-11 09:50:37.483 INFO  org.glowroot - Java args: -Xmx1024m -Xms512m -javaagent:/glowroot/glowroot.jar
2018-12-11 09:50:40.027 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Kafka Plugin, Logger Plugin, MongoDB Plugin, Netty Plugin, Play Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-12-11 09:50:40.436 INFO  org.glowroot - agent id: vc_scheduler
2018-12-11 09:50:40.901 INFO  org.glowroot - connected to the central collector http://glowroot:8181, version 0.12.2, built 2018-11-09 00:50:19 +0000
2018-12-11 09:50:40.902 WARN  org.glowroot - the central collector version is older than the agent version which could cause unpredictable issues
```

**Comment by pilgrim2go** [comment]
Thanks @trask 
You're right that we have `ClassNotFoundException` in the beginning of log. Thanks for your time ( i'd better export container log to file to check ).
The latest agent does show it.

```
2018-12-11 10:20:00.986 ERROR o.g.agent.impl.BytecodeServiceImpl - cloud.sqs.listener.SQSListener$$Lambda$882
java.lang.ClassNotFoundException: cloud.sqs.listener.SQSListener$$Lambda$882
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.glowroot.agent.weaving.MetaHolder27.<clinit>(Unknown Source
```

**Comment by trask** [comment]
Great, can you download this build https://glowroot.org/issue-488/glowroot-agent-0.12.3-SNAPSHOT-dist.zip, and repro again?

This build will write out the generated `MetaHolder` class bytes, and it will log INFO messages where they are written.

Then can you email me the `MetaHolder27.class` file that is written out (the one that is having the `<clinit>` problem)?  My email address is on my github profile.

Thanks.

**Comment by pilgrim2go** [comment]
Check your inbox

**Comment by trask** [comment]
Hi @pilgrim2go, this should be fixed now in the latest snapshot release [glowroot-agent-0.13.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.0-SNAPSHOT).
