### ISSUE TITLE
Glowroot Cassandra user needs create on all keyspaces

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#505]
Hello, we recently enabled password authentication and RBAC on the Cassandra cluster that is utlized by our Glowroot Central server. Everything seemed to work at first however the next day we noticed that our Glowroot agents were emitting errors about being unable to connect. After investigation the following error was discovered on the central server:

```2019-01-04 01:19:03.906 INFO  com.datastax.driver.core.Cluster - New Cassandra host cassandra/100.98.0.0:9042 added
2019-01-04 01:19:03.906 INFO  com.datastax.driver.core.Cluster - New Cassandra host cassandra/100.99.0.1:9042 added
2019-01-04 01:19:03.906 INFO  com.datastax.driver.core.Cluster - New Cassandra host cassandra/100.122.0.1:9042 added
2019-01-04 01:19:04.175 ERROR org.glowroot - User glowroot has no CREATE permission on <all keyspaces> or any of its parents
com.datastax.driver.core.exceptions.UnauthorizedException: User glowroot has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:56)
	at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:25)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:442)
	at org.glowroot.central.util.Session.<init>(Session.java:99)
	at org.glowroot.central.CentralModule.connect(CentralModule.java:736)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:160)
	at org.glowroot.central.CentralModule.create(CentralModule.java:120)
	at org.glowroot.central.CentralModule.create(CentralModule.java:115)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
Caused by: com.datastax.driver.core.exceptions.UnauthorizedException: User glowroot has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:179)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:215)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:226)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:62)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:986)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:789)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1233)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1151)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm not sure why Glowroot needs the create on all keyspaces permission given that it has all permissions on the `glowroot` keyspace which is already created. I was able to (for now) fix this by granting that permission but just wanted to double check here that that permission is actually needed by Glowroot.

For reference here are our permissions before:
```
admin@cqlsh> list all of glowroot;

 role     | username | resource            | permission
----------+----------+---------------------+------------
 glowroot | glowroot | <keyspace glowroot> |     CREATE
 glowroot | glowroot | <keyspace glowroot> |      ALTER
 glowroot | glowroot | <keyspace glowroot> |       DROP
 glowroot | glowroot | <keyspace glowroot> |     SELECT
 glowroot | glowroot | <keyspace glowroot> |     MODIFY
 glowroot | glowroot | <keyspace glowroot> |  AUTHORIZE
```

And this worked:
```admin@cqlsh> list all of glowroot;

 role     | username | resource            | permission
----------+----------+---------------------+------------
 glowroot | glowroot |     <all keyspaces> |     CREATE
 glowroot | glowroot | <keyspace glowroot> |     CREATE
 glowroot | glowroot | <keyspace glowroot> |      ALTER
 glowroot | glowroot | <keyspace glowroot> |       DROP
 glowroot | glowroot | <keyspace glowroot> |     SELECT
 glowroot | glowroot | <keyspace glowroot> |     MODIFY
 glowroot | glowroot | <keyspace glowroot> |  AUTHORIZE
```

**Comment by ReillyProcentive** [comment]
Yep, that fixed it. Thanks!

**Comment by trask** [comment]
👍
