### ISSUE TITLE
Error while registering Oracle JDBC Diagnosability MBean

### ISSUE THREAD

**Issue by Skyzoninfotech** [glowroot/glowroot#511]
I have configured glowtroot agent for our payara (glassfish) instance, when i restarted the instance, i am getting below error
  Error while registering Oracle JDBC Diagnosability MBean.
java.lang.ExceptionInInitializerError
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:500)
	at oracle.jdbc.driver.OracleDriver.registerMBeans(OracleDriver.java:322)
	at oracle.jdbc.driver.OracleDriver$1.run(OracleDriver.java:201)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.jdbc.driver.OracleDriver.<clinit>(OracleDriver.java:197)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)
	at org.glassfish.web.loader.JdbcLeakPrevention.clearJdbcDriverRegistrations(JdbcLeakPrevention.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.web.loader.WebappClassLoader.clearReferencesJdbc(WebappClassLoader.java:2031)
	at org.glassfish.web.loader.WebappClassLoader.clearReferences(WebappClassLoader.java:1954)
	at org.glassfish.web.loader.WebappClassLoader.stop(WebappClassLoader.java:1832)
	at org.glassfish.web.loader.WebappClassLoader.preDestroy(WebappClassLoader.java:1801)
	at org.glassfish.deployment.common.DeploymentContextImpl.getClassLoader(DeploymentContextImpl.java:266)
	at org.glassfish.deployment.common.DeploymentContextImpl.getClassLoader(DeploymentContextImpl.java:216)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:486)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Bytecode service retrieved too early
	at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:30)
	at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:27)
	... 45 more
]]

Can you please help resolve it

**Comment by trask** [comment]
Hi @Skyzoninfotech, can you post the glowroot agent log? Thanks.

**Comment by trask** [comment]
Hi @Skyzoninfotech, I tried latest Payara 5.184 Full install and could not reproduce that error, though I think the Glowroot wiki was wrong about how to add `-javaagent:path/to/glowroot.jar` to Payara, so I have updated it, see https://github.com/glowroot/glowroot/wiki/Where-are-my-application-server's-JVM-args%3F#payara-5

If you are still having issues, can you post (or email to me) your full Payara log? Thanks.

**Comment by trask** [comment]
Hi @Skyzoninfotech, I ran into the `java.lang.RuntimeException: Bytecode service retrieved too early` error also. It should be fixed now in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).
