### ISSUE TITLE
Heapdumps fail in OpenJ9

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#518]
Hello, we've been experimenting with the OpenJ9 JVM (this [build](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#x64_linux) specifically) in order to reduce the memory footprint of our application. We just noticed that taking heapdumps is broken.

The following exception appears in the logs for the central collector:
```2019-01-28 21:53:45.726 ERROR o.g.central.CollectorServiceImpl - master::web::admin::ourapp-web-admin-665d98748f-56k98 - 2019-01-28 21:53:45.713 ERROR org.glowroot.agent.central.DownstreamServiceObserver - com.sun.management:type=HotSpotDiagnostic
javax.management.InstanceNotFoundException: com.sun.management:type=HotSpotDiagnostic
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean()
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke()
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke()
	at org.glowroot.agent.util.LazyPlatformMBeanServer.invoke(LazyPlatformMBeanServer.java:148)
	at org.glowroot.agent.live.LiveJvmServiceImpl.heapDump(LiveJvmServiceImpl.java:202)
	at org.glowroot.agent.live.LiveJvmServiceImpl.heapDump(LiveJvmServiceImpl.java:142)
	at org.glowroot.agent.central.DownstreamServiceObserver.heapDumpAndRespond(DownstreamServiceObserver.java:401)
	at org.glowroot.agent.central.DownstreamServiceObserver.onNextInternal(DownstreamServiceObserver.java:226)
	at org.glowroot.agent.central.DownstreamServiceObserver.onNext(DownstreamServiceObserver.java:160)
	at org.glowroot.agent.central.DownstreamServiceObserver.onNext(DownstreamServiceObserver.java:96)
	at org.glowroot.agent.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at org.glowroot.agent.shaded.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at org.glowroot.agent.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at org.glowroot.agent.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.glowroot.agent.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker()
	at java.util.concurrent.ThreadPoolExecutor$Worker.run()
	at java.lang.Thread.run()
2019-01-28 21:53:45.727 ERROR org.glowroot.ui.CommonHandler - null
org.glowroot.central.DownstreamServiceImpl$AgentException: null
	at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:452)
	at org.glowroot.central.DownstreamServiceImpl.heapDump(DownstreamServiceImpl.java:202)
	at org.glowroot.central.LiveJvmServiceImpl.heapDump(LiveJvmServiceImpl.java:60)
	at org.glowroot.ui.JvmJsonService.heapDump(JvmJsonService.java:304)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:586)
	at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:325)
	at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:236)
	at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
	at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The `HotSpotDiagnostic` exception also appears in the stdout of the running application that I attempted to take a heapdump of. It appears to me that Glowroot is trying to call a Hotspot-specific management interface (which obviously fails). It looks like [this](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.api.80.doc/com.ibm.lang.management/openj9/lang/management/OpenJ9DiagnosticsMXBean.html) is probably the right API to use instead.

Oh, and I doubt that it matters but our central collector is 0.13.0 while agents are 0.12.3.

**Comment by trask** [comment]
Hi @ReillyProcentive, thanks for reporting this! It should be fixed now in the latest snapshot release [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT).
