### ISSUE TITLE
Glowroot having issue in Spring service which uses ForkJoinPool 

### ISSUE THREAD

**Issue by mtuksal** [glowroot/glowroot#542]
Hi guyz,
We are having issue when we use ForkJoinPool in XServiceImpl. We use spring framework. The error log shown in below. I think this migth be a bug. 
Thanks in advance... 

 **at org.glowroot.agent.plugin.executor.ExecutorAspect.onBeforeCommon(ExecutorAspect.java:448)
        at org.glowroot.agent.plugin.executor.ExecutorAspect.access$100(ExecutorAspect.java:44)
        at org.glowroot.agent.plugin.executor.ExecutorAspect$ExecuteAdvice.onBefore(ExecutorAspect.java:101)
        at org.springframework.core.task.SimpleAsyncTaskExecutor.submit(SimpleAsyncTaskExecutor.java)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:287)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:129)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy253.distributeMessageMultiAsync(Unknown Source)
        at com.xxx.xxx.xxx.service.impl.XServiceImpl.doSomething(XServiceImpl.java:682)
        at com.xxx.xxx.xxx.ctrl.XCtrl.doSomething(XCtrl.java:316)**

**Comment by trask** [comment]
Hi @mtuksal, thanks for reporting this! Can you include the line above what you posted? It should contain the exception name. Also, what glowroot version are you using so I can match up the line numbers in the code? Thanks.

**Comment by mtuksal** [comment]
Glowroot version is 0.13.1 and i checked master branch. But i didn't match the branch with version sorry for that. Link provided in below.

**Comment by trask** [comment]
Can you post the full stack trace? What you posted above is missing the exception name/exception message, should be at the very top of what you posted already. Thanks.

**Comment by mtuksal** [comment]
You can find full stack trace below.

java.lang.AbstractMethodError
        at org.glowroot.agent.plugin.executor.ExecutorAspect.onBeforeCommon(ExecutorAspect.java:448)
        at org.glowroot.agent.plugin.executor.ExecutorAspect.access$100(ExecutorAspect.java:44)
        at org.glowroot.agent.plugin.executor.ExecutorAspect$ExecuteAdvice.onBefore(ExecutorAspect.java:101)
        at org.springframework.core.task.SimpleAsyncTaskExecutor.submit(SimpleAsyncTaskExecutor.java)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:287)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:129)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy253.distributeMessageMultiAsync(Unknown Source)
        at xxx.xxx.xxx.xxx.xxx.xxx.MessageServiceImpl.postMessage(MessageServiceImpl.java)
        at xxx.xxx.xxx.xxx.xxx.MessageCtrl.postMessage(MessageCtrl.java)
        at jdk.internal.reflect.GeneratedMethodAccessor662.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by trask** [comment]
Hi @mtuksal, I'm hoping this should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT). Can you give it a try and let me know?

**Comment by trask** [comment]
Hi @mtuksal, I think I did not fix this. Can you post the beginning of your glowroot agent log? I'd like to see the Java version info printed there. Thanks.

**Comment by trask** [comment]
Hi @mtuksal, I was able to repro, I think this should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).

**Comment by mtuksal** [comment]
Hi @trask , we tried with glowroot-agent-0.13.2-SNAPSHOT-dist.zip. Bu we got following error in below. Do we miss something here or is it still about glowroot-agent ?

java.lang.NoClassDefFoundError: io/netty/handler/codec/http/LastHttpContent
        at org.glowroot.agent.plugin.netty.NettyAspect$OutboundAdvice_.onAfter(NettyAspect.java:199)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1392)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
        at com.datastax.driver.core.OutboundTrafficMeter.write(OutboundTrafficMeter.java:39)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:124)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1056)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290)
        at com.datastax.driver.core.Connection$Flusher.run(Connection.java:948)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by trask** [comment]
Thanks for the quick feedback, I think this latest issue should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).
