### ISSUE TITLE
NullPointerException when calling ClassLoader.defineClass()

### ISSUE THREAD

**Issue by GagouKun** [glowroot/glowroot#543]
Hello,

After upgrading from v0.13.0 to v0.13.1, we are getting this error :
```
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at org.glowroot.agent.impl.PreloadSomeSuperTypesCache.get(PreloadSomeSuperTypesCache.java:123)
    at org.glowroot.agent.impl.BytecodeServiceImpl.preloadSomeSuperTypes(BytecodeServiceImpl.java:152)
    at org.glowroot.agent.bytecode.api.Bytecode.preloadSomeSuperTypes(Bytecode.java:83)
    at java.lang.ClassLoader.defineClass(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
```

It happens because we are calling `ClassLoader.defineClass(String name, byte[] b, int off, int len)` with `null` for `name` parameter.

**Comment by trask** [comment]
Hi @GagouKun, thanks for reporting this! It should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).

**Comment by GagouKun** [comment]
Sorry for the late feedback as I was out of town for a few weeks.
I've just tested with v0.13.2 release and no NPE anymore :)

Thanks for the fix !

**Comment by trask** [comment]
👍
