### ISSUE TITLE
org.glowroot.agent.weaving.Weaver wildfly 8.2.1.Final

### ISSUE THREAD

**Issue by jhuertaa** [glowroot/glowroot#544]
Hi,

Could you help me please with this error on 8.2.1.Final.
I m configuring other glowroot version [check bellow], but in all case i have the same error.

0.10.9-SNAPSHOT
0.13.0-SNAPSHOT
0.12.3-SNAPSHOT

other informations:
Java version: 1.7.0_67

---
[complete log.log](https://github.com/glowroot/glowroot/files/2936688/complete.log.log)
---

2019-02-15 00:41:07.287 ERROR org.glowroot.agent.weaving.Weaver - unable to weave java/nio/DirectByteBuffer$Deallocator: Unexpected frame type: 0
java.lang.IllegalStateException: Unexpected frame type: 0
at org.glowroot.agent.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at org.glowroot.agent.weaving.WeavingMethodVisitor.visitFrame(WeavingMethodVisitor.java:1132)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.FrameNode.accept(FrameNode.java:131)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
at org.glowroot.agent.shaded.org.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:150)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:286)
at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:139)
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
2019-02-15 00:41:07.288 ERROR org.glowroot.agent.weaving.Weaver - wrote bytecode to: /tmp/glowroot-weaving-error-DirectByteBuffer$Deallocator.class
2019-02-15 00:41:07.611 ERROR org.glowroot.agent.weaving.Weaver - unable to weave java/util/concurrent/FutureTask: Unexpected frame type: 0
java.lang.IllegalStateException: Unexpected frame type: 0
at org.glowroot.agent.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at org.glowroot.agent.weaving.WeavingMethodVisitor.visitFrame(WeavingMethodVisitor.java:1132)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.FrameNode.accept(FrameNode.java:131)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
at org.glowroot.agent.shaded.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
at org.glowroot.agent.shaded.org.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:150)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:286)
at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:270)
at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:587)
at org.glowroot.agent.shaded.org.glowroot.common.util.ScheduledRunnable.scheduleWithFixedDelay(ScheduledRunnable.java:43)
at org.glowroot.agent.init.AgentModule.onEnteringMain(AgentModule.java:241)
at org.glowroot.agent.embedded.init.EmbeddedAgentModule.onEnteringMain(EmbeddedAgentModule.java:164)
at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit$1.run(EmbeddedGlowrootAgentInit.java:78)
at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainCommon(BytecodeServiceImpl.java:184)
at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMain(BytecodeServiceImpl.java:67)
at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
at org.jboss.modules.Main.main(Main.java)

**Comment by trask** [comment]
Hi @jhuertaa, thanks for reporting this!

Can you post (or email me) the file Glowroot wrote out `/tmp/glowroot-weaving-error-DirectByteBuffer$Deallocator.class`?

**Comment by trask** [comment]
Hi @jhuertaa, can you test and see if this is resolved in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT)?

**Comment by jhuertaa** [comment]
Hi, thanks your answer.
I installed the version that you suggest, but now my application failed to start.
When i remove glowroot, the application starting OK.

This is the log of JBOSS

07:57:36,496 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./MyApp: org.jboss.msc.service.StartException in service jboss.unde
rtow.deployment.default-server.default-host./MyApp: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_67]
Caused by: java.lang.RuntimeException: ProgramException: null
                cause: java.lang.ExceptionInInitializerError
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:223)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:87)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:72)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        ... 3 more
Caused by: ProgramException: null
                cause: java.lang.ExceptionInInitializerError
        at com.cubika.framework.aop.ReflectiveObject.invoke(ReflectiveObject.java:38)
        at com.cubika.framework.aop.ReflectiveObject.invoke(ReflectiveObject.java:51)
        at com.cubika.framework.security.AOPReflectiveServletContextListener.contextInitialized(AOPReflectiveServletContextListener.java:41)
        at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:194)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at com.cubika.framework.security.KendariServletContextListener.contextInitialized(KendariServletContextListener.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_67]
        at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_67]
        at com.cubika.framework.aop.ReflectiveObject.invoke(ReflectiveObject.java:33)
        ... 11 more
Caused by: java.lang.RuntimeException: Bytecode service retrieved from class loader: com.cubika.framework.aop.FrameworkClassLoader@36dfcd81
        at org.glowroot.agent.bytecode.api.BytecodeServiceHolder.get(BytecodeServiceHolder.java:34) [glowroot.jar:0.13.2-SNAPSHOT]
        at org.glowroot.agent.bytecode.api.Bytecode.<clinit>(Bytecode.java:26) [glowroot.jar:0.13.2-SNAPSHOT]
        ... 17 more

07:57:36,509 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 2) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "MyApp.war")]) - failure description: {"JBAS014671: Failed s
ervices" => {"jboss.undertow.deployment.default-server.default-host./MyApp" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./MyApp: Failed to start service
    Caused by: java.lang.RuntimeException: ProgramException: null
                cause: java.lang.ExceptionInInitializerError
    Caused by: ProgramException: null
                cause: java.lang.ExceptionInInitializerError
    Caused by: java.lang.ExceptionInInitializerError
    Caused by: java.lang.RuntimeException: Bytecode service retrieved from class loader: com.cubika.framework.aop.FrameworkClassLoader@36dfcd81"}}

Log detail of glowroot

2019-03-15 07:55:42.824 INFO  org.glowroot - Glowroot version: 0.13.2-SNAPSHOT, commit 66b0bc5ebf, built 2019-03-15 03:03:29 +0000
2019-03-15 07:55:42.827 INFO  org.glowroot - Java version: 1.7.0_67 (Oracle Corporation / Linux)
2019-03-15 07:55:42.827 INFO  org.glowroot - Java args: -XX:+UseCompressedOops -XX:+UseCompressedOops -Xms3G -Xmx3G -Xmn2G -XX:PermSize=400m -XX:MaxPermSize=400m -Xss1024k -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -XX:-TraceClassUnloading -XX:+CMSClassUnloadingEnabled -javaagent:/path/glowroot/glowroot.jar
2019-03-15 07:55:46.883 INFO  org.glowroot - creating glowroot schema...
2019-03-15 07:55:47.410 INFO  org.glowroot - glowroot schema created
2019-03-15 07:55:47.785 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
2019-03-15 08:10:56.593 INFO  org.glowroot - Glowroot version: 0.13.2-SNAPSHOT, commit 66b0bc5ebf, built 2019-03-15 03:03:29 +0000
2019-03-15 08:10:56.596 INFO  org.glowroot - Java version: 1.7.0_67 (Oracle Corporation / Linux)
2019-03-15 08:10:57.083 INFO  org.glowroot - Java args: -XX:+UseCompressedOops -XX:+UseCompressedOops -Xms3G -Xmx3G -Xmn2G -XX:PermSize=400m -XX:MaxPermSize=400m -Xss1024k -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -XX:-TraceClassUnloading -XX:+CMSClassUnloadingEnabled -javaagent:/patch/glowroot/glowroot.jar
2019-03-15 08:11:05.522 INFO  org.glowroot - UI listening on IP:4000

**Comment by trask** [comment]
(new issue #554 was opened for above error)
