### ISSUE TITLE
NoSuchMethodError: org.apache.commons.dbcp.AbandonedTrace.getObject(ILjava/Lang/class;)Ljava/Lang/Object

### ISSUE THREAD

**Issue by maddaliravi** [glowroot/glowroot#550]
Hi,

I am using latest glowroot ..0.13.1

A working functionality is giving the above error after I plugged glowroot to my application that runs on tomcat 8.0.17 and java8.

I tried to change my application to tomcat 7.0.39 and java7 and the issue still persist.

If I removed glowroot it is working fine but comes back if add it again.

The class in question is from commons-dbcp 1.3 jar ... Which is in my pom
XML.. 

Tried several trial and error but no luck and I failed to understand what could be the cause..

Just a point to add.. Glowroot UI comes up for me...and it monitors the information also ... But one existing functionality breaking and monitoring of a functionality stops halfway through , after the error.

 Thanks to help.

**Comment by trask** [comment]
Hi @maddaliravi, thanks for reporting this! Can you post the full stack trace for the exception?

**Comment by maddaliravi** [comment]
Caused by: java.lang.NoSuchMethodError: org.apache.commons.dbcp.AbandonedTrace.getObject(ILjava/lang/Class;)Ljava/lang/Object;

                at org.apache.commons.dbcp.DelegatingResultSet.getObject(DelegatingResultSet.java)

                at org.springframework.jdbc.support.JdbcUtils.getResultSetValue(JdbcUtils.java:197)

                at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)

                at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)

                at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:697)

                at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)

                at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)

                at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)

                at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726)

                at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776)

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

                at java.lang.reflect.Method.invoke(Unknown Source)

                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)

                at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)

                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)

                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)

                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)

                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)

                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)

                at com.sun.proxy.$Proxy69.getResult(Unknown Source)

                at java.util.concurrent.FutureTask.run(Unknown Source)

                at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

                at java.util.concurrent.FutureTask.run(Unknown Source)

**Comment by trask** [comment]
Hi @maddaliravi, thanks, also, what Spring Framework version are you using?

**Comment by maddaliravi** [comment]
Spring core 4.3.3.RELEASE

Compiled on java7.

And it is not a spring boot application.

**Comment by maddaliravi** [comment]
Hi @trask  ,  thanks for the quick turnaround.

i see that you labelled it as a bug and added to v0.13.2 release. do we have any timelines for this release ?

or if you have any workaround solutions / configuration change that you can suggest me in the meanwhile , so that i can try in the 0.13.1 version itself ?

**Comment by maddaliravi** [comment]
Hi @trask,

Can you give me a snapshot build please?

Thanks a lot..!

**Comment by trask** [comment]
Hi @maddaliravi, I think this should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).

**Comment by maddaliravi** [comment]
Hi @trask,

Thank you so much.. it is working now.

Can we use this with weblogic server too ?

**Comment by trask** [comment]
Hi @maddaliravi, yes it should work with weblogic server. Let me know if you have any issue.

**Comment by maddaliravi** [comment]
Hi @trask, I am able to plug glowroot to weblogic ..but we use mainly for RMI invocations through spring.. but it seems it is not instrumented by glowroot as it focus mostly on http requests.


Another point In general for Glowroot is .. can we log the input details also for the http request to be able to match whose request is that..

**Comment by trask** [comment]
Hi @maddaliravi, can you open a new issue for RMI support? That is a nice idea.

For the other point about logging the input details for an http request, can you explain a bit more? Do you mean capturing something additional in the slow traces? Thanks.

**Comment by maddaliravi** [comment]
Let's say if it is a REST API, then is it possible to log input request in the trace to understand which input request caused the slowness or took most time in case of an issue.

**Comment by trask** [comment]
Hi @maddaliravi, I'm not clear what you mean by "input request", can you explain a bit more? Thanks.

**Comment by maddaliravi** [comment]
Input request means ... The parameters and their values in the http request.

**Comment by trask** [comment]
Hm, Servlet request parameters and their values should already be captured in the traces. There's some configuration settings, e.g. https://demo.glowroot.org/config/plugin?plugin-id=servlet, but the default is to capture them. Is this a Servlet request trace where they are missing?
