### ISSUE TITLE
java.lang.ClassCastException 

### ISSUE THREAD

**Issue by mbejan** [glowroot/glowroot#564]
Version: Agent version 0.13.2, built 2019-03-27 

java.lang.ClassCastException: org.glowroot.agent.plugin.executor.CallableWrapper cannot be cast to oracle.ucp.util.UCPTaskBase
        at oracle.ucp.util.UCPTaskManagerImpl$UCPFutureTask.<init>(UCPTaskManagerImpl.java:330)
        at oracle.ucp.util.UCPTaskManagerImpl$UCPThreadPoolExecutor.newTaskFor(UCPTaskManagerImpl.java:319)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:133)
        at oracle.ucp.util.UCPTaskManagerImpl.submitToWTP(UCPTaskManagerImpl.java:252)
        at oracle.ucp.util.UCPTaskManagerImpl.submitTask(UCPTaskManagerImpl.java:178)
        at oracle.ucp.common.UniversalPooledConnectionImpl.isValid(UniversalPooledConnectionImpl.java:290)
        at oracle.ucp.common.FailoverableUniversalPooledConnectionBase.isValid(FailoverableUniversalPooledConnectionBase.java:17)
        at oracle.ucp.jdbc.oracle.OracleUniversalPooledConnection.isValid(OracleUniversalPooledConnection.java:229)

**Comment by trask** [comment]
Hi @mbejan, thanks for reporting this! This looks like it was caused by something I did in 0.13.2. I will fix soon, in the meantime, 0.13.1 should not have this issue.

**Comment by trask** [comment]
Hi @mbejan, this should be fixed in the latest snapshot release [glowroot-agent-0.13.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.3-SNAPSHOT).
