### ISSUE TITLE
WildFly 13 startup issue

### ISSUE THREAD

**Issue by tstiemerling** [glowroot/glowroot#567]
Seeing this on startup. Not sure how significant, since still see traces.

2019-04-04 15:24:33,136 INFO  [stdout] (MSC service thread 1-3) 2019-04-04 15:24:33.135 ERROR org.glowroot.agent.weaving.Weaver - unable to weave io/undertow/servlet/handlers/DefaultServlet: null
2019-04-04 15:24:33,136 INFO  [stdout] (MSC service thread 1-3) java.lang.reflect.InvocationTargetException: null
2019-04-04 15:24:33,136 INFO  [stdout] (MSC service thread 1-3)         at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at java.lang.reflect.Method.invoke(Unknown Source)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:86)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:105)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.ClassLoaders.defineClassIfNotExists(ClassLoaders.java:79)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:297)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:148)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at sun.instrument.TransformerManager.transform(Unknown Source)
2019-04-04 15:24:33,137 INFO  [stdout] (MSC service thread 1-3)         at sun.instrument.InstrumentationImpl.transform(Unknown Source)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at java.lang.ClassLoader.defineClass1(Native Method)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.Module.loadModuleClass(Module.java:731)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.createServletConfig(UndertowDeploymentInfoService.java:807)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.start(UndertowDeploymentInfoService.java:277)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
2019-04-04 15:24:33,138 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at java.lang.Thread.run(Unknown Source)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3) Caused by: java.lang.LinkageError: loader (instance of  org/jboss/modules/ModuleClassLoader): attempted  duplicate class definition for name: "org/glowroot/agent/plugin/servlet/DetailCapture_"
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at java.lang.ClassLoader.defineClass1(Native Method)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,139 INFO  [stdout] (MSC service thread 1-3)         ... 37 common frames omitted
2019-04-04 15:24:33,142 INFO  [stdout] (MSC service thread 1-4) 2019-04-04 15:24:33.142 ERROR org.glowroot.agent.weaving.Weaver - unable to weave io/undertow/servlet/handlers/DefaultServlet: null
2019-04-04 15:24:33,142 INFO  [stdout] (MSC service thread 1-4) java.lang.reflect.InvocationTargetException: null
2019-04-04 15:24:33,142 INFO  [stdout] (MSC service thread 1-4)         at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
2019-04-04 15:24:33,143 INFO  [stdout] (MSC service thread 1-4)         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2019-04-04 15:24:33,143 INFO  [stdout] (MSC service thread 1-4)         at java.lang.reflect.Method.invoke(Unknown Source)
2019-04-04 15:24:33,143 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:86)
2019-04-04 15:24:33,143 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:105)
2019-04-04 15:24:33,144 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.ClassLoaders.defineClass(ClassLoaders.java:102)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.ClassLoaders.defineClassIfNotExists(ClassLoaders.java:79)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:297)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:148)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at sun.instrument.TransformerManager.transform(Unknown Source)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at sun.instrument.InstrumentationImpl.transform(Unknown Source)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at java.lang.ClassLoader.defineClass1(Native Method)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
2019-04-04 15:24:33,145 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.Module.loadModuleClass(Module.java:731)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.createServletConfig(UndertowDeploymentInfoService.java:807)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.start(UndertowDeploymentInfoService.java:277)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
2019-04-04 15:24:33,146 INFO  [stdout] (MSC service thread 1-4)         at java.lang.Thread.run(Unknown Source)
2019-04-04 15:24:33,147 INFO  [stdout] (MSC service thread 1-4) Caused by: java.lang.LinkageError: loader (instance of  org/jboss/modules/ModuleClassLoader): attempted  duplicate class definition for name: "org/glowroot/agent/plugin/servlet/ServletAspect$GetSessionOneArgAdvice_"
2019-04-04 15:24:33,147 INFO  [stdout] (MSC service thread 1-4)         at java.lang.ClassLoader.defineClass1(Native Method)
2019-04-04 15:24:33,147 INFO  [stdout] (MSC service thread 1-4)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,147 INFO  [stdout] (MSC service thread 1-4)         at java.lang.ClassLoader.defineClass(Unknown Source)
2019-04-04 15:24:33,147 INFO  [stdout] (MSC service thread 1-4)         ... 35 common frames omitted

**Comment by trask** [comment]
Hi @tstiemerling, thanks for reporting this! I think it is fixed in the latest snapshot release [glowroot-agent-0.13.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.3-SNAPSHOT).

**Comment by tstiemerling** [comment]
ok, thanks. Will give it a try.

**Comment by tstiemerling** [comment]
Fix confirmed. No more errors on startup. Any issues with using this agent with 0.13.2 collector?

**Comment by trask** [comment]
👍 No issue using this agent snapshot with the 0.13.2 collector.

**Comment by tstiemerling** [comment]
Thx! Great work on this btw.
