### ISSUE TITLE
Central collector address in use?

### ISSUE THREAD

**Issue by tstiemerling** [glowroot/glowroot#568]
Running central collector with Apache Tomcat and Cassandra on same node. Get this on startup, but not sure which port is being opened.

2019-04-05 15:44:53.006 WARN  org.glowroot.common.util.Version - could not find Build-Time attribute in META-INF/MANIFEST.MF file
2019-04-05 15:44:53.009 INFO  org.glowroot - Glowroot version: 0.13.2
2019-04-05 15:44:53.011 INFO  org.glowroot - Java version: 1.8.0_201
2019-04-05 15:44:53.011 INFO  org.glowroot - Glowroot home: /home/local/glowroot-central
2019-04-05 15:44:53.321 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2019-04-05 15:44:53.334 INFO  com.datastax.driver.core - DataStax Java driver 3.6.0 for Apache Cassandra
2019-04-05 15:44:53.339 INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
2019-04-05 15:44:53.499 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2019-04-05 15:44:54.163 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2019-04-05 15:44:54.165 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2019-04-05 15:44:54.225 INFO  org.glowroot - connected to Cassandra (version 3.11.4), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM
2019-04-05 15:44:55.448 ERROR org.glowroot - Failed to bind
java.io.IOException: Failed to bind
        at io.grpc.netty.NettyServer.start(NettyServer.java:252)
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:163)
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:78)
        at org.glowroot.central.GrpcServer.startServer(GrpcServer.java:135)
        at org.glowroot.central.GrpcServer.<init>(GrpcServer.java:95)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:233)
        at org.glowroot.central.CentralModule.createForServletContainer(CentralModule.java:142)
        at org.glowroot.central.GlowrootServlet.init(GlowrootServlet.java:74)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4956)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5270)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1852)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

**Comment by tstiemerling** [comment]
Self inflicted - for some reason Tomcat shutdown failed, and there was already instance running.

**Comment by trask** [comment]
👍 to answer your questions about which port it was trying to open, it was the gRPC port, default is `8181` (configurable in the `glowroot-central.properties`)

**Comment by Rinkuujjainwal** [comment]
Dear Trask,

When I run the command java -jar glowroot-central/glowroot-central.jar
I am getting this error.

java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:252)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:163)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:78)
	at org.glowroot.central.GrpcServer.startServer(GrpcServer.java:135)
	at org.glowroot.central.GrpcServer.<init>(GrpcServer.java:95)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:233)
	at org.glowroot.central.CentralModule.create(CentralModule.java:137)
	at org.glowroot.central.CentralModule.create(CentralModule.java:132)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:252)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:163)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:78)
	at org.glowroot.central.GrpcServer.startServer(GrpcServer.java:135)
	at org.glowroot.central.GrpcServer.<init>(GrpcServer.java:95)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:233)
	at org.glowroot.central.CentralModule.create(CentralModule.java:137)
	at org.glowroot.central.CentralModule.create(CentralModule.java:132)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
