### ISSUE TITLE
Glowroot do not work with WebSphere and Open Liberty Server 

### ISSUE THREAD

**Issue by tfarterooe** [glowroot/glowroot#574]
Hello with Update to Version 0.13.3 the Agent stop working with WebSphere and Open Liberty Server .

2019-04-16 10:00:19.169 INFO org.glowroot - Glowroot version: 0.13.3, built 2019-04-09 15:44:03 +0000
2019-04-16 10:00:19.171 INFO org.glowroot - Java version: 1.8.0_202 (Eclipse OpenJ9 / Linux)
2019-04-16 10:00:19.177 INFO org.glowroot - Java args: -Xoptionsfile=/opt/openliberty/java_b/8.0/jre/lib/amd64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse7b_29 -Xshareclasses:name=liberty-%u,nonfatal,cacheDir=/opt/wslp/servers/.classCache,cacheDirPerm=1000 -XX:ShareClassesEnableBCI -Xscmx80m -javaagent:/opt/openliberty/wlp/bin/tools/ws-javaagent.jar -Xms356m -Xmx756m -verbose:gc -Xverbosegclog:/opt/wslp/servers/olei003s01/logs/verbgc_%seq.log,8,1000 -Xcompressedrefs -Xgcpolicy:gencon -Xdisableexplicitgc -XsamplingExpirationTime240 -Xjit:disableLockReservation -Xdump:java+heap+system:events=user -javaagent:/opt/jarlibs/glowroot/glowroot.jar
2019-04-16 10:00:20.335 ERROR org.glowroot - Glowroot failed to start: null
java.lang.VerifyError: null
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:156)
at org.glowroot.agent.live.LiveWeavingServiceImpl.initialReweave(LiveWeavingServiceImpl.java:262)
at org.glowroot.agent.weaving.AdviceCache.initialReweave(AdviceCache.java:158)
at org.glowroot.agent.init.AgentModule.(AgentModule.java:208)
at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit.init(NonEmbeddedGlowrootAgentInit.java:105)
at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:266)
at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:416)

**Comment by trask** [comment]
Hi @tfarterooe, thanks for reporting this! What version of WebSphere and Open Liberty Server are you using? And what version of Glowroot last worked?

**Comment by tfarterooe** [comment]
Hello, we are using WebSphere Liberty and OpenLiberty in version 19.0.0.3. The JVM for WebSphere Liberty is IBM 8.0.5.31 (1.8.0_201) and for OpenLiberty on Linux is OpenJ9 in version „OpenJDK Runtime Environment (1.8.0_202-b08)“.

The last working version of the agent was 0.13.2 (same Liberty Server and JVM versions.


_________________________________
Mit freudlichen Grüßen / best regards

Gerhard Thumfart

Von: Trask Stalnaker [mailto:notifications@github.com]
Gesendet: Dienstag, 16. April 2019 15:03
An: glowroot/glowroot <glowroot@noreply.github.com>
Cc: Thumfart, Gerhard <Gerhard.Thumfart@ooe.gv.at>; Mention <mention@noreply.github.com>
Betreff: Re: [glowroot/glowroot] Glowroot do not work with WebSphere and Open Liberty Server (#574)


Hi @tfarterooe<https://github.com/tfarterooe>, thanks for reporting this! What version of WebSphere and Open Liberty Server are you using? And what version of Glowroot last worked?

**Comment by ThiagoMenezesAbreu** [comment]
I also noted this after upgrading to latest version. Downgraded to 0.11.0 and works fine again.
WebSphere Base 9.x and WebSphere Liberty 18.x

**Comment by trask** [comment]
Hi @ThiagoMenezesAbreu, can you see if 0.13.2 works for you also? That will help me narrow down what might be the issue. Thanks.

**Comment by trask** [comment]
@ThiagoMenezesAbreu, nevermind, I can repro, and will look into fix. Thanks.

**Comment by trask** [comment]
This should be fixed now in the latest snapshot release [glowroot-agent-0.13.4-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.4-SNAPSHOT).

**Comment by tfarterooe** [comment]
Thank you,
the Snapshot works fine.


_________________________________
Mit freudlichen Grüßen / best regards

Gerhard Thumfart

Von: Trask Stalnaker [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. April 2019 04:48
An: glowroot/glowroot <glowroot@noreply.github.com>
Cc: Thumfart, Gerhard <Gerhard.Thumfart@ooe.gv.at>; Mention <mention@noreply.github.com>
Betreff: Re: [glowroot/glowroot] Glowroot do not work with WebSphere and Open Liberty Server (#574)


This should be fixed now in the latest snapshot release glowroot-agent-0.13.4-SNAPSHOT-dist.zip<https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.4-SNAPSHOT>.
