### ISSUE TITLE
Crash on Websphere 8.5.5 IBM JDK7

### ISSUE THREAD

**Issue by gregsting** [glowroot/glowroot#578]
Hi Trask,

I've used glowroot with great success on our jboss infrastructure (amazing software, really!), but now I'm trying to do the same on our older Websphere infra.

We are running WS 8.5.5 with IBM JVM and I tried the latest version of the agent (0.13.4).

On startup glowroot is triggered but fails with the following error:

2019-04-23 14:13:00.977 INFO  org.glowroot - Glowroot version: 0.13.4, built 2019-04-21 20:27:33 +0000
2019-04-23 14:13:01.008 INFO  org.glowroot - Java version: 1.7.0 (IBM Corporation / Windows Server 2008 R2)
2019-04-23 14:13:01.133 INFO  org.glowroot - Java args: -Xoptionsfile=E:\WebSphere\AppServer\java_1.7_64\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse7b_26 -Xshareclasses:name=webspherev85_1.7_64,nonFatal -Xbootclasspath/p:E:\WebSphere\AppServer/java_1.7_64/jre/lib/ibmorb.jar -verbose:gc -Xms2048m -Xmx6144m -Xcompressedrefs -Xscmaxaot4M -Xscmx90M -javaagent:E:\WebSphere\glowroot\glowroot.jar
2019-04-23 14:13:03.165 ERROR org.glowroot - Glowroot failed to start: null
java.lang.instrument.UnmodifiableClassException: null
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:164)
	at org.glowroot.agent.init.AgentModule.<init>(AgentModule.java:211)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit.init(NonEmbeddedGlowrootAgentInit.java:105)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:266)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:405)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:420)

Thanks for your help!

**Comment by gregsting** [comment]
I see this in your code, so probably highly related ;)

            } catch (UnmodifiableClassException e) {
                // IBM J9 VM Java 6 throws UnmodifiableClassException even though call to
                // isModifiableClass() in getExistingModifiableSubClasses() returns true
                logger.debug(e.getMessage(), e);

**Comment by gregsting** [comment]
I guess this is related:
https://www.ibm.com/support/knowledgecenter/SSYKE2_7.0.0/com.ibm.java.win.70.doc/user/retransformclasses.html

Now I have to find how to "disable the shared class cache" and decide if it's a good idea...

**Comment by gregsting** [comment]
"-Xshareclasses:none" seems to do the trick!

According to documentation this affect primarily the startup time:
https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/is_your_websphere_application_server_not_starting_due_to_shared_class_cache_problem?lang=en
