### ISSUE TITLE
getting errr

### ISSUE THREAD

**Issue by mayankjain9005** [glowroot/glowroot#582]
Even the jar  lib/glowroot-embedded-collector .jar is present 

java.lang.ClassNotFoundException: org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInitFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.glowroot.agent.MainEntryPoint.createGlowrootAgentInit(MainEntryPoint.java:311)
        at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:273)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

**Comment by jjlharrison** [comment]
I'm seeing this issue with Wildfly 10.1.0.Final and AdoptOpenJDK 1.8.162.

Seems to have been introduced in 0.10.3 as I don't see the issue with 0.10.2.

**Comment by mayankjain9005** [comment]
solved

**Comment by jjlharrison** [comment]
@mayankjain9005: Could you share how you solved it please?
