### ISSUE TITLE
TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#585]
Glowroot version 0.13.4.

Sometimes one of our servers will stop reporting data to the central collector, and instead the log starts to fill up with messages like

```
[5/14/19 16:42:00:001 GMT] 00000019 SystemOut     O   2019-05-14 16:42:00.001 WARN  o.g.agent.impl.TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
```

```
[5/14/19 16:28:42:749 GMT] 00000020 SystemOut     O   2019-05-14 16:28:42.748 WARN  o.g.a.s.i.g.internal.ChannelExecutor - Runnable threw exception in ChannelExecutor
java.lang.IllegalStateException: nameResolver is null
	at org.glowroot.agent.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.glowroot.agent.shaded.io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:328)
	at org.glowroot.agent.shaded.io.grpc.internal.ManagedChannelImpl.enterIdleMode(ManagedChannelImpl.java:386)
	at org.glowroot.agent.shaded.io.grpc.internal.ManagedChannelImpl.access$1400(ManagedChannelImpl.java:84)
```
and

```
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[5/14/19 15:58:11:849 GMT] 000000db filter        E com.ibm.ws.webcontainer.filter.FilterInstanceWrapper doFilter SRVE8109W: Uncaught exception thrown by filter RESTDispatcherFilter: java.lang.OutOfMemoryError: Java heap space
	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoImpl(Native Method)
	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:335)
	at org.glowroot.agent.model.ThreadStatsComponent.<init>(ThreadStatsComponent.java:55)
	at org.glowroot.agent.impl.ThreadContextImpl.<init>(ThreadContextImpl.java:157)
	at org.glowroot.agent.impl.Transaction.<init>(Transaction.java:237)
	at org.glowroot.agent.impl.TransactionService.startTransaction(TransactionService.java:91)
```

The server is basically idle before this occurs. We have other instances of the server where this does not happen, even after processing a few million requests.

Once it fails, it never seems to recover. 

Server is 
```
************ Start Display Current Environment ************
WebSphere Platform 9.0.0.10 [BASE 9.0.0.10 cf101846.03] [JAVA8 8.0.5.26 pxa6480sr5fp26-20181115_03] [WXS 8.6.1.2 cf21712.22141622] running with process name localhost\localhost\server1 and process id 1917```

Any clues as to what could cause this?

Glowroot agent config is the default config, with only agent name and collector address filled in.

**Comment by gregsting** [comment]
Just had the same error, restarting glowroot central and cassandra does not help, only way is to retstart the agent

**Comment by maheshkumargp** [comment]
I'm also facing the same error

**Comment by Hani2002** [comment]
2023-10-22 09:15:42.214 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 11 warnings were suppressed since it was last logged)
2023-10-22 09:16:42.248 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 10 warnings were suppressed since it was last logged)
2023-10-22 09:17:00.003 WARN  o.g.agent.impl.TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
2023-10-22 09:17:42.365 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 11 warnings were suppressed since it was last logged)

**Comment by Hani2002** [comment]
Same error any update ?

**Comment by Never-lab** [comment]
`not storing an aggregate because of an excessive backlog` = agent under pressure (capture volume / disk / CPU). Raise resources, lower slow-threshold volume, upgrade 0.14.x; same capacity family as other backlog reports.

@nowheresly — please close as support.
