### ISSUE TITLE
 Glowroot failed to start: Unable to create lock file

### ISSUE THREAD

**Issue by willsilvano** [glowroot/glowroot#591]
Hi, I'm trying to build and Docker image with Glowroot and Willdfly, but when the server is starting this message is showed:

```
Glowroot failed to start: Unable to create lock file: /opt/jboss/glowroot/tmp/.lock
java.io.IOException: Unable to create lock file: /opt/jboss/glowroot/tmp/.lock
        at org.glowroot.agent.AgentDirsLocking.touchLockFile(AgentDirsLocking.java:73)
        at org.glowroot.agent.AgentDirsLocking.tryLockAgentDirs(AgentDirsLocking.java:36)
        at org.glowroot.agent.Directories.<init>(Directories.java:120)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at org.glowroot.agent.AgentDirsLocking.touchLockFile(AgentDirsLocking.java:71)
        ... 14 more
```
Should I set any permission in folder `/opt/jboss/glowroot/`?

**Comment by trask** [comment]
Hi @willsilvano, thanks for posting! Are you still having the issue? If you don't want to change the permissions on the glowroot folder, you could create the `tmp` folder, and make that writable for whatever user is running the JVM process. Or you can change the temp folder that glowroot uses, e.g. https://github.com/glowroot/glowroot/wiki/Agent-Installation-(with-Embedded-Collector)#changing-up-the-directory-locations

**Comment by willsilvano** [comment]
Hi @trask ! We have already solved the permission problem and now it's working. Thanks!

**Comment by trask** [comment]
👍
