### ISSUE TITLE
Can not start glowroot with thorntail app

### ISSUE THREAD

**Issue by ihor-mozil** [glowroot/glowroot#595]
I'm trying to start an glowroot all and getting the exception below. It possible somehow to workaround this?

2019-05-29 12:35:39.038 INFO  org.glowroot - Glowroot version: 0.13.4, built 2019-04-21 20:27:33 +0000
2019-05-29 12:35:39.040 INFO  org.glowroot - Java version: 1.8.0_211 (Oracle Corporation / Windows 10)
2019-05-29 12:35:39.040 INFO  org.glowroot - Java args: -javaagent:D:/glowroot/glowroot.jar
Wed May 29 12:35:42 EEST 2019 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
2019-05-29 12:35:42.978 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      JPA - STABLE          io.thorntail:jpa:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                  Logging - STABLE          io.thorntail:logging:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:              Datasources - STABLE          io.thorntail:datasources:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:               Infinispan - STABLE          io.thorntail:infinispan:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      JMX - STABLE          io.thorntail:jmx:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                 Remoting - STABLE          io.thorntail:remoting:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:         JAX-RS with JAXB - STABLE          io.thorntail:jaxrs-jaxb:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                   JAX-RS - STABLE          io.thorntail:jaxrs:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      JSF - STABLE          io.thorntail:jsf:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                 Undertow - STABLE          io.thorntail:undertow:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                     Mail - STABLE          io.thorntail:mail:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
WARN: THORN0013: Installed fraction:                   Flyway - EXPERIMENTAL    io.thorntail:flyway:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:             Web Services - STABLE          io.thorntail:webservices:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                  Elytron - STABLE          io.thorntail:elytron:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      CDI - STABLE          io.thorntail:cdi:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:        CDI Configuration - STABLE          io.thorntail:cdi-config:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:          Bean Validation - STABLE          io.thorntail:bean-validation:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:             Transactions - STABLE          io.thorntail:transactions:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      EJB - STABLE          io.thorntail:ejb:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: THORN0013: Installed fraction:                      JCA - STABLE          io.thorntail:jca:2.4.0.Final
Mai 29, 2019 12:35:49 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.0.5 (Final)
Mai 29, 2019 12:35:49 PM org.jboss.weld.util.ServiceLoader loadClass
WARNUNG: Could not load service class org.wildfly.swarm.cdi.config.deployment.InjectConfigViewExtension
Mai 29, 2019 12:35:49 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Mai 29, 2019 12:35:50 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Mai 29, 2019 12:35:51 PM org.jboss.weld.interceptor.reader.InterceptorMetadataUtils isValidTargetClassLifecycleInterceptorMethod
WARN: WELD-001471: Interceptor method setupFactories defined on class org.wildfly.swarm.container.runtime.xmlconfig.StandaloneXMLParserProducer is not defined according to the specification. It should not throw java.lang.Exception, which is a checked exception.
	at org.wildfly.swarm.container.runtime.xmlconfig.StandaloneXMLParserProducer.setupFactories(StandaloneXMLParserProducer.java:0)
  StackTrace
Mai 29, 2019 12:35:51 PM org.jboss.weld.interceptor.reader.InterceptorMetadataUtils isValidTargetClassLifecycleInterceptorMethod
WARN: WELD-001471: Interceptor method postConstruct defined on class org.wildfly.swarm.container.runtime.wildfly.ShrinkWrapFileSystem is not defined according to the specification. It should not throw java.io.IOException, which is a checked exception.
	at org.wildfly.swarm.container.runtime.wildfly.ShrinkWrapFileSystem.postConstruct(ShrinkWrapFileSystem.java:0)
  StackTrace
java.lang.RuntimeException: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:113)
	at org.wildfly.swarm.Swarm.start(Swarm.java:401)
	at org.wildfly.swarm.Swarm.main(Swarm.java:745)
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:73)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:59)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:67)
	at org.jboss.weld.bootstrap.ConcurrentValidator.validateDecorators(ConcurrentValidator.java:90)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:485)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:490)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:801)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$null$0(ServerBootstrapImpl.java:149)
	at org.wildfly.swarm.container.runtime.LogSilencer$SilentExecutor.execute(LogSilencer.java:75)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$bootstrap$1(ServerBootstrapImpl.java:120)
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:43)
	... 3 more
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at org.jboss.weld.util.Decorators.checkDelegateType(Decorators.java:140)
	at org.jboss.weld.bootstrap.Validator.validateDecorator(Validator.java:585)
	at org.jboss.weld.bootstrap.ConcurrentValidator$3.doWork(ConcurrentValidator.java:92)
	at org.jboss.weld.bootstrap.ConcurrentValidator$3.doWork(ConcurrentValidator.java:90)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.lang.RuntimeException: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:113)
	at org.wildfly.swarm.Swarm.start(Swarm.java:401)
	at org.wildfly.swarm.Swarm.main(Swarm.java:745)
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:73)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:59)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:67)
	at org.jboss.weld.bootstrap.ConcurrentValidator.validateDecorators(ConcurrentValidator.java:90)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:485)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:490)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:801)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$null$0(ServerBootstrapImpl.java:149)
	at org.wildfly.swarm.container.runtime.LogSilencer$SilentExecutor.execute(LogSilencer.java:75)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$bootstrap$1(ServerBootstrapImpl.java:120)
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:43)
	... 3 more
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000061: The delegate type does not extend or implement the decorated type. 
  Decorated type: interface org.glowroot.agent.plugin.executor.ExecutorAspect$RunnableEtcMixin
  Decorator: Decorator [class org.jboss.weld.environment.se.threading.RunnableDecorator] decorates [RunnableEtcMixin, Runnable] with delegate type [Runnable] and delegate qualifiers [@Default]
	at org.jboss.weld.util.Decorators.checkDelegateType(Decorators.java:140)
	at org.jboss.weld.bootstrap.Validator.validateDecorator(Validator.java:585)
	at org.jboss.weld.bootstrap.ConcurrentValidator$3.doWork(ConcurrentValidator.java:92)
	at org.jboss.weld.bootstrap.ConcurrentValidator$3.doWork(ConcurrentValidator.java:90)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by trask** [comment]
Hi @ihor-mozil , thanks for reporting this! I think this is fixed now in the latest snapshot release [glowroot-agent-0.13.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.5-SNAPSHOT).
