### ISSUE TITLE
Glow root not starting, could not create platform mbean server

### ISSUE THREAD

**Issue by saketthaploo** [glowroot/glowroot#596]
getting the below error while starting my java application.
" ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
        at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
        at org.glowroot.agent.plugin.servlet.ContainerStartup_.onBeforeCommon(ContainerStartup.java:38)
        at org.glowroot.agent.plugin.servlet.CatalinaAppStartupAspect$StartAdvice_.onBefore(CatalinaAppStartupAspect.java:53)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        at com.l7tech.server.transport.http.HttpTransportModule.b(Unknown Source)
        at com.l7tech.server.transport.http.HttpTransportModule.doStart(Unknown Source)
        at com.l7tech.server.LifecycleBean.start(Unknown Source)
        at com.l7tech.server.b0.run(Unknown Source)
        at com.l7tech.server.util.ac.doRun(Unknown Source)
        at com.l7tech.server.util.ManagedTimerTask.run(Unknown Source)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
"

I have followed installation steps as mentioned in https://github.com/glowroot/glowroot

**Comment by trask** [comment]
Hi @saketthaploo, it looks like you are using a security manager, and need to give glowroot the requested right ("javax.management.MBeanServerPermission" "createMBeanServer").

**Comment by yogeshjangrax** [comment]
hi @trask can you help how to do that. 
giving permission.

**Comment by yogeshjangrax** [comment]
below is the error

17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70) 2023-07-06 17:29:10.459 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at javax.servlet.GenericServlet.init(GenericServlet.java)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
17:29:10,460 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:309)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,461 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
17:29:10,462 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at java.lang.Thread.run(Thread.java:750)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.threads.JBossThread.run(JBossThread.java:513)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70) Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory from [Module "javax.servlet.api" version 2.0.0.Final-redhat-00001 from local module loader @3401a114 (finder: local module finder @5066d65f (roots: /some_path/jboss-eap-7.4.11/modules,/some_path/jboss-eap-7.4.11/modules/system/layers/base/.overlays/layer-base-jboss-eap-7.4.11.CP,/some_path/jboss-eap-7.4.11/modules/system/layers/base))]
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
17:29:10,463 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
17:29:10,464 INFO  [stdout] (ServerService Thread Pool -- 70)     at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
17:29:10,464 INFO  [stdout] (ServerService Thread Pool -- 70)     ... 28 common frames omitted
17:29:10,492 INFO  [stdout] (ServerService Thread Pool -- 73) 2023-07-06 17:29:10.490 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
17:29:10,493 INFO  [stdout] (ServerService Thread Pool -- 73) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
17:29:10,493 INFO  [stdout] (ServerService Thread Pool -- 73)     at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
17:29:10,495 INFO  [stdout] (ServerService Thread Pool -- 73)     at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
17:29:10,495 INFO  [stdout] (ServerService Thread Pool -- 73)     at javax.servlet.GenericServlet.init(GenericServlet.java)

**Comment by xkidera** [comment]
Same issue here. JBoss EAP 7.4.16.

Everything appear to work fine but keeps logging this stacktrace @yogeshjangrax posted

**Comment by Never-lab** [comment]
Already answered by @trask: this is a **Java SecurityManager** denial (`MBeanServerPermission createMBeanServer`), not a Glowroot crash. The servlet plugin’s startup advice calls `ManagementFactory.getPlatformMBeanServer()`; under a security manager that permission must be granted to the agent / app policy.

Grant e.g. `permission javax.management.MBeanServerPermission "createMBeanServer";` (and related JMX rights as needed) in the policy used by your container (CA Layer7 / Tomcat / JBoss policy files). The ERROR is logged and caught — agent may still run without gauges/JMX until fixed.

Related (different root cause): WildFly/JBoss **module** CNFE for `ManagementFactory` → #1025 (`java.management` dependency in servlet `module.xml`).

OK to close as support.

@nowheresly
