### ISSUE TITLE
Glowroot WeavingClassFileTransformer - error weaving a class

### ISSUE THREAD

**Issue by danzone** [glowroot/glowroot#598]
Hi all, after setting-up Glowroot on a JBoss 7.1.1 AS, we are facing a error weaving class, and the result is that Glowroot is up and running (we can access to Glowroot console), while our webapp isn't. So we had to disable Glowroot, making our webapp running again.
Following the JBoss log excerpt showing the error:
```
2019-05-30 18:27:41.457 INFO  org.glowroot - Glowroot version: 0.13.4, built 2019-04-21 20:27:33 +0000
2019-05-30 18:27:41.459 INFO  org.glowroot - Java version: 1.7.0_51 (Oracle Corporation / Linux)
2019-05-30 18:27:41.459 INFO  org.glowroot - Java args: -javaagent:/appl/nettuno/glowroot/glowroot.jar -Xms2048m -Xmx5120m
2019-05-30 18:28:03.290 INFO  org.glowroot - Glowroot version: 0.13.4, built 2019-04-21 20:27:33 +0000
2019-05-30 18:28:03.292 INFO  org.glowroot - Java version: 1.7.0_79 (Oracle Corporation / Linux)
2019-05-30 18:28:03.292 INFO  org.glowroot - Java args: -XX:+UseCompressedOops -XX:+TieredCompilation -javaagent:/appl/nettuno/glowroot/glowro
ot.jar -Xms2048m -Xmx5120m -XX:MaxPermSize=1024m
2019-05-30 18:28:06.687 INFO  org.glowroot - UI listening on 172.31.250.243:4000
2019-05-30 18:28:12.434 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving it/eng/municipia/prodotti/bingest/ejb/EjbBingest$$$view2: 16
1
java.lang.ArrayIndexOutOfBoundsException: 161
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3451)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3431)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3412)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:559)
        at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:183)
        at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:148)
        at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
        at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.classfilewriter.ClassFile.define(ClassFile.java:275)
        at org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:164)
        at org.jboss.invocation.proxy.AbstractProxyFactory.getCachedMethods(AbstractProxyFactory.java:145)
        at org.jboss.as.ejb3.component.stateless.StatelessComponentDescription$3.configure(StatelessComponentDescription.java:138)
        at org.jboss.as.ee.component.ComponentDescription$DefaultComponentConfigurator.configure(ComponentDescription.java:921)
        at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2019-05-30 18:28:16.103 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving it/eng/tributi/prodotti/nettuno/services/tares/f24/EJBF24RequestManager$$$view61: null
java.lang.ArrayIndexOutOfBoundsException: null
2019-05-30 18:28:16.657 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving it/eng/tributi/prodotti/nettuno/services/tares/f24/EJBF24RequestManager$$$view108: null
java.lang.ArrayIndexOutOfBoundsException: null
```

I can't figure out what's wrong: any idea or hint?

Thanks in advance,
Daniele

**Comment by trask** [comment]
Hi @danzone, thanks for reporting this! Can you post or send me `it/eng/municipia/prodotti/bingest/ejb/EjbBingest$$$view2.class`? (trask.stalnaker@gmail.com)

**Comment by danzone** [comment]
Hi @trask ! Sorry for responding so late, I have to ask to my colleagues. I will be back to you soon

**Comment by trask** [comment]
Closing, but please re-open if you are still having any issue. Thanks.
