### ISSUE TITLE
Pointcut subTypeRestriction not working?

### ISSUE THREAD

**Issue by Arnaud-Nauwynck** [glowroot/glowroot#605]
Hi,

First of all, thanks for your excellent work.

I am writing an aspect for counting separatly methods calls on a instances of a class and on its subclass, so I am trying using Pointcut subTypeRestriction.
It seems to have no effect, maybe I don't understand how to use it.

In real life, I need to study keep-alive connection on Socket and SSLServerSocket, but to reproduce it simply, I provided here a sample project with 2 classes "A" and "B extends A".

```
class A { 
  public void open() {..}   public void close() { .. }
}
class B extends A {
  public void open() {..}   public void close() { .. }
}    
```

My instrumenting plugin is as follow:
```
public class InheritsTestGlowrootAspect {

    static int aOpenCount = 0;
    static int bOpenCount = 0;

    /**
     * Instrument calls to <code>fr.an.test.glowroot.A.open()</code>
     */
    @Pointcut(className = "fr.an.test.glowroot.A", methodName = "open", methodParameterTypes = {},
	    subTypeRestriction = "fr.an.test.glowroot.A")
    public static class Aopen_Pointcut {

	@OnBefore
	public static void onBefore() {
	    aOpenCount++;
	    logCall("A.open() .. count current opened A:" + aOpenCount);
	}

    }
    
    /**
     * Instrument calls to <code>fr.an.test.glowroot.A.close()</code>
     */
    @Pointcut(className = "fr.an.test.glowroot.A", methodName = "close", methodParameterTypes = {},
	    subTypeRestriction = "fr.an.test.glowroot.A")
    public static class Aclose_Pointcut {

	@OnBefore
	public static void onBefore() {
	    aOpenCount--;
	    logCall("A.close() .. count current opened A:" + aOpenCount);
	}

    }


    /**
     * Instrument calls to <code>fr.an.test.glowroot.B.open()</code>
     */
    @Pointcut(className = "fr.an.test.glowroot.B", methodName = "open", methodParameterTypes = {},
	    subTypeRestriction = "fr.an.test.glowroot.B")
    public static class Bopen_Pointcut {

	@OnBefore
	public static void onBefore() {
	    bOpenCount++;
	    logCall("B.open() .. count current opened B:" + bOpenCount);
	}

    }
    
    /**
     * Instrument calls to <code>fr.an.test.glowroot.B.close()</code>
     */
    @Pointcut(className = "fr.an.test.glowroot.B", methodName = "close", methodParameterTypes = {},
	    subTypeRestriction = "fr.an.test.glowroot.B")
    public static class Bclose_Pointcut {

	@OnBefore
	public static void onBefore() {
	    bOpenCount--;
	    logCall("B.close() .. count current opened B:" + bOpenCount);
	}

    }

    private static void logCall(String msg) {
	System.out.println(msg);
	System.out.println("at ");
	new Exception().printStackTrace(System.out);
	System.out.println();
    }
```

The main code to test is
```
B b = new B();
b.open();
b.close()
```
It should not call aspects on A because on subTypeRestriction ... but it does, as you can see in logs:

```
A.open() .. count current opened A:1
at
java.lang.Exception
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.logCall(InheritsTestGlowrootAspect.java:75)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.access$000(InheritsTestGlowrootAspect.java:6)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect$Aopen_Pointcut.onBefore(InheritsTestGlowrootAspect.java:21)
        at fr.an.test.glowroot.B.open(B.java)
        at fr.an.test.glowroot.Main.main(Main.java:13)

B.open() .. count current opened B:1
at
java.lang.Exception
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.logCall(InheritsTestGlowrootAspect.java:75)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.access$000(InheritsTestGlowrootAspect.java:6)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect$Bopen_Pointcut.onBefore(InheritsTestGlowrootAspect.java:52)
        at fr.an.test.glowroot.B.open(B.java)
        at fr.an.test.glowroot.Main.main(Main.java:13)

B.open()
A.close() .. count current opened A:0
at
java.lang.Exception
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.logCall(InheritsTestGlowrootAspect.java:75)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.access$000(InheritsTestGlowrootAspect.java:6)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect$Aclose_Pointcut.onBefore(InheritsTestGlowrootAspect.java:36)
        at fr.an.test.glowroot.B.close(B.java)
        at fr.an.test.glowroot.Main.main(Main.java:14)

B.close() .. count current opened B:0
at
java.lang.Exception
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.logCall(InheritsTestGlowrootAspect.java:75)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect.access$000(InheritsTestGlowrootAspect.java:6)
        at fr.an.test.glowroot.InheritsTestGlowrootAspect$Bclose_Pointcut.onBefore(InheritsTestGlowrootAspect.java:67)
        at fr.an.test.glowroot.B.close(B.java)
        at fr.an.test.glowroot.Main.main(Main.java:14)
```

Is it a bug or something I don't understand?
How to have an aspect that applies only to a class with subTypeRestriction ?

I have put the full sample source code as attachment
I run it with 
1/ mvn install 
2/ cd test-glowroot-inherits-test + unzip the glowroot distribution
3/ execute run-test.sh

Thanks in advance

[test-glowroot-inherits.zip](https://github.com/glowroot/glowroot/files/3343013/test-glowroot-inherits.zip)

**Comment by trask** [comment]
Hi @Arnaud-Nauwynck, thanks for posting!

`subTypeRestriction` applies to that type and all subtypes.

For example, it is used [here](https://github.com/glowroot/glowroot/blob/v0.13.4/agent/plugins/http-client-plugin/src/main/java/org/glowroot/agent/plugin/httpclient/AsyncHttpClientAspect1x.java#L147-L149) to apply to `Future.get()` but only applies under the Future subtype `ListenableFuture`.

The problem is that there is no method `get` on the `ListenableFuture` interface (it is inherited from `Future`).  Otherwise the above pointcut could be put directly onto `ListenableFuture.get()`.

So in your case, `subTypeRestriction` is not going to do anything.

The problem for your use case is that when pointcuts apply to a method, they are always applied to overrides of that method.

So instead, you'll want to pass in `@BindReceiver` to your `@OnBefore` and check `instanceof`. Or you could pass in `@BindClassMeta` to your `@OnBefore`.
