### ISSUE TITLE
Warning initializing weblogic server with glowroot

### ISSUE THREAD

**Issue by cjover** [glowroot/glowroot#625]
Hi,
I'm triying to run a weblogic server in a centos with glowroot-0.13.5-dist but when I initialize de server  and invoke http;//localhost:4000, IE shows a "Cant't access thisi page" error message.

I've modified the setDomainEnv.sh file with this line:
JAVA_OPTIONS="${JAVA_OPTIONS} -javaagent:/***/****/****/*****/*****/glowroot/glowroot.jar -Dglowroot.debug.mainClass=true

The log shows following trace:

2019-08-22 08:54:47.870 INFO  org.glowroot - Glowroot version: 0.13.5, built 2019-07-23 01:30:08 +0000
2019-08-22 08:54:47.902 INFO  org.glowroot - Java version: 1.6.0_14 (BEA Systems, Inc. / Linux)
2019-08-22 08:54:47.905 INFO  org.glowroot - Java args: -Xms512m -Xmx512m -Xverify:none -da -javaagent:/****/****/****/****/****/****/****/****/****/glowroot.jar
2019-08-22 08:54:50.263 WARN  org.glowroot - one or more important classes were loaded before Glowroot instrumentation could be applied to            them: java.net.HttpURLConnection
2019-08-22 08:54:50.351 INFO  o.g.agent.impl.BytecodeServiceImpl - entering weblogic.Server.main()
java.lang.Exception: location stack trace
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:252)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
        at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
        at weblogic.Server.main(Server.java:54)
2019-08-22 08:54:51.869 WARN  o.g.a.s.c.google.protobuf.UnsafeUtil - platform method missing - proto runtime falling back to safer methods:            java.lang.NoSuchMethodException: sun.misc.Unsafe.copyMemory(java.lang.Object, long, java.lang.Object, long, long)
2019-08-22 08:54:52.464 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address            to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)

Thanks in advance!

**Comment by Never-lab** [comment]
WebLogic init warning with Glowroot — usually classloader/MBean noise; attach full warning text if still on 0.14.x. Likely support/stale.

@nowheresly — close stale / support.
