### ISSUE TITLE
stackoverflow

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#644]
Hi,

Context : 
OpenJDK8
Wildfly8 

we have a stackoverflow error, on a functionnality :

Caused by: java.lang.StackOverflowError
        at org.glowroot.agent.shaded.com.google.common.base.Throwables.getRootCause(Throwables.java:253) [glowroot.jar:0.13.5]
        at org.glowroot.agent.shaded.org.glowroot.common.util.Throwables.getBestMessage(Throwables.java:31) [glowroot.jar:0.13.5]
        at org.glowroot.agent.model.ErrorMessage.create(ErrorMessage.java:56) [glowroot.jar:0.13.5]
        at org.glowroot.agent.impl.ThreadContextImpl$DummyTraceEntryOrQuery.endWithErrorInternal(ThreadContextImpl.java:1168) [glowroot.jar:0.13.5]
        at org.glowroot.agent.impl.ThreadContextImpl$DummyTraceEntryOrQuery.endWithError(ThreadContextImpl.java:1142) [glowroot.jar:0.13.5]
        at org.glowroot.agent.weaving.GeneratedAdvice53.onThrow(Unknown Source) [config-pointcuts.jar:0.13.5]

I can provide full log in private.

Thanks

**Comment by lfen21** [comment]
up, we cannot use the last version of glowroot, and we others bug in the older one.

**Comment by lfen21** [comment]
@trask  will try, to debug it and propose a contribution

**Comment by Never-lab** [comment]
StackOverflowError with Glowroot — need stack + version; often app recursion or weave edge. Retest 0.14.x or close stale.

@nowheresly — needs-info / close stale.
