### ISSUE TITLE
Glowroot with karaf  

### ISSUE THREAD

**Issue by Thereactor20** [glowroot/glowroot#648]
when i use glowroot to monitor karaf container i got  this message :

modify the container\bin\setenv 

add the line :
 
SET KARAF_OPTS=-javaagent:"C:\Talend\TOS_ESB-20190620_1446-V7.2.1\Runtime_ESBSE\container\glowroot\glowroot.jar" 

trun.bat: Ignoring predefined value for KARAF_HOME
2019-10-08 10:13:08.776 INFO  org.glowroot - Glowroot version: 0.13.5, built 2019-07-23 01:30:08 +0000
2019-10-08 10:13:08.779 INFO  org.glowroot - Java version: 1.8.0_221 (Oracle Corporation / Windows 10)
2019-10-08 10:13:08.780 INFO  org.glowroot - Java args: -Xms128M -Xmx512M -XX:+UnlockDiagnosticVMOptions -XX:+UnsyncloadClass -javaagent:C:\Talend\TOS_ESB-20190620_1446-V7.2.1\Runtime_ESBSE\container\glowroot\glowroot.jar
2019-10-08 10:13:12.533 INFO  org.glowroot - agent id: Karafwind
2019-10-08 10:13:14.726 INFO  org.glowroot - connected to the central collector http://localhost:8181, version 0.13.5, built 2019-07-23 01:30:08 +0000
2019-10-08 10:13:18.005 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method org.eclipse.jetty.server.handler.ScopedHandler.handle(java.lang.String, org.eclipse.jetty.server.Request, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse) which is being used by a subclass org.ops4j.pax.web.service.jetty.internal.HttpServiceContext to implement one or more instrumented interfaces
2019-10-08 10:13:19.554 INFO  o.g.agent.weaving.ClassAnalyzer - Not able to override and instrument final method org.eclipse.jetty.server.handler.ScopedHandler.handle(java.lang.String, org.eclipse.jetty.server.Request, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse) which is being used by a subclass org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler to implement one or more instrumented interfaces

the problem that the glowroot stop the access to the karaf  console please can you  give us the way to  the configuration of  glowroot with karaf without impacting it  

http://localhost:8040/system/console/bundles

thanks very much for the nicest apm

**Comment by paul-mcculloch** [comment]
I think this is related to https://github.com/glowroot/glowroot/pull/859 . I saw the same behaviour as reported in Karaf 4.1.1 with Glowroot 0.13.6 along with a CNF error when attempting to access any servlet

java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceAdvice.onBeforeCommon(ServletAspect.java:130) ~[?:?]
	at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceAdvice.access$000(ServletAspect.java:64) ~[?:?]
	at org.glowroot.agent.plugin.servlet.ServletAspect$JettyHandlerAdvice.onBefore(ServletAspect.java:255) ~[?:?]

In 14.0-beta2 I still get the INFO message reported, but the CNF no longer occurs, and the web console works

**Comment by Thereactor20** [comment]
Hello Thanks Paul for your answer i didn't give it a try i forgot the subject i have been a while i will try it ASAP  and i will give you a review thanks

**Comment by Never-lab** [comment]
Karaf + Glowroot — OSGi weaving/classloader sharp edges (#1148 / PR #1147). Keep related; try current 0.14.x.

@nowheresly — keep with #1148 or close support if only noise.
