### ISSUE TITLE
Error not shwoing for JBOSS application connected to JMS AMQ

### ISSUE THREAD

**Issue by NiksTheLearner** [glowroot/glowroot#670]
Error not shwoing for JBOSS application connected to JMS AMQ. The error comes when the startup is occurring for the server and the code wie it tries to connect with JMS AMQ

[Server:] [0m[31m05:32:53,001 ERROR [stderr] (ServerService Thread Pool -- 80) javax.jms.JMSSecurityException: User  is not authorized to create: topic://ActiveMQ.Producer[0m
[Server:] [31m[0m[31m05:32:53,001 ERROR [stderr] (ServerService Thread Pool -- 80) 	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:52)[0m
[Server:] [31m[0m[31m05:32:53,001 ERROR [stderr] (ServerService Thread Pool -- 80) 	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1399)[0m
[Server:] [31m[0m[31m05:32:53,002 ERROR [stderr] (ServerService Thread Pool -- 80) 	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1428)[0m

Kindly help what needs to be done to capture this error.

**Comment by Never-lab** [comment]
JMS/AMQ errors not on Errors tab — Errors need traced txn + error mark (logger plugin / uncaught), same as #887. Support.

@nowheresly — please close as support.
