### ISSUE TITLE
Weblogic Application Failing to start with Agent 13.3

### ISSUE THREAD

**Issue by pacific28** [glowroot/glowroot#683]
Hi @trask 
I have been trying to deploy the agent(13.3) on a WebLogic server but the application fails to start with the following error. 
`<Jan 30, 2020 4:06:54,589 PM JST> <Error> <Deployer> <BEA-149205> <Failed to initialize the application  due to error weblogic.application.ModuleException: java.lang.ClassCastException: weblogic.jdbc.wrapper.ResultSet_oracle_jdbc_driver_ForwardOnlyResultSet cannot be cast to com.netcracker.framework.jdbc.RSProxy
weblogic.application.ModuleException: java.lang.ClassCastException: weblogic.jdbc.wrapper.ResultSet_oracle_jdbc_driver_ForwardOnlyResultSet cannot be cast to com.netcracker.framework.jdbc.RSProxy
at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:192)
at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:187)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassCastException: weblogic.jdbc.wrapper.ResultSet_oracle_jdbc_driver_ForwardOnlyResultSet cannot be cast to com.netcracker.framework.jdbc.RSProxy
at com.netcracker.framework.jdbc.RSProxy$$EnhancerByCGLIB$$3fe32af3.glowroot$getStatementMirror(<generated>)
at org.glowroot.agent.plugin.jdbc.ResultSetAspect.isEnabledCommon(ResultSetAspect.java:165)
at org.glowroot.agent.plugin.jdbc.ResultSetAspect.access$100(ResultSetAspect.java:36)
at org.glowroot.agent.plugin.jdbc.ResultSetAspect$NextAdvice.isEnabled(ResultSetAspect.java:53)
at com.netcracker.framework.jdbc.RSProxy.next(RSProxy.java)
Truncated. see log file for complete stacktrace`

**Comment by Never-lab** [comment]
WebLogic fail start with agent 0.13.3 — retest [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7); old line. Support/stale.

@nowheresly — please close as support/stale.
