### ISSUE TITLE
IllegalStateException when trying to save instrumentation

### ISSUE THREAD

**Issue by hapeka72** [glowroot/glowroot#684]
First let me say that I am very impressed by glowroot - it is easy to use but still powerful.
Now my problem: I try to use the central collector, with cassandra running in a docker container.
I started my application with the agent, it connects to the collector and shows up in the UI. But when I configure an instrumentation with the UI and try to save it, the collector reports an exception:

java.lang.IllegalStateException: Instrumentation config not found: 8056c0f3a06c311df6b05f44cef3ce3e8592928c
        at org.glowroot.central.repo.ConfigRepositoryImpl.getInstrumentationConfig(ConfigRepositoryImpl.java:288)
        at org.glowroot.ui.InstrumentationConfigJsonService.getInstrumentationConfigInternal(InstrumentationConfigJsonService.java:231)
        at org.glowroot.ui.InstrumentationConfigJsonService.addInstrumentationConfig(InstrumentationConfigJsonService.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:585)
        at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:324)
        at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:235)
        at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:159)
        at org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
...

If I put the instrumentation in the config.json it is uploaded to the collector and works. It also works to configure the instrumentation in the UI if I don't use the central collector.
I am currently running the collector and my application under test on Windows, only Cassandra runs in a docker container.

**Comment by Never-lab** [comment]
IllegalStateException saving Instrumentation — needs stack + version; try 0.14.7. Keep needs-info or close stale.

@nowheresly — needs-info / close stale.
