### ISSUE TITLE
No NameResolverProviders found issue when connecting to central collector PR#690

### ISSUE THREAD

**Issue by sjmittal** [glowroot/glowroot#691]
I had found an issue when connecting to a central collector, which is more aptly described under following issue:
https://github.com/grpc/grpc-java/issues/2149

I have created a PR to fix this: https://github.com/glowroot/glowroot/pull/690
Please merge.

**Comment by trask** [comment]
Hi @sjmittal, are you getting the same error as posted in that issue? e.g.

```
java.lang.IllegalStateException: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using
ProGuard, check your configuration
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at io.grpc.NameResolverProvider$NameResolverFactory.checkForProviders(NameResolverProvider.java:200)
    at io.grpc.NameResolverProvider$NameResolverFactory.getDefaultScheme(NameResolverProvider.java:195)
    at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:384)
    at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:316)
    at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:251)
```

**Comment by sjmittal** [comment]
@trask I was getting similar error and adding `DnsNameResolverProvider` fixed the issue at my end.
So I feel this can be applied as a fix. I am not sure if anyone else has faced similar issue when connecting to a central collector.

**Comment by Never-lab** [comment]
﻿PR #690 is still **open / unmerged**. Symptom matches gRPC shaded/ServiceLoader ``No NameResolverProviders found`` when the agent connects to Central ([grpc-java#2149](https://github.com/grpc/grpc-java/issues/2149)); registering ``DnsNameResolverProvider`` was the reporter’s fix.

Current agent shading already **excludes** ``META-INF/services/io.grpc.NameResolverProvider`` in places (see ``agent/shaded/core``) to avoid duplicate-service merge issues — so the failure mode may depend on build/classpath. If this still reproduces on a current **0.14.x** dist connecting to Central, please comment with agent+central versions and full stack; otherwise OK to close as stale and leave #690 for maintainers.

@nowheresly
