### ISSUE TITLE
collector address with underscore raise exception

### ISSUE THREAD

**Issue by devnewton** [glowroot/glowroot#696]
An exception is raised when collector.address value in glowroot.properties agent configuration file refer to a domain with underscores like this:

`collector.address=http://my_machine.myzone.com:8181`

Exception:

` java.lang.IllegalArgumentException: Invalid host or port: my_machine.myzone.com 818
 at org.glowroot.agent.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:480)
 at org.glowroot.agent.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:115)
 at org.glowroot.agent.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:101)
 at org.glowroot.agent.central.CentralConnection.<init>(CentralConnection.java:95)
 at org.glowroot.agent.central.CentralCollector.<init>(CentralCollector.java:135)
 at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:136)
 at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:255)
 at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
 at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
 at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java)
 Caused by: java.net.URISyntaxException: Illegal character in hostname at index ...: //my_machine.myzone.com
 at java.base/java.net.URI$Parser.fail(URI.java:2913)
 at java.base/java.net.URI$Parser.parseHostname(URI.java:3448)
 at java.base/java.net.URI$Parser.parseServer(URI.java:3297)
 at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216)
 at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
 at java.base/java.net.URI$Parser.parse(URI.java:3125)
 at java.base/java.net.URI.<init>(URI.java:685)
 at org.glowroot.agent.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:478)
 ... 9 common frames omitted`

**Comment by devnewton** [comment]
I have downloaded the glowroot-0.13.6-dist.zip release.

Here is my configuration file:
[glowroot.zip](https://github.com/glowroot/glowroot/files/4297122/glowroot.zip)

**Comment by trask** [comment]
Hi @devnewton, check out the explanation in https://github.com/grpc/grpc-java/issues/3701

**Comment by Never-lab** [comment]
﻿Already answered by @trask: this is a **gRPC / URI hostname** rule, not a Glowroot-specific bug. Underscores are not valid in hostnames for ``java.net.URI`` / gRPC authority parsing (see [grpc-java#3701](https://github.com/grpc/grpc-java/issues/3701)).

Workaround: use a DNS name **without** underscores, an IP, or a CNAME/alias that is a valid hostname. ``collector.address=http://my_machine…`` will keep failing the same way on current agents.

OK to close as support / wontfix-upstream.

@nowheresly
