### ISSUE TITLE
Infinispan: No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey

### ISSUE THREAD

**Issue by bmhm** [glowroot/glowroot#698]
Hi,

I recently updated from 0.13.0 to 0.13.6.
Now my central collector log gets spammed with such messages:

```
[3/17/20 13:11:37:333 CET] 00000152 SystemOut                                                    O 2020-03-17 13:11:37.332 WARN  o.g.central.CollectorServiceImpl - agentname.here - 2020-03-17 13:11:37.329 WARN org.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 10 warnings were suppressed since it was last logged)
[3/17/20 13:11:34:191 CET] 00000152 SystemOut                                                    O 2020-03-17 13:11:34.191 ERROR o.g.central.CollectorServiceImpl - agent-name.here - No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey
org.infinispan.commons.marshall.MarshallingException: No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToBuffer(PersistenceMarshallerImpl.java:164)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:137)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:145)
        at org.infinispan.marshall.core.GlobalMarshaller.writeRawUnknown(GlobalMarshaller.java:638)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:627)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:618)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:384)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:352)
        at org.infinispan.marshall.core.BytesObjectOutput.writeObject(BytesObjectOutput.java:26)
        at org.infinispan.commons.marshall.MarshallUtil.marshallMap(MarshallUtil.java:62)
        at org.infinispan.commands.write.PutMapCommand.writeTo(PutMapCommand.java:111)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.writeCommandParameters(ReplicableCommandExternalizer.java:70)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.writeObject(ReplicableCommandExternalizer.java:66)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.writeObject(ReplicableCommandExternalizer.java:54)
        at org.infinispan.marshall.core.GlobalMarshaller.writeInternal(GlobalMarshaller.java:656)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:371)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:352)
        at org.infinispan.marshall.core.BytesObjectOutput.writeObject(BytesObjectOutput.java:26)
        at org.infinispan.commands.remote.SingleRpcCommand.writeTo(SingleRpcCommand.java:52)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.writeCommandParameters(ReplicableCommandExternalizer.java:70)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.marshallParameters(CacheRpcCommandExternalizer.java:122)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.writeObject(CacheRpcCommandExternalizer.java:118)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.writeObject(CacheRpcCommandExternalizer.java:69)
        at org.infinispan.marshall.core.GlobalMarshaller.writeInternal(GlobalMarshaller.java:656)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:371)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:352)
        at org.infinispan.marshall.core.GlobalMarshaller.writeObjectOutput(GlobalMarshaller.java:181)
        at org.infinispan.marshall.core.GlobalMarshaller.writeObjectOutput(GlobalMarshaller.java:174)
        at org.infinispan.marshall.core.GlobalMarshaller.objectToBuffer(GlobalMarshaller.java:302)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.marshallRequest(JGroupsTransport.java:1051)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.sendCommand(JGroupsTransport.java:1039)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.sendTo(JGroupsTransport.java:265)
        at org.infinispan.remoting.rpc.RpcManagerImpl.sendTo(RpcManagerImpl.java:383)
        at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.lambda$createLocalInvocationHandler$8(NonTxDistributionInterceptor.java:459)
        at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor$$Lambda$599.00000000D4042320.accept(Unknown Source)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:168)
        at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.handleLocalSegmentsForReadWriteManyCommand(NonTxDistributionInterceptor.java:352)
        at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.handleReadWriteManyCommand(NonTxDistributionInterceptor.java:299)
        at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.visitPutMapCommand(NonTxDistributionInterceptor.java:146)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:59)
        at org.infinispan.interceptors.BaseAsyncInterceptor.asyncInvokeNext(BaseAsyncInterceptor.java:232)
        at org.infinispan.interceptors.impl.EntryWrappingInterceptor.setSkipRemoteGetsAndInvokeNextForManyEntriesCommand(EntryWrappingInterceptor.java:695)
        at org.infinispan.interceptors.impl.EntryWrappingInterceptor.visitPutMapCommand(EntryWrappingInterceptor.java:434)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:155)
        at org.infinispan.interceptors.locking.AbstractLockingInterceptor.lambda$nonTxLockAndInvokeNext$3(AbstractLockingInterceptor.java:308)
        at org.infinispan.interceptors.locking.AbstractLockingInterceptor$$Lambda$554.00000000656C22C0.apply(Unknown Source)
        at org.infinispan.interceptors.SyncInvocationStage.andHandle(SyncInvocationStage.java:69)
        at org.infinispan.interceptors.locking.AbstractLockingInterceptor.nonTxLockAndInvokeNext(AbstractLockingInterceptor.java:303)
        at org.infinispan.interceptors.locking.NonTransactionalLockingInterceptor.handleWriteManyCommand(NonTransactionalLockingInterceptor.java:65)
        at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitPutMapCommand(AbstractLockingInterceptor.java:182)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndHandle(BaseAsyncInterceptor.java:188)
        at org.infinispan.statetransfer.StateTransferInterceptor.handleNonTxWriteCommand(StateTransferInterceptor.java:307)
        at org.infinispan.statetransfer.StateTransferInterceptor.handleWriteCommand(StateTransferInterceptor.java:251)
        at org.infinispan.statetransfer.StateTransferInterceptor.visitPutMapCommand(StateTransferInterceptor.java:102)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:155)
        at org.infinispan.interceptors.impl.CacheMgmtInterceptor.visitPutMapCommand(CacheMgmtInterceptor.java:196)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:59)
        at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:53)
        at org.infinispan.interceptors.DDAsyncInterceptor.visitPutMapCommand(DDAsyncInterceptor.java:89)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndExceptionally(BaseAsyncInterceptor.java:128)
        at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:90)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:61)
        at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:53)
        at org.infinispan.interceptors.DDAsyncInterceptor.visitPutMapCommand(DDAsyncInterceptor.java:89)
        at org.infinispan.commands.write.PutMapCommand.acceptVisitor(PutMapCommand.java:68)
        at org.infinispan.interceptors.DDAsyncInterceptor.visitCommand(DDAsyncInterceptor.java:49)
        at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:244)
        at org.infinispan.cache.impl.CacheImpl.executeCommandAndCommitIfNeeded(CacheImpl.java:1829)
        at org.infinispan.cache.impl.CacheImpl.putAll(CacheImpl.java:1412)
        at org.infinispan.cache.impl.CacheImpl.putAll(CacheImpl.java:1958)
        at org.infinispan.cache.impl.CacheImpl.putAll(CacheImpl.java:465)
        at org.infinispan.cache.impl.AbstractDelegatingCache.putAll(AbstractDelegatingCache.java:460)
        at org.infinispan.cache.impl.AbstractDelegatingCache.putAll(AbstractDelegatingCache.java:460)
        at org.infinispan.cache.impl.AbstractDelegatingCache.putAll(AbstractDelegatingCache.java:460)
        at org.infinispan.cache.impl.EncoderCache.putAll(EncoderCache.java:689)
        at org.glowroot.central.repo.GaugeValueDaoImpl.store(GaugeValueDaoImpl.java:268)
        at org.glowroot.central.repo.GaugeValueDaoImpl.store(GaugeValueDaoImpl.java:191)
        at org.glowroot.central.CollectorServiceImpl.collectGaugeValuesUnderThrottle(CollectorServiceImpl.java:378)
        at org.glowroot.central.CollectorServiceImpl.access$300(CollectorServiceImpl.java:84)
        at org.glowroot.central.CollectorServiceImpl$3.run(CollectorServiceImpl.java:281)
        at org.glowroot.central.CollectorServiceImpl.throttle(CollectorServiceImpl.java:316)
        at org.glowroot.central.CollectorServiceImpl.throttledCollectGaugeValues(CollectorServiceImpl.java:277)
        at org.glowroot.central.CollectorServiceImpl.collectGaugeValues(CollectorServiceImpl.java:209)
        at org.glowroot.wire.api.model.CollectorServiceGrpc$MethodHandlers.invoke(CollectorServiceGrpc.java:631)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by bmhm** [comment]
I get many similar messages:

```
[3/17/20 13:11:34:190 CET] 00000152 SystemOut                                                    O 2020-03-17 13:11:34.190 ERROR o.i.i.i.InvocationContextInterceptor - ISPN000136: Error executing command PutMapCommand on Cache 'gaugeNeedsRollupCache1', writing keys [NeedsRollupKey{agentRollupId=agent-name.here, captureTime=1584447060000}]
org.infinispan.commons.marshall.MarshallingException: No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToBuffer(PersistenceMarshallerImpl.java:164)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:137)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:145)
        at org.infinispan.marshall.core.GlobalMarshaller.writeRawUnknown(GlobalMarshaller.java:638)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:627)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:618)
```

and

```
[3/17/20 13:11:34:189 CET] 00000152 SystemOut                                                    O 2020-03-17 13:11:34.188 ERROR org.infinispan.CLUSTER - ISPN000073: Unexpected error while replicating
org.infinispan.commons.marshall.MarshallingException: No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToBuffer(PersistenceMarshallerImpl.java:164)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:137)
        at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:145)
```

```
[3/17/20 13:11:34:187 CET] 00000152 SystemOut                                                    O 2020-03-17 13:11:34.186 WARN  org.infinispan.PERSISTENCE - ISPN000559: Cannot marshall 'class org.glowroot.central.repo.ImmutableNeedsRollupKey'
java.lang.IllegalArgumentException: No marshaller registered for Java type org.glowroot.central.repo.ImmutableNeedsRollupKey
        at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:279)
        at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:240)
        at org.infinispan.protostream.ProtobufUtil.toWrappedStream(ProtobufUtil.java:196)
```

**Comment by bmhm** [comment]
To make it complete, here is the `system.log` from any cassandra instance:

```
WARN  [ReadStage-8] 2020-03-17 13:26:10,543 ReadCommand.java:569 - Read 5 live rows and 1763 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-14] 2020-03-17 13:26:10,630 ReadCommand.java:569 - Read 0 live rows and 1735 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-5] 2020-03-17 13:26:10,651 ReadCommand.java:569 - Read 0 live rows and 1742 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.3 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-3] 2020-03-17 13:26:10,657 ReadCommand.java:569 - Read 10 live rows and 1785 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.4 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-3] 2020-03-17 13:26:10,667 ReadCommand.java:569 - Read 10 live rows and 1785 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.4 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-14] 2020-03-17 13:26:10,682 ReadCommand.java:569 - Read 0 live rows and 1758 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.5 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-4] 2020-03-17 13:26:10,864 ReadCommand.java:569 - Read 0 live rows and 1758 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.5 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-10] 2020-03-17 13:26:10,933 ReadCommand.java:569 - Read 0 live rows and 1768 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-4] 2020-03-17 13:26:10,964 ReadCommand.java:569 - Read 0 live rows and 1707 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.6 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2020-03-17 13:26:11,012 ReadCommand.java:569 - Read 0 live rows and 1758 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_1 WHERE agent_rollup = agent-name.1 LIMIT 5000 (see tombstone_warn_threshold)

```

**Comment by ReillyProcentive** [comment]
We encountered this issue too. As far as I can tell it's because Infinispan was updated in 768b5d12217bb5bde86bbd0271d194745f532afa from 9.4.x to 10.1.x and there was a breaking change in that the marshaller for classes now needs to be directly specified. 

@bmhm To fix this you can do the following:
* Use 0.13.5 instead
* Disable clustered central
* Clone the Glowroot repo locally and then in `central/pom.xml` change the version of `jgroups` to `4.0.21.Final` and `infinspan-core` to `9.4.16.Final`. <-- We did this and it seems to be working so far.
