### ISSUE TITLE
Amazon Managed Cassandra Service support

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#700]
As it is, glowroot can't create all cassandra tables. After manually creating "glowroot" keyspace the following error appears:
`2020-03-29 16:15:41.583 ERROR org.glowroot - unconfigured table glowroot.schema_version
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table glowroot.schema_version
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at org.glowroot.central.util.Session.prepare(Session.java:121)
	at org.glowroot.central.repo.SchemaUpgrade.<init>(SchemaUpgrade.java:129)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:189)
	at org.glowroot.central.CentralModule.create(CentralModule.java:137)
	at org.glowroot.central.CentralModule.create(CentralModule.java:132)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)`

**Comment by ionutursuleanu** [comment]
This needs more work that I initially thought. After modifying the schema update code to wait for table creation I ran into a new issue: 
`Query invalid
TTL is not yet supported.`

**Comment by ionutursuleanu** [comment]
Closing for now. Will reopen if AWS adds TTL functionality

**Comment by ionutursuleanu** [comment]
Hi @toshyak ,

> would it be enough for glowroot to support it?

Unfortunately isn't enough. `Apache Cassandra` creates tables synchronously, but `Amazon Keyspaces` works asynchronously. This means that glowroot schema initialization needs some changes in order to check if tables where created before trying to insert some data. https://docs.aws.amazon.com/keyspaces/latest/devguide/working-with-tables.html#tables-create

I will try again to make it work. Thanks for the update on TTL support

**Comment by ionutursuleanu** [comment]
Hi @toshyak ,

Waiting for table creation(8796eadd40ef35a9a763f6aa1f0ae671b22fd820) it's not enough. `count(*)` it's not supported by amazon keyspaces at this moment and considering it's usage in glowroot this is a blocking issue. 
```
2021-12-04 18:27:51.998 INFO  org.glowroot - Glowroot version: 0.13.6, built 2021-12-04 15:55:52 +0000
2021-12-04 18:27:52.004 INFO  org.glowroot - Java version: 11.0.13
2021-12-04 18:27:52.537 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2021-12-04 18:27:52.564 INFO  com.datastax.driver.core - DataStax Java driver 3.7.2 for Apache Cassandra
2021-12-04 18:27:52.572 INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
2021-12-04 18:27:53.092 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2021-12-04 18:27:54.433 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'eu-central-1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2021-12-04 18:27:54.435 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.184:9142 added
2021-12-04 18:27:54.436 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.183:9142 added
2021-12-04 18:27:54.436 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.182:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.180:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host cassandra.eu-central-1.amazonaws.com/3.127.48.178:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.191:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.188:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.187:9142 added
2021-12-04 18:27:54.437 INFO  com.datastax.driver.core.Cluster - New Cassandra host /3.127.48.186:9142 added
2021-12-04 18:27:55.069 INFO  org.glowroot - connected to Cassandra (version 3.11.2), using keyspace 'glowroot' (replication factor unknown) and consistency level LOCAL_QUORUM
2021-12-04 18:27:55.545 ERROR org.glowroot - countRows is not yet supported.
com.datastax.driver.core.exceptions.InvalidQueryException: countRows is not yet supported.
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:440)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:350)
	at org.glowroot.central.util.Session.createTableWithTracking(Session.java:365)
	at org.glowroot.central.util.Session.createTableWithLCS(Session.java:338)
	at org.glowroot.central.util.Session.createTableWithLCS(Session.java:332)
	at org.glowroot.central.repo.SchemaUpgrade.<init>(SchemaUpgrade.java:126)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:189)
	at org.glowroot.central.CentralModule.create(CentralModule.java:137)
	at org.glowroot.central.CentralModule.create(CentralModule.java:132)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
```

**Comment by rweintraub-cycleon** [comment]
Hey @ionutursuleanu,
thanks for investigating this topic. I've looked into this a bit and found that AWS didn't implement it due to scalability reasons. I'm not sure if these apply for glowroot as well. However, given that [this thread on AWS Forums](https://forums.aws.amazon.com/thread.jspa?messageID=949855) is still unanswered after 1 year it seems unlikely to me that the `COUNT(*)` operation will be implemented soon.

Depending on how big the tables are that are being counted this could maybe be implemented with a `SELECT (*)`? However, this would come with the downside that this will cause a lot of RCU which could end up quite costly for such a simple operation.
Otherwise, it might be also possible to implement this with an extra table that keeps track of the count for the relevant tables?

**Comment by ionutursuleanu** [comment]
> Depending on how big the tables are that are being counted this could maybe be implemented with a SELECT (*)? However, this would come with the downside that this will cause a lot of RCU which could end up quite costly for such a simple operation.
> Otherwise, it might be also possible to implement this with an extra table that keeps track of the count for the relevant tables?

I wouldn't recommend this approach. It's just too much effort to work around the missing `count(*)`, and the final solution most probably will introduce performance issues to glowroot itself
