### ISSUE TITLE
Protocol message had too many levels of nesting.  

### ISSUE THREAD

**Issue by gregsting** [glowroot/glowroot#704]
Hello,

I continuously have this message in glowroot central logs, even after restart. I guess this is from an agent sending bad info, how can I troubleshoot? 

2020-03-30 09:10:01.884 ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@13e066df
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:289)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
	at com.google.protobuf.InvalidProtocolBufferException.recursionLimitExceeded(InvalidProtocolBufferException.java:132)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2395)
	at org.glowroot.wire.api.model.AggregateOuterClass$Aggregate$Timer.<init>(AggregateOuterClass.java:3362)
	at org.glowroot.wire.api.model.AggregateOuterClass$Aggregate$Timer.<init>(AggregateOuterClass.java:3287)
	at org.glowroot.wire.api.model.AggregateOuterClass$Aggregate$Timer$1.parsePartialFrom(AggregateOuterClass.java:4331)
	at org.glowroot.wire.api.model.AggregateOuterClass$Aggregate$Timer$1.parsePartialFrom(AggregateOuterClass.java:4326)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2399)
(...)

Thanks

**Comment by madhu-liferay** [comment]
We are getting this same error, any workaround or fix available for this?
```
2020-09-16 12:45:00.053 ERROR o.g.agent.impl.TransactionProcessor - org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
java.lang.AssertionError: org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
	at org.glowroot.agent.embedded.util.ResultSetCloser.close(ResultSetCloser.java:51)
	at org.glowroot.agent.embedded.util.DataSource.query(DataSource.java:291)
	at org.glowroot.agent.embedded.repo.AggregateDao.rollup(AggregateDao.java:433)
	at org.glowroot.agent.embedded.repo.AggregateDao.store(AggregateDao.java:243)
	at org.glowroot.agent.embedded.init.EmbeddedCollector.collectAggregates(EmbeddedCollector.java:75)
	at org.glowroot.agent.init.CollectorProxy.collectAggregates(CollectorProxy.java:55)
	at org.glowroot.agent.impl.AggregateIntervalCollector.flush(AggregateIntervalCollector.java:215)
	at org.glowroot.agent.impl.TransactionProcessor$AggregateFlushingLoop.run(TransactionProcessor.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
	at org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBu
```

**Comment by Never-lab** [comment]
Central is rejecting an agent aggregate payload whose **timer protobuf nest is deeper than protobuf’s recursion limit** (`Aggregate$Timer` in the stack) — same root cause family as embedded #730. Often one chatty agent with extremely deep timer trees.

Troubleshoot: find which `agent.id` coincides with the ERROR bursts; upgrade agent+Central to current 0.14.x; reduce nested instrumentation on that app; temporarily isolate agents. Related profile-depth override is Jackson (`glowroot.jackson.max.nesting.depth`, #1122) — this log is the **protobuf timer** path on the wire.

@nowheresly — keep with #730, or close as support after upgrade guidance.
