### ISSUE TITLE
Usage with CA Layer7

### ISSUE THREAD

**Issue by gregsting** [glowroot/glowroot#705]
Hello,

I already use glowroot with success on Jboss and Websphere. Today I try to integrate it with our ESB product; Layer7

I first had some permission issue, I solves by creating a user.home/.java.policy file with following content:
grant {
        permission java.util.PropertyPermission "glowroot.transaction.throwable.frame.limit", "read";
        permission java.lang.RuntimePermission "getClassLoader";
        permission java.util.PropertyPermission "glowroot.transaction.aux.thread.context.limit", "read";
        permission java.lang.management.ManagementPermission "monitor";
};

Now it's running but give continous warning logs, both in Layer 7 and glowroot logs, any idea if that could cause any trouble and how to solve this if possible?:
2020-03-31 13:41:48.497 WARN  o.g.agent.plugin.api.util.Reflection - error calling javax.servlet.http.HttpServletResponse.getStatus()
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor676.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glowroot.agent.plugin.api.util.Reflection.invokeWithDefault(Reflection.java:94)
        at org.glowroot.agent.plugin.servlet._.ResponseInvoker.getStatus(ResponseInvoker.java:64)
        at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceAdvice_.onReturn(ServletAspect.java:88)
        at org.glowroot.agent.plugin.servlet.ServletAspect$DoFilterAdvice_.onReturn(ServletAspect.java:227)
        at com.l7tech.gateway.common.transport.http.FeatureFilter.doFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:234)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:181)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at com.l7tech.server.tomcat.ResponseKillerValve.invoke(Unknown Source)
        at com.l7tech.server.tomcat.ConnectionIdValve.invoke(Unknown Source)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:295)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:410)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: org.apache.catalina.connector.ResponseFacade.getStatus()I
        ... 24 common frames omitted

Thanks

**Comment by gregsting** [comment]
Upon futher research, it seems to me this might be related to the embedded tomcat/catalilne, that is a version 6.0.53

In Tomcat Doc I see:

https://tomcat.apache.org/tomcat-6.0-doc/api/org/apache/catalina/connector/Response.html#getStatus()

int getStatus()
Get the HTTP status code for this Response.
Returns:
The HTTP status code for this Response
Since:
Servlet 3.0

But servlet 3.0 is only in tomcat 7 and above, so that could be related...

**Comment by gregsting** [comment]
For posterity, in the end I used a workaround, reconfigured glowroot logs for that class by using glowroot.logback.xml found in glowroot.jar

**Comment by Never-lab** [comment]
Layer7’s embedded Tomcat is old enough that `HttpServletResponse.getStatus()` isn’t on the facade (`AbstractMethodError` — Servlet 3.0 API). Glowroot servlet plugin reflects `getStatus` and warns; usually **noise**, not a hard failure (you already muted via `glowroot.logback.xml`).

SecurityManager grants you added are the right approach for ESB lockdown. Not much else to “fix” without a Layer7-specific response wrapper.

@nowheresly — please close as support / environment.
