### ISSUE TITLE
JavaLoggingAspect NPE

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#706]
I occasionally see this in my server logs
```
Caused by: java.lang.NullPointerExceptionCaused by: java.lang.NullPointerException at java.util.PropertyResourceBundle.handleGetObject(PropertyResourceBundle.java:167) at java.util.ResourceBundle.getObject(ResourceBundle.java:401) at java.util.ResourceBundle.getString(ResourceBundle.java:367) at java.util.logging.Formatter.formatMessage(Formatter.java:130) at org.glowroot.agent.plugin.logger.JavaLoggingAspect$LogAdvice.onBeforeCommon(JavaLoggingAspect.java:92) at org.glowroot.agent.plugin.logger.JavaLoggingAspect$LogAdvice.onBefore(JavaLoggingAspect.java:64) at 
```

I am unsure if its because the thing being logged is making reference to some parameters that are null, or if its because Websphere has its own property resource loader.

Its also unclear if this will effectively block execution or just be logged as an exception but main code will continue on.

Using 0.13.5

Any clues are appreciated.

**Comment by asgerjensen** [comment]
recently this has resurfaced. If anyone has any clue, it would be much appreciated

**Comment by Never-lab** [comment]
`JavaLoggingAspect` calling `Formatter.formatMessage` can NPE inside `PropertyResourceBundle` when JUL formatting hits bad/null bundle state (WAS classloading quirks). Unclear historically whether it always aborts the log call only or surfaces further — worth treating as a **logger-plugin robustness** bug: catch and skip formatting failure.

Please re-check on [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7); workaround = disable logger plugin or avoid that JUL path.

@nowheresly — keep as bug (logger plugin NPE).
