### ISSUE TITLE
Issues with Wildfly19 and OpenJDK14

### ISSUE THREAD

**Issue by allyssons** [glowroot/glowroot#711]
Hello there!

I'm facing issues when trying to use glowroot with Wildfly 19 (recent release) and OpenJDK14 (recent too).

I configured the path in standalone.conf as said in the site: -javaagent:path/to/glowroot.jar

This is the stack that shows when I try to start Wildfly using it:

`
Exception Details:
  Location:
    com/sun/proxy/$Proxy134.getNamedDispatcher(Ljava/lang/String;)Ljavax/servlet/RequestDispatcher; @125: iload
  Reason:
    Type 'java/lang/Throwable' (current frame, locals[1]) is not assignable to 'java/lang/String' (stack map, locals[1])
  Current Frame:
    bci: @90
    flags: { }
    locals: { 'com/sun/proxy/$Proxy134', 'java/lang/Throwable', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'java/lang/String' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @125
    flags: { }
    locals: { 'com/sun/proxy/$Proxy134', 'java/lang/String', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'java/lang/String' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0000000: 033d 014e 013a 0402 3605 2b3a 062d c700
    0000010: 07b8 0090 4e2d b600 9859 3a04 c600 1b19
    0000020: 04b9 009b 0100 5936 0512 9c9f 0010 1904
    0000030: 129c b900 a002 0004 a700 0403 3d2a b400
    0000040: 552a b200 a204 bd00 6d59 032b 53b9 005d
    0000050: 0400 c000 a4a7 000e bf4c bb00 6459 2bb7
    0000060: 0067 bf1c 9900 0959 1906 b800 aa15 0502
    0000070: 9f00 0c19 0415 05b9 00a0 0200 b015 0502
    0000080: 9f00 0c19 0415 05b9 00a0 0200 bf       
  Exception Handler Table:
    bci [61, 88] => handler: 88
    bci [61, 88] => handler: 88
    bci [61, 88] => handler: 89
    bci [61, 99] => handler: 125
  Stackmap Table:
    full_frame(@21,{Object[#2],Object[#121],Integer,Object[#146],Object[#148],Integer,Object[#121]},{})
    same_frame(@55)
    same_frame(@59)
    same_locals_1_stack_item_frame(@60,Integer)
    same_locals_1_stack_item_frame(@88,Object[#81])
    same_locals_1_stack_item_frame(@89,Object[#81])
    same_locals_1_stack_item_frame(@99,Object[#164])
    same_locals_1_stack_item_frame(@109,Object[#164])
    same_locals_1_stack_item_frame(@124,Object[#164])
    same_locals_1_stack_item_frame(@125,Object[#81])
    same_locals_1_stack_item_frame(@140,Object[#81])
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 125 `

One last thing. When I use Wildfly18.0.1 and jdk-13.0.1 I don't have any of these problems.

**Comment by fabiodalazem** [comment]
Hello,
I am having exactly the same problem!
Does anyone have any solutions?

**Comment by trask** [comment]
My first guess is glowroot's asm dependency needs to be updated.

**Comment by ionutursuleanu** [comment]
Hi @allyssons ,

Can you also try with 14.0.1? Wildfly starts, but nothing appears in glowroot(just clicked a few times in the admin console)

**Comment by ionutursuleanu** [comment]
@allyssons also tested with [this](https://tomcat.apache.org/tomcat-9.0-doc/appdev/sample/) sample war and traces showed up. I think that, for now, the asm update isn't a must

**Comment by allyssons** [comment]
Hi @ionutursuleanu . Tested with 14.0.1 and it works. Only having problems with the recent version.

**Comment by iherasymenko** [comment]
I'm using `jdk-14.0.1+7` from AdoptOpenJDK. Having a similar exception. 
```
Exception Details:
  Location:
    com/sun/proxy/$Proxy31.prepareStatement(Ljava/lang/String;I)Ljava/sql/PreparedStatement; @159: iload_3
  Reason:
    Type 'java/lang/Throwable' (current frame, locals[1]) is not assignable to 'java/lang/String' (stack map, locals[1])
  Current Frame:
    bci: @115
    flags: { }
    locals: { 'com/sun/proxy/$Proxy31', 'java/lang/Throwable', integer, integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/Timer', 'java/lang/String' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @159
    flags: { }
    locals: { 'com/sun/proxy/$Proxy31', 'java/lang/String', integer, integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/Timer', 'java/lang/String' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0000000: 033e 013a 0401 3a05 0236 0601 3a07 2b3a
    0000010: 0819 04c7 0008 b800 9a3a 0419 04b6 00a2
    0000020: 593a 05c6 001f 1905 b900 a501 0059 3606
    0000030: 12a6 9f00 1019 0512 a6b9 00aa 0200 04a7
    0000040: 0004 033e 1d99 000a 1905 b801 103a 072a
    0000050: b400 5f2a b201 1205 bd00 7759 032b 5359
    0000060: 041c b800 d653 b900 6704 00c0 0114 a700
    0000070: 0ebf 4cbb 006e 592b b700 71bf 1d99 0009
    0000080: 5919 08b8 0117 1d99 0008 1907 b801 1b15
    0000090: 0602 9f00 0c19 0515 06b9 00aa 0200 b01d
    00000a0: 9900 0819 07b8 011b 1506 029f 000c 1905
    00000b0: 1506 b900 aa02 00bf                    
  Exception Handler Table:
    bci [79, 113] => handler: 113
    bci [79, 113] => handler: 113
    bci [79, 113] => handler: 113
    bci [79, 113] => handler: 114
    bci [79, 124] => handler: 159
  Stackmap Table:
    full_frame(@27,{Object[#2],Object[#131],Integer,Integer,Object[#156],Object[#158],Integer,Object[#267],Object[#131]},{})
    same_frame(@66)
    same_locals_1_stack_item_frame(@67,Integer)
    same_frame(@79)
    same_locals_1_stack_item_frame(@113,Object[#91])
    same_locals_1_stack_item_frame(@114,Object[#91])
    same_locals_1_stack_item_frame(@124,Object[#276])
    same_locals_1_stack_item_frame(@134,Object[#276])
    same_locals_1_stack_item_frame(@143,Object[#276])
    same_locals_1_stack_item_frame(@158,Object[#276])
    same_locals_1_stack_item_frame(@159,Object[#91])
    same_locals_1_stack_item_frame(@168,Object[#91])
    same_locals_1_stack_item_frame(@183,Object[#91])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getConstructor0(Class.java:3420)
	at java.base/java.lang.Class.getConstructor(Class.java:2165)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:660)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:435)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:433)
	at java.base/java.lang.reflect.Proxy.getProxyClass(Proxy.java:393)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getProxyConstructor(ConnectionPool.java:364)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.setupConnection(ConnectionPool.java:336)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:201)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:128)
	at org.apache.tomcat.jdbc.pool.DataSource.getConnection(DataSource.java)
```

**Comment by ionutursuleanu** [comment]
@iherasymenko

I did a test with an oracle datasource and it works. Is anything particular for your setup?
Could you also test wildfly 19 with an older java version(9, 11, or 13)? Maybe is something changed on the lastest wildfly, not java

**Comment by stefpiatek** [comment]
May want to check to see if the 0.14.0-beta.2 release fixes this, I had a similar error and its now working using it
