### ISSUE TITLE
Glowroot cannot find files that are auto generated by weblogic

### ISSUE THREAD

**Issue by stevengerdes-SW** [glowroot/glowroot#713]
Glowroot cannot find files that are auto generated by weblogic. Currently using  glowroot-central:0.13.4 and the corresponding agent as the current version would not start up.

In my mind it should not actually try to find them as this doesn't seem to mess up any profiling done by glowroot

Below is the call stack that is showing during weblogic startup. 

`  | 2020-04-17 11:35:39.944 ERROR org.glowroot.agent.weaving.Weaver - error analyzing com/companyName/path/To/file/NameOfStatelessAdminBeanClass_mq65c_Impl: .class (No such file or directory)
  | java.io.FileNotFoundException: .class (No such file or directory)
  |     at java.io.FileInputStream.open0(Native Method)
  |     at java.io.FileInputStream.open(FileInputStream.java:195)
  |     at java.io.FileInputStream.<init>(FileInputStream.java:138)
  |     at java.io.FileInputStream.<init>(FileInputStream.java:93)
  |     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
  |     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
  |     at java.net.URL.openStream(URL.java:1045)
  |     at org.glowroot.agent.shaded.com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
  |     at org.glowroot.agent.shaded.com.google.common.io.ByteSource.read(ByteSource.java:285)
  |     at org.glowroot.agent.shaded.com.google.common.io.Resources.toByteArray(Resources.java:98)
  |     at org.glowroot.agent.weaving.ClassAnalyzer.getNonAbstractMethods(ClassAnalyzer.java:771)
  |     at org.glowroot.agent.weaving.ClassAnalyzer.removeMethodsThatAreNotImplementedInSuperClass(ClassAnalyzer.java:511)
  |     at org.glowroot.agent.weaving.ClassAnalyzer.getMethodsThatOnlyNowFulfillAdvice(ClassAnalyzer.java:430)
  |     at org.glowroot.agent.weaving.ClassAnalyzer.analyzeMethods(ClassAnalyzer.java:243)
  |     at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:210)
  |     at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:148)
  |     at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
  |     at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
  |     at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
  |     at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
  |     at java.lang.ClassLoader.defineClass1(Native Method)
  |     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  |     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  |     at weblogic.utils.classloaders.GenericClassLoader.defineClassInternal(GenericClassLoader.java:1113)
  |     at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:1046)
  |     at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1038)
  |     at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
  |     at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
  |     at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
  |     at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:496)
  |     at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:473)
  |     at java.lang.Class.forName0(Native Method)
  |     at java.lang.Class.forName(Class.java:348)
  |     at weblogic.utils.classloaders.GenericClassLoader.defineCodeGenClass(GenericClassLoader.java:1360)
  |     at weblogic.ejb.container.ejbc.bytecodegen.GeneratorFactory.generateClass(GeneratorFactory.java:100)
  |     at weblogic.ejb.container.ejbc.bytecodegen.GeneratorFactory.generate(GeneratorFactory.java:51)
  |     at weblogic.ejb.container.ejbc.EJBCompiler.generate(EJBCompiler.java:597)
  |     at weblogic.ejb.container.ejbc.EJBCompiler.doCompile(EJBCompiler.java:202)
  |     at weblogic.ejb.container.ejbc.EJBCompiler.compileEJB(EJBCompiler.java:336)
  |     at weblogic.ejb.container.ejbc.EJBCompiler.compileEJB(EJBCompiler.java:304)
  |     at weblogic.ejb.container.deployer.EJBDeployer.compileEjbs(EJBDeployer.java:424)
  |     at weblogic.ejb.container.deployer.EJBDeployer.compileIfNecessary(EJBDeployer.java:355)
  |     at weblogic.ejb.container.deployer.EJBDeployer.prepare(EJBDeployer.java:723)
  |     at weblogic.ejb.container.deployer.EJBModule.prepare(EJBModule.java:405)
  |     at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:295)
  |     at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:285)
  |     at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
  |     at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:109)
  |     at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
  |     at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:192)
  |     at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:187)
  |     at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
  |     at weblogic.application.internal.flow.ModuleStateDriver.prepare(ModuleStateDriver.java:37)
  |     at weblogic.application.internal.flow.DeploymentCallbackFlow.prepare(DeploymentCallbackFlow.java:77)
  |     at weblogic.application.internal.flow.DeploymentCallbackFlow.prepare(DeploymentCallbackFlow.java:55)
  |     at weblogic.application.internal.BaseDeployment$1.next(BaseDeployment.java:729)
  |     at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
  |     at weblogic.application.internal.BaseDeployment.prepare(BaseDeployment.java:241)
  |     at weblogic.application.internal.EarDeployment.prepare(EarDeployment.java:66)
  |     at weblogic.application.internal.DeploymentStateChecker.prepare(DeploymentStateChecker.java:158)
  |     at weblogic.deploy.internal.targetserver.AppContainerInvoker.prepare(AppContainerInvoker.java:65)
  |     at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:166)
  |     at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:41)
  |     at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:193)
  |     at weblogic.management.deploy.internal.AppTransition$1.transitionApp(AppTransition.java:31)
  |     at weblogic.management.deploy.internal.ConfiguredDeployments$2.doItem(ConfiguredDeployments.java:741)
  |     at weblogic.management.deploy.internal.parallel.BucketInvoker.invoke(BucketInvoker.java:138)
  |     at weblogic.management.deploy.internal.ConfiguredDeployments.transitionAppsParallel(ConfiguredDeployments.java:749)
  |     at weblogic.management.deploy.internal.ConfiguredDeployments.prepare(ConfiguredDeployments.java:363)
  |     at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:232)
  |     at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:219)
  |     at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:133)
  |     at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
  |     at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  |     at java.lang.reflect.Method.invoke(Method.java:498)
  |     at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
  |     at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
  |     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
  |     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
  |     at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
  |     at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
  |     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
  |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
  |     at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
  |     at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
  |     at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
  |     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
  |     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
  |     at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
  |     at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
  |     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:786)
  |     at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:678)
  |     at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
  |     at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
  |     at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
  |     at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
  |     at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:652)
  |     at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
  |     at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
`

**Comment by Never-lab** [comment]
WebLogic EJB codegen (`*_Impl` / `defineCodeGenClass`) often has **no `.class` file URL** on disk; Glowroot’s analyzer tries to read bytes and logs `FileNotFoundException: .class`. Noisy and usually **non-fatal** if profiling still works — as you noted.

Please try current 0.14.x; if it’s still spam-only, treat as logging noise / weaving hard edge on generated classes (could be quieted). Not typically “Glowroot broken.”

@nowheresly — keep as noise/weaving polish, or close as support if “harmless on WL codegen” is enough.
