### ISSUE TITLE
Glowroot with Wildfly and security manager

### ISSUE THREAD

**Issue by adrianboangiu** [glowroot/glowroot#719]
I have some errors when I use glowroot to monitor an application under Wildfly using security manager. The following errors occur when starting the wildfly server:

```
2020-05-06 10:36:14.365 ERROR o.g.a.s.o.g.c.util.ScheduledRunnable - WFSM000001: Permission check failed (permission "("javax.management.MBeanServerPermission" "createMBeanServer")" in code source "(file:/C:/siv718/javatools/monitor/glowroot/lib/glowroot-embedded-collector.jar <no signer certificates>)" of "java.net.URLClassLoader@5ca881b5")
java.security.AccessControlException: WFSM000001: Permission check failed (permission "("javax.management.MBeanServerPermission" "createMBeanServer")" in code source "(file:/C:/siv718/javatools/monitor/glowroot/lib/glowroot-embedded-collector.jar <no signer certificates>)" of "java.net.URLClassLoader@5ca881b5")
        at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:273)
        at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:175)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
…
10:36:16,165 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
org.glowroot.agent.embedded.shaded.org.h2.message.DbException: Log file error: "C:/siv718/javatools/monitor/glowroot/data/data.trace.db", cause: "java.security.AccessControlException: WFSM000001: Permission check failed (permission ""(""java.io.FilePermission"" ""C:\siv718\javatools\monitor\glowroot\data"" ""read"")"" in code source ""(file:/C:/siv718/javatools/monitor/glowroot/lib/glowroot-embedded-collector.jar <no signer certificates>)"" of ""java.net.URLClassLoader@5ca881b5"")" [90034-176]
10:36:16,891 ERROR [stderr] (Thread-3) org.glowroot.agent.embedded.shaded.org.h2.message.DbException: Log file error: "C:/siv718/javatools/monitor/glowroot/data/data.trace.db", cause: "java.security.AccessControlException: WFSM000001: Permission check failed (permission ""(""java.io.FilePermission"" ""C:\siv718\javatools\monitor\glowroot\data"" ""read"")"" in code source ""(file:/C:/siv718/javatools/monitor/glowroot/lib/glowroot-embedded-collector.jar <no signer certificates>)"" of ""java.net.URLClassLoader@5ca881b5"")" [90034-176]
```
…

From my experience, solving these ones will open the door to some others.
I know how to set the permissions for the application but I do not know how to set the permissions for glowroot jars. Is there a way to give all permissions to glowroot jar?
Disabling Wildfly security manager (set SECMGR=false) eliminate all these errors.
How can I use glowroot to monitor Wildfly under security manager?

**Comment by Never-lab** [comment]
Same **SecurityManager** family as #596 / #882: WildFly SECMGR denies Glowroot `createMBeanServer`, `FilePermission` on the agent `data/` dir, etc. Grant the Glowroot install tree (and reflective/JMX perms) in the server policy for the Glowroot code source, or run with SECMGR off in lab.

There isn’t a one-click “all permissions for glowroot.jar” switch inside Glowroot — it’s a container policy grant on those JARs/`lib/*`.

@nowheresly — please close as support.
