### ISSUE TITLE
Glowroot stops a web application functioning

### ISSUE THREAD

**Issue by danormsby** [glowroot/glowroot#721]
Hi,

Glowroot is great.  In a Tomcat deployment we have a few web applications.  They are all fine except one which when glowroot is configured that app just stops working with an error as shown below.  Is there a mechanism to make glowroot ignore some some classpaths like ignore com/mycompany/myapp/* so this particular web app will keep working when glow root is configured on the application server?

Cheers,
Dan.

```
11-May-2020 13:12:27.398 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
	org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/myappweb]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 226
Exception Details:
  Location:
    com/mycompany/myapp/webserver/myappContextListener.contextInitialized(Ljavax/servlet/ServletContextEvent;)V @226: iload_2
  Reason:
    Type 'javax/servlet/ServletContext' (current frame, locals[1]) is not assignable to 'javax/servlet/ServletContextEvent' (stack map, locals[1])
  Current Frame:
    bci: @119
    flags: { }
    locals: { 'com/mycompany/myapp/webserver/myappContextListener', 'javax/servlet/ServletContext', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/TraceEntry' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @226
    flags: { }
    locals: { 'com/mycompany/myapp/webserver/myappContextListener', 'javax/servlet/ServletContextEvent', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/TraceEntry' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 033d 014e 013a 0402 3605 013a 062d c700
    0x0000010: 07b8 0015 4e2d b600 2159 3a04 c600 1b19
    0x0000020: 04b9 0025 0100 5936 0512 269f 0010 1904
    0x0000030: 1226 b900 2a02 0004 a700 0403 3d1c 9900
    0x0000040: 342d c700 07b8 0015 4e2d b600 2159 3a04
    0x0000050: c700 0d2d 1226 122b b800 2f3a 0419 042a
    0x0000060: 1230 04bd 0004 5903 2b53 b200 36b8 003c
    0x0000070: 3a06 2bb6 0042 4cbb 0044 592b 1246 b900
    0x0000080: 4c02 00b7 004f 3a07 bb00 5159 b700 5212
    0x0000090: 5419 07b6 0058 572a 2bb6 005b 4c12 5d3a
    0x00000a0: 072b b600 633a 07a7 0010 4cb2 0067 2bb6
    0x00000b0: 006a b900 6f02 00b2 0067 1271 1907 b900
    0x00000c0: 7503 00a7 0003 1c99 000b b800 7b19 06b8
    0x00000d0: 007f 1505 029f 000c 1904 1505 b900 2a02
    0x00000e0: 00b1 1c99 0009 5919 06b8 0085 1505 029f
    0x00000f0: 000c 1904 1505 b900 2a02 00bf          
  Exception Handler Table:
    bci [161, 167] => handler: 170
    bci [114, 198] => handler: 226
  Stackmap Table:
    full_frame(@21,{Object[#2],Object[#23],Integer,Object[#25],Object[#27],Integer,Object[#29]},{})
    same_frame(@55)
    same_frame(@59)
    same_locals_1_stack_item_frame(@60,Integer)
    same_frame(@73)
    same_frame(@93)
    same_frame(@114)
    full_frame(@170,{Object[#2],Object[#23],Integer,Object[#25],Object[#27],Integer,Object[#29],Object[#101]},{Object[#62]})
    same_frame(@183)
    chop_frame(@198,1)
    same_frame(@210)
    same_frame(@225)
    same_locals_1_stack_item_frame(@226,Object[#129])
    same_locals_1_stack_item_frame(@236,Object[#129])
    same_locals_1_stack_item_frame(@251,Object[#129])

		at java.lang.Class.getDeclaredFields0(Native Method)
		at java.lang.Class.privateGetDeclaredFields(Class.java:2611)
		at java.lang.Class.getDeclaredFields(Class.java:1944)
		at org.apache.catalina.util.Introspection.getDeclaredFields(Introspection.java:110)
		at org.apache.catalina.startup.WebAnnotationSet.loadFieldsAnnotation(WebAnnotationSet.java:269)
		at org.apache.catalina.startup.WebAnnotationSet.loadApplicationListenerAnnotations(WebAnnotationSet.java:89)
		at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:67)
		at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:328)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5065)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
11-May-2020 13:12:27.410 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\myappweb]
	java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/myappweb]]
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:747)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by iam8139** [comment]
Hi @danormsby, have you found anything on this issue ?? would be really helpful if you can share...

**Comment by danormsby** [comment]
Suspect false positive bytecode problem.  Workaround was add this flag -Xverify:none then glowroot works fine.  I don't recommend that flag in production use but is certainly useful when debugging.

**Comment by stefpiatek** [comment]
May want to check to see if the 0.14.0-beta.2 release fixes this, I had a similar error and its now working using it

**Comment by Never-lab** [comment]
`VerifyError` / bad stack map after Glowroot weaves a `ServletContextListener` is a real weaving edge (not “ignore this war” config). There is **no** supported per-classpath exclude list like `ignore com/mycompany/myapp/*` today.

Reporter workaround `-Xverify:none` is debug-only. Please retry on current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7) (others reported similar VerifyError fixed on 0.14 betas). If still broken: `-Dglowroot.debug.className=…` + class bytecode, keep as weaving defect.

@nowheresly — keep as weaving / VerifyError unless confirmed fixed on 0.14.x.

**Comment by Never-lab** [comment]
Draft fix in **#1218**: `visitFrame` now keeps the expanded frame’s updated local types (e.g. parameter slot overwritten with another reference type) instead of resetting to method-entry types — that was the `VerifyError` / stack-map mismatch on woven `ServletContextListener`-style methods.

Please re-check on a build from that PR if you still have a repro. `-Xverify:none` should no longer be needed for this case.

@nowheresly

**Comment by Never-lab** [comment]
Fixed on main via #1218 (rebased/ff). Will be in the next release.

@nowheresly — OK to close?
