### ISSUE TITLE
Jetty error - BadMessageException: 500: No Version

### ISSUE THREAD

**Issue by gamefundas** [glowroot/glowroot#722]
Java version: OpenJdk 11
Agent version: 0.13.6
Collector Server: 0.13.4

My HTTP web API request fails with the following jetty error. Once I remove the glowroot agent the 
same request succeeds. So its clearly something to do with instrumentation. Cant figure out what can cause this. Does glowroot support Jetty with OpenJDK 11?

This is a normal HTTP GET request with text/plain response.

org.eclipse.jetty.io.RuntimeIOException: java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
        at org.eclipse.jetty.server.ResponseWriter.isOpen(ResponseWriter.java:131)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:228)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:246)
        at com.foo.bar.common.servlet.AbstractServlet$ResponseWriterHandler.writeTo(AbstractServlet.java:669)
        at com.foo.bar.common.servlet.AbstractServlet.sendOkResponse(AbstractServlet.java:486)
        at com.foo.bar.servlets.QueryServlet.doGetBackgroundUnderLock(QueryServlet.java:66)
        at com.foo.bar.servlets.QueryServlet.doGetBackgroundUnderLock(QueryServlet.java:27)
        at com.foo.bar.common.servlet.AbstractServlet.lambda$doGet$0(AbstractServlet.java:101)
        at com.foo.bar.common.servlet.AbstractServlet$1.run(AbstractServlet.java:238)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.AsyncContextState$1.run(AsyncContextState.java:149)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:245)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:623)
        at java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:187)
        at org.eclipse.jetty.server.Iso88591HttpWriter.write(Iso88591HttpWriter.java:70)
        at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:67)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:229)
        ... 12 common frames omitted
Caused by: org.eclipse.jetty.http.BadMessageException: 500: No version
        at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:389)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:735)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:541)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:839)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:916)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:259)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
        ... 17 common frames omitted
		
Also no errors reported in glowroot logs.

**Comment by gamefundas** [comment]
Please ignore. The exception was caused due to request timeout configured in the Servlet, since it was set to a very short interval this was occasionally with errors. Noticed the error at times even without Glowroot. Closing this as its not an issue.
