### ISSUE TITLE
Glowroot's log populating in Jboss' server.log continuously.

### ISSUE THREAD

**Issue by santhoshcharan** [glowroot/glowroot#730]
Server.log in jboss is flooded with below log. Wondering why glowroot log is written in jboss server.log. Temporarily we have disabled glowroot.

2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing) java.lang.AssertionError: org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBufferEx
ception: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.embedded.util.ResultSetCloser.close(ResultSetCloser.java:51)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.embedded.util.DataSource.query(DataSource.java:291)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.embedded.repo.AggregateDao.rollup(AggregateDao.java:433)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.embedded.repo.AggregateDao.store(AggregateDao.java:243)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.embedded.init.EmbeddedCollector.collectAggregates(EmbeddedCollector.ja
va:82)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.init.CollectorProxy.collectAggregates(CollectorProxy.java:55)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.impl.AggregateIntervalCollector.flush(AggregateIntervalCollector.java:
215)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at org.glowroot.agent.impl.TransactionProcessor$AggregateFlushingLoop.run(TransactionProcess
or.java:298)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing)    at java.lang.Thread.run(Thread.java:748)
2020-06-26 00:00:00,962 INFO  [stdout] (Glowroot-Aggregate-Flushing) Caused by: org.glowroot.agent.shaded.com.google.protobuf.InvalidProtocolBufferException: Protoc
ol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.

**Comment by Never-lab** [comment]
The flood in JBoss `server.log` is Glowroot’s aggregate flush hitting **protobuf nesting limit** on a very deep timer tree (`InvalidProtocolBufferException: Protocol message had too many levels of nesting`) — same family as #704. It prints via stdout, so it lands in the container log.

Mitigations: upgrade to current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7); reduce capture depth/noise (fewer nested plugins / instrumentation); point Glowroot logging at its own file (`glowroot.logback.xml`) so AssertionErrors don’t spam `server.log`. Deep profile JSON had a related Jackson knob (`glowroot.jackson.max.nesting.depth`, #1122); timer protobuf depth is the aggregate path.

@nowheresly — keep with #704 as nesting/depth, or close as support if upgrade + log isolation is enough.
