### ISSUE TITLE
Tomcat server not starting

### ISSUE THREAD

**Issue by KUNAL13** [glowroot/glowroot#734]
Hi, 

I have installed the 0.13.6 version of glowroot using the steps mentioned in the [quickstart](https://github.com/glowroot/glowroot#quick-start).

I am using tomcat 9.0.10 and java 11.0.4 and when I start my server, I get the following error:

```
Exception in thread "Glowroot-Init-UI" java.lang.IncompatibleClassChangeError: Class sun.security.jca.ProviderList$3 does not implement the requested interface org.glowroot.agent.plugin.cassandra.ResultSetAspect$ResultSetMixin
	at org.glowroot.agent.plugin.cassandra.ResultSetAspect$IteratorAdvice.onReturn(ResultSetAspect.java:102)
	at java.base/sun.security.jca.ProviderList$3.iterator(ProviderList.java)
	at java.base/java.security.SecureRandom.getPrngAlgorithm(SecureRandom.java:877)
	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:261)
	at java.base/java.security.SecureRandom.<init>(SecureRandom.java:218)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpSessionManager.<init>(HttpSessionManager.java:69)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.UiModule.createUiModule(UiModule.java:181)
	at org.glowroot.agent.embedded.shaded.org.glowroot.ui.CreateUiModuleBuilder.build(CreateUiModuleBuilder.java:571)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.initEmbeddedServer(EmbeddedAgentModule.java:270)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit$1$1.run(EmbeddedGlowrootAgentInit.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Please help, Thanks!

**Comment by bmhm** [comment]
Hello Kunal,

have you tried using another application server or another java runtime?
Application server (for example) could be OpenLiberty: https://github.com/OpenLiberty/open-liberty
As a java runtime you can try a runtime from adoptium (former adopt openjdk): https://adoptopenjdk.net/

Let me/us know if this helps! 
Also, please post the exact output of your current "java -version". Thanks!

**Comment by Never-lab** [comment]
﻿``IncompatibleClassChangeError`` with ``ResultSetMixin`` on ``sun.security.jca.ProviderList$3`` means the **cassandra plugin** advice for ``Iterable.iterator`` was applied to the wrong class (JDK security code), not a Tomcat misconfig.

On **0.13.6** this weaving edge case showed up during embedded UI init (``SecureRandom``). Practical mitigations:
1. Try a current **0.14.x** agent (weaving/plugins have moved since).
2. If you don’t use the Datastax Cassandra driver in that app, remove/disable the cassandra plugin jar under ``plugins/``.
3. Confirm with a clean Adoptium/Temurin JDK build as @bmarwell suggested.

Stale (2020) with no follow-up. Further help → [Discussions](https://github.com/glowroot/glowroot/discussions).

@nowheresly — OK to close as needs-info / stale, or keep if still reproducible on 0.14.x.
