### ISSUE TITLE
Issue with NotNullCheck

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#74]
```
2016-02-25 08:14:25.694 ERROR o.g.agent.impl.TransactionCollector - null
 java.lang.NullPointerException: null
 at org.glowroot.agent.shaded.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
 at org.glowroot.agent.model.TraceEntryComponent.toProto(TraceEntryComponent.java:92)
 at org.glowroot.agent.model.ThreadContextImpl.getEntriesProtobuf(ThreadContextImpl.java:145)
 at org.glowroot.agent.model.Transaction.getEntriesProtobuf(Transaction.java:370)
 at org.glowroot.agent.model.TraceCreator.createFullTrace(TraceCreator.java:82)
 at org.glowroot.agent.model.TraceCreator.createCompletedTrace(TraceCreator.java:48)
 at org.glowroot.agent.impl.TransactionCollector$1.run(TransactionCollector.java:117)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
```

**Comment by trask** [comment]
Is there anything else in the glowroot log? Also, I added some better handling and logging of this error if you can try that out and report back that would be great.  Thanks.

**Comment by trask** [comment]
Closing, please re-open if there is any update, thanks.
