### ISSUE TITLE
Central Collector - No transactions

### ISSUE THREAD

**Issue by rosscintelematics** [glowroot/glowroot#744]
Hello,
I've setup the Glowroot Central collector v0.13.6 using Option 3 (docker) from the [installation instructions](https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation) on an AWS EC2 t3.medium instance running Ubuntu 18.04. I had to use the patched docker image to workaround issue [#626](https://github.com/glowroot/glowroot/issues/626#issuecomment-646221076), but I can confirm that the collector starts and I can access the UI.

I then add the 0.13.6 Agent to each node of my Java application, which is a clustered implementation of [Open Trip Planner v1.4.0](https://github.com/opentripplanner/OpenTripPlanner/tree/v1.4.0). These are deployed in AWS ECS and checking the logs, I can confirm that the app starts fine and the agent can connect to the collector:
```
org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
org.glowroot - Java version: 1.8.0_242 (Amazon.com Inc. / Linux)
org.glowroot - Java args: -XX:ActiveProcessorCount=50 -Xmx8192m -javaagent:/opt/glowroot/glowroot.jar
org.glowroot - agent id: otp-cluster::ip-10-63-17-148.ap-southeast-2.compute.internal
org.glowroot - connected to the central collector http://10.63.12.93:8181, version 0.13.6, built 2020-03-01 01:25:31 +0000
```
Once I start sending requests to my application though, I don't see any Transactions come through on the glowroot collector UI. I can see JVM stats come through but thats about it. The Transaction page shows my cluster name in the dropdown and I can view the Rollup or each agent name but there aren't any recorded transactions on that page. It looks like [someone on SO had a similar issue](https://stackoverflow.com/questions/55527996/unable-to-see-any-web-transactions-of-my-vertx-application-in-glowroot) but there is no resolution there, wondering if I could get a little help.

Thanks

**Comment by ionutursuleanu** [comment]
Hi @rosscintelematics 

Could you upload a screenshot?

**Comment by rosscintelematics** [comment]
![Glowroot Screenshot](https://drive.google.com/file/d/1R-U8kt9eZV9PP6m31szI2gVcPJ9iLbud/view?usp=sharing)

**Comment by ionutursuleanu** [comment]
If you change last 30 minutes to last 30 days has any effect?

**Comment by rosscintelematics** [comment]
@ionutursuleanu Changing the time period has no affect unfortunately. I've grabbed the `/usr/share/glowroot-central/logs/glowroot-central.log` from the glowroot central container and attached here. 

[glowroot-central.log](https://github.com/glowroot/glowroot/files/4985331/glowroot-central.log)

There doesn't seem to be any 'errors', but I do see some warnings, mainly:
```
2020-07-24 10:39:10.139 WARN  c.d.driver.core.RequestHandler - Query '[1 bound values] select capture_time, uniqueness, child_agent_rollup, gauge_names from gauge_needs_rollup_from_child where agent_rollup = ?;' generated server side warning(s): Read 10 live rows and 2400 tombstone cells for query SELECT * FROM glowroot.gauge_needs_rollup_from_child WHERE agent_rollup = otp-cluster:: LIMIT 5000 (see tombstone_warn_threshold)
```

**Comment by ionutursuleanu** [comment]
That's very weird. Did you tried to use glowroot without docker? I also use EC2 instances(without docker) with ubuntu & it's working fine

**Comment by rosscintelematics** [comment]
I did try setting up the collector on an EC2 natively without docker, but I struggled for a few days and couldn't even get Cassandra installed and working properly. Do you have some scripts or something to do the installation on EC2 that you might want to share? Theoretically it _should_ be the same though right?

**Comment by ionutursuleanu** [comment]
> Do you have some scripts or something to do the installation on EC2 that you might want to share?

I just unzipped cassandra & glowroot-central and run this basically:

`./apache-cassandra-3.11.6/bin/cassandra`
`java -jar ./glowroot-central/glowroot-central.jar `

**Comment by rosscintelematics** [comment]
So I did the above:
```
sudo apt install openjdk-8-jre-headless
curl -OL https://downloads.apache.org/cassandra/3.11.7/apache-cassandra-3.11.7-bin.tar.gz
tar xzvf apache-cassandra-3.11.7-bin.tar.gz
```
Then uploaded the glowroot-central dir with everything in it and ran the two commands in different tabs and I _still_ get the same behaviour.

Agents register and show in logs but no transactions are coming through. Could it have something to do with the cluster/rollup config? Should I try dropping it and have each agent register independently? I'm going to try this locally on my machine as well to see if that works too.

**Comment by rosscintelematics** [comment]
I've now tried on my local machine using the following versions:
- cassandra 3.11.7 and glowroot 0.13.6
- cassandra 3.11.6 and glowroot 0.13.6
- cassandra 3.11.6 and glowroot 0.13.5

Neither of these combinations are working. I'm going to have to give up on this tool now as I've already burned several days trying to get it working to no avail. The setup is pretty easy to reproduce if someone wants to ever look into why it's not working, I'm pretty sure everything required to reproduce is above.

**Comment by ionutursuleanu** [comment]
> sudo apt install openjdk-8-jre-headless

The only  difference that I can see is that I always used a jdk,  not just the jre...for the agents and central collector also. 

> I see your using 3.11.6 of cassandra, which version of Glowroot do you use? 

The latest one 0.13.6, but never had issues like that with older ones

**Comment by bakageddy** [comment]
I have a very similar issue with glowroot central setup.
Central Collector Node: 14.7
Agent: 14.0
Database: ScyllaDB 2026.06.01

Logs: 
ng to be stored (this warning will be logged at most once a minute, 83 warnings were suppressed since it was last logged)
2026-07-15 05:31:08.930 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1531 warnings were suppressed since it was last logged)
2026-07-15 06:00:06.695 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 39 warnings were suppressed since it was last logged)
2026-07-15 06:30:04.310 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 145 warnings were suppressed since it was last logged)
2026-07-15 07:00:08.282 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 129 warnings were suppressed since it was last logged)
2026-07-15 07:23:04.878 WARN  o.g.a.e.s.o.g.ui.HttpServerHandler - Connection reset                                                                 java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)                                                                      at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at org.glowroot.agent.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)                                                         at org.glowroot.agent.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at org.glowroot.agent.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)                                    at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)                                            at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)                                           at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)                                                           at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)                           at org.glowroot.agent.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                              at java.base/java.lang.Thread.run(Unknown Source)                                                                                           2026-07-15 07:30:10.302 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 82 warnings were suppressed since it was last logged)                           2026-07-15 07:37:05.124 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 149 warnings were suppressed since it was last logged)                          2026-07-15 08:00:06.885 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute)                                                                                 2026-07-15 08:30:02.608 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 107 warnings were suppressed since it was last logged)                          2026-07-15 10:03:49.514 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000                                              2026-07-15 10:03:49.515 INFO  org.glowroot - Java version: 17.0.19 (Azul Systems, Inc. / Windows Server 2025)                                       2026-07-15 10:03:49.516 INFO  org.glowroot - Java args: -XX:+HeapDumpOnOutOfMemoryError -Xlog:gc*,stringdedup*=debug:../logs/GCDetails::filecount=3,filesize=5M --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -XX:+UseStringDeduplication -XX:StringDeduplicationAgeThreshold=3 -XX:MaxMetaspaceSize=512m -javaagent:../glowroot/glowroot.jar -javaagent:../lib/hotswapAgent.jar -XX:-OmitStackTraceInFastThrow --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.impl=ALL-UNNAMED=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.xni=ALL-UNNAMED=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xerces.internal.xni.parser=ALL-UNNAMED=ALL-UNNAMED -javaagent:../lib/hotswapAgent.jar -Xms128m -Xmx4096m                             2026-07-15 10:03:52.992 INFO  org.glowroot - agent id: "sdp-loadt-3"                                                                                2026-07-15 10:04:01.777 INFO  org.glowroot - connected to the central collector http://sdp-fed44-1:8181, version 0.14.7, built 2026-04-30 21:10:27 +0000                                                                                                                                                2026-07-15 10:04:30.408 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute)                                                                                 2026-07-15 10:05:01.064 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute)                                                                 2026-07-15 10:05:29.401 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2732 warnings were suppressed since it was last logged)                         2026-07-15 10:06:29.885 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 4005 warnings were suppressed since it was last logged)                         2026-07-15 10:07:12.876 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:07:29.414 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3544 warnings were suppressed since it was last logged)                         2026-07-15 10:08:12.036 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)            2026-07-15 10:08:29.402 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 4241 warnings were suppressed since it was last logged)                         2026-07-15 10:09:13.321 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 3 warnings were suppressed since it was last logged)            2026-07-15 10:09:29.417 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3341 warnings were suppressed since it was last logged)                         2026-07-15 10:10:29.417 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2803 warnings were suppressed since it was last logged)                         2026-07-15 10:10:46.728 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)            2026-07-15 10:11:29.404 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2575 warnings were suppressed since it was last logged)                         2026-07-15 10:11:54.647 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)            2026-07-15 10:12:29.737 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2498 warnings were suppressed since it was last logged)                         2026-07-15 10:13:26.241 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 4 warnings were suppressed since it was last logged)            2026-07-15 10:13:29.638 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1551 warnings were suppressed since it was last logged)                         2026-07-15 10:14:29.400 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1598 warnings were suppressed since it was last logged)                         2026-07-15 10:14:49.856 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:14:57.920 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute)                                                            2026-07-15 10:15:29.470 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1626 warnings were suppressed since it was last logged)                         2026-07-15 10:16:23.724 WARN  o.glowroot.agent.init.GaugeCollector - not storing a gauge collection because of an excessive backlog of 60 gauge collections already waiting to be stored (this warning will be logged at most once a minute, 10 warnings were suppressed since it was last logged)      2026-07-15 10:16:29.448 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1818 warnings were suppressed since it was last logged)                         2026-07-15 10:16:39.960 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 5 warnings were suppressed since it was last logged)            2026-07-15 10:17:29.666 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2520 warnings were suppressed since it was last logged)                         2026-07-15 10:17:45.523 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)            2026-07-15 10:18:29.401 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3021 warnings were suppressed since it was last logged)                         2026-07-15 10:19:29.402 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2474 warnings were suppressed since it was last logged)                         2026-07-15 10:20:01.375 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 4 warnings were suppressed since it was last logged)            2026-07-15 10:20:29.674 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2180 warnings were suppressed since it was last logged)                         2026-07-15 10:21:29.724 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1855 warnings were suppressed since it was last logged)                         2026-07-15 10:21:33.718 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:22:29.887 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1988 warnings were suppressed since it was last logged)                         2026-07-15 10:22:37.370 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:23:29.648 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1244 warnings were suppressed since it was last logged)                         2026-07-15 10:23:55.882 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:24:29.408 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1924 warnings were suppressed since it was last logged)                         2026-07-15 10:25:29.672 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 1653 warnings were suppressed since it was last logged)                         2026-07-15 10:25:38.498 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 5 warnings were suppressed since it was last logged)            2026-07-15 10:26:29.460 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 2491 warnings were suppressed since it was last logged)                         2026-07-15 10:26:47.254 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:27:29.674 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3849 warnings were suppressed since it was last logged)                         2026-07-15 10:28:29.623 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3334 warnings were suppressed since it was last logged)                         2026-07-15 10:28:36.032 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)            2026-07-15 10:29:29.410 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3242 warnings were suppressed since it was last logged)                         0026-07-15 10:29:52.718 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute)                                                                 2026-07-15 10:30:29.682 WARN  o.glowroot.agent.impl.TraceCollector - not storing a trace because of an excessive backlog of 150 traces already waiting to be stored (this warning will be logged at most once a minute, 3037 warnings were suppressed since it was last logged)

**Comment by nowheresly** [comment]
Hi @bakageddy 
could you retry with this version https://github.com/glowroot/glowroot/releases/tag/v0.14.8-beta.3 ?
Could you try to tune https://github.com/glowroot/glowroot/blob/main/central/src/main/resources/datastax-driver.conf to match your scylladb settings?

**Comment by Never-lab** [comment]
﻿Two separate threads here:

### Original (OTP + Central 0.13.6, 2020)
Agent connects and **JVM gauges** show up, but **no Web transactions**. That pattern usually means Central is fine and the agent is **not capturing HTTP** as Glowroot transactions (wrong entry stack / no servlet-filter weave), not “Central UI broken.” OpenTripPlanner’s HTTP path may not hit the servlet plugin the way a classic Tomcat app does — check agent logs for woven transactions, try **Startup** vs **Web**, and if needed add **Configuration → Instrumentation** on OTP’s request handlers. Similar “gauges yes, Web no” reports often turn out to be framework/plugin gaps (see also Vert.x-style cases).

### Recent (Scylla + backlog / ``StatusRuntimeException: UNKNOWN``, 2026)
That is **Central↔store capacity / connectivity** (trace backlog, UNKNOWN to Central) — follow @nowheresly: try [v0.14.8-beta.3](https://github.com/glowroot/glowroot/releases/tag/v0.14.8-beta.3) and tune ``datastax-driver.conf`` for Scylla. Related: #748 #900.

Stale on the OTP side with no successful repro follow-up.

@nowheresly — close OP as needs-info/stale if you agree; keep open only for the Scylla thread if still active.
