### ISSUE TITLE
Central Collector running out of resources

### ISSUE THREAD

**Issue by niketk10** [glowroot/glowroot#748]
Hello 

I am getting this logs on glowroot. Glowroot version: 0.13.5, Tomcat 7
 
2020-07-01 15:45:51.629 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning wil
l be logged at most once a minute)
2020-07-01 15:52:57.309 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning wil
l be logged at most once a minute)
2020-07-01 15:55:35.268 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning wil
l be logged at most once a minute)
2020-07-01 15:59:03.628 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: colle
ction rejected due to backlog (this warning will be logged at most once a minute)
2020-07-01 16:00:04.054 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: colle
ction rejected due to backlog (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)
2020-07-01 16:01:05.037 WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: colle
ction rejected due to backlog (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)

**Comment by niketk10** [comment]
Hey @trask 
I am getting this logs on glowroot. Glowroot version: 0.13.5, Tomcat 7

2020-07-24 00:01:19.465 WARN  o.g.a.s.i.n.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.io.IOException: Broken pipe
        at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
        at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
        at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:207)
        at org.glowroot.agent.shaded.io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup(SelectedSelectionKeySetSelector.java:73)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.selectNow(NioEventLoop.java:723)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop$1.get(NioEventLoop.java:71)
        at org.glowroot.agent.shaded.io.netty.channel.DefaultSelectStrategy.calculateStrategy(DefaultSelectStrategy.java:30)
        at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:406)
        at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by visva2005** [comment]
Hi , Is this resolved? I am also getting the same error while receiving large log from Multiple application server.

.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: collection rejected due to backlog (this warning will be logged at most once a minute, 2 warnings were suppressed since it was last logged)

**Comment by Never-lab** [comment]
`RESOURCE_EXHAUSTED: collection rejected due to backlog` is **Central back-pressure**, not a silent “Glowroot bug”. The collector (or its Cassandra store path) cannot keep up with inbound agent data, so it rejects collections. The Netty `Broken pipe` / `UNKNOWN` lines are usually fallout from that connection stress.

Typical causes: undersized Central/Cassandra, too many agents / too much capture, Cassandra slow or unreachable, very old agent/central (**0.13.5** in the OP — worth trying a current **0.14.x** pair).

Ops checklist: Central + Cassandra CPU/disk/latency, agent count, whether warnings correlate with load spikes, upgrade agent+central together. Related backlog/OOM discussions elsewhere in the tracker.

Stale (2020) with no sizing details. Further help → [Discussions](https://github.com/glowroot/glowroot/discussions) / [Central wiki](https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation).

@nowheresly — OK to close as ops/support (needs-info, no follow-up), unless you want it kept as a capacity FAQ.
