### ISSUE TITLE
Glowroot 0.13.5 hits OOM while loading H2 db file

### ISSUE THREAD

**Issue by lim255** [glowroot/glowroot#749]
Hi,

I have Glowroot 0.13.5 embedded with my application. 

My app info:
- OpenJDK11 (amazon-corretto-11.0.6.10.1-linux-x64)
- JVM memory configuration: -Xmx=3000M -XXMaxMetaspaceSize=256M -XX:ReservedCodeCacheSize=256M -XX:+UseCodeCacheFlushing
- Tomcat 8.5

Recently, it hits OOM during startup. It happens when loading the H2 DB file. When this happens, it never recovers from it. I hit the issue once so far. So, I don't know if I can repro it.

My current workaround is to delete the data/ directory and restarts my application.

I suspect that the H2 DB could be corrupted. This is my test VM and it restarts repeatedly, in many cases the tomcat is not shut down gracefully.

I would like to know if this is a known issue. If yes, if there is a fix. 
Or there is some configuration that I could try to "auto recover" the Glowroot from a situation like this.

Glowroot-Init-Repo tid=39 [RUNNABLE] [DAEMON] <--- OutOfMemoryError happened in this thread
java.lang.OutOfMemoryError.<init>()
org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.readRow(DataReader, Data)
org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.recover(int)
org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.recover()
org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.openExisting()
org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.open()
org.glowroot.agent.embedded.shaded.org.h2.engine.Database.getPageStore()
org.glowroot.agent.embedded.shaded.org.h2.engine.Database.open(int, int)
org.glowroot.agent.embedded.shaded.org.h2.engine.Database.openDatabase(int, int, boolean)
org.glowroot.agent.embedded.shaded.org.h2.engine.Database.<init>(ConnectionInfo, String)
org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(ConnectionInfo, boolean, String)
org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(ConnectionInfo)
org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSessionAndValidate(ConnectionInfo)
org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(ConnectionInfo)
org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(ConnectionInfo)
org.glowroot.agent.embedded.shaded.org.h2.engine.SessionRemote.connectEmbeddedOrServer(boolean)
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(ConnectionInfo, boolean)
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(String, Properties)
org.glowroot.agent.embedded.util.DataSource.createConnection(File)
org.glowroot.agent.embedded.util.DataSource.<init>(File)
org.glowroot.agent.embedded.init.EmbeddedAgentModule.createDataSource(boolean, File)
org.glowroot.agent.embedded.init.EmbeddedAgentModule.access$100(boolean, File)
org.glowroot.agent.embedded.init.EmbeddedAgentModule$1.run()
java.lang.Thread.run()

Glowroot info:
	Manifest-Version: 1.0
	Implementation-Title: Glowroot Agent
	Premain-Class: org.glowroot.agent.AgentPremain
	Build-Commit: b329aa934e8276502bb1473b107632e8b76969b5
	Implementation-Version: 0.13.5
	Built-By: trask
	Can-Redefine-Classes: true
	Build-Time: 2019-07-23 01:30:08 +0000
	Can-Retransform-Classes: true
	Created-By: Apache Maven 3.6.1
	Build-Jdk: 1.8.0_212
	Main-Class: org.glowroot.agent.ToolMai

Thanks in advance for the assistance.

**Comment by atulpendse** [comment]
+1

**Comment by lim255** [comment]
A quick update. 

I took the data directory and launch the Glowroot manually, outside of my application. I got the same error but the stack trace looks different.

# /tools/amazon-corretto-11.0.6.10.1-linux-x64/bin/java -jar glowroot.jar 
2020-08-04 10:53:05.292 INFO  org.glowroot - Glowroot version: 0.13.5, built 2019-07-23 01:30:08 +0000
2020-08-04 10:53:05.298 INFO  org.glowroot - Java version: 11.0.6 (Amazon.com Inc. / Linux)
2020-08-04 10:53:06.251 ERROR org.glowroot - Glowroot cannot start: Out of memory. [90108-176]
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: Out of memory. [90108-176]
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:167)
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.convert(DbException.java:288)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.openDatabase(Database.java:291)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.<init>(Database.java:254)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(Engine.java:57)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.openSession(Engine.java:164)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(Engine.java:125)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Engine.createSession(Engine.java:27)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.glowroot.agent.embedded.util.DataSource.createConnection(DataSource.java:624)
	at org.glowroot.agent.embedded.util.DataSource.<init>(DataSource.java:108)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.createDataSource(EmbeddedAgentModule.java:367)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.onEnteringMain(EmbeddedAgentModule.java:157)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit$1.run(EmbeddedGlowrootAgentInit.java:78)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit.init(EmbeddedGlowrootAgentInit.java:103)
	at org.glowroot.agent.MainEntryPoint.runOfflineViewer(MainEntryPoint.java:192)
	at org.glowroot.agent.embedded.ToolMain.main(ToolMain.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glowroot.agent.ToolMain.main(ToolMain.java:50)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.openDatabase(Database.java:277)
	... 22 common frames omitted


My application is configured with max heap around 3GB. This may be the reason why I hit the OOM. However, I configured the Glowroot to keep a minimal set of data, not more than 20MB. I am surprised to see Glowroot uses so much memory.

Did I misconfigure my Glowroot?

[data.old.tar.gz](https://github.com/glowroot/glowroot/files/5023700/data.old.tar.gz)

[admin.json.gz](https://github.com/glowroot/glowroot/files/5023759/admin.json.gz)


Thanks.

**Comment by Never-lab** [comment]
Classic embedded failure mode: hard/kill restarts leave **H2 `data.h2.db` needing recover**; recover can **OOM** and Glowroot won’t come back until the data dir is removed (your workaround). Same family as unbounded/corrupt H2 notes (#755 / #763).

Mitigations: graceful shutdown, lower retention/capped sizes, more heap headroom for recover, current 0.14.x. There is no reliable “auto heal corrupt H2” — delete/move `data/` (accept data loss) or restore a good backup.

@nowheresly — please close as support.
