### ISSUE TITLE
Getting error in SystemOut in WebSphere 9

### ISSUE THREAD

**Issue by lcp573** [glowroot/glowroot#753]
Good Morning
I am having a problem with websphere version 9, in AIX environment, Central collector: 0.13.5 and Agent: 0.13.5
I have to say glowroot works wonders, but I have a permanent exception in the SystemOut causing unnecessary IO to be generated on the server
The exception is the following:

2020-08-19 00:00:00.696 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java.lang.management.ManagementFactory$ServerHolder (initializ
ation failure)
java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory$ServerHolder (initialization failure)
at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:98)
at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
at org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
at org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.init(ServletWrapperImpl.java)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.load(ServletWrapper.java:1385)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1029)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963)
at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
at com.ibm.ws.ssl.channel.impl.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1187)
at com.ibm.ws.ssl.channel.impl.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:694)
at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
at com.ibm.ws.tcp.channel.impl.WorkQueueManager.requestComplete(WorkQueueManager.java:558)
at com.ibm.ws.tcp.channel.impl.WorkQueueManager.attemptIO(WorkQueueManager.java:608)
at com.ibm.ws.tcp.channel.impl.WorkQueueManager.workerRun(WorkQueueManager.java:985)
at com.ibm.ws.tcp.channel.impl.WorkQueueManager$Worker.run(WorkQueueManager.java:1074)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
Caused by: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.ibm.ws.management.PlatformMBeanServerBuilder: java.lang.ClassNotFoundExcepti
on: com.ibm.ws.management.PlatformMBeanServerBuilder
at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:514)
at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:550)
at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:327)
at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:242)
at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:203)
at java.lang.management.ManagementFactory$ServerHolder.(ManagementFactory.java:466)
at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
at oracle.jdbc.driver.OracleDriver.registerMBeans(OracleDriver.java:365)
at oracle.jdbc.driver.OracleDriver$1.run(OracleDriver.java:241)
at java.security.AccessController.doPrivileged(AccessController.java:647)
at oracle.jdbc.driver.OracleDriver.(OracleDriver.java:237)
at java.lang.J9VMInternals.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1848)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:391)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:415)
at java.util.ServiceLoader$1.next(ServiceLoader.java:491)
at java.sql.DriverManager$2.run(DriverManager.java:614)
at java.sql.DriverManager$2.run(DriverManager.java:594)
at java.security.AccessController.doPrivileged(AccessController.java:647)
at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:594)
at java.sql.DriverManager.(DriverManager.java:112)
at com.ibm.ws.runtime.component.JreMemoryLeakPreventionListener.lifecycleEvent(JreMemoryLeakPreventionListener.java:239)
at com.ibm.ws.runtime.component.MemoryLeakMgrImpl.initialize(MemoryLeakMgrImpl.java:150)
at com.ibm.ws.runtime.component.ContainerHelper.initWsComponent(ContainerHelper.java:1193)
at com.ibm.ws.runtime.component.ContainerHelper.initializeComponent(ContainerHelper.java:1100)
at com.ibm.ws.runtime.component.ContainerHelper.initializeComponents(ContainerHelper.java:902)
at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:776)
at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:750)
at com.ibm.ws.runtime.component.ApplicationServerImpl.initialize(ApplicationServerImpl.java:192)
at com.ibm.ws.runtime.component.ContainerHelper.initWsComponent(ContainerHelper.java:1193)
at com.ibm.ws.runtime.component.ContainerHelper.initializeComponent(ContainerHelper.java:1100)
at com.ibm.ws.runtime.component.ContainerHelper.initializeComponents(ContainerHelper.java:929)
at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:776)
at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:750)
at com.ibm.ws.runtime.component.ServerImpl.initialize(ServerImpl.java:377)
at com.ibm.ws.runtime.WsServerImpl.bootServerContainer(WsServerImpl.java:293)
at com.ibm.ws.runtime.WsServerImpl.start(WsServerImpl.java:224)
at com.ibm.ws.runtime.WsServerImpl.main(WsServerImpl.java:697)
at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at com.ibm.wsspi.bootstrap.WSLauncher.launchMain(WSLauncher.java:234)
at com.ibm.wsspi.bootstrap.WSLauncher.main(WSLauncher.java:101)
at com.ibm.wsspi.bootstrap.WSLauncher.run(WSLauncher.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
at org.eclipse.core.launcher.Main.run(Main.java:981)
at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:415)
at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:176)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
at java.net.URLClassLoader.findClass(URLClassLoader.java:610)
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:937)
at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:343)
at java.lang.ClassLoader.loadClass(ClassLoader.java:865)
at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:457)
at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:499)
... 64 common frames omitted

I've searched a lot before asking for help and can't really find any information about it
Any suggestion is welcome

Thank you!

**Comment by lcp573** [comment]
anyone with this error?

**Comment by asgerjensen** [comment]
FWIW I'm running on WAS 9 on Linux, using 0.13.4, and I'm not seeing this error.

**Comment by lcp573** [comment]
> FWIW I'm running on WAS 9 on Linux, using 0.13.4, and I'm not seeing this error.

Thanks for answering.
On other partitions with AIX I don't get the error either. I suspect that there is some duplicate class, embedded in one of the applications deployed in WAS, which causes the error ... but I cannot identify which one :(

**Comment by Never-lab** [comment]
Same call site as the WildFly/JBoss **platform MBean** family (`ContainerStartup.initPlatformMBeanServer` / servlet plugin): Glowroot asks for `ManagementFactory.getPlatformMBeanServer()` and on WAS/AIX the IBM `PlatformMBeanServerBuilder` isn’t visible to that class loader → noisy `NoClassDefFoundError` in SystemOut. Often environmentally specific (you already saw it on one AIX partition and not others).

Workarounds: ensure WAS management classes are visible to the app/TCCL path that triggers servlet init; try current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7); gauges may be degraded but tracing can still work. Related: `#1025` `#956`.

@nowheresly — keep as WAS/AIX compatibility, or close if “noise only / known platform MBean” is enough.
