### ISSUE TITLE
unable to send data to the central collector

### ISSUE THREAD

**Issue by shivpathak** [glowroot/glowroot#757]
Hi,

I am running glowroot-collector (as a central collector) of version `0.13.6` with cassandra as storage backend both running in `kubernetes` environment.

when I did setup it started up and everything looks good but after a while I started getting following error on my agent pod - 

```
 o.g.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: UNKNOWN (this warning will be logged at most once a minute, 4 warnings were suppressed since it was last logged)
```

The agent clearly says that there is some problem with glowroot-collector.

logs on glowroot-collector server as follows:
```
2020-10-19 08:32:36.845 ERROR o.g.central.CollectorServiceImpl - env::microservice::microservice-cc6957c97-8zjpx - All host(s) tried for query failed (no host was tried)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
	at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:83)
	at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
	at org.glowroot.central.util.MoreFutures.unwrapDriverException(MoreFutures.java:179)
	at org.glowroot.central.util.MoreFutures.waitForAll(MoreFutures.java:61)
	at org.glowroot.central.repo.TraceDaoImpl.storeInternal(TraceDaoImpl.java:860)
	at org.glowroot.central.repo.TraceDaoImpl.store(TraceDaoImpl.java:592)
	at org.glowroot.central.repo.TraceDaoImpl.store(TraceDaoImpl.java:582)
	at org.glowroot.central.CollectorServiceImpl.collectTraceUnderThrottle(CollectorServiceImpl.java:436)
	at org.glowroot.central.CollectorServiceImpl.access$400(CollectorServiceImpl.java:84)
	at org.glowroot.central.CollectorServiceImpl$4.run(CollectorServiceImpl.java:291)
	at org.glowroot.central.CollectorServiceImpl.throttle(CollectorServiceImpl.java:316)
	at org.glowroot.central.CollectorServiceImpl.throttledCollectTrace(CollectorServiceImpl.java:288)
	at org.glowroot.central.CollectorServiceImpl.access$900(CollectorServiceImpl.java:84)
	at org.glowroot.central.CollectorServiceImpl$TraceStreamObserver.onCompletedInternal(CollectorServiceImpl.java:752)
	at org.glowroot.central.CollectorServiceImpl$TraceStreamObserver.onCompleted(CollectorServiceImpl.java:674)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onHalfClose(ServerCalls.java:259)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:284)
	at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:62)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:376)
	at com.datastax.driver.core.RequestHandler.startNewExecution(RequestHandler.java:140)
	at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:122)
	at com.datastax.driver.core.SessionManager.execute(SessionManager.java:697)
	at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:143)
	at org.glowroot.central.util.Session.lambda$writeAsync$1(Session.java:222)
	at org.glowroot.central.util.Session.throttle(Session.java:409)
	at org.glowroot.central.util.Session.throttleWrite(Session.java:399)
	at org.glowroot.central.util.Session.writeAsync(Session.java:218)
	at org.glowroot.central.repo.TraceDaoImpl.storeInternal(TraceDaoImpl.java:716)
	... 18 common frames omitted
```

restarting glowroot collector and cassandra pod didn't helped, what could be the issue here?

I checked glowroot collector and cassandra service using telnet and was able to make connection successfully.

```
root@test-shiv:/# telnet glowroot-collector.mynamespace 4000
Trying 10.221.32.13...
Connected to glowroot-collector.mynamespace.svc.cluster.local.
Escape character is '^]'.
^]
telnet> q
Connection closed.

root@test-shiv:/# telnet glowroot-collector.mynamespace 8181
Trying 10.221.32.13...
Connected to glowroot-collector.mynamespace.svc.cluster.local.
Escape character is '^]'.
^]
telnet> q
Connection closed.

root@test-shiv:/# telnet cassandra-glowroot-service.mynamespace 9042
Trying 10.221.42.245...
Connected to cassandra-glowroot-service.mynamespace.svc.cluster.local.
Escape character is '^]'.
^]
telnet> q
Connection closed.

root@test-shiv:/# telnet cassandra-glowroot-service.mynamespace 8080
Trying 10.221.42.245...
Connected to cassandra-glowroot-service.mynamespace.svc.cluster.local.
Escape character is '^]'.
^]
telnet> q
Connection closed.
```

**Comment by shivpathak** [comment]
I found the issue:

My cassandra pod got restarted since then glowroot central was unable to make connection to cassandra pod.
After restarting glowroot central it started working fine.

The main problem was we are using single cassandra instance cluster with service type Headless in kubernetes after cassandra pod restart IP got changed for cassandra pod and glowroot keeps looking for old cassandra IP.

This is probably due to cassandra driver limitation on glowroot side.
