### ISSUE TITLE
Cassandra failure during read query at consistency QUORUM

### ISSUE THREAD

**Issue by ksunil6266** [glowroot/glowroot#785]
Facing this while running glowroot-central jar ,

full logs:- 

`com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency QUORUM (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.exceptions.ReadFailureException.copy(ReadFailureException.java:180)
	at com.datastax.driver.core.exceptions.ReadFailureException.copy(ReadFailureException.java:30)
	at org.glowroot.central.util.MoreFutures.unwrapDriverException(MoreFutures.java:179)
	at org.glowroot.central.util.MoreFutures.waitForAll(MoreFutures.java:61)
	at org.glowroot.central.repo.AggregateDaoImpl.rollup(AggregateDaoImpl.java:923)
	at org.glowroot.central.repo.AggregateDaoImpl.rollup(AggregateDaoImpl.java:826)
	at org.glowroot.central.repo.AggregateDaoImpl.rollup(AggregateDaoImpl.java:812)
	at org.glowroot.central.RollupService$1.run(RollupService.java:194)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency QUORUM (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.exceptions.ReadFailureException.copy(ReadFailureException.java:192)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:173)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:627)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1233)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1151)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
Caused by: com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency QUORUM (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:118)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:66)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:297)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:268)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)`

central-version= 0.13.6

**Comment by ksunil6266** [comment]
Any update on this ..

**Comment by ReillyBrogan** [comment]
@ksunil6266 The error means exactly what it says. "1 responses were required but only 0 replica responded, 1 failed". You should look into why your Cassandra cluster isn't responding occasionally. You may need to have additional replicas or increase the resources allocated to Cassandra, or any of a host of potential Cassandra changes.

This is not a Glowroot issue.

**Comment by ksunil6266** [comment]
@ReillyBrogan , can you please give me some minimal or maximum specifications of Cassandra which Glowroot used,

As I am using the docker containers using the below link(option:3).

https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation

**Comment by ReillyBrogan** [comment]
@ksunil6266 If you are doing that then you should check the logs of the cassandra container to see why it's not responding. The Docker commands on that page are mostly there as a quick start, and are unsuitable for any kind of production installation of Cassandra. 

The sizing of your Cassandra nodes, how many replicas you need, etc are all questions that can only be answered based on how many traces you are storing in Cassandra, how complex those traces are, number of metrics, data retention, etc. The only way to really know for sure is to test it out and see what works.

**Comment by ksunil6266** [comment]
@ReillyBrogan , is it the same issue 
https://github.com/glowroot/glowroot/issues/489

**Comment by ReillyBrogan** [comment]
@ksunil6266 Probably not. Did you do anything to check the logs of your Cassandra instance or did you just search the Github issues for anything that looked vaguely similar?

**Comment by ksunil6266** [comment]
@ReillyBrogan , yes I checked the log, not found anything


> ```
> INFO  [StorageServiceShutdownHook] 2021-03-11 08:41:12,322 HintsService.java:209 - Paused hints dispatch
> INFO  [StorageServiceShutdownHook] 2021-03-11 08:41:12,413 Server.java:179 - Stop listening for CQL clients
> INFO  [StorageServiceShutdownHook] 2021-03-11 08:41:12,418 Gossiper.java:1662 - Announcing shutdown
> INFO  [StorageServiceShutdownHook] 2021-03-11 08:41:12,419 StorageService.java:2452 - Node /a.b.c.d state jump to shutdown
> INFO  [StorageServiceShutdownHook] 2021-03-11 08:41:14,421 MessagingService.java:985 - Waiting for messaging service to quiesce
> INFO  [ACCEPT-/172.17.0.3] 2021-03-11 08:41:14,428 MessagingService.java:1346 - MessagingService has terminated the accept() thread
> INFO  [CompactionExecutor:2] 2021-03-11 08:41:17,512 CompactionManager.java:1895 - Compaction interrupted: Compaction@f935e630-7598-11eb-8d20-f58bd8d3766a(glowroot, trace_entry_v2, 1743963466/3234950108)bytes
> ```

**Comment by ksunil6266** [comment]
@ReillyBrogan . here is some update, so whenever I try to build glowroot agent without rollup configurations it works. but when I switch to the rollup setting in the agent config, the same error occurs in Glowroot central logs.

**Comment by ksunil6266** [comment]
Any luck here.

**Comment by trask** [comment]
hi @ksunil6266, managing Cassandra is a bit tricky, if you are still having issues, I'd recommend trying out a managed Cassandra service, e.g. https://docs.microsoft.com/en-us/azure/cosmos-db/cassandra/glowroot-cassandra
