### ISSUE TITLE
Invalid version number: Version number may be negative or greater than 255

### ISSUE THREAD

**Issue by prateek7j** [glowroot/glowroot#787]
I am using glowroot  glowroot-0.13.6-dist.zip on following java version:
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

Since Java8 version is >255 I am getting the following exception while trying to start Java server with glowroot agent whereas it's working properly with Java version:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

Exception encountered:
2021-03-16 04:44:53.493 ERROR org.glowroot - Glowroot cannot start: null
java.lang.ExceptionInInitializerError: null
        at com.ibm.icu.text.Collator.<clinit>(Collator.java:961)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.glowroot.agent.embedded.shaded.org.h2.value.CompareMode.<clinit>(CompareMode.java:58)
        at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:83)
        at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.glowroot.agent.embedded.util.DataSource.createConnection(DataSource.java:624)
        at org.glowroot.agent.embedded.util.DataSource.<init>(DataSource.java:108)
        at org.glowroot.agent.embedded.init.EmbeddedAgentModule.createDataSource(EmbeddedAgentModule.java:367)
        at org.glowroot.agent.embedded.init.EmbeddedAgentModule.access$100(EmbeddedAgentModule.java:76)
        at org.glowroot.agent.embedded.init.EmbeddedAgentModule$1.run(EmbeddedAgentModule.java:176)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
        at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:188)
        at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
        at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
        ... 12 common frames omitted

**Comment by ReillyBrogan** [comment]
@prateek7j I poked around this for a bit. As far as I can tell this issue is caused by icu4j being from any version before 68.1 ([this](https://github.com/unicode-org/icu/commit/9a6a64ce05b7257a85f8d04125428e4a081105b7#diff-209d8b0454c3b3a27b26047b765206b843c40a676eb42d537c357637038a5818) is the commit that fixes it). Now, Glowroot does not embed this library as it is typically provided as part of the JDK/JRE itself OR is put on the classpath by your application. 

To fix this you should try to update icu4j if it's part of your application (even if it's just part of your dependency tree) or manually put the updated version on your classpath.

**Comment by prateek7j** [comment]
@ReillyBrogan Thanks for looking into it & providing valuable support.
I put latest icu4j_68.2.jar in the classpath & glowroot is UP & running.
Thanks again.
