### ISSUE TITLE
ClassCircularityError

### ISSUE THREAD

**Issue by aaplavisharma** [glowroot/glowroot#809]
I am seeing the following error and wonder if folks have come across this. We are using glowroot 0.13.1. Version update to 0.13.6 also did not fix the issue.
java.lang.ClassCircularityError: com/google/common/util/concurrent/GwtFluentFutureCatchingSpecialization
    at java.lang.Class.forName0(Class.java)
    at java.lang.Class.forName(Class.java:348)
    at org.glowroot.agent.impl.BytecodeServiceImpl.preloadSomeSuperTypes(BytecodeServiceImpl.java:156)
    at org.glowroot.agent.bytecode.api.Bytecode.preloadSomeSuperTypes(Bytecode.java:83)
    at java.lang.ClassLoader.defineClass(ClassLoader.java)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at java.lang.Class.forName0(Class.java)
    at java.lang.Class.forName(Class.java:348)
    at org.glowroot.agent.impl.BytecodeServiceImpl.preloadSomeSuperTypes(BytecodeServiceImpl.java:156)
    at org.glowroot.agent.bytecode.api.Bytecode.preloadSomeSuperTypes(Bytecode.java:83)
    at java.lang.ClassLoader.defineClass(ClassLoader.java)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at java.lang.ClassLoader.defineClass1(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at java.lang.Class.forName0(Class.java)
    at java.lang.Class.forName(Class.java:348)
    at org.glowroot.agent.impl.BytecodeServiceImpl.preloadSomeSuperTypes(BytecodeServiceImpl.java:156)
    at org.glowroot.agent.bytecode.api.Bytecode.preloadSomeSuperTypes(Bytecode.java:83)
    at java.lang.ClassLoader.defineClass(ClassLoader.java)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

**Comment by Never-lab** [comment]
`ClassCircularityError` on Guava’s `GwtFluentFutureCatchingSpecialization` during `preloadSomeSuperTypes` is a known painful interaction: Glowroot’s preload walks supers while the app (or another agent) is defining the same Guava types. Seen especially on older **0.13.x** with Guava on the app classpath.

Please retry on current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7) with Glowroot as the **only** javaagent and no duplicate Guava shading surprises. If it still blows up, attach full JVM args + whether another agent is present. Related weave/preload sharp edges also show up under SecurityManager (#882).

@nowheresly — keep if reproducible on 0.14.x; otherwise close as support / upgrade.
