### ISSUE TITLE
Glowroot failed to start: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found

### ISSUE THREAD

**Issue by laks-martha** [glowroot/glowroot#813]
I am trying to Instrument java application running on Jetty server with using openjdk 11 version. I am using glowroot-0.13.6 version. I am running in embedded mode with default configuration. Java Application is working fine but Glowroot is not starting up. Seeing below exception in JVM logs.. It appears class loading issue. Could you please let me know how to resolve this issue. Thanks.

Glowroot failed to start: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
        at java.xml/javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:194)
        at java.xml/javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:147)
        at java.xml/javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:226)
        at java.xml/javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:147)
        at org.glowroot.agent.shaded.ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:79)
        at org.glowroot.agent.shaded.ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:57)
        at org.glowroot.agent.shaded.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
        at org.glowroot.agent.shaded.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at org.glowroot.agent.shaded.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at org.glowroot.agent.shaded.ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at org.glowroot.agent.shaded.ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at org.glowroot.agent.shaded.org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.glowroot.agent.shaded.org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55) 
        at org.glowroot.agent.shaded.org.slf4j.LoggerFactory.bind(LoggerFactory.java:150) 
        at org.glowroot.agent.shaded.org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.glowroot.agent.shaded.org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.glowroot.agent.shaded.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.glowroot.agent.MainEntryPoint.initLogging(MainEntryPoint.java:242)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ClassNotFoundException: org/apache/xerces/jaxp/SAXParserFactoryImpl
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.xml/javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:119)
        at java.xml/javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:183)
        ... 29 more

**Comment by trask** [comment]
hi @laks-martha, I'm not sure what's causing this, can you provide a repro that I can use to troubleshoot the issue?

**Comment by laks-martha** [comment]
@trask We are using Jetty server with Open JDK server. 
As per instructions we need to add "--exec -javaagent:<path>/glowroot.jar" to start.ini file. But application does not use start.ini file. we use wrapper-run.xml file to configure JVM arguments like below. 
<jvmarg value="-javaagent:/home/<app-home>/glowroot/glowroot.jar "/>
<jvmarg value="-agentpath:/home/<app-home>/yourkit-bin/libyjpagent.so=delay=240000,listen=all,disableoomedumper,port=10001"/>

If I use --exec flag in this argument value then JVM wont start up with this "Unrecognized option: --exec -javaagent:/home/sfdc/glowroot/glowroot.jar" error.
If I skip --exec argument, app starts but glowroot agent is not starting with above error.

**Comment by laks-martha** [comment]
@trask I am able to bring up glowroot agent with the below arguments. but my application failed to startup as it has a conflict with its own SAXParserFactory (org.apache.xerces.jaxp.SAXParserFactoryImpl). 

-javaagent:/home/<app-home>/glowroot/glowroot.jar -Djavax.xml.parsers.SAXParsorFactory=com.sun.org.xerces.internal.jaxp.SAXParserFactoryImpl

You can reproduce this issue with this argument  -Djavax.xml.parsers.SAXParsorFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl

Could you please suggest if there is any workaround? Thanks.

**Comment by Never-lab** [comment]
﻿Root cause (from your follow-up): the JVM sets ``javax.xml.parsers.SAXParserFactory`` to ``org.apache.xerces.jaxp.SAXParserFactoryImpl``, but that class is **not** visible on the agent/bootstrap path when Glowroot’s shaded logback initializes → ``FactoryConfigurationError``.

``--exec`` is a **Jetty start.ini** flag only — it does not belong in a plain ``-javaagent`` ``jvmarg``.

Workarounds:
1. Prefer the JDK factory for the process (or only while the agent starts): ``-Djavax.xml.parsers.SAXParserFactory=com.sun.org.xerces.internal.jaxp.SAXParserFactoryImpl`` (note spelling: ``SAXParserFactory``, not ``SAXParsorFactory``).
2. If the app **requires** Apache Xerces on the system property, ensure that jar is on a classpath the agent can load **or** avoid setting the property globally (set it later in app code after agent premain).
3. Dual agents (Glowroot + YourKit) increase weaving/classloader risk — try Glowroot alone while debugging.
4. Retry on current **0.14.x**.

Stale with no minimal repro beyond the system property. Further → [Discussions](https://github.com/glowroot/glowroot/discussions).

@nowheresly — OK to close as support / environment (XML factory clash).
