### ISSUE TITLE
NoClassDefFoundError for HttpServletRequest with JBoss EAP

### ISSUE THREAD

**Issue by sheldebaume** [glowroot/glowroot#830]
Hi,
We've started our app with JBoss EAP 6.4 using 
`set "JAVA_OPTS=%JAVA_OPTS% -javaagent:U:\JBoss\glowroot-0.13.6-dist\glowroot\glowroot.jar"`

When accessing our app web page, we've got a NoClassDefFoundError :
`Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.onReturn(RequestParameterAspect.java:41) [glowroot.jar:0.13.6]
	at com.icesoft.faces.webapp.http.servlet.ServletExternalContext$1.getParameter(ServletExternalContext.java)
	at com.asis.x2010.fmk.gui.listener.AsisPhaseListener.checkCASLogin(AsisPhaseListener.java:105)
	at com.asis.x2010.fmk.gui.listener.AsisPhaseListener.afterPhase(AsisPhaseListener.java:77)
	at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersAfter(PhaseListenerManager.java:92)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:109)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:80)
	at com.icesoft.faces.webapp.http.core.JsfLifecycleExecutor.apply(JsfLifecycleExecutor.java:50)
	at com.icesoft.faces.context.View$2$1.respond(View.java:85)
	at com.icesoft.faces.webapp.http.servlet.ServletRequestResponse.respondWith(ServletRequestResponse.java:242)
	at com.icesoft.faces.context.View$2.serve(View.java:119)
	at com.icesoft.faces.context.View.servePage(View.java:193)
	... 29 more`

Any idea what could be the problem ?

Thanks

Steve

**Comment by trask** [comment]
oh, this should be fixed also by #859

**Comment by sheldebaume** [comment]
Thanks @trask
