### ISSUE TITLE
o.g.a.w.WeavingClassFileTransformer

### ISSUE THREAD

**Issue by shubhankar946** [glowroot/glowroot#882]
I am trying to configure glowroot 0.13.6-dist with Elastcisearch 7.9.3 but getting access denied ERROR

2021-12-09 09:28:02.687 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2021-12-09 09:28:02.702 INFO  org.glowroot - Java version: 1.8.0_301 (Oracle Corporation / Windows 10)
2021-12-09 09:28:02.702 INFO  org.glowroot - Java args: -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:logs/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=32 -XX:GCLogFileSize=64m -javaagent:D:/ES7.9.3/elasticsearch-7.9.3/glowroot-0.13.6-dist/glowroot/glowroot.jar -Xshare:off -XX:+PrintFlagsFinal
2021-12-09 09:28:06.366 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2021-12-09 09:28:06.366 INFO  org.glowroot - Java version: 1.8.0_301 (Oracle Corporation / Windows 10)
2021-12-09 09:28:06.366 INFO  org.glowroot - Java args: -XX:+AlwaysPreTouch -Xss1m -XX:-OmitStackTraceInFastThrow -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:logs/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=32 -XX:GCLogFileSize=64m -javaagent:D:/ES7.9.3/elasticsearch-7.9.3/glowroot-0.13.6-dist/glowroot/glowroot.jar -XX:MaxDirectMemorySize=536870912
2021-12-09 09:28:16.343 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
2021-12-09 09:28:19.333 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:886)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.Class.checkMemberAccess(Class.java:2348)
	at java.lang.Class.getDeclaredMethods(Class.java:1974)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClassPlanC(AnalyzedWorld.java:454)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClassPlanB(AnalyzedWorld.java:343)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:288)
	at org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:240)
	at org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:187)
	at org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:144)
	at org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:129)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:213)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:674)
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:642)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:473)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:165)
	at org.elasticsearch.node.Node.<init>(Node.java:328)
	at org.elasticsearch.node.Node.<init>(Node.java:277)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
2021-12-09 09:28:20.112 ERROR o.g.a.i.PreloadSomeSuperTypesCache - access denied ("java.io.FilePermission" "D:\ES7.9.3\elasticsearch-7.9.3\glowroot-0.13.6-dist\glowroot\tmp\preload-some-super-types-cache" "write")
java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\ES7.9.3\elasticsearch-7.9.3\glowroot-0.13.6-dist\glowroot\tmp\preload-some-super-types-cache" "write")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:886)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:200)
	at org.glowroot.agent.impl.PreloadSomeSuperTypesCache.appendNewLinesToFile(PreloadSomeSuperTypesCache.java:221)
	at org.glowroot.agent.impl.PreloadSomeSuperTypesCache.writeToFile(PreloadSomeSuperTypesCache.java:173)
	at org.glowroot.agent.impl.PreloadSomeSuperTypesCache$1.run(PreloadSomeSuperTypesCache.java:152)
	at java.lang.Thread.run(Thread.java:748)
2021-12-09 09:28:20.591 ERROR o.g.a.s.o.g.c.util.ScheduledRunnable - access denied ("javax.management.MBeanServerPermission" "findMBeanServer")
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:886)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at javax.management.MBeanServerFactory.checkPermission(MBeanServerFactory.java:413)
	at javax.management.MBeanServerFactory.findMBeanServer(MBeanServerFactory.java:361)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.findAllMBeanServers(LazyPlatformMBeanServer.java:262)
	at org.glowroot.agent.init.GaugeCollector.runInternal(GaugeCollector.java:146)
	at org.glowroot.agent.shaded.org.glowroot.common.util.ScheduledRunnable.run(ScheduledRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-12-09 09:28:23.950 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving java/util/concurrent/CompletableFuture: java/util/concurrent/CompletableFuture
java.lang.ClassCircularityError: java/util/concurrent/CompletableFuture
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClassPlanC(AnalyzedWorld.java:454)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClassPlanB(AnalyzedWorld.java:343)
	at org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:288)
	at org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:240)
	at org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:187)
	at org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:144)
	at org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:129)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:213)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at org.elasticsearch.common.cache.Cache.<init>(Cache.java:493)
	at org.elasticsearch.common.cache.CacheBuilder.build(CacheBuilder.java:94)
	at org.elasticsearch.xpack.core.security.support.Automatons.buildCache(Automatons.java:213)
	at org.elasticsearch.xpack.core.security.support.Automatons.<clinit>(Automatons.java:52)
	at org.elasticsearch.xpack.security.Security.<init>(Security.java:334)
	at org.elasticsearch.xpack.security.Security.<init>(Security.java:320)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:691)
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:642)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:473)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:165)
	at org.elasticsearch.node.Node.<init>(Node.java:328)
	at org.elasticsearch.node.Node.<init>(Node.java:277)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
2021-12-09 09:28:24.987 ERROR o.g.a.i.PreloadSomeSuperTypesCache - access denied ("java.io.FilePermission" "D:\ES7.9.3\elasticsearch-7.9.3\glowroot-0.13.6-dist\glowroot\tmp\preload-some-super-types-cache" "write")
java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\ES7.9.3\elasticsearch-7.9.3\glowroot-0.13.6-dist\glowroot\tmp\preload-some-super-types-cache" "write")

**Comment by shubhankar946** [comment]
[glowroot.2021-12-09.log](https://github.com/glowroot/glowroot/files/7682178/glowroot.2021-12-09.log)

Attaching the log file as well

**Comment by ganeshan123** [comment]
Iam also facing the same issue, Any Solution for this.

**Comment by Never-lab** [comment]
Elasticsearch enables a **SecurityManager**. The log is classic permission denial while Glowroot weaves / writes tmp / touches JMX (`accessDeclaredMembers`, `FilePermission` on `glowroot/tmp`, `MBeanServerPermission`) — same SecurityManager family as #596, not a random weaver crash.

Grant Glowroot’s install dir (read/write/tmp) and the reflective/JMX permissions ES’s policy requires for javaagents, **or** run without ES security policy in a lab. Prefer current [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7) over 0.13.6. Dual APM on ES is still fragile (#938 / #709).

@nowheresly — please close as support (policy grants), or keep if you want a documented ES grant list.
