### ISSUE TITLE
Weaving breaks default method on EJB interfaces 

### ISSUE THREAD

**Issue by MFAshby** [glowroot/glowroot#883]
Steps to reproduce: 
* Have an application with remote EJBs (in this case deployed on WildFly 17)
* Add a `default` method to a remote EJB interface and some code which calls it.
* Add glowroot javaagent

Expected behaviour:
* EJB call succeeds

Actual behaviour:
* EJB call fails with NoSuchMethodError

Without glowroot agent, this code works OK. EJB makes heavy use of reflection to dispatch method calls to the right objects, and I suspect that glowroot's modifications to classes change the signature in a way that causes this to crash.

Workaround is to avoid `default` methods on EJB interfaces.

Excerpt of stack trace from the app which encountered this, saveSingleMessage is the default method.
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.Long java.lang.Object.saveSingleMessage(com.pkb.app.entity.LoggedInEHRRequestContext, java.lang.String, com.pkb.encounter.entity.Message, java.util.List)'
	at deployment.phr.ear.tolvenEJB.jar//com.pkb.encounter.bean.EHREncounterBean.saveSingleMessage(EHREncounterBean.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.as.ee@17.0.1.Final//org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
```

I'll try to produce a minimal repro of this soon.

**Comment by Never-lab** [comment]
Credible **weaving / EJB reflection** bug: remote EJB interface `default` methods work without the agent and fail with `NoSuchMethodError` with Glowroot (WildFly). Same broad family as other “agent changes what reflection expects” issues (see also Weld/generics threads like #977). Workaround you already have — avoid `default` methods on EJB remote interfaces — is the right short-term fix.

If you (or anyone) can still land a minimal EAR repro on current 0.14.x, that would unlock a real weaver fix; until then this stays a known sharp edge.

@nowheresly — keep open as weaving defect / needs minimal repro.

**Comment by Never-lab** [comment]
Not included in **#1218** (#1106/#721 only). EJB remote interface `default` methods still need a minimal EAR repro before a weaver change is safe.

@nowheresly

**Comment by Never-lab** [comment]
Closing as **obsolete**.

This report predates the current 0.14.x line, has no recent reproducible path, and we are not keeping it open without a fresh repro on a supported build. If it still happens, please open a new issue with version, JVM, and a minimal repro.

**Brief analysis:** EJB default-method weaving break marked needs-repro; no modern reproducer provided.
