### ISSUE TITLE
NoHostAvailableException from glowroot-central-collect

### ISSUE THREAD

**Issue by shivpathak** [glowroot/glowroot#900]
Hi,

We are facing connectionTimedOutException in glowroot-central (please se exception below)

**Setup:**
gloworoot-central-collector have multiple agents (roughly 15 microservices total containers around 60-70).
glowroot-central-collector usages cassandra db as backend.

**Issue:**
- glowroot-central-collector container throws following exception after couple of minutes, restarting solves the issue but only for few minutes.

**Note:** cassandra is always up and running.

**What I suspect:**
glowroot-central-collector cassandra driver might needs to be adjusted for connection pooling? (Just thoughts, please suggest in case this is wrong path).

`
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra-main-glowroot-service-cluster-ip/10.210.28.142:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [cassandra-main-glowroot-service-cluster-ip.ontrack-system/10.210.28.142:9042] Timed out waiting for server response))
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:284)
	at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:62)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:376)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.retry(RequestHandler.java:558)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.processRetryDecision(RequestHandler.java:540)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:981)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1582)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
`

please suggest where we can tune the performance or fix the issue.

**Comment by Never-lab** [comment]
﻿Same class of problem as other Central↔Cassandra capacity reports (`BusyPoolException` / `NoHostAvailableException` while Cassandra “is up”).

The Datastax pool on **Central** has no free connection within the timeout — usually Cassandra (or Central) cannot keep up with write volume from ~60–70 containers, not a missing “turn up one pool knob and forget sizing” fix.

Checklist: Cassandra CPU/disk/compaction/latency; Central heap/CPU; agent count + capture volume (slow threshold, gauges); size Cassandra for the write rate; upgrade Central+agents to current **0.14.x** together. Related: #748 #899 #957.

Stale (2022) with no sizing follow-up. Wiki: [Central Collector Installation](https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation). Qs → [Discussions](https://github.com/glowroot/glowroot/discussions).

@nowheresly — OK to close as ops/support (needs-info / stale).
