### ISSUE TITLE
A connection with a remote socket was reset by that socket

### ISSUE THREAD

**Issue by kingpric** [glowroot/glowroot#904]
When running glowroot at port 12123, error with message **A connection with a remote socket was reset by that socket** is logging on log.

Below is the complete log:-
2022-03-08 17:42:16.906 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2022-03-08 17:42:16.910 INFO  org.glowroot - Java version: 1.8.0_291 (IBM Corporation / AIX)
2022-03-08 17:42:16.933 INFO  org.glowroot - Java args: -Xoptionsfile=/data/was/java/jre/lib/ppc64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -XX:+OriginalJDK8HeapSizeCompatibilityMode -XX:+LegacyXlogOption -Xjcl:jclse29 -Xshareclasses:name=webspherev85_1.8_64_bundled_%g,nonFatal -Xcheck:dump -Xbootclasspath/p:/data/was/java/jre/lib/ibmorb.jar -Xms256m -Xmx2048m -Xcompressedrefs -Xscmaxaot16M -Xscmx120M -javaagent:/demo/glowroot/glowroot.jar
2022-03-08 17:42:21.629 INFO  org.glowroot - UI listening on 0.0.0.0:12123
2022-03-08 17:42:38.225 WARN  o.g.a.e.s.o.g.ui.HttpServerHandler - A connection with a remote socket was reset by that socket.
java.io.IOException: A connection with a remote socket was reset by that socket.
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:235)
	at sun.nio.ch.IOUtil.read(IOUtil.java:209)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:394)
	at org.glowroot.agent.shaded.io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261)
	at org.glowroot.agent.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at org.glowroot.agent.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:822)

**Comment by kingpric** [comment]
Its a firewall issue
