### ISSUE TITLE
Login Failed after updating to 0.14.0-beta.3 

### ISSUE THREAD

**Issue by ReillyBrogan** [glowroot/glowroot#925]
Hi! Just updated one of our test Glowroot clusters to 0.14.0-beta.3 and now logins are failing with the below exception:

```
2022-04-11 23:11:27.562 ERROR org.infinispan.CLUSTER - ISPN000474: Error processing request 42@glowroot-central-78b4cb66d9-zn82n-638
org.infinispan.commons.CacheException: ISPN000936: Class 'org.glowroot.ui.ImmutableSession$SerialForm' blocked by deserialization allow list. Adjust the configuration serialization allow list regular expression to include this class.
        at org.infinispan.commons.marshall.CheckedInputStream.resolveClass(CheckedInputStream.java:26)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
        at java.base/java.io.ObjectInputStream.readClassDesc(Unknown Source)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
        at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
        at org.infinispan.commons.marshall.JavaSerializationMarshaller.objectFromByteBuffer(JavaSerializationMarshaller.java:53)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectFromByteBuffer(AbstractMarshaller.java:82)
        at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectFromByteBuffer(DelegatingUserMarshaller.java:63)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:139)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:100)
        at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.unmarshall(ProtobufTagMarshallerDelegate.java:32)
        at org.infinispan.protostream.WrappedMessage.readMessage(WrappedMessage.java:539)
        at org.infinispan.protostream.WrappedMessage.read(WrappedMessage.java:351)
        at org.infinispan.protostream.ProtobufUtil.fromWrappedByteArray(ProtobufUtil.java:129)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:97)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:92)
        at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:905)
        at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:890)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:714)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.commands.write.PutKeyValueCommand.readFrom(PutKeyValueCommand.java:96)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.commands.remote.SingleRpcCommand.readFrom(SingleRpcCommand.java:56)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:164)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:86)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1449)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1389)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:144)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1562)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.pbcast.STATE_TRANSFER.up(STATE_TRANSFER.java:129)
        at org.jgroups.protocols.FRAG2.up(FRAG2.java:174)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.Encrypt.handleEncryptedMessage(Encrypt.java:276)
        at org.jgroups.protocols.Encrypt.up(Encrypt.java:189)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups.protocols.BARRIER.up(BARRIER.java:171)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FD.up(FD.java:227)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

I fully adapted the cluster configuration as described in the recent JDK 17 PR and as far as I can tell the cluster jgroups configuration is correct as I'm seeing messages like the following indicating successful cluster formation:
```
2022-04-11 23:09:54.324 INFO  org.infinispan.CLUSTER - [Context=sessionMap] ISPN100002: Starting rebalance with members [glowroot-central-78b4cb66d9-jft9v-53911, glowroot-central-78b4cb66d9-zn82n-638], phase READ_OLD_WRITE_ALL, topology id 2
2022-04-11 23:09:54.565 INFO  org.infinispan.CLUSTER - [Context=sessionMap] ISPN100009: Advancing to rebalance phase READ_ALL_WRITE_ALL, topology id 3
2022-04-11 23:09:54.643 INFO  org.infinispan.CLUSTER - [Context=sessionMap] ISPN100009: Advancing to rebalance phase READ_NEW_WRITE_ALL, topology id 4
2022-04-11 23:09:54.696 INFO  org.infinispan.CLUSTER - [Context=sessionMap] ISPN100010: Finished rebalance with members [glowroot-central-78b4cb66d9-jft9v-53911, glowroot-central-78b4cb66d9-zn82n-638], topology id 5
```

Jgroups config file (note that we manage this file with Helm so that's where that .Release.Namespace template thing comes from:
``` 
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">

  <TCP bind_port="7800"
       recv_buf_size="${jgroups.recvBufSize:130k}"
       send_buf_size="${jgroups.sendBufSize:130k}"
       max_bundle_size="64K"
       enable_diagnostics="false"
       sock_conn_timeout="300"
       thread_pool.min_threads="${jgroups.minThreads:0}"
       thread_pool.max_threads="${jgroups.maxThreads:20}"
       thread_pool.keep_alive_time="30000" />
  <org.jgroups.protocols.kubernetes.KUBE_PING
     port_range="0"
     namespace="{{ .Release.Namespace }}"
     labels="app=glowroot-central"
  />
  <MERGE3  min_interval="10000"
           max_interval="30000" />
  <FD_SOCK />
  <FD timeout="30000" max_tries="3" />
  <VERIFY_SUSPECT timeout="1500" />
  <BARRIER />
  <pbcast.NAKACK2 use_mcast_xmit="false"
                  discard_delivered_msgs="true" />
  <UNICAST3 />
  <pbcast.STABLE desired_avg_gossip="50000"
                 max_bytes="4M" />
  <!-- Symmetric encryption with a keystore -->
  <SYM_ENCRYPT
          provider="SunJCE"
          sym_algorithm="AES/CBC/PKCS5Padding"
          sym_iv_length="16"
          keystore_name="${jgroups.symEncryptKeystoreLocation}"
          store_password="glowroot"
          alias="cluster"
          key_password="glowroot"
  />
  <pbcast.GMS print_local_addr="false"
              join_timeout="${jgroups.joinTimeout:2000}" />
  <MFC max_credits="2M"
       min_threshold="0.4" />
  <FRAG2 frag_size="60K" />
  <pbcast.STATE_TRANSFER />
</config>
```

The only change that I made from moving from 0.13.6 (running on JDK 11) was swapping out the SASL section for the SYM_ENCRYPT section as described in the JDK 17 PR. 

We built the cluster image with the Semeru (AKA OpenJ9) jdk-17.0.2+8_openj9-0.30.0 runtime.

**Comment by ReillyBrogan** [comment]
CC @Nowheresly

**Comment by ReillyBrogan** [comment]
Update, I added `"org\\.glowroot\\.ui\\..*",` to line 132 of `central/src/main/java/org/glowroot/central/util/ClusterManager.java` and login is working now. I'm unsure of whether it's a good idea to just whitelist all UI classes or whether scoping it to just anything session related is fine.

**Comment by trask** [comment]
@ReillyBrogan thanks for reporting this!

> Update, I added `"org\\.glowroot\\.ui\\..*",` to line 132 of `central/src/main/java/org/glowroot/central/util/ClusterManager.java` and login is working now. I'm unsure of whether it's a good idea to just whitelist all UI classes or whether scoping it to just anything session related is fine.


I think this is good, see similar discussion at https://github.com/glowroot/glowroot/pull/909#discussion_r835982091

can you send PR?

**Comment by Nowheresly** [comment]
That's correct @ReillyBrogan. Thank you for taking the time to test it. That's really helpful!
