### ISSUE TITLE
HttpServerHandler - Connection reset (Netty)

### ISSUE THREAD

**Issue by robinroos** [glowroot/glowroot#942]
Running Glowroot Central inside OpenShift (hooray!) I get "Connection reset" exceptions from Netty every minute.

I raised this as a comment on the existing issue over at Netty, which the team there are as-yet unable to reproduce ( https://github.com/netty/netty/issues/12082 ).

Raising here for tracability.  If Netty can identify root cause and fix, then Glowroot will need to adopt the latest Netty release to avail of that fix.

It is possible that the error only presents in a containerised environment.

```
2022-06-06 08:16:16.503 INFO  org.glowroot - Glowroot version: 0.14.0-beta.4-SNAPSHOT, built 2022-06-02 07:19:47 +0000
2022-06-06 08:16:16.506 INFO  org.glowroot - Java version: 17.0.2
...
2022-06-06 08:16:16.727 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
...
2022-06-06 08:24:27.528 INFO  org.glowroot - gRPC listening on 0.0.0.0:8181
2022-06-06 08:24:27.820 INFO  org.glowroot - UI listening on 0.0.0.0:4000
2022-06-06 08:24:27.820 INFO  org.glowroot - startup complete
2022-06-06 08:25:19.214 WARN  org.glowroot.ui.HttpServerHandler - Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Nowheresly** [comment]
Hi @robinroos 
Maybe could you try to increase the log level to DEBUG of glowroot central using the approach described here:
https://github.com/glowroot/glowroot/blob/979535d28ceca0e9e7b1ec3067ffc9bf456c6364/central/src/main/resources/logback.xml#L5

Set root level to DEBUG here
https://github.com/glowroot/glowroot/blob/979535d28ceca0e9e7b1ec3067ffc9bf456c6364/central/src/main/resources/logback.xml#L33

**Comment by robinroos** [comment]
Not sure how to accomplish that, given that I install the Helm chart and launch from there.  Perhaps the ConfigMap contains log settings - I will check that.

Should we consider adding SocketException with message "Connection reset" to the list of exceptions logged only at Debug here: https://github.com/glowroot/glowroot/blob/715d6e403a1306bffe29367f7a4f5a0a7b63e0ca/ui/src/main/java/org/glowroot/ui/HttpServices.java#L61

Such an action was implicit in a comment on https://github.com/netty/netty/issues/12082 .

**Comment by Never-lab** [comment]
﻿``HttpServerHandler`` ``Connection reset`` on Central UI/gRPC in OpenShift is very often **benign** (LB/health probes, idle close, client abort) — Netty surfaces it; not proof of a Glowroot data bug. @nowheresly’s DEBUG tip helps confirm.

Reasonable product tweak (as you and the Netty thread suggested): treat ``SocketException: Connection reset`` like other browser-disconnect noise in ``HttpServices.shouldLogException`` (log at DEBUG only). That is a small **enhancement**, independent of waiting on a Netty upstream fix / Netty bump.

OK to close as ops/noise, or keep labeled enhancement for the quieter logging.

@nowheresly
