### ISSUE TITLE
Glowroot failure: Too many open files, gauge value collection rejected due to backlog

### ISSUE THREAD

**Issue by adc-jnguyen** [glowroot/glowroot#957]
We've been using Glowroot to monitor our java applications (using a rollup for the different application and the test/production environments for each application). Our application works briefly for a few days but then we start these warnings in the logs and eventually we find that the application is down. These are some excerpts from the glowroot-central.log file, I was hoping to get some assistance on the causes and what we can do to get the application functional. 

**Warnings we see while the collector is running, but failing to display on the UI:**
`WARN  o.g.central.CollectorServiceImpl - BITBUCKET::PROD::NODE1 - gauge value collection rejected due to backlog 2022-10-11 17:11:16.094 WARN  o.g.central.CollectorServiceImpl - BITBUCKET::PROD::NODE1 - 2022-10-11 17:11:16.096 WARN org.glowroot.agent.central.CentralConnection - unable to send data to the central collector: org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: collection rejected due to backlog (this warning will be logged at most once a minute, 1 warnings were suppressed since it was last logged)`

**central collector is down, unable to access the UI:**
`2022-10-13 09:49:32.086 WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:421)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:249)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:750)
`

May be unrelated, but is this a problem with the way the database is configured or resources allocated to glowroot?  We noticed these logs for cassandra previously as well: 
`ERROR [MutationStage-7] 2022-09-22 12:37:15,669 StorageProxy.java:1542 - Failed to apply mutation locally : 
ERROR [MutationStage-2] 2022-09-22 12:37:38,950 StorageProxy.java:1542 - Failed to apply mutation locally : 
ERROR [MutationStage-4] 2022-09-22 12:37:58,802 StorageProxy.java:1542 - Failed to apply mutation locally : 
ERROR [MutationStage-4] 2022-09-22 12:38:20,591 StorageProxy.java:1542 - Failed to apply mutation locally : 
WARN  [ReadStage-1] 2022-09-22 12:38:39,962 ReadCommand.java:536 - Read 10 live rows and 1190 tombstone cells for query SELECT child_agent_rollup, transaction_types FROM glowroot.aggregate_needs_rollup_from_child WHERE agent_rollup = BITBUCKET::PROD:: LIMIT 5000; token 2143402896946179421 (see tombstone_warn_threshold)`

**Comment by visva2005** [comment]
Hi Josh, Is this issue resolved? May I know the root cause and fix for it?

**Comment by visva2005** [comment]
@joshnadc  Is this issue resolved? May I know the root cause and fix for it?

**Comment by Never-lab** [comment]
This reads as an **ops / capacity** problem on **Glowroot Central + Cassandra**, not a bug in the monitored application. The central process is falling over; the `RESOURCE_EXHAUSTED` messages are the agent being told “Central is overloaded / backlogged.”

### How the symptoms fit together

1. **`gauge value collection rejected due to backlog` / `RESOURCE_EXHAUSTED`**  
   Central is refusing new gauge (and similar) writes because an internal queue is full. Usual causes: Central or Cassandra too slow/small for the agent volume, or Central already unhealthy.

2. **`java.io.IOException: Too many open files` on Central**  
   The Central JVM hit the OS **file descriptor** limit (`ulimit -n` / systemd `LimitNOFILE`). After that, Netty can’t accept connections → UI/gRPC die. This is almost always an environment limit (or a FD leak under sustained overload), not “Glowroot can’t run.”

3. **Cassandra `Failed to apply mutation locally` + tombstone warnings** on `aggregate_needs_rollup_from_child`  
   Strong signal that **Cassandra is struggling** (disk/CPU/compaction, or tombstone-heavy reads). When Cassandra lags, Central backlogs → agents get `RESOURCE_EXHAUSTED` → if FDs also run out, Central goes dark. Rollups + frequent agent traffic make this worse on undersized clusters.

So: treat it as **Cassandra health + Central host limits + agent volume**, not “reconfigure the Java app.”

### What to check / do

| Area | Action |
|------|--------|
| Host for Central | `ulimit -n` / systemd `LimitNOFILE` — raise substantially (e.g. 65535+), restart Central, confirm with `ls /proc/<pid>/fd \| wc -l` under load |
| Cassandra | Disk, compaction pending, GC, mutation stage errors; tombstone_warn on rollup tables → review TTL/compaction and whether the cluster is sized for your agent count / rollup agents (`BITBUCKET::PROD::…`) |
| Central | Heap, CPU; avoid co-locating Central+Cassandra on a starved box if that’s the case |
| Agents | After Central is healthy, confirm backlog warnings stop; temporarily reduce gauge/trace volume if needed while recovering |
| Versions | Logs look like the **0.13 / 2022** era — if still on that line, plan an upgrade to current **0.14.x** after stabilizing infra |

### Status

Opened **2022**, one “is this fixed?” ping in **2023**, **no resolution from the reporter**. Without current versions, `ulimit`, Cassandra sizing, and whether it still happens on 0.14.x, this isn’t an actionable product bug.

I’d close as **stale / needs-info (ops)** unless someone can still reproduce on a recent Central with FD limits and Cassandra metrics attached.

@nowheresly — I can’t close issues; please close if you agree (or leave open only as a tracking note for “Central backlog + ulimit + Cassandra tombstones” runbook).
