### ISSUE TITLE
Error deploying version Glowroot version: 0.14.0-beta.3 on agents apps

### ISSUE THREAD

**Issue by ernestoalejandrocu** [glowroot/glowroot#971]
2023-01-11 15:54:01.115 ERROR o.g.agent.impl.BytecodeServiceImpl - Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
        at org.glowroot.agent.central.CentralConnection.<init>(CentralConnection.java:121)
        at org.glowroot.agent.central.CentralCollector.<init>(CentralCollector.java:135)
        at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:136)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:255)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
        at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
        at org.jboss.Main.main(Main.java)

**Comment by ernestoalejandrocu** [comment]
Fixed with major java release

**Comment by Dinty0** [comment]
Reopening this issue because i have the same problem but due to project constraints i am unable to change my JDK.

I had to anonymize some bits of logs with XXX.

Java version : 
> openjdk version "1.8.0_191"
> OpenJDK Runtime Environment (build 1.8.0_191-b12)
> OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`

Agent version : 0.14.0
Central collector version : 0.14.0

2023-06-30 10:25:22.327 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-06-30 10:25:22.331 INFO  org.glowroot - Java version: 1.8.0_191 (Oracle Corporation / Linux)
2023-06-30 10:25:22.332 INFO  org.glowroot - Java args: -javaagent:/XXX/glowroot_agent/glowroot.jar -Xbootclasspath/p:/XXX/alpn-boot-8.1.13.v20181017.jar -Xms2048m -Xmx6144m -XX:+UseG1GC -XX:+UseStringDeduplication
2023-06-30 10:25:30.863 INFO  org.glowroot - agent id: XXX_XXX
2023-06-30 10:25:31.174 ERROR o.g.agent.impl.BytecodeServiceImpl - Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.glowroot.agent.central.CentralConnection.<init>(CentralConnection.java:121)
	at org.glowroot.agent.central.CentralCollector.<init>(CentralCollector.java:135)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:136)
	at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:255)
	at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77)
	at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32)
	at XXXX.mainclass.main(XXX.java)
	
I tried to manually add the jetty alpn boot jar in the classpath with the JVM ARG 
> Xbootclasspath/p:/XXX/alpn-boot-8.1.13.v20181017.jar

It doesn't solve the issue.

Thanks in advance for any lead you may have.
