### ISSUE TITLE
NullPointerException when deploying EAR in jboss EAP7.4.8 and glowroot configured

### ISSUE THREAD

**Issue by sheldebaume** [glowroot/glowroot#977]
Hi team,

We're facing a problem when trying to deploy our EAR application in jboss AS EAP7.4.8, and glowroot activated.

```
11-01-2023 11:13:12,746 ERROR [org.jboss.msc.service.fail] MSC000001: Failed to start service jboss.deployment.unit."wcs-Application.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."wcs-Application.ear".WeldStartService: Failed to start service
	at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:60)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:78)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.resources.SharedObjectCache.getTypeClosureHolder(SharedObjectCache.java:77)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotated.initTypeClosure(BackedAnnotated.java:23)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotated.<init>(BackedAnnotated.java:19)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedParameter.<init>(BackedAnnotatedParameter.java:52)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedParameter.of(BackedAnnotatedParameter.java:44)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedParameter.forExecutable(BackedAnnotatedParameter.java:38)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedCallable.initParameters(BackedAnnotatedCallable.java:42)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedCallable.<init>(BackedAnnotatedCallable.java:38)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.<init>(BackedAnnotatedMethod.java:29)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.of(BackedAnnotatedMethod.java:25)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:198)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:191)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:159)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:191)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:191)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:66)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:47)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:84)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:79)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$null$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.WeakLazyValueHolder$1.computeValue(WeakLazyValueHolder.java:35)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.WeakLazyValueHolder.get(WeakLazyValueHolder.java:53)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:78)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:177)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:194)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadSlimAnnotatedType(FastAnnotatedTypeLoader.java:124)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.createContext(FastAnnotatedTypeLoader.java:114)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:103)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:55)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:52)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.core@3.1.6.Final-redhat-00001//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

When removing glowroot at startup, no problem for deploying.
With previous JBoss version (7.3.10) we're not facing this issue.
Glowroot version : 0.13.6

Any idea ?

Regards,

Steve

**Comment by rsassi** [comment]
I encountered the same issue. After debugging, I found that sun.reflect.generics.repository.MethodRepository#computeReturnType returns null when extracting the return type from the subtree.

Tack trace:
<img width="413" height="146" alt="Image" src="https://github.com/user-attachments/assets/55f7a472-a14f-4353-99e0-40f305ec7910" />

org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod#BackedAnnotatedMethod 31:
<img width="909" height="65" alt="Image" src="https://github.com/user-attachments/assets/089cacf5-0781-4bab-ba15-a207e806def4" />

org.jboss.weld.annotated.slim.backed.BackedAnnotatedCallable#BackedAnnotatedCallable 38:
<img width="1145" height="591" alt="Image" src="https://github.com/user-attachments/assets/26c31bde-f52c-4ce1-a2ea-bf5e8d0f6609" />


The parameters types also are null.

**Comment by rsassi** [comment]
My understanding:

To make the issue clearer, here is a simplified class diagram representing the inheritance:

GenericParentA<T>
       ▲
       │
GenericParentB<U>
       ▲
       │
   ConcreteChild

- Both `GenericParentA<T>` and `GenericParentB<U>` are generic.
- `ConcreteChild` is **not** generic.

The problem is that a **generic method** is being generated in `ConcreteChild`, as if it still declares type parameters. But since `ConcreteChild` is not generic, this is invalid – the type parameters should have been resolved already during compilation.

➡️ The method in the generated bytecode still includes type parameters like `<T>` or `<U>`, even though `ConcreteChild` does not define them.

This seems to be an issue with how the bytecode generation handles inheritance and generics resolution.

**Comment by rsassi** [comment]
**Root Cause: Improper handling of generic specialization in `overrideAndWeaveInheritedMethod`**

The method `org.glowroot.agent.weaving.WeavingClassVisitor#overrideAndWeaveInheritedMethod` does not correctly account for specialized generic signatures in subclass methods. When inherited methods have generics that are specialized in subclasses, the signature matching logic fails, causing invalid method resolution and leading to a NullPointerException during reflection after weaving.

**Comment by rsassi** [comment]
> > ### 🔧 Implementation Update
> > Implementation for **generic specialization weaving** has been completed in branch [`weaving-generic-specialization-977`](https://github.com/rsassi/glowroot/tree/weaving-generic-specialization-977).
> > Changes include:
> > 
> > * Added support for **generic type specialization** in the weaving process.
> > 
> > ✅ Works for my case, and I'm now checking it against other real applications.
> > The branch has been **pushed and is ready for review**. A pull request will be created after tests are verified. 🧪 Any help with testing is **welcome and appreciated**!
> 
> Hi [@rsassi](https://github.com/rsassi)
> 
> I've just tested [glowroot-0.14.5-beta.1-dist.zip](https://github.com/glowroot/glowroot/releases/download/v0.14.5-beta.1/glowroot-0.14.5-beta.1-dist.zip), but I have the same issue when starting my application in JBoss EAP 8.1.1
> 
> 17:04:53,350 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."tra-Application.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."tra-Application.ear".WeldStartService: Failed to start service
> 	at org.jboss.msc@1.5.5.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1609)
> 	at org.jboss.msc@1.5.5.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
> 	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
> 	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
> 	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:62)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.resources.SharedObjectCache.getTypeClosureHolder(SharedObjectCache.java:79)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotated.initTypeClosure(BackedAnnotated.java:23)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotated.<init>(BackedAnnotated.java:19)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedMember.<init>(BackedAnnotatedMember.java:20)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedCallable.<init>(BackedAnnotatedCallable.java:38)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.<init>(BackedAnnotatedMethod.java:31)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.of(BackedAnnotatedMethod.java:27)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:204)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:197)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:165)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:197)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:197)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:72)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:52)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:84)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:79)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:57)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.WeakLazyValueHolder$1.computeValue(WeakLazyValueHolder.java:35)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.WeakLazyValueHolder.get(WeakLazyValueHolder.java:53)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:74)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:201)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadSlimAnnotatedType(FastAnnotatedTypeLoader.java:128)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.createContext(FastAnnotatedTypeLoader.java:118)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:107)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:55)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:52)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.core@5.1.6.Final-redhat-00001//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> 	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:513)


Hi @sheldebaume 
Could you please check out the branch  
[`weaving-generic-specialization-977`](https://github.com/rsassi/glowroot/tree/weaving-generic-specialization-977),  
build it, and run the tests to verify the changes?

Regards,

**Comment by rsassi** [comment]
Hi @sheldebaume 

you can find the build of new PR here [glowroot-agent-0.14.5-beta.2.1-dist.zip](https://github.com/rsassi/glowroot/releases/download/977-0.14.5-beta.2-SNAPSHOT-v2/glowroot-agent-0.14.5-beta.2.1-dist.zip)

**Comment by rsassi** [comment]
Hi @Nowheresly 

I’m unable to determine whether the glowroot-webdriver-tests failure is caused by my changes, as I can’t run those tests locally.

could you please help check?

**Comment by Never-lab** [comment]
﻿**Hard weaving bug** (keep open): Glowroot + JBoss/Weld NPE in ``ConcurrentHashMap.get`` while building annotated types — without the agent, deploy works. Community analysis (@rsassi) points at invalid/generic signatures from ``WeavingClassVisitor#overrideAndWeaveInheritedMethod`` when a **non-generic** subclass inherits **generic** parents (bridge/specialization), related spirit to #550.

### Status
- Open PRs: [#1157](https://github.com/glowroot/glowroot/pull/1157) (and earlier [#1156](https://github.com/glowroot/glowroot/pull/1156)). Not confirmed fixed for all reporters on stock **0.14.5** / EAP 8.
- Module.xml ``java.management`` gaps are a **separate** class of failure (#1025) — don’t conflate with this Weld NPE.

### Debug playbook (for anyone reproducing)
1. Confirm fail **only** with ``-javaagent``.
2. Isolate the class: ``-Dglowroot.debug.className=…`` → inspect woven bytecode (``javap``) vs without agent.
3. Prefer a minimal EAR/EJB repro (generic parents → concrete child) over full product EAR.
4. Any fix: unit/IT around weaving generics + smoke on WildFly/EAP; watch webdriver/CI regressions.

@nowheresly — keep as **bug** linked to #1157; happy to help review/test when you want a second pair of eyes.
