### ISSUE TITLE
Collision with others java agents at startup

### ISSUE THREAD

**Issue by bflorat** [glowroot/glowroot#986]
When starting a spring boot application (war packaging) with both agents Jolokia and Glowroot attached, we get the error bellow in some seldom cases (when CPU consumption is high so agents threads run concurrently). We can reproduce this easily by generating high CPU consumption (for instance using the 'stress' command).

Do you think there is something we can do to prevent this ?

```
JAVA_OPTS="-Djava.awt.headless=true -Xms1024M -Xmx1024M -XX:+PrintGC -XX:+PrintGCDetails -Xloggc:/var/log/tomcat-batch-4/loggc.log -javaagent:/usr/share/jolokia/jolokia-jvm-agent.jar=host=IP-PROD,port=**** -Djava.net.preferIPv4Stack=true -javaagent:/var/local/share/glowroot/glowroot/glowroot.jar -Dglowroot.agent.id=tomcat-intranet-batch-4"
```

```
 java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)
``` 

```
25407 Mar  1 14:25:14 **** tomcat-****-intranet-batch-4[22164]: 2 Spring WebApplicationInitializers detected on classpath
25408 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:   .   ____          _            __ _ _
25409 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
25410 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
25411 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
25412 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:   '  |____| .__|_| |_|_| |_\__, | / / / /
25413 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:  =========|_|==============|___/=/_/_/_/
25414 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]:  :: Spring Boot ::                (v2.6.6)
25415 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]: 2023-03-01 14:25:16,737|[main]|INFO|NO_TID|NO_USER|foo.****.ServletInitializer|Starting ServletInitializer v0.18.1 using Java 11.0.18 on **** with PID 22164 (/var/local/share/****/tomcat/****-***-batch/****-***-batch-0.18.1/WEB-INF/classes started by tomcat in /var/lib/tomcat-****-intranet-batch-4)
25416 Mar  1 14:25:16 **** tomcat-****-intranet-batch-4[22164]: 2023-03-01 14:25:16,789|[main]|INFO|NO_TID|NO_USER|foo.****.ServletInitializer|No active profile set, falling back to 1 default profile: "default"
25417 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]: Exception in thread "jolokia-0" java.lang.IncompatibleClassChangeError: Class sun.net.httpserver.HttpExchangeImpl does not implement the requested interface org.glowroot.agent.plugin.javahttpserver.HttpHandlerAspect$HttpExchange
25418 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at org.glowroot.agent.plugin.javahttpserver.HttpHandlerAspect$HandleAdvice.onBeforeCommon(HttpHandlerAspect.java:134)
25419 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at org.glowroot.agent.plugin.javahttpserver.HttpHandlerAspect$HandleAdvice.onBefore(HttpHandlerAspect.java:87)
25420 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java)
25421 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
25422 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:817)
25423 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
25424 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
25425 Mar  1 14:25:18 **** tomcat-****-intranet-batch-4[22164]:     at java.base/java.lang.Thread.run(Unknown Source)


```

**Comment by Never-lab** [comment]
This is a **real multi-agent weaving conflict**, not a Spring Boot app bug.

### What’s going on

Jolokia’s JVM agent serves over the JDK **`com.sun.net.httpserver`** stack. Glowroot’s **`java-http-server`** plugin weaves `HttpHandler.handle(HttpExchange)` and expects `HttpExchange` instances to carry Glowroot’s shim interface (`HttpHandlerAspect$HttpExchange`).

Under load (you already correlated with high CPU / concurrent agent threads), class transformation / loading can race between **Jolokia** and **Glowroot**. Then `sun.net.httpserver.HttpExchangeImpl` is *not* shimmed the way the advice expects →:

`IncompatibleClassChangeError: Class sun.net.httpserver.HttpExchangeImpl does not implement the requested interface org.glowroot.agent.plugin.javahttpserver.HttpHandlerAspect$HttpExchange`

on the `jolokia-*` thread (your stack). That’s Glowroot advice running on Jolokia’s HTTP server, not on your Tomcat/Spring request path.

### Practical mitigations (try in order)

1. **Agent order** — put Glowroot first, then Jolokia (or the reverse if the first order still races). Restart and re-run the `stress` repro.
2. **If you don’t need Glowroot to monitor JDK HttpServer / Jolokia** (typical for a Tomcat WAR — Servlet plugin covers the app): remove or move aside the plugin jar under the Glowroot agent `lib/` directory matching **`java-http-server`** / `glowroot-agent-java-http-server-plugin*.jar`, then restart. Your Spring/Tomcat traffic should still be instrumented.
3. **Upgrade** Glowroot to a current **0.14.x** and re-test the same dual-agent + CPU stress setup.

A durable code fix would mean hardening that plugin against non-shimmed `HttpExchange` types (or excluding JDK HttpServer classes used only by other agents). That’s non-trivial weaving work and isn’t tracked elsewhere that I can see.

### Status

Opened **2023-03**, **no follow-up comments**. Unless this still reproduces on a recent agent with a short “still happens / these workarounds helped” note, I’d treat it as **stale / needs-info**.

@nowheresly — I can’t close issues; please close as stale/needs-info if you’re fine with that, or leave open if you want it as a tracked dual-agent weaving bug.

**Comment by bflorat** [comment]
Thanks. 
We used the second solution for years and it works great.
