### ISSUE TITLE
HTTP to HTTPS - "Missing lib/glowroot-central-collector-https-linux.jar" error

### ISSUE THREAD

**Issue by SpencerWoo** [glowroot/glowroot#989]
Hi all, I'm running an Agent and Central Collector and attempting to setup HTTPS.  I'm following https://github.com/glowroot/glowroot/wiki/Agent-Installation-(for-Central-Collector)#https-between-the-agent-and-central-collector

My connection works successfully with HTTP on 8181, however when I attempt HTTPS on 8182 I get the following error on the agent and no logs on the collector.
```
2023-03-16 16:34:57.019 INFO  org.glowroot - Glowroot version: 0.13.6, built 2020-03-01 01:25:31 +0000
2023-03-16 16:34:57.021 INFO  org.glowroot - Java version: 11.0.18 (Azul Systems, Inc. / Linux)
2023-03-16 16:34:57.023 INFO  org.glowroot - Java args: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -XX:+PrintFlagsFinal -XX:+UnlockDiagnosticVMOptions -Xlog:gc*,gc+ref=debug,gc+heap=debug,gc+age=trace:file=/opt/liferay/tomcat/logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=20m --add-opens=jdk.naming.dns/com.sun.jndi.dns=java.naming -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NewSize=4096m -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=12 -XX:InitialCodeCacheSize=64m -XX:ReservedCodeCacheSize=96m -XX:+IgnoreUnrecognizedVMOptions -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1g -javaagent:/opt/liferay/tools/glowroot/glowroot.jar
2023-03-16 16:34:57.027 ERROR org.glowroot - Glowroot failed to start: Missing lib/glowroot-central-collector-https-linux.jar
java.lang.IllegalStateException: Missing lib/glowroot-central-collector-https-linux.jar
        at org.glowroot.agent.MainEntryPoint.createGlowrootAgentInit(MainEntryPoint.java:329)
        at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:265)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
```

This does not make sense to me as the ONLY thing I'm changing is the agent's `glowroot-template.properties` from `collector.address=http://...:8181` to `collector.address=https://...:8182`.

The error appears to be from https://github.com/glowroot/glowroot/blob/main/agent/core/src/main/java/org/glowroot/agent/ToolMain.java#L43 however I don't yet understand the code and intuitively changing `collector.address` wouldn't be related to loading the JAR/starting glowroot?

My questions are about this error on the agent.  There are no logs on the collector and AFAIK it's configured as per https://github.com/glowroot/glowroot/wiki/Agent-Installation-(for-Central-Collector)#https-between-the-agent-and-central-collector with `grpc.httpPort=8181` and `grpc.httpsPort=8182`

Let me know if anyone has ideas how to resolve this -- thank you!

**Comment by Nowheresly** [comment]
Hello @SpencerWoo 

from what I can see in the code [here](https://github.com/glowroot/glowroot/blob/eac9c4dda0fdd3dd48aaf55d00347d0c5364d254/agent/core/src/main/java/org/glowroot/agent/MainEntryPoint.java#L319), as soon as you use https, the additional lib jar (lib/glowroot-central-collector-https-linux.jar) is [required](https://github.com/glowroot/glowroot/blob/eac9c4dda0fdd3dd48aaf55d00347d0c5364d254/agent/core/src/main/java/org/glowroot/agent/MainEntryPoint.java#L328).

Could you check if the jar is indeed available in a lib folder where you have the agent installed?

**Comment by SpencerWoo** [comment]
@Nowheresly perfect -- thank you!  Quick response and this all makes sense.  I see only the `glowroot.jar` was there and not the other jars from lib.  Thanks again!

Now I'm getting certificate problems but I'll work through them =)
