### ISSUE TITLE
Can not upgrade glowroot-centrol from 0.13.6 to 0.14.0

### ISSUE THREAD

**Issue by ynsdl** [glowroot/glowroot#993]
I am trying to upgrade glowroot-central but it returns an error to connect to cassandra. 

Cassandra is up and running.

```
2023-03-30 10:41:55.680 ERROR org.glowroot - All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=f9ed02bc-5dee-468a-93ac-ecce89040fb4, hashCode=25e3b0f8): [com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError]
com.datastax.oss.driver.api.core.AllNodesFailedException: All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=f9ed02bc-5dee-468a-93ac-ecce89040fb4, hashCode=25e3b0f8): [com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:384)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:305)
	at org.glowroot.central.repo.SchemaUpgrade.addColumnIfNotExists(SchemaUpgrade.java:2861)
	at org.glowroot.central.repo.SchemaUpgrade.addAggregateSummaryColumns(SchemaUpgrade.java:2838)
	at org.glowroot.central.repo.SchemaUpgrade.upgrade(SchemaUpgrade.java:530)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:185)
	at org.glowroot.central.CentralModule.create(CentralModule.java:130)
	at org.glowroot.central.CentralModule.create(CentralModule.java:125)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
	Suppressed: com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError
Exception in thread "main" com.datastax.oss.driver.api.core.AllNodesFailedException: All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=f9ed02bc-5dee-468a-93ac-ecce89040fb4, hashCode=25e3b0f8): [com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:384)
	at org.glowroot.central.util.Session.updateSchemaWithRetry(Session.java:305)
	at org.glowroot.central.repo.SchemaUpgrade.addColumnIfNotExists(SchemaUpgrade.java:2861)
	at org.glowroot.central.repo.SchemaUpgrade.addAggregateSummaryColumns(SchemaUpgrade.java:2838)
	at org.glowroot.central.repo.SchemaUpgrade.upgrade(SchemaUpgrade.java:530)
	at org.glowroot.central.CentralModule.<init>(CentralModule.java:185)
	at org.glowroot.central.CentralModule.create(CentralModule.java:130)
	at org.glowroot.central.CentralModule.create(CentralModule.java:125)
	at org.glowroot.central.Main.start(Main.java:44)
	at org.glowroot.central.Main.main(Main.java:28)
	Suppressed: com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError
```

**Comment by Nowheresly** [comment]
Hi
Thanks for your feedback 
Could you provide the version of your Cassandra instances please ?

**Comment by ynsdl** [comment]
[cqlsh 5.0.1 | Cassandra 3.10 | CQL spec 3.4.4

**Comment by Nowheresly** [comment]
ok. Maybe could you try the solution proposed here ?
https://stackoverflow.com/questions/10359592/cassandra-assertionerror

**Comment by wanqiu410** [comment]
1、非docker:修改glowroot-central.properties文件中的cassandra.contactPoints={cassandra ip}可解决此问题
2、docker:添加 -e CASSANDRA_CONTACT_POINTS="xxx.xxx.xxx.xxx"可解决此问题
3、k8s:添加如下
- name: CASSANDRA_CONTACT_POINTS
    value: xxx.xxx.xxx.xxx

**Comment by Nowheresly** [comment]
Hi @ynsdl 
could you check the value of your CASSANDRA_CONTACT_POINTS environment variable as suggested by @wanqiu410 ?
If you use docker or k8s, be sure to have an environment variable CASSANDRA_CONTACT_POINTS that specifies the ip of your cassandra server.

**Comment by Never-lab** [comment]
﻿Upgrade path **0.13.6 → 0.14.x** runs ``SchemaUpgrade`` against Cassandra. Your stack showed ``ServerError`` / ``AssertionError`` on C* **3.10** at ``addAggregateSummaryColumns`` — often a **Cassandra node health / schema** problem (or wrong contact point), not “Glowroot can’t talk to a healthy cluster.”

Checklist already partly in-thread:
1. Point Central at the real Cassandra IP (``cassandra.contactPoints`` / ``CASSANDRA_CONTACT_POINTS``) — not a stale ``127.0.0.1`` inside Docker/k8s (@wanqiu410 / @nowheresly).
2. Prefer a supported Cassandra **3.11+** (wiki) for current Central; inspect ``system.log`` on the C* node for the AssertionError.
3. Retry schema upgrade only when C* is healthy; backup keyspace first.

Stale with no OP confirmation. OK to close as ops/needs-info.

@nowheresly
