### ISSUE TITLE
Deployment error with glowroot in Jboss-EAP7.3

### ISSUE THREAD

**Issue by poovendhiran** [glowroot/glowroot#994]
Hello Team, 

While deploying my war file in Jboss-Eap7.3 with glowroot, I'm unable to deploy and encountered below-mentioned error. If I deploy the war file without the glowroot(After removing the -javaagent:path/to/glowroot.jar from JVM parameters), I'm able to deploy the war file without any issue. Kindly provide your support on this issue to resolve. Thanks in advance!!!

Error : 
2023-04-03 14:40:13,464 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 93) MSC000001: Failed to start service jboss.deployment.unit."*****.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."*****.war".undertow-deployment: java.lang.RuntimeException: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [META-INF/spring/camel-context.xml]; nested exception is org.apache.xerces.impl.dv.ObjectFactory$ConfigurationError: Provider org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl could not be instantiated: java.lang.SecurityException: class "org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl"'s signer information does not match signer information of other classes in the same package
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.lang.Thread.run(Thread.java:750)
    at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [META-INF/spring/camel-context.xml]; nested exception is org.apache.xerces.impl.dv.ObjectFactory$ConfigurationError: Provider org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl could not be instantiated: java.lang.SecurityException: class "org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl"'s signer information does not match signer information of other classes in the same package
    at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
    ... 8 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [META-INF/spring/camel-context.xml]; nested exception is org.apache.xerces.impl.dv.ObjectFactory$ConfigurationError: Provider org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl could not be instantiated: java.lang.SecurityException: class "org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl"'s signer information does not match signer information of other classes in the same package
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:337)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:305)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
    at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
    at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
    at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
    at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
    at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
    at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
    at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
    ... 10 more
Caused by: org.apache.xerces.impl.dv.ObjectFactory$ConfigurationError: Provider org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl could not be instantiated: java.lang.SecurityException: class "org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl"'s signer information does not match signer information of other classes in the same package
    at org.apache.xerces.impl.dv.ObjectFactory.newInstance(Unknown Source)
    at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
    at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
    at org.apache.xerces.impl.xs.SchemaGrammar$BuiltinSchemaGrammar.<init>(Unknown Source)
    at org.apache.xerces.impl.xs.SchemaGrammar.<clinit>(Unknown Source)
    at org.apache.xerces.impl.xs.XMLSchemaValidator.<clinit>(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.configurePipeline(Unknown Source)
    at org.apache.xerces.parsers.XIncludeAwareParserConfiguration.configurePipeline(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:435)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:393)
[glowroot_issue.txt](https://github.com/glowroot/glowroot/files/11159682/glowroot_issue.txt)

Regards,
Poovendhiran

**Comment by Nowheresly** [comment]
Hi @poovendhiran,
thanks for reporting your issue. Could you please tell us which exact jdk version you are using ?

**Comment by Nowheresly** [comment]
Would it be possible to provide a minimalist example that reproduces the issue please?

**Comment by poovendhiran** [comment]
Hello @Nowheresly , 

  Apologies for the delay in response. The exact JDK version is openjdk-1.8.0.352. To replicate this issue, you need the same war file, which contains our code. So, as per security policy, I can't share the war file with you. If you need any other details, will share with you.

**Comment by Nowheresly** [comment]
This error may happen when the same class is present twice in the classpath and when at least one class is in a signed jar. 
See [here](https://stackoverflow.com/questions/2877262/java-securityexception-signer-information-does-not-match) a description of the error.
My guess is that at startup, glowroot tries to instrument all classes and unfortunately, the class `SchemaDVFactoryImpl` is a class that matches a rule for instrumentation in glowroot.
So this error is probably not related to glowroot agent. The fix is to remove the duplicate.

So why this error does not happen without glowroot agent?
My guess is that glowroot agent forces an eager loading of the class, thus the error appears on startup.

I think you should check whether this class is indeed present twice in the classpath (maybe already here in the jboss classpath?).

**Comment by poovendhiran** [comment]
Hello @Nowheresly , 


 Will check internally and update you back.
